package com.sndi.models;
// Generated 14 mars 2020 14:41:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TActeurs generated by hbm2java
 */
@Entity
@Table(name = "T_ACTEURS", schema = "EMAP")
public class TActeurs implements java.io.Serializable {

	private TActeursId id;

	public TActeurs() {
	}

	public TActeurs(TActeursId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "code", column = @Column(name = "CODE", length = 200)),
			@AttributeOverride(name = "ministère", column = @Column(name = "MINISTÈRE", length = 200)),
			@AttributeOverride(name = "codeAc", column = @Column(name = "CODE_AC", length = 200)),
			@AttributeOverride(name = "libellleAc", column = @Column(name = "LIBELLLE_AC", length = 200)),
			@AttributeOverride(name = "nomPrenoms", column = @Column(name = "NOM_PRENOMS", length = 200)),
			@AttributeOverride(name = "structure", column = @Column(name = "STRUCTURE", length = 200)),
			@AttributeOverride(name = "mail", column = @Column(name = "MAIL", length = 200)),
			@AttributeOverride(name = "telphone", column = @Column(name = "TELPHONE", length = 200)),
			@AttributeOverride(name = "matricule", column = @Column(name = "MATRICULE", length = 200)) })
	public TActeursId getId() {
		return this.id;
	}

	public void setId(TActeursId id) {
		this.id = id;
	}

}
