package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TBesoin generated by hbm2java
 */
@Entity
@Table(name = "T_BESOIN", schema = "EMAP")
public class TBesoin implements java.io.Serializable {

	private TBesoinId id;

	public TBesoin() {
	}

	public TBesoin(TBesoinId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "besId", column = @Column(name = "BES_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "besRegId", column = @Column(name = "BES_REG_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "besProId", column = @Column(name = "BES_PRO_ID", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "besLibelle", column = @Column(name = "BES_LIBELLE", length = 1000)),
			@AttributeOverride(name = "besStatut", column = @Column(name = "BES_STATUT", length = 1)) })
	public TBesoinId getId() {
		return this.id;
	}

	public void setId(TBesoinId id) {
		this.id = id;
	}

}
