package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TComposante generated by hbm2java
 */
@Entity
@Table(name = "T_COMPOSANTE", schema = "EMAP")
public class TComposante implements java.io.Serializable {

	private TComposanteId id;

	public TComposante() {
	}

	public TComposante(TComposanteId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "COM_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "comProId", column = @Column(name = "COM_PRO_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "comCode", column = @Column(name = "COM_CODE", length = 50)),
			@AttributeOverride(name = "comLibelleCourt", column = @Column(name = "COM_LIBELLE_COURT", nullable = false, length = 500)),
			@AttributeOverride(name = "comLibelleLong", column = @Column(name = "COM_LIBELLE_LONG", length = 1000)) })
	public TComposanteId getId() {
		return this.id;
	}

	public void setId(TComposanteId id) {
		this.id = id;
	}

}
