package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TCorrectionDac generated by hbm2java
 */
@Entity
@Table(name = "T_CORRECTION_DAC", schema = "EMAP")
public class TCorrectionDac implements java.io.Serializable {

	private TCorrectionDacId id;

	public TCorrectionDac() {
	}

	public TCorrectionDac(TCorrectionDacId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "corNum", column = @Column(name = "COR_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "corDacCode", column = @Column(name = "COR_DAC_CODE", length = 20)),
			@AttributeOverride(name = "corLieblle", column = @Column(name = "COR_LIEBLLE", length = 200)),
			@AttributeOverride(name = "corDteSaisi", column = @Column(name = "COR_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "corOpeMatricule", column = @Column(name = "COR_OPE_MATRICULE", length = 25)),
			@AttributeOverride(name = "corResultat", column = @Column(name = "COR_RESULTAT", length = 20)),
			@AttributeOverride(name = "corObservation", column = @Column(name = "COR_OBSERVATION", length = 4000)),
			@AttributeOverride(name = "corResultatRespo", column = @Column(name = "COR_RESULTAT_RESPO", length = 20)),
			@AttributeOverride(name = "corObservationRespo", column = @Column(name = "COR_OBSERVATION_RESPO", length = 4000)),
			@AttributeOverride(name = "corFoncodValid", column = @Column(name = "COR_FONCOD_VALID", length = 1000)) })
	public TCorrectionDacId getId() {
		return this.id;
	}

	public void setId(TCorrectionDacId id) {
		this.id = id;
	}

}
