package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TDestinations generated by hbm2java
 */
@Entity
@Table(name = "T_DESTINATIONS", schema = "EMAP")
public class TDestinations implements java.io.Serializable {

	private TDestinationsId id;

	public TDestinations() {
	}

	public TDestinations(TDestinationsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "desCode", column = @Column(name = "DES_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "desAdr", column = @Column(name = "DES_ADR", length = 200)),
			@AttributeOverride(name = "desLib", column = @Column(name = "DES_LIB", nullable = false, length = 500)),
			@AttributeOverride(name = "desOpeMatricule", column = @Column(name = "DES_OPE_MATRICULE", length = 25)),
			@AttributeOverride(name = "desOpeModif", column = @Column(name = "DES_OPE_MODIF", length = 25)),
			@AttributeOverride(name = "desDteModif", column = @Column(name = "DES_DTE_MODIF", length = 7)),
			@AttributeOverride(name = "desDteSaisi", column = @Column(name = "DES_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "desRegCode", column = @Column(name = "DES_REG_CODE", length = 2)) })
	public TDestinationsId getId() {
		return this.id;
	}

	public void setId(TDestinationsId id) {
		this.id = id;
	}

}
