package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TDetailVente generated by hbm2java
 */
@Entity
@Table(name = "T_DETAIL_VENTE", schema = "EMAP")
public class TDetailVente implements java.io.Serializable {

	private TDetailVenteId id;

	public TDetailVente() {
	}

	public TDetailVente(TDetailVenteId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dveNum", column = @Column(name = "DVE_NUM", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "dveDacCode", column = @Column(name = "DVE_DAC_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "dveVenNum", column = @Column(name = "DVE_VEN_NUM", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "dveLaaNum", column = @Column(name = "DVE_LAA_NUM", precision = 20, scale = 0)),
			@AttributeOverride(name = "dveQte", column = @Column(name = "DVE_QTE", length = 3)),
			@AttributeOverride(name = "dveCout", column = @Column(name = "DVE_COUT", precision = 11, scale = 0)),
			@AttributeOverride(name = "dveCoutLettre", column = @Column(name = "DVE_COUT_LETTRE", length = 500)),
			@AttributeOverride(name = "dveFonCod", column = @Column(name = "DVE_FON_COD", length = 12)) })
	public TDetailVenteId getId() {
		return this.id;
	}

	public void setId(TDetailVenteId id) {
		this.id = id;
	}

}
