package com.sndi.models;
// Generated 30 juin 2020 16:42:29 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TDossierDemande generated by hbm2java
 */
@Entity
@Table(name = "T_DOSSIER_DEMANDE", schema = "EMAP")
public class TDossierDemande implements java.io.Serializable {

	private BigDecimal dodId;
	private TDemande TDemande;
	private TPieceDemande TPieceDemande;
	private String dodLibelle;
	private String dodReference;

	public TDossierDemande() {
	}

	public TDossierDemande(BigDecimal dodId, TDemande TDemande) {
		this.dodId = dodId;
		this.TDemande = TDemande;
	}

	public TDossierDemande(BigDecimal dodId, TDemande TDemande, TPieceDemande TPieceDemande, String dodLibelle,
			String dodReference) {
		this.dodId = dodId;
		this.TDemande = TDemande;
		this.TPieceDemande = TPieceDemande;
		this.dodLibelle = dodLibelle;
		this.dodReference = dodReference;
	}

	@Id

	@Column(name = "DOD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDodId() {
		return this.dodId;
	}

	public void setDodId(BigDecimal dodId) {
		this.dodId = dodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOD_DEM_NUM", nullable = false)
	public TDemande getTDemande() {
		return this.TDemande;
	}

	public void setTDemande(TDemande TDemande) {
		this.TDemande = TDemande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOD_PDM_NUM")
	public TPieceDemande getTPieceDemande() {
		return this.TPieceDemande;
	}

	public void setTPieceDemande(TPieceDemande TPieceDemande) {
		this.TPieceDemande = TPieceDemande;
	}

	@Column(name = "DOD_LIBELLE", length = 500)
	public String getDodLibelle() {
		return this.dodLibelle;
	}

	public void setDodLibelle(String dodLibelle) {
		this.dodLibelle = dodLibelle;
	}

	@Column(name = "DOD_REFERENCE", length = 500)
	public String getDodReference() {
		return this.dodReference;
	}

	public void setDodReference(String dodReference) {
		this.dodReference = dodReference;
	}

}
