package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * THistoPlanGeneral generated by hbm2java
 */
@Entity
@Table(name = "T_HISTO_PLAN_GENERAL", schema = "EMAP")
public class THistoPlanGeneral implements java.io.Serializable {

	private THistoPlanGeneralId id;

	public THistoPlanGeneral() {
	}

	public THistoPlanGeneral(THistoPlanGeneralId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "hpgId", column = @Column(name = "HPG_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "hpgFonCod", column = @Column(name = "HPG_FON_COD", nullable = false, length = 12)),
			@AttributeOverride(name = "hpgGpgId", column = @Column(name = "HPG_GPG_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "hpgStaCode", column = @Column(name = "HPG_STA_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "hpgDate", column = @Column(name = "HPG_DATE", length = 7)),
			@AttributeOverride(name = "hpgMotif", column = @Column(name = "HPG_MOTIF", length = 1000)),
			@AttributeOverride(name = "hpgOpeMatricule", column = @Column(name = "HPG_OPE_MATRICULE", length = 25)) })
	public THistoPlanGeneralId getId() {
		return this.id;
	}

	public void setId(THistoPlanGeneralId id) {
		this.id = id;
	}

}
