package com.sndi.models;
// Generated 30 mars 2020 01:35:59 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * THistoDemande generated by hbm2java
 */
@Entity
@Table(name = "T_HISTO_DEMANDE", schema = "EMAP")
public class THistoDemande implements java.io.Serializable {

	private short hdmNum;
	private TDemande TDemande;
	private TOperateur TOperateur;
	private TStatut TStatut;
	private TFonction TFonction;
	private Date hdmDteSaisi;

	public THistoDemande() {
	}

	public THistoDemande(short hdmNum, TDemande TDemande) {
		this.hdmNum = hdmNum;
		this.TDemande = TDemande;
	}

	public THistoDemande(short hdmNum, TDemande TDemande, TOperateur TOperateur, TStatut TStatut, TFonction TFonction,
			Date hdmDteSaisi) {
		this.hdmNum = hdmNum;
		this.TDemande = TDemande;
		this.TOperateur = TOperateur;
		this.TStatut = TStatut;
		this.TFonction = TFonction;
		this.hdmDteSaisi = hdmDteSaisi;
	}

	@Id

	@Column(name = "HDM_NUM", unique = true, nullable = false, precision = 4, scale = 0)
	public short getHdmNum() {
		return this.hdmNum;
	}

	public void setHdmNum(short hdmNum) {
		this.hdmNum = hdmNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HDM_DEM_NUM", nullable = false)
	public TDemande getTDemande() {
		return this.TDemande;
	}

	public void setTDemande(TDemande TDemande) {
		this.TDemande = TDemande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HDM_OPE_CODE")
	public TOperateur getTOperateur() {
		return this.TOperateur;
	}

	public void setTOperateur(TOperateur TOperateur) {
		this.TOperateur = TOperateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HDM_STA_CODE")
	public TStatut getTStatut() {
		return this.TStatut;
	}

	public void setTStatut(TStatut TStatut) {
		this.TStatut = TStatut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HDM_FON_COD")
	public TFonction getTFonction() {
		return this.TFonction;
	}

	public void setTFonction(TFonction TFonction) {
		this.TFonction = TFonction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HDM_DTE_SAISI", length = 7)
	public Date getHdmDteSaisi() {
		return this.hdmDteSaisi;
	}

	public void setHdmDteSaisi(Date hdmDteSaisi) {
		this.hdmDteSaisi = hdmDteSaisi;
	}

}
