package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * THistoDemande generated by hbm2java
 */
@Entity
@Table(name = "T_HISTO_DEMANDE", schema = "EMAP")
public class THistoDemande implements java.io.Serializable {

	private THistoDemandeId id;

	public THistoDemande() {
	}

	public THistoDemande(THistoDemandeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "hdmNum", column = @Column(name = "HDM_NUM", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "hdmDemNum", column = @Column(name = "HDM_DEM_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "hdmDteSaisi", column = @Column(name = "HDM_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "hdmStaCode", column = @Column(name = "HDM_STA_CODE", length = 3)),
			@AttributeOverride(name = "hdmFonCod", column = @Column(name = "HDM_FON_COD", length = 20)),
			@AttributeOverride(name = "hdmOpeCode", column = @Column(name = "HDM_OPE_CODE", length = 25)),
			@AttributeOverride(name = "hdmMotif", column = @Column(name = "HDM_MOTIF", length = 500)) })
	public THistoDemandeId getId() {
		return this.id;
	}

	public void setId(THistoDemandeId id) {
		this.id = id;
	}

}
