package com.sndi.models;
// Generated 30 mars 2020 01:35:59 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * THistoPlanGeneral generated by hbm2java
 */
@Entity
@Table(name = "T_HISTO_PLAN_GENERAL", schema = "EMAP")
public class THistoPlanGeneral implements java.io.Serializable {

	private long hpgId;
	private TDetailPlanGeneral TDetailPlanGeneral;
	private TStatut TStatut;
	private TFonction TFonction;
	private Date hpgDate;
	private String hpgMotif;
	private String hpgOpeMatricule;

	public THistoPlanGeneral() {
	}

	public THistoPlanGeneral(long hpgId, TDetailPlanGeneral TDetailPlanGeneral, TStatut TStatut, TFonction TFonction) {
		this.hpgId = hpgId;
		this.TDetailPlanGeneral = TDetailPlanGeneral;
		this.TStatut = TStatut;
		this.TFonction = TFonction;
	}

	public THistoPlanGeneral(long hpgId, TDetailPlanGeneral TDetailPlanGeneral, TStatut TStatut, TFonction TFonction,
			Date hpgDate, String hpgMotif, String hpgOpeMatricule) {
		this.hpgId = hpgId;
		this.TDetailPlanGeneral = TDetailPlanGeneral;
		this.TStatut = TStatut;
		this.TFonction = TFonction;
		this.hpgDate = hpgDate;
		this.hpgMotif = hpgMotif;
		this.hpgOpeMatricule = hpgOpeMatricule;
	}

	@Id

	@Column(name = "HPG_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getHpgId() {
		return this.hpgId;
	}

	public void setHpgId(long hpgId) {
		this.hpgId = hpgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HPG_GPG_ID", nullable = false)
	public TDetailPlanGeneral getTDetailPlanGeneral() {
		return this.TDetailPlanGeneral;
	}

	public void setTDetailPlanGeneral(TDetailPlanGeneral TDetailPlanGeneral) {
		this.TDetailPlanGeneral = TDetailPlanGeneral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HPG_STA_CODE", nullable = false)
	public TStatut getTStatut() {
		return this.TStatut;
	}

	public void setTStatut(TStatut TStatut) {
		this.TStatut = TStatut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HPG_FON_COD", nullable = false)
	public TFonction getTFonction() {
		return this.TFonction;
	}

	public void setTFonction(TFonction TFonction) {
		this.TFonction = TFonction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HPG_DATE", length = 7)
	public Date getHpgDate() {
		return this.hpgDate;
	}

	public void setHpgDate(Date hpgDate) {
		this.hpgDate = hpgDate;
	}

	@Column(name = "HPG_MOTIF", length = 1000)
	public String getHpgMotif() {
		return this.hpgMotif;
	}

	public void setHpgMotif(String hpgMotif) {
		this.hpgMotif = hpgMotif;
	}

	@Column(name = "HPG_OPE_MATRICULE", length = 20)
	public String getHpgOpeMatricule() {
		return this.hpgOpeMatricule;
	}

	public void setHpgOpeMatricule(String hpgOpeMatricule) {
		this.hpgOpeMatricule = hpgOpeMatricule;
	}

}
