package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TLotAao generated by hbm2java
 */
@Entity
@Table(name = "T_LOT_AAO", schema = "EMAP", uniqueConstraints = @UniqueConstraint(columnNames = { "LAA_ID",
		"LAA_NUM" }))
public class TLotAao implements java.io.Serializable {

	private TLotAaoId id;

	public TLotAao() {
	}

	public TLotAao(TLotAaoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "laaId", column = @Column(name = "LAA_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "laaAaoCode", column = @Column(name = "LAA_AAO_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "laaObjet", column = @Column(name = "LAA_OBJET", nullable = false, length = 1000)),
			@AttributeOverride(name = "laaObservation", column = @Column(name = "LAA_OBSERVATION", length = 200)),
			@AttributeOverride(name = "laaMtCaut", column = @Column(name = "LAA_MT_CAUT", precision = 22, scale = 0)),
			@AttributeOverride(name = "laaMtEst", column = @Column(name = "LAA_MT_EST", precision = 22, scale = 0)),
			@AttributeOverride(name = "laaDteSaisi", column = @Column(name = "LAA_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "laaStaCode", column = @Column(name = "LAA_STA_CODE", length = 3)),
			@AttributeOverride(name = "laaFonCodSaisi", column = @Column(name = "LAA_FON_COD_SAISI", length = 20)),
			@AttributeOverride(name = "laaFonCodCpmp", column = @Column(name = "LAA_FON_COD_CPMP", length = 20)),
			@AttributeOverride(name = "laaOpeMatricule", column = @Column(name = "LAA_OPE_MATRICULE", length = 20)),
			@AttributeOverride(name = "laaLieuExe", column = @Column(name = "LAA_LIEU_EXE", length = 1000)),
			@AttributeOverride(name = "laaLbgImputation", column = @Column(name = "LAA_LBG_IMPUTATION", length = 50)),
			@AttributeOverride(name = "laaNum", column = @Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "laaCoutLot", column = @Column(name = "LAA_COUT_LOT", precision = 22, scale = 0)),
			@AttributeOverride(name = "laaDacCode", column = @Column(name = "LAA_DAC_CODE", length = 20)),
			@AttributeOverride(name = "laaAjoutPanier", column = @Column(name = "LAA_AJOUT_PANIER", length = 1)),
			@AttributeOverride(name = "laaDelaiExe", column = @Column(name = "LAA_DELAI_EXE", precision = 10, scale = 0)),
			@AttributeOverride(name = "laaVariante", column = @Column(name = "LAA_VARIANTE", length = 1)),
			@AttributeOverride(name = "laaAno", column = @Column(name = "LAA_ANO", length = 1)),
			@AttributeOverride(name = "laaObservationDmp", column = @Column(name = "LAA_OBSERVATION_DMP", length = 1000)) })
	public TLotAaoId getId() {
		return this.id;
	}

	public void setId(TLotAaoId id) {
		this.id = id;
	}

}
