package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TNaturePiece generated by hbm2java
 */
@Entity
@Table(name = "T_NATURE_PIECE", schema = "EMAP")
public class TNaturePiece implements java.io.Serializable {

	private TNaturePieceId id;

	public TNaturePiece() {
	}

	public TNaturePiece(TNaturePieceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "napCode", column = @Column(name = "NAP_CODE", nullable = false, length = 5)),
			@AttributeOverride(name = "napNapLibelleCourt", column = @Column(name = "NAP_NAP_LIBELLE_COURT", nullable = false, length = 500)),
			@AttributeOverride(name = "napNapLibelleLong", column = @Column(name = "NAP_NAP_LIBELLE_LONG", length = 1000)) })
	public TNaturePieceId getId() {
		return this.id;
	}

	public void setId(TNaturePieceId id) {
		this.id = id;
	}

}
