package com.sndi.models;
// Generated 30 juin 2020 16:42:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TParametres generated by hbm2java
 */
@Entity
@Table(name = "T_PARAMETRES", schema = "EMAP")
public class TParametres implements java.io.Serializable {

	private String parCode;
	private TOperateur TOperateur;
	private String parLibelle;
	private String parVal;
	private Date parDteSaisi;
	private String parActif;

	public TParametres() {
	}

	public TParametres(String parCode) {
		this.parCode = parCode;
	}

	public TParametres(String parCode, TOperateur TOperateur, String parLibelle, String parVal, Date parDteSaisi,
			String parActif) {
		this.parCode = parCode;
		this.TOperateur = TOperateur;
		this.parLibelle = parLibelle;
		this.parVal = parVal;
		this.parDteSaisi = parDteSaisi;
		this.parActif = parActif;
	}

	@Id

	@Column(name = "PAR_CODE", unique = true, nullable = false, length = 20)
	public String getParCode() {
		return this.parCode;
	}

	public void setParCode(String parCode) {
		this.parCode = parCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAR_OPE_MATRICULE")
	public TOperateur getTOperateur() {
		return this.TOperateur;
	}

	public void setTOperateur(TOperateur TOperateur) {
		this.TOperateur = TOperateur;
	}

	@Column(name = "PAR_LIBELLE", length = 200)
	public String getParLibelle() {
		return this.parLibelle;
	}

	public void setParLibelle(String parLibelle) {
		this.parLibelle = parLibelle;
	}

	@Column(name = "PAR_VAL", length = 200)
	public String getParVal() {
		return this.parVal;
	}

	public void setParVal(String parVal) {
		this.parVal = parVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAR_DTE_SAISI", length = 7)
	public Date getParDteSaisi() {
		return this.parDteSaisi;
	}

	public void setParDteSaisi(Date parDteSaisi) {
		this.parDteSaisi = parDteSaisi;
	}

	@Column(name = "PAR_ACTIF", length = 2)
	public String getParActif() {
		return this.parActif;
	}

	public void setParActif(String parActif) {
		this.parActif = parActif;
	}

}
