package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TParametres generated by hbm2java
 */
@Entity
@Table(name = "T_PARAMETRES", schema = "EMAP")
public class TParametres implements java.io.Serializable {

	private TParametresId id;

	public TParametres() {
	}

	public TParametres(TParametresId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "parCode", column = @Column(name = "PAR_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "parLibelle", column = @Column(name = "PAR_LIBELLE", length = 200)),
			@AttributeOverride(name = "parVal", column = @Column(name = "PAR_VAL", length = 4000)),
			@AttributeOverride(name = "parOpeMatricule", column = @Column(name = "PAR_OPE_MATRICULE", length = 25)),
			@AttributeOverride(name = "parDteSaisi", column = @Column(name = "PAR_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "parActif", column = @Column(name = "PAR_ACTIF", length = 2)) })
	public TParametresId getId() {
		return this.id;
	}

	public void setId(TParametresId id) {
		this.id = id;
	}

}
