package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPaysReference generated by hbm2java
 */
@Entity
@Table(name = "T_PAYS_REFERENCE", schema = "EMAP")
public class TPaysReference implements java.io.Serializable {

	private String repCode;
	private String repLibelle;
	private String repLibelleCourt;
	private String repStatut;
	private String repIndicatif;
	private Set<TSoumissions> TSoumissionses = new HashSet<TSoumissions>(0);

	public TPaysReference() {
	}

	public TPaysReference(String repCode) {
		this.repCode = repCode;
	}

	public TPaysReference(String repCode, String repLibelle, String repLibelleCourt, String repStatut,
			String repIndicatif, Set<TSoumissions> TSoumissionses) {
		this.repCode = repCode;
		this.repLibelle = repLibelle;
		this.repLibelleCourt = repLibelleCourt;
		this.repStatut = repStatut;
		this.repIndicatif = repIndicatif;
		this.TSoumissionses = TSoumissionses;
	}

	@Id

	@Column(name = "REP_CODE", unique = true, nullable = false, length = 10)
	public String getRepCode() {
		return this.repCode;
	}

	public void setRepCode(String repCode) {
		this.repCode = repCode;
	}

	@Column(name = "REP_LIBELLE", length = 200)
	public String getRepLibelle() {
		return this.repLibelle;
	}

	public void setRepLibelle(String repLibelle) {
		this.repLibelle = repLibelle;
	}

	@Column(name = "REP_LIBELLE_COURT", length = 100)
	public String getRepLibelleCourt() {
		return this.repLibelleCourt;
	}

	public void setRepLibelleCourt(String repLibelleCourt) {
		this.repLibelleCourt = repLibelleCourt;
	}

	@Column(name = "REP_STATUT", length = 1)
	public String getRepStatut() {
		return this.repStatut;
	}

	public void setRepStatut(String repStatut) {
		this.repStatut = repStatut;
	}

	@Column(name = "REP_INDICATIF", length = 50)
	public String getRepIndicatif() {
		return this.repIndicatif;
	}

	public void setRepIndicatif(String repIndicatif) {
		this.repIndicatif = repIndicatif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPaysReference")
	public Set<TSoumissions> getTSoumissionses() {
		return this.TSoumissionses;
	}

	public void setTSoumissionses(Set<TSoumissions> TSoumissionses) {
		this.TSoumissionses = TSoumissionses;
	}

}
