package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TSoumissions generated by hbm2java
 */
@Entity
@Table(name = "T_SOUMISSIONS", schema = "EMAP")
public class TSoumissions implements java.io.Serializable {

	private TSoumissionsId id;
	private TPaysReference TPaysReference;

	public TSoumissions() {
	}

	public TSoumissions(TSoumissionsId id) {
		this.id = id;
	}

	public TSoumissions(TSoumissionsId id, TPaysReference TPaysReference) {
		this.id = id;
		this.TPaysReference = TPaysReference;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "souNcc", column = @Column(name = "SOU_NCC", nullable = false, length = 20)),
			@AttributeOverride(name = "souInter", column = @Column(name = "SOU_INTER", length = 1)),
			@AttributeOverride(name = "souSigleSte", column = @Column(name = "SOU_SIGLE_STE", length = 500)),
			@AttributeOverride(name = "souNomCom", column = @Column(name = "SOU_NOM_COM", length = 500)),
			@AttributeOverride(name = "souStaCode", column = @Column(name = "SOU_STA_CODE", length = 3)),
			@AttributeOverride(name = "souTel", column = @Column(name = "SOU_TEL", length = 200)),
			@AttributeOverride(name = "souAdresse", column = @Column(name = "SOU_ADRESSE", length = 200)),
			@AttributeOverride(name = "souDteSaisi", column = @Column(name = "SOU_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "souOpeMatricule", column = @Column(name = "SOU_OPE_MATRICULE", length = 25)),
			@AttributeOverride(name = "souSigleDmp", column = @Column(name = "SOU_SIGLE_DMP", length = 500)),
			@AttributeOverride(name = "souPayCode", column = @Column(name = "SOU_PAY_CODE", length = 20)),
			@AttributeOverride(name = "souNatInt", column = @Column(name = "SOU_NAT_INT", length = 1)) })
	public TSoumissionsId getId() {
		return this.id;
	}

	public void setId(TSoumissionsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOU_PAY_CODE", insertable = false, updatable = false)
	public TPaysReference getTPaysReference() {
		return this.TPaysReference;
	}

	public void setTPaysReference(TPaysReference TPaysReference) {
		this.TPaysReference = TPaysReference;
	}

}
