package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TSourceFinancement generated by hbm2java
 */
@Entity
@Table(name = "T_SOURCE_FINANCEMENT", schema = "EMAP")
public class TSourceFinancement implements java.io.Serializable {

	private TSourceFinancementId id;

	public TSourceFinancement() {
	}

	public TSourceFinancement(TSourceFinancementId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "souCode", column = @Column(name = "SOU_CODE", nullable = false, length = 5)),
			@AttributeOverride(name = "souLibelle", column = @Column(name = "SOU_LIBELLE", length = 500)) })
	public TSourceFinancementId getId() {
		return this.id;
	}

	public void setId(TSourceFinancementId id) {
		this.id = id;
	}

}
