package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTypePiecesDac generated by hbm2java
 */
@Entity
@Table(name = "T_TYPE_PIECES_DAC", schema = "EMAP")
public class TTypePiecesDac implements java.io.Serializable {

	private TTypePiecesDacId id;

	public TTypePiecesDac() {
	}

	public TTypePiecesDac(TTypePiecesDacId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tpiCode", column = @Column(name = "TPI_CODE", nullable = false, length = 10)),
			@AttributeOverride(name = "tpiLibelle", column = @Column(name = "TPI_LIBELLE", length = 1000)),
			@AttributeOverride(name = "tpiDacPec", column = @Column(name = "TPI_DAC_PEC", length = 15)),
			@AttributeOverride(name = "tpiMdtCode", column = @Column(name = "TPI_MDT_CODE", length = 10)),
			@AttributeOverride(name = "tpiSecNum", column = @Column(name = "TPI_SEC_NUM", length = 5)) })
	public TTypePiecesDacId getId() {
		return this.id;
	}

	public void setId(TTypePiecesDacId id) {
		this.id = id;
	}

}
