package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTypeProcedure generated by hbm2java
 */
@Entity
@Table(name = "T_TYPE_PROCEDURE", schema = "EMAP")
public class TTypeProcedure implements java.io.Serializable {

	private TTypeProcedureId id;

	public TTypeProcedure() {
	}

	public TTypeProcedure(TTypeProcedureId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "typId", column = @Column(name = "TYP_ID", nullable = false, length = 5)),
			@AttributeOverride(name = "typLib", column = @Column(name = "TYP_LIB", length = 1000)) })
	public TTypeProcedureId getId() {
		return this.id;
	}

	public void setId(TTypeProcedureId id) {
		this.id = id;
	}

}
