package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTypeSeance generated by hbm2java
 */
@Entity
@Table(name = "T_TYPE_SEANCE", schema = "EMAP")
public class TTypeSeance implements java.io.Serializable {

	private TTypeSeanceId id;

	public TTypeSeance() {
	}

	public TTypeSeance(TTypeSeanceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tseCode", column = @Column(name = "TSE_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "tseLibelle", column = @Column(name = "TSE_LIBELLE", length = 500)),
			@AttributeOverride(name = "tseDteSaisi", column = @Column(name = "TSE_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "tseFonCode", column = @Column(name = "TSE_FON_CODE", length = 12)),
			@AttributeOverride(name = "tseOpeMatricule", column = @Column(name = "TSE_OPE_MATRICULE", length = 25)) })
	public TTypeSeanceId getId() {
		return this.id;
	}

	public void setId(TTypeSeanceId id) {
		this.id = id;
	}

}
