package com.sndi.models;
// Generated 31 mars 2020 01:27:37 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VAdresseAvis generated by hbm2java
 */
@Entity
@Table(name = "V_ADRESSE_AVIS", schema = "EMAP")
public class VAdresseAvis implements java.io.Serializable {

	private VAdresseAvisId id;

	public VAdresseAvis() {
	}

	public VAdresseAvis(VAdresseAvisId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "VAd", column = @Column(name = "V_AD", precision = 22, scale = 0)),
			@AttributeOverride(name = "dacCode", column = @Column(name = "DAC_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "adaFonCod", column = @Column(name = "ADA_FON_COD", length = 12)),
			@AttributeOverride(name = "adaNum", column = @Column(name = "ADA_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "liaLibelle", column = @Column(name = "LIA_LIBELLE", length = 500)),
			@AttributeOverride(name = "dtaLibelle", column = @Column(name = "DTA_LIBELLE", length = 500)) })
	public VAdresseAvisId getId() {
		return this.id;
	}

	public void setId(VAdresseAvisId id) {
		this.id = id;
	}

}
