package com.sndi.models;
// Generated 3 avr. 2020 00:55:57 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VbDacSpecs generated by hbm2java
 */
@Entity
@Table(name = "VB_DAC_SPECS", schema = "EMAP")
public class VbDacSpecs implements java.io.Serializable {

	private VbDacSpecsId id;

	public VbDacSpecs() {
	}

	public VbDacSpecs(VbDacSpecsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "dacCode", column = @Column(name = "DAC_CODE")),
			@AttributeOverride(name = "dacObjet", column = @Column(name = "DAC_OBJET")),
			@AttributeOverride(name = "dacDteSaisi", column = @Column(name = "DAC_DTE_SAISI")),
			@AttributeOverride(name = "dacStaCode", column = @Column(name = "DAC_STA_CODE")),
			@AttributeOverride(name = "dacTymCode", column = @Column(name = "DAC_TYM_CODE")),
			@AttributeOverride(name = "dacMopCode", column = @Column(name = "DAC_MOP_CODE")),
			@AttributeOverride(name = "dacNbrOuv", column = @Column(name = "DAC_NBR_OUV")),
			@AttributeOverride(name = "dacGesCode", column = @Column(name = "DAC_GES_CODE")),
			@AttributeOverride(name = "dacFonCodAc", column = @Column(name = "DAC_FON_COD_AC")),
			@AttributeOverride(name = "dacStrCode", column = @Column(name = "DAC_STR_CODE")),
			@AttributeOverride(name = "dacFonCodeCpmp", column = @Column(name = "DAC_FON_CODE_CPMP")),
			@AttributeOverride(name = "dacDteValCpmp", column = @Column(name = "DAC_DTE_VAL_CPMP")),
			@AttributeOverride(name = "dacDteValDmp", column = @Column(name = "DAC_DTE_VAL_DMP")),
			@AttributeOverride(name = "dacTdCode", column = @Column(name = "DAC_TD_CODE")),
			@AttributeOverride(name = "dacDppId", column = @Column(name = "DAC_DPP_ID")),
			@AttributeOverride(name = "dacDateReception", column = @Column(name = "DAC_DATE_RECEPTION")),
			@AttributeOverride(name = "dacStatutRetour", column = @Column(name = "DAC_STATUT_RETOUR")),
			@AttributeOverride(name = "dacMention", column = @Column(name = "DAC_MENTION")) })
	public VbDacSpecsId getId() {
		return this.id;
	}

	public void setId(VbDacSpecsId id) {
		this.id = id;
	}

}
