package com.sndi.models;
// Generated 23 mars 2020 10:48:44 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VbDetOffresSaisi generated by hbm2java
 */
@Entity
@Table(name = "VB_DET_OFFRES_SAISI", schema = "EMAP")
public class VbDetOffresSaisi implements java.io.Serializable {

	private VbDetOffresSaisiId id;

	public VbDetOffresSaisi() {
	}

	public VbDetOffresSaisi(VbDetOffresSaisiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dofNum", column = @Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dofLaaId", column = @Column(name = "DOF_LAA_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dofLaaAaoCode", column = @Column(name = "DOF_LAA_AAO_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "dofOffNum", column = @Column(name = "DOF_OFF_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dofTyp", column = @Column(name = "DOF_TYP", length = 1)),
			@AttributeOverride(name = "dofDelai", column = @Column(name = "DOF_DELAI", nullable = false, precision = 20, scale = 0)),
			@AttributeOverride(name = "dofDelai2", column = @Column(name = "DOF_DELAI2", precision = 20, scale = 0)),
			@AttributeOverride(name = "dofRangOfr", column = @Column(name = "DOF_RANG_OFR", precision = 10, scale = 0)),
			@AttributeOverride(name = "dofMtCor", column = @Column(name = "DOF_MT_COR", precision = 20, scale = 0)),
			@AttributeOverride(name = "dofMtOfr", column = @Column(name = "DOF_MT_OFR", precision = 20, scale = 0)),
			@AttributeOverride(name = "dofRab", column = @Column(name = "DOF_RAB", length = 5)),
			@AttributeOverride(name = "dofEstimRab", column = @Column(name = "DOF_ESTIM_RAB", precision = 20, scale = 0)),
			@AttributeOverride(name = "dofBanCode", column = @Column(name = "DOF_BAN_CODE", length = 10)),
			@AttributeOverride(name = "dofSeuil", column = @Column(name = "DOF_SEUIL", length = 1)),
			@AttributeOverride(name = "dofScore", column = @Column(name = "DOF_SCORE", precision = 3, scale = 0)),
			@AttributeOverride(name = "dofRecevabl", column = @Column(name = "DOF_RECEVABL", length = 1)),
			@AttributeOverride(name = "dofRet", column = @Column(name = "DOF_RET", length = 1)),
			@AttributeOverride(name = "dofRetBai", column = @Column(name = "DOF_RET_BAI", length = 1)),
			@AttributeOverride(name = "dofRetDmp", column = @Column(name = "DOF_RET_DMP", length = 1)),
			@AttributeOverride(name = "dofMtAtt", column = @Column(name = "DOF_MT_ATT", precision = 20, scale = 0)),
			@AttributeOverride(name = "dofTot", column = @Column(name = "DOF_TOT", length = 2)),
			@AttributeOverride(name = "dofDteSaisi", column = @Column(name = "DOF_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "dofFonCodeAc", column = @Column(name = "DOF_FON_CODE_AC", length = 25)),
			@AttributeOverride(name = "dofOpeMatricule", column = @Column(name = "DOF_OPE_MATRICULE", length = 25)) })
	public VbDetOffresSaisiId getId() {
		return this.id;
	}

	public void setId(VbDetOffresSaisiId id) {
		this.id = id;
	}

}
