package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VbDetCommissionSeance generated by hbm2java
 */
@Entity
@Table(name = "VB_DET_COMMISSION_SEANCE", schema = "EMAP")
public class VbDetCommissionSeance implements java.io.Serializable {

	private VbDetCommissionSeanceId id;

	public VbDetCommissionSeance() {
	}

	public VbDetCommissionSeance(VbDetCommissionSeanceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dcsNum", column = @Column(name = "DCS_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dcsDacCode", column = @Column(name = "DCS_DAC_CODE", length = 20)),
			@AttributeOverride(name = "dcsFonCod", column = @Column(name = "DCS_FON_COD", length = 100)),
			@AttributeOverride(name = "dcsOpeMatricule", column = @Column(name = "DCS_OPE_MATRICULE", length = 20)),
			@AttributeOverride(name = "dcsSeaNum", column = @Column(name = "DCS_SEA_NUM", precision = 22, scale = 0)),
			@AttributeOverride(name = "dcsDteSaisi", column = @Column(name = "DCS_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "dcsFonCodSaisi", column = @Column(name = "DCS_FON_COD_SAISI", length = 12)),
			@AttributeOverride(name = "dcsObservation", column = @Column(name = "DCS_OBSERVATION", length = 200)),
			@AttributeOverride(name = "dcsComTcoCode", column = @Column(name = "DCS_COM_TCO_CODE", length = 3)),
			@AttributeOverride(name = "dcsComNum", column = @Column(name = "DCS_COM_NUM", precision = 22, scale = 0)),
			@AttributeOverride(name = "dcsNomMbm", column = @Column(name = "DCS_NOM_MBM", length = 100)),
			@AttributeOverride(name = "dcsPreMbm", column = @Column(name = "DCS_PRE_MBM", length = 200)),
			@AttributeOverride(name = "dcsTelMbm", column = @Column(name = "DCS_TEL_MBM", length = 50)),
			@AttributeOverride(name = "dcsPresent", column = @Column(name = "DCS_PRESENT", length = 1)),
			@AttributeOverride(name = "dcsComStrCode", column = @Column(name = "DCS_COM_STR_CODE", length = 20)),
			@AttributeOverride(name = "dcsOpeMatSaisi", column = @Column(name = "DCS_OPE_MAT_SAISI", length = 20)),
			@AttributeOverride(name = "dcsMbmRespo", column = @Column(name = "DCS_MBM_RESPO", length = 1)),
			@AttributeOverride(name = "dcsRepMandate", column = @Column(name = "DCS_REP_MANDATE", length = 1)),
			@AttributeOverride(name = "dcsFonAdmin", column = @Column(name = "DCS_FON_ADMIN", length = 500)),
			@AttributeOverride(name = "dcsStrCom", column = @Column(name = "DCS_STR_COM", length = 500)) })
	public VbDetCommissionSeanceId getId() {
		return this.id;
	}

	public void setId(VbDetCommissionSeanceId id) {
		this.id = id;
	}

}
