package com.sndi.models;
// Generated 8 août 2020 14:11:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VbDemande generated by hbm2java
 */
@Entity
@Table(name = "VB_DEMANDE", schema = "EMAP")
public class VbDemande implements java.io.Serializable {

	private VbDemandeId id;

	public VbDemande() {
	}

	public VbDemande(VbDemandeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "demNum", column = @Column(name = "DEM_NUM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "demObjet", column = @Column(name = "DEM_OBJET", length = 1000)),
			@AttributeOverride(name = "demMotif", column = @Column(name = "DEM_MOTIF", length = 1000)),
			@AttributeOverride(name = "demTdmCode", column = @Column(name = "DEM_TDM_CODE", length = 10)),
			@AttributeOverride(name = "demDteSaisi", column = @Column(name = "DEM_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "demOpeMatricule", column = @Column(name = "DEM_OPE_MATRICULE", length = 128)),
			@AttributeOverride(name = "demStaCode", column = @Column(name = "DEM_STA_CODE", length = 3)),
			@AttributeOverride(name = "demStrCode", column = @Column(name = "DEM_STR_CODE", length = 10)),
			@AttributeOverride(name = "demFonCodeAc", column = @Column(name = "DEM_FON_CODE_AC", length = 20)),
			@AttributeOverride(name = "demRefAvisMin", column = @Column(name = "DEM_REF_AVIS_MIN", length = 200)),
			@AttributeOverride(name = "demRef", column = @Column(name = "DEM_REF", length = 200)),
			@AttributeOverride(name = "demGesCode", column = @Column(name = "DEM_GES_CODE", precision = 4, scale = 0)),
			@AttributeOverride(name = "demRefActIni", column = @Column(name = "DEM_REF_ACT_INI", length = 20)),
			@AttributeOverride(name = "demStatutRetour", column = @Column(name = "DEM_STATUT_RETOUR", length = 1)),
			@AttributeOverride(name = "demFonCodePf", column = @Column(name = "DEM_FON_CODE_PF", length = 20)),
			@AttributeOverride(name = "demFonCodeDmp", column = @Column(name = "DEM_FON_CODE_DMP", length = 20)) })
	public VbDemandeId getId() {
		return this.id;
	}

	public void setId(VbDemandeId id) {
		this.id = id;
	}

}
