package com.sndi.models;
// Generated 8 août 2020 14:11:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VbDestinations generated by hbm2java
 */
@Entity
@Table(name = "VB_DESTINATIONS", schema = "EMAP")
public class VbDestinations implements java.io.Serializable {

	private VbDestinationsId id;

	public VbDestinations() {
	}

	public VbDestinations(VbDestinationsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "desCode", column = @Column(name = "DES_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "desAdr", column = @Column(name = "DES_ADR", length = 200)),
			@AttributeOverride(name = "desLib", column = @Column(name = "DES_LIB", nullable = false, length = 500)),
			@AttributeOverride(name = "desOpeMatricule", column = @Column(name = "DES_OPE_MATRICULE", length = 25)),
			@AttributeOverride(name = "desOpeModif", column = @Column(name = "DES_OPE_MODIF", length = 25)),
			@AttributeOverride(name = "desDteModif", column = @Column(name = "DES_DTE_MODIF", length = 7)),
			@AttributeOverride(name = "desDteSaisi", column = @Column(name = "DES_DTE_SAISI", length = 7)),
			@AttributeOverride(name = "desRegCode", column = @Column(name = "DES_REG_CODE", length = 2)) })
	public VbDestinationsId getId() {
		return this.id;
	}

	public void setId(VbDestinationsId id) {
		this.id = id;
	}

}
