package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VbTempParamVenteId generated by hbm2java
 */
@Embeddable
public class VbTempParamVenteId implements java.io.Serializable {

	private String canNom;
	private String canNomResp;
	private String canSouNcc;
	private String canTel;
	private String canTieNcc;
	private String dveCout;
	private String dveDacCode;
	private String dveLaaNum;
	private String dveQte;
	private String venNum;
	private String venMrgCod;
	private String canPrenoms;

	public VbTempParamVenteId() {
	}

	public VbTempParamVenteId(String canNom, String canNomResp, String canSouNcc, String canTel, String canTieNcc,
			String dveCout, String dveDacCode, String dveLaaNum, String dveQte, String venNum, String venMrgCod,
			String canPrenoms) {
		this.canNom = canNom;
		this.canNomResp = canNomResp;
		this.canSouNcc = canSouNcc;
		this.canTel = canTel;
		this.canTieNcc = canTieNcc;
		this.dveCout = dveCout;
		this.dveDacCode = dveDacCode;
		this.dveLaaNum = dveLaaNum;
		this.dveQte = dveQte;
		this.venNum = venNum;
		this.venMrgCod = venMrgCod;
		this.canPrenoms = canPrenoms;
	}

	@Column(name = "CAN_NOM", length = 500)
	public String getCanNom() {
		return this.canNom;
	}

	public void setCanNom(String canNom) {
		this.canNom = canNom;
	}

	@Column(name = "CAN_NOM_RESP", length = 500)
	public String getCanNomResp() {
		return this.canNomResp;
	}

	public void setCanNomResp(String canNomResp) {
		this.canNomResp = canNomResp;
	}

	@Column(name = "CAN_SOU_NCC", length = 500)
	public String getCanSouNcc() {
		return this.canSouNcc;
	}

	public void setCanSouNcc(String canSouNcc) {
		this.canSouNcc = canSouNcc;
	}

	@Column(name = "CAN_TEL", length = 500)
	public String getCanTel() {
		return this.canTel;
	}

	public void setCanTel(String canTel) {
		this.canTel = canTel;
	}

	@Column(name = "CAN_TIE_NCC", length = 500)
	public String getCanTieNcc() {
		return this.canTieNcc;
	}

	public void setCanTieNcc(String canTieNcc) {
		this.canTieNcc = canTieNcc;
	}

	@Column(name = "DVE_COUT", length = 500)
	public String getDveCout() {
		return this.dveCout;
	}

	public void setDveCout(String dveCout) {
		this.dveCout = dveCout;
	}

	@Column(name = "DVE_DAC_CODE", length = 500)
	public String getDveDacCode() {
		return this.dveDacCode;
	}

	public void setDveDacCode(String dveDacCode) {
		this.dveDacCode = dveDacCode;
	}

	@Column(name = "DVE_LAA_NUM", length = 500)
	public String getDveLaaNum() {
		return this.dveLaaNum;
	}

	public void setDveLaaNum(String dveLaaNum) {
		this.dveLaaNum = dveLaaNum;
	}

	@Column(name = "DVE_QTE", length = 500)
	public String getDveQte() {
		return this.dveQte;
	}

	public void setDveQte(String dveQte) {
		this.dveQte = dveQte;
	}

	@Column(name = "VEN_NUM", length = 500)
	public String getVenNum() {
		return this.venNum;
	}

	public void setVenNum(String venNum) {
		this.venNum = venNum;
	}

	@Column(name = "VEN_MRG_COD", length = 500)
	public String getVenMrgCod() {
		return this.venMrgCod;
	}

	public void setVenMrgCod(String venMrgCod) {
		this.venMrgCod = venMrgCod;
	}

	@Column(name = "CAN_PRENOMS", length = 500)
	public String getCanPrenoms() {
		return this.canPrenoms;
	}

	public void setCanPrenoms(String canPrenoms) {
		this.canPrenoms = canPrenoms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VbTempParamVenteId))
			return false;
		VbTempParamVenteId castOther = (VbTempParamVenteId) other;

		return ((this.getCanNom() == castOther.getCanNom()) || (this.getCanNom() != null
				&& castOther.getCanNom() != null && this.getCanNom().equals(castOther.getCanNom())))
				&& ((this.getCanNomResp() == castOther.getCanNomResp()) || (this.getCanNomResp() != null
						&& castOther.getCanNomResp() != null && this.getCanNomResp().equals(castOther.getCanNomResp())))
				&& ((this.getCanSouNcc() == castOther.getCanSouNcc()) || (this.getCanSouNcc() != null
						&& castOther.getCanSouNcc() != null && this.getCanSouNcc().equals(castOther.getCanSouNcc())))
				&& ((this.getCanTel() == castOther.getCanTel()) || (this.getCanTel() != null
						&& castOther.getCanTel() != null && this.getCanTel().equals(castOther.getCanTel())))
				&& ((this.getCanTieNcc() == castOther.getCanTieNcc()) || (this.getCanTieNcc() != null
						&& castOther.getCanTieNcc() != null && this.getCanTieNcc().equals(castOther.getCanTieNcc())))
				&& ((this.getDveCout() == castOther.getDveCout()) || (this.getDveCout() != null
						&& castOther.getDveCout() != null && this.getDveCout().equals(castOther.getDveCout())))
				&& ((this.getDveDacCode() == castOther.getDveDacCode()) || (this.getDveDacCode() != null
						&& castOther.getDveDacCode() != null && this.getDveDacCode().equals(castOther.getDveDacCode())))
				&& ((this.getDveLaaNum() == castOther.getDveLaaNum()) || (this.getDveLaaNum() != null
						&& castOther.getDveLaaNum() != null && this.getDveLaaNum().equals(castOther.getDveLaaNum())))
				&& ((this.getDveQte() == castOther.getDveQte()) || (this.getDveQte() != null
						&& castOther.getDveQte() != null && this.getDveQte().equals(castOther.getDveQte())))
				&& ((this.getVenNum() == castOther.getVenNum()) || (this.getVenNum() != null
						&& castOther.getVenNum() != null && this.getVenNum().equals(castOther.getVenNum())))
				&& ((this.getVenMrgCod() == castOther.getVenMrgCod()) || (this.getVenMrgCod() != null
						&& castOther.getVenMrgCod() != null && this.getVenMrgCod().equals(castOther.getVenMrgCod())))
				&& ((this.getCanPrenoms() == castOther.getCanPrenoms())
						|| (this.getCanPrenoms() != null && castOther.getCanPrenoms() != null
								&& this.getCanPrenoms().equals(castOther.getCanPrenoms())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCanNom() == null ? 0 : this.getCanNom().hashCode());
		result = 37 * result + (getCanNomResp() == null ? 0 : this.getCanNomResp().hashCode());
		result = 37 * result + (getCanSouNcc() == null ? 0 : this.getCanSouNcc().hashCode());
		result = 37 * result + (getCanTel() == null ? 0 : this.getCanTel().hashCode());
		result = 37 * result + (getCanTieNcc() == null ? 0 : this.getCanTieNcc().hashCode());
		result = 37 * result + (getDveCout() == null ? 0 : this.getDveCout().hashCode());
		result = 37 * result + (getDveDacCode() == null ? 0 : this.getDveDacCode().hashCode());
		result = 37 * result + (getDveLaaNum() == null ? 0 : this.getDveLaaNum().hashCode());
		result = 37 * result + (getDveQte() == null ? 0 : this.getDveQte().hashCode());
		result = 37 * result + (getVenNum() == null ? 0 : this.getVenNum().hashCode());
		result = 37 * result + (getVenMrgCod() == null ? 0 : this.getVenMrgCod().hashCode());
		result = 37 * result + (getCanPrenoms() == null ? 0 : this.getCanPrenoms().hashCode());
		return result;
	}

}
