package com.sndi.models;
// Generated 23 nov. 2020 12:59:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VbTempParamVente generated by hbm2java
 */
@Entity
@Table(name = "VB_TEMP_PARAM_VENTE", schema = "EMAP")
public class VbTempParamVente implements java.io.Serializable {

	private VbTempParamVenteId id;

	public VbTempParamVente() {
	}

	public VbTempParamVente(VbTempParamVenteId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "canNom", column = @Column(name = "CAN_NOM", length = 500)),
			@AttributeOverride(name = "canNomResp", column = @Column(name = "CAN_NOM_RESP", length = 500)),
			@AttributeOverride(name = "canSouNcc", column = @Column(name = "CAN_SOU_NCC", length = 500)),
			@AttributeOverride(name = "canTel", column = @Column(name = "CAN_TEL", length = 500)),
			@AttributeOverride(name = "canTieNcc", column = @Column(name = "CAN_TIE_NCC", length = 500)),
			@AttributeOverride(name = "dveCout", column = @Column(name = "DVE_COUT", length = 500)),
			@AttributeOverride(name = "dveDacCode", column = @Column(name = "DVE_DAC_CODE", length = 500)),
			@AttributeOverride(name = "dveLaaNum", column = @Column(name = "DVE_LAA_NUM", length = 500)),
			@AttributeOverride(name = "dveQte", column = @Column(name = "DVE_QTE", length = 500)),
			@AttributeOverride(name = "venNum", column = @Column(name = "VEN_NUM", length = 500)),
			@AttributeOverride(name = "venMrgCod", column = @Column(name = "VEN_MRG_COD", length = 500)),
			@AttributeOverride(name = "canPrenoms", column = @Column(name = "CAN_PRENOMS", length = 500)) })
	public VbTempParamVenteId getId() {
		return this.id;
	}

	public void setId(VbTempParamVenteId id) {
		this.id = id;
	}

}
