package com.sndi.models;
// Generated 19 mars 2020 18:39:08 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDetailEtat generated by hbm2java
 */
@Entity
@Table(name = "V_DETAIL_ETAT", schema = "EMAP")
public class VDetailEtat implements java.io.Serializable {

	private VDetailEtatId id;

	public VDetailEtat() {
	}

	public VDetailEtat(VDetailEtatId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "agpId", column = @Column(name = "AGP_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "tcaLibelle", column = @Column(name = "TCA_LIBELLE", length = 200)),
			@AttributeOverride(name = "tdaTitre", column = @Column(name = "TDA_TITRE", length = 100)),
			@AttributeOverride(name = "tdaCommentaire", column = @Column(name = "TDA_COMMENTAIRE", length = 4000)),
			@AttributeOverride(name = "tcaCode", column = @Column(name = "TCA_CODE", length = 4)),
			@AttributeOverride(name = "tdaNumOrdre", column = @Column(name = "TDA_NUM_ORDRE", length = 3)) })
	public VDetailEtatId getId() {
		return this.id;
	}

	public void setId(VDetailEtatId id) {
		this.id = id;
	}

}
