package com.sndi.models;
// Generated 23 mars 2020 10:48:44 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VModePassationPn generated by hbm2java
 */
@Entity
@Table(name = "V_MODE_PASSATION_PN", schema = "EMAP")
public class VModePassationPn implements java.io.Serializable {

	private VModePassationPnId id;

	public VModePassationPn() {
	}

	public VModePassationPn(VModePassationPnId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mopCode", column = @Column(name = "MOP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "mopLibelleCourt", column = @Column(name = "MOP_LIBELLE_COURT", nullable = false, length = 500)),
			@AttributeOverride(name = "mopLibelleLong", column = @Column(name = "MOP_LIBELLE_LONG", length = 1000)) })
	public VModePassationPnId getId() {
		return this.id;
	}

	public void setId(VModePassationPnId id) {
		this.id = id;
	}

}
