package com.sndi.models;
// Generated 4 juil. 2020 18:05:44 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VPieceDac generated by hbm2java
 */
@Entity
@Table(name = "V_PIECE_DAC", schema = "EMAP")
public class VPieceDac implements java.io.Serializable {

	private VPieceDacId id;

	public VPieceDac() {
	}

	public VPieceDac(VPieceDacId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pidCode", column = @Column(name = "PID_CODE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "pidTpiCode", column = @Column(name = "PID_TPI_CODE", length = 10)),
			@AttributeOverride(name = "pidLibelle", column = @Column(name = "PID_LIBELLE", length = 1008)),
			@AttributeOverride(name = "pidDacCode", column = @Column(name = "PID_DAC_CODE", length = 20)),
			@AttributeOverride(name = "tpiMdtCode", column = @Column(name = "TPI_MDT_CODE", length = 10)) })
	public VPieceDacId getId() {
		return this.id;
	}

	public void setId(VPieceDacId id) {
		this.id = id;
	}

}
