package com.sndi.models;
// Generated 4 juil. 2020 18:05:44 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPiecesOffreId generated by hbm2java
 */
@Embeddable
public class VPiecesOffreId implements java.io.Serializable {

	private BigDecimal opdNum;
	private String tpoCode;
	private String opdDacCode;
	private String tpoLibelle;
	private String odpTpoEtapPiece;

	public VPiecesOffreId() {
	}

	public VPiecesOffreId(BigDecimal opdNum, String tpoCode) {
		this.opdNum = opdNum;
		this.tpoCode = tpoCode;
	}

	public VPiecesOffreId(BigDecimal opdNum, String tpoCode, String opdDacCode, String tpoLibelle,
			String odpTpoEtapPiece) {
		this.opdNum = opdNum;
		this.tpoCode = tpoCode;
		this.opdDacCode = opdDacCode;
		this.tpoLibelle = tpoLibelle;
		this.odpTpoEtapPiece = odpTpoEtapPiece;
	}

	@Column(name = "OPD_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOpdNum() {
		return this.opdNum;
	}

	public void setOpdNum(BigDecimal opdNum) {
		this.opdNum = opdNum;
	}

	@Column(name = "TPO_CODE", nullable = false, length = 10)
	public String getTpoCode() {
		return this.tpoCode;
	}

	public void setTpoCode(String tpoCode) {
		this.tpoCode = tpoCode;
	}

	@Column(name = "OPD_DAC_CODE", length = 25)
	public String getOpdDacCode() {
		return this.opdDacCode;
	}

	public void setOpdDacCode(String opdDacCode) {
		this.opdDacCode = opdDacCode;
	}

	@Column(name = "TPO_LIBELLE", length = 200)
	public String getTpoLibelle() {
		return this.tpoLibelle;
	}

	public void setTpoLibelle(String tpoLibelle) {
		this.tpoLibelle = tpoLibelle;
	}

	@Column(name = "ODP_TPO_ETAP_PIECE", length = 20)
	public String getOdpTpoEtapPiece() {
		return this.odpTpoEtapPiece;
	}

	public void setOdpTpoEtapPiece(String odpTpoEtapPiece) {
		this.odpTpoEtapPiece = odpTpoEtapPiece;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPiecesOffreId))
			return false;
		VPiecesOffreId castOther = (VPiecesOffreId) other;

		return ((this.getOpdNum() == castOther.getOpdNum()) || (this.getOpdNum() != null
				&& castOther.getOpdNum() != null && this.getOpdNum().equals(castOther.getOpdNum())))
				&& ((this.getTpoCode() == castOther.getTpoCode()) || (this.getTpoCode() != null
						&& castOther.getTpoCode() != null && this.getTpoCode().equals(castOther.getTpoCode())))
				&& ((this.getOpdDacCode() == castOther.getOpdDacCode()) || (this.getOpdDacCode() != null
						&& castOther.getOpdDacCode() != null && this.getOpdDacCode().equals(castOther.getOpdDacCode())))
				&& ((this.getTpoLibelle() == castOther.getTpoLibelle()) || (this.getTpoLibelle() != null
						&& castOther.getTpoLibelle() != null && this.getTpoLibelle().equals(castOther.getTpoLibelle())))
				&& ((this.getOdpTpoEtapPiece() == castOther.getOdpTpoEtapPiece())
						|| (this.getOdpTpoEtapPiece() != null && castOther.getOdpTpoEtapPiece() != null
								&& this.getOdpTpoEtapPiece().equals(castOther.getOdpTpoEtapPiece())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOpdNum() == null ? 0 : this.getOpdNum().hashCode());
		result = 37 * result + (getTpoCode() == null ? 0 : this.getTpoCode().hashCode());
		result = 37 * result + (getOpdDacCode() == null ? 0 : this.getOpdDacCode().hashCode());
		result = 37 * result + (getTpoLibelle() == null ? 0 : this.getTpoLibelle().hashCode());
		result = 37 * result + (getOdpTpoEtapPiece() == null ? 0 : this.getOdpTpoEtapPiece().hashCode());
		return result;
	}

}
