package com.sndi.models;
// Generated 20 juin 2020 17:16:02 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUpdatePgpm generated by hbm2java
 */
@Entity
@Table(name = "V_UPDATE_PGPM", schema = "EMAP")
public class VUpdatePgpm implements java.io.Serializable {

	private VUpdatePgpmId id;

	public VUpdatePgpm() {
	}

	public VUpdatePgpm(VUpdatePgpmId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "gpgId", column = @Column(name = "GPG_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "gpgPlgId", column = @Column(name = "GPG_PLG_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "gpgAgpId", column = @Column(name = "GPG_AGP_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "gpgTypePlan", column = @Column(name = "GPG_TYPE_PLAN", nullable = false, length = 3)),
			@AttributeOverride(name = "gpgStaCode", column = @Column(name = "GPG_STA_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "gpgTymCode", column = @Column(name = "GPG_TYM_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "gpgMopCode", column = @Column(name = "GPG_MOP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "gpgCode", column = @Column(name = "GPG_CODE", length = 50)),
			@AttributeOverride(name = "gpgObjet", column = @Column(name = "GPG_OBJET", length = 1000)),
			@AttributeOverride(name = "gpgNumeroOrdre", column = @Column(name = "GPG_NUMERO_ORDRE", precision = 8, scale = 0)),
			@AttributeOverride(name = "gpgPartiePmePmi", column = @Column(name = "GPG_PARTIE_PME_PMI", length = 1)),
			@AttributeOverride(name = "gpgCommentaire", column = @Column(name = "GPG_COMMENTAIRE", length = 1000)),
			@AttributeOverride(name = "gpgSourceFin", column = @Column(name = "GPG_SOURCE_FIN", length = 1000)),
			@AttributeOverride(name = "gpgDateDao", column = @Column(name = "GPG_DATE_DAO", length = 7)),
			@AttributeOverride(name = "gpgActeurSaisie", column = @Column(name = "GPG_ACTEUR_SAISIE", length = 12)),
			@AttributeOverride(name = "gpgStatutRetour", column = @Column(name = "GPG_STATUT_RETOUR", length = 4)),
			@AttributeOverride(name = "gpgDateSaisie", column = @Column(name = "GPG_DATE_SAISIE", length = 7)),
			@AttributeOverride(name = "gpgStrCode", column = @Column(name = "GPG_STR_CODE", length = 20)),
			@AttributeOverride(name = "gpgDateValAc", column = @Column(name = "GPG_DATE_VAL_AC", length = 7)),
			@AttributeOverride(name = "gpgDateValCpmp", column = @Column(name = "GPG_DATE_VAL_CPMP", length = 7)),
			@AttributeOverride(name = "gpgDateValDmp", column = @Column(name = "GPG_DATE_VAL_DMP", length = 7)),
			@AttributeOverride(name = "gpgLibFin", column = @Column(name = "GPG_LIB_FIN", length = 200)),
			@AttributeOverride(name = "gpgDteModif", column = @Column(name = "GPG_DTE_MODIF", length = 7)),
			@AttributeOverride(name = "gpgFonCodPf", column = @Column(name = "GPG_FON_COD_PF", length = 20)),
			@AttributeOverride(name = "gpgFonCodDmp", column = @Column(name = "GPG_FON_COD_DMP", length = 20)),
			@AttributeOverride(name = "gpgRecherche", column = @Column(name = "GPG_RECHERCHE", length = 4000)),
			@AttributeOverride(name = "fipId", column = @Column(name = "FIP_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "fipDevCode", column = @Column(name = "FIP_DEV_CODE", length = 8)),
			@AttributeOverride(name = "fipBaiCode", column = @Column(name = "FIP_BAI_CODE", length = 5)),
			@AttributeOverride(name = "fipSouCode", column = @Column(name = "FIP_SOU_CODE", length = 5)),
			@AttributeOverride(name = "fipGpgId", column = @Column(name = "FIP_GPG_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "fipMontantCfa", column = @Column(name = "FIP_MONTANT_CFA", precision = 15)),
			@AttributeOverride(name = "fipMontantDevise", column = @Column(name = "FIP_MONTANT_DEVISE", precision = 15)),
			@AttributeOverride(name = "fipCommentaire", column = @Column(name = "FIP_COMMENTAIRE", length = 500)),
			@AttributeOverride(name = "fipTypeFinance", column = @Column(name = "FIP_TYPE_FINANCE", length = 20)),
			@AttributeOverride(name = "fipTresor", column = @Column(name = "FIP_TRESOR", precision = 22, scale = 0)),
			@AttributeOverride(name = "mopCode", column = @Column(name = "MOP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "mopLibelleCourt", column = @Column(name = "MOP_LIBELLE_COURT", nullable = false, length = 500)),
			@AttributeOverride(name = "mopLibelleLong", column = @Column(name = "MOP_LIBELLE_LONG", length = 1000)),
			@AttributeOverride(name = "tymCode", column = @Column(name = "TYM_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "tymLibelleCourt", column = @Column(name = "TYM_LIBELLE_COURT", nullable = false, length = 500)),
			@AttributeOverride(name = "tymLibelleLong", column = @Column(name = "TYM_LIBELLE_LONG", length = 1000)),
			@AttributeOverride(name = "tymTymCode", column = @Column(name = "TYM_TYM_CODE", length = 3)),
			@AttributeOverride(name = "tymGroupe", column = @Column(name = "TYM_GROUPE", length = 2)) })
	public VUpdatePgpmId getId() {
		return this.id;
	}

	public void setId(VUpdatePgpmId id) {
		this.id = id;
	}

}
