package com.sndi.model;
// Generated 12 août 2021 18:57:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbAttributionsId generated by hbm2java
 */
@Entity
@Table(name = "T_ATTRIBUTIONS")
public class TAttributions implements java.io.Serializable {

	private BigDecimal attNum;
	private String attStaCode;
	private String attFonCodeCojo;
	private String attDofAaoCode;
	private BigDecimal attDofOffNum;
	private String attDacCode;
	private short attDofLaaNum;
	private String attFonCode;
	private String attBanCode;
	private Long attPvNum;
	private String attFonCodeDmp;
	private Date attDteVal;
	private Date attDteCojo;
	private String attDofLaaAaoNumSeq;
	private Date attDteRef;
	private Date attDteAtt;
	private Date attDteSaisi;
	private String attMotifRef;
	private String attFonCodeRef;
	private String attFonCodeAtt;
	private String attFonCodeSaisi;
	private Date attDteRej;
	private String attMotifRej;
	private String attFonCodeRej;
	private String attDef;
	private String attLaaBenCode;
	private String attLaaBenCodeAc;
	private String attSouNcc;
	private Date attDteValCom;
	private String attMotifValCom;
	private String attMotifVal;
	private Date attDteRefCom;
	private String attFonCodeValCom;
	private String attFonCodeRefCom;
	private String attMotifRefCom;
	private String attLaaBenCodeRej;
	private String attLaaBenCodeAcRej;
	private Date attDteStaCour;
	private Date attDteRecPhysRecvblProv;
	private Date attDteRecAttribProv;
	private Date attDteRetAttribProv;
	private String attFonCodeRec;
	private String attFonCodeRet;
	private String attObsRec;
	private String attMotifRet;
	private String attDmp;
	private String attBai;
	private String attCom;
	private BigDecimal attDofNum;
	private String attFonCodeAttAct;
	private Integer attGroupNum;
	private Long attDemNumDerog;
	private BigDecimal attLaaId;
	private String attOpeMatricule;
	private BigDecimal attMtAttr;
	private String attCommentaire;
	private String attReserve;

	public void VbAttributions() {
	}

	public void VbAttributions(BigDecimal attNum, String attStaCode, String attDofAaoCode, BigDecimal attDofOffNum,
			short attDofLaaNum, BigDecimal attDofNum) {
		this.attNum = attNum;
		this.attStaCode = attStaCode;
		this.attDofAaoCode = attDofAaoCode;
		this.attDofOffNum = attDofOffNum;
		this.attDofLaaNum = attDofLaaNum;
		this.attDofNum = attDofNum;
	}

	public void VbAttributions(BigDecimal attNum, String attStaCode, String attFonCodeCojo, String attDofAaoCode,
			BigDecimal attDofOffNum, String attDacCode, short attDofLaaNum, String attFonCode, String attBanCode,
			Long attPvNum, String attFonCodeDmp, Date attDteVal, Date attDteCojo, String attDofLaaAaoNumSeq,
			Date attDteRef, Date attDteAtt, Date attDteSaisi, String attMotifRef, String attFonCodeRef,
			String attFonCodeAtt, String attFonCodeSaisi, Date attDteRej, String attMotifRej, String attFonCodeRej,
			String attDef, String attLaaBenCode, String attLaaBenCodeAc, String attSouNcc, Date attDteValCom,
			String attMotifValCom, String attMotifVal, Date attDteRefCom, String attFonCodeValCom,
			String attFonCodeRefCom, String attMotifRefCom, String attLaaBenCodeRej, String attLaaBenCodeAcRej,
			Date attDteStaCour, Date attDteRecPhysRecvblProv, Date attDteRecAttribProv, Date attDteRetAttribProv,
			String attFonCodeRec, String attFonCodeRet, String attObsRec, String attMotifRet, String attDmp,
			String attBai, String attCom, BigDecimal attDofNum, String attFonCodeAttAct, Integer attGroupNum,
			Long attDemNumDerog, BigDecimal attLaaId, String attOpeMatricule, BigDecimal attMtAttr,
			String attCommentaire, String attReserve) {
		this.attNum = attNum;
		this.attStaCode = attStaCode;
		this.attFonCodeCojo = attFonCodeCojo;
		this.attDofAaoCode = attDofAaoCode;
		this.attDofOffNum = attDofOffNum;
		this.attDacCode = attDacCode;
		this.attDofLaaNum = attDofLaaNum;
		this.attFonCode = attFonCode;
		this.attBanCode = attBanCode;
		this.attPvNum = attPvNum;
		this.attFonCodeDmp = attFonCodeDmp;
		this.attDteVal = attDteVal;
		this.attDteCojo = attDteCojo;
		this.attDofLaaAaoNumSeq = attDofLaaAaoNumSeq;
		this.attDteRef = attDteRef;
		this.attDteAtt = attDteAtt;
		this.attDteSaisi = attDteSaisi;
		this.attMotifRef = attMotifRef;
		this.attFonCodeRef = attFonCodeRef;
		this.attFonCodeAtt = attFonCodeAtt;
		this.attFonCodeSaisi = attFonCodeSaisi;
		this.attDteRej = attDteRej;
		this.attMotifRej = attMotifRej;
		this.attFonCodeRej = attFonCodeRej;
		this.attDef = attDef;
		this.attLaaBenCode = attLaaBenCode;
		this.attLaaBenCodeAc = attLaaBenCodeAc;
		this.attSouNcc = attSouNcc;
		this.attDteValCom = attDteValCom;
		this.attMotifValCom = attMotifValCom;
		this.attMotifVal = attMotifVal;
		this.attDteRefCom = attDteRefCom;
		this.attFonCodeValCom = attFonCodeValCom;
		this.attFonCodeRefCom = attFonCodeRefCom;
		this.attMotifRefCom = attMotifRefCom;
		this.attLaaBenCodeRej = attLaaBenCodeRej;
		this.attLaaBenCodeAcRej = attLaaBenCodeAcRej;
		this.attDteStaCour = attDteStaCour;
		this.attDteRecPhysRecvblProv = attDteRecPhysRecvblProv;
		this.attDteRecAttribProv = attDteRecAttribProv;
		this.attDteRetAttribProv = attDteRetAttribProv;
		this.attFonCodeRec = attFonCodeRec;
		this.attFonCodeRet = attFonCodeRet;
		this.attObsRec = attObsRec;
		this.attMotifRet = attMotifRet;
		this.attDmp = attDmp;
		this.attBai = attBai;
		this.attCom = attCom;
		this.attDofNum = attDofNum;
		this.attFonCodeAttAct = attFonCodeAttAct;
		this.attGroupNum = attGroupNum;
		this.attDemNumDerog = attDemNumDerog;
		this.attLaaId = attLaaId;
		this.attOpeMatricule = attOpeMatricule;
		this.attMtAttr = attMtAttr;
		this.attCommentaire = attCommentaire;
		this.attReserve = attReserve;
	}

	@Id
	@Column(name = "ATT_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAttNum() {
		return this.attNum;
	}

	public void setAttNum(BigDecimal attNum) {
		this.attNum = attNum;
	}

	@Column(name = "ATT_STA_CODE", nullable = false, length = 3)
	public String getAttStaCode() {
		return this.attStaCode;
	}

	public void setAttStaCode(String attStaCode) {
		this.attStaCode = attStaCode;
	}

	@Column(name = "ATT_FON_CODE_COJO", length = 50)
	public String getAttFonCodeCojo() {
		return this.attFonCodeCojo;
	}

	public void setAttFonCodeCojo(String attFonCodeCojo) {
		this.attFonCodeCojo = attFonCodeCojo;
	}

	@Column(name = "ATT_DOF_AAO_CODE", nullable = false, length = 20)
	public String getAttDofAaoCode() {
		return this.attDofAaoCode;
	}

	public void setAttDofAaoCode(String attDofAaoCode) {
		this.attDofAaoCode = attDofAaoCode;
	}

	@Column(name = "ATT_DOF_OFF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAttDofOffNum() {
		return this.attDofOffNum;
	}

	public void setAttDofOffNum(BigDecimal attDofOffNum) {
		this.attDofOffNum = attDofOffNum;
	}

	@Column(name = "ATT_DAC_CODE", length = 25)
	public String getAttDacCode() {
		return this.attDacCode;
	}

	public void setAttDacCode(String attDacCode) {
		this.attDacCode = attDacCode;
	}

	@Column(name = "ATT_DOF_LAA_NUM", nullable = false, precision = 3, scale = 0)
	public short getAttDofLaaNum() {
		return this.attDofLaaNum;
	}

	public void setAttDofLaaNum(short attDofLaaNum) {
		this.attDofLaaNum = attDofLaaNum;
	}

	@Column(name = "ATT_FON_CODE", length = 50)
	public String getAttFonCode() {
		return this.attFonCode;
	}

	public void setAttFonCode(String attFonCode) {
		this.attFonCode = attFonCode;
	}

	@Column(name = "ATT_BAN_CODE", length = 10)
	public String getAttBanCode() {
		return this.attBanCode;
	}

	public void setAttBanCode(String attBanCode) {
		this.attBanCode = attBanCode;
	}

	@Column(name = "ATT_PV_NUM", precision = 10, scale = 0)
	public Long getAttPvNum() {
		return this.attPvNum;
	}

	public void setAttPvNum(Long attPvNum) {
		this.attPvNum = attPvNum;
	}

	@Column(name = "ATT_FON_CODE_DMP", length = 50)
	public String getAttFonCodeDmp() {
		return this.attFonCodeDmp;
	}

	public void setAttFonCodeDmp(String attFonCodeDmp) {
		this.attFonCodeDmp = attFonCodeDmp;
	}

	@Column(name = "ATT_DTE_VAL", length = 7)
	public Date getAttDteVal() {
		return this.attDteVal;
	}

	public void setAttDteVal(Date attDteVal) {
		this.attDteVal = attDteVal;
	}

	@Column(name = "ATT_DTE_COJO", length = 7)
	public Date getAttDteCojo() {
		return this.attDteCojo;
	}

	public void setAttDteCojo(Date attDteCojo) {
		this.attDteCojo = attDteCojo;
	}

	@Column(name = "ATT_DOF_LAA_AAO_NUM_SEQ", length = 10)
	public String getAttDofLaaAaoNumSeq() {
		return this.attDofLaaAaoNumSeq;
	}

	public void setAttDofLaaAaoNumSeq(String attDofLaaAaoNumSeq) {
		this.attDofLaaAaoNumSeq = attDofLaaAaoNumSeq;
	}

	@Column(name = "ATT_DTE_REF", length = 7)
	public Date getAttDteRef() {
		return this.attDteRef;
	}

	public void setAttDteRef(Date attDteRef) {
		this.attDteRef = attDteRef;
	}

	@Column(name = "ATT_DTE_ATT", length = 7)
	public Date getAttDteAtt() {
		return this.attDteAtt;
	}

	public void setAttDteAtt(Date attDteAtt) {
		this.attDteAtt = attDteAtt;
	}

	@Column(name = "ATT_DTE_SAISI", length = 7)
	public Date getAttDteSaisi() {
		return this.attDteSaisi;
	}

	public void setAttDteSaisi(Date attDteSaisi) {
		this.attDteSaisi = attDteSaisi;
	}

	@Column(name = "ATT_MOTIF_REF", length = 240)
	public String getAttMotifRef() {
		return this.attMotifRef;
	}

	public void setAttMotifRef(String attMotifRef) {
		this.attMotifRef = attMotifRef;
	}

	@Column(name = "ATT_FON_CODE_REF", length = 50)
	public String getAttFonCodeRef() {
		return this.attFonCodeRef;
	}

	public void setAttFonCodeRef(String attFonCodeRef) {
		this.attFonCodeRef = attFonCodeRef;
	}

	@Column(name = "ATT_FON_CODE_ATT", length = 50)
	public String getAttFonCodeAtt() {
		return this.attFonCodeAtt;
	}

	public void setAttFonCodeAtt(String attFonCodeAtt) {
		this.attFonCodeAtt = attFonCodeAtt;
	}

	@Column(name = "ATT_FON_CODE_SAISI", length = 50)
	public String getAttFonCodeSaisi() {
		return this.attFonCodeSaisi;
	}

	public void setAttFonCodeSaisi(String attFonCodeSaisi) {
		this.attFonCodeSaisi = attFonCodeSaisi;
	}

	@Column(name = "ATT_DTE_REJ", length = 7)
	public Date getAttDteRej() {
		return this.attDteRej;
	}

	public void setAttDteRej(Date attDteRej) {
		this.attDteRej = attDteRej;
	}

	@Column(name = "ATT_MOTIF_REJ", length = 240)
	public String getAttMotifRej() {
		return this.attMotifRej;
	}

	public void setAttMotifRej(String attMotifRej) {
		this.attMotifRej = attMotifRej;
	}

	@Column(name = "ATT_FON_CODE_REJ", length = 50)
	public String getAttFonCodeRej() {
		return this.attFonCodeRej;
	}

	public void setAttFonCodeRej(String attFonCodeRej) {
		this.attFonCodeRej = attFonCodeRej;
	}

	@Column(name = "ATT_DEF", length = 1)
	public String getAttDef() {
		return this.attDef;
	}

	public void setAttDef(String attDef) {
		this.attDef = attDef;
	}

	@Column(name = "ATT_LAA_BEN_CODE", length = 20)
	public String getAttLaaBenCode() {
		return this.attLaaBenCode;
	}

	public void setAttLaaBenCode(String attLaaBenCode) {
		this.attLaaBenCode = attLaaBenCode;
	}

	@Column(name = "ATT_LAA_BEN_CODE_AC", length = 20)
	public String getAttLaaBenCodeAc() {
		return this.attLaaBenCodeAc;
	}

	public void setAttLaaBenCodeAc(String attLaaBenCodeAc) {
		this.attLaaBenCodeAc = attLaaBenCodeAc;
	}

	@Column(name = "ATT_SOU_NCC", length = 20)
	public String getAttSouNcc() {
		return this.attSouNcc;
	}

	public void setAttSouNcc(String attSouNcc) {
		this.attSouNcc = attSouNcc;
	}

	@Column(name = "ATT_DTE_VAL_COM", length = 7)
	public Date getAttDteValCom() {
		return this.attDteValCom;
	}

	public void setAttDteValCom(Date attDteValCom) {
		this.attDteValCom = attDteValCom;
	}

	@Column(name = "ATT_MOTIF_VAL_COM", length = 240)
	public String getAttMotifValCom() {
		return this.attMotifValCom;
	}

	public void setAttMotifValCom(String attMotifValCom) {
		this.attMotifValCom = attMotifValCom;
	}

	@Column(name = "ATT_MOTIF_VAL", length = 240)
	public String getAttMotifVal() {
		return this.attMotifVal;
	}

	public void setAttMotifVal(String attMotifVal) {
		this.attMotifVal = attMotifVal;
	}

	@Column(name = "ATT_DTE_REF_COM", length = 7)
	public Date getAttDteRefCom() {
		return this.attDteRefCom;
	}

	public void setAttDteRefCom(Date attDteRefCom) {
		this.attDteRefCom = attDteRefCom;
	}

	@Column(name = "ATT_FON_CODE_VAL_COM", length = 50)
	public String getAttFonCodeValCom() {
		return this.attFonCodeValCom;
	}

	public void setAttFonCodeValCom(String attFonCodeValCom) {
		this.attFonCodeValCom = attFonCodeValCom;
	}

	@Column(name = "ATT_FON_CODE_REF_COM", length = 50)
	public String getAttFonCodeRefCom() {
		return this.attFonCodeRefCom;
	}

	public void setAttFonCodeRefCom(String attFonCodeRefCom) {
		this.attFonCodeRefCom = attFonCodeRefCom;
	}

	@Column(name = "ATT_MOTIF_REF_COM", length = 240)
	public String getAttMotifRefCom() {
		return this.attMotifRefCom;
	}

	public void setAttMotifRefCom(String attMotifRefCom) {
		this.attMotifRefCom = attMotifRefCom;
	}

	@Column(name = "ATT_LAA_BEN_CODE_REJ", length = 20)
	public String getAttLaaBenCodeRej() {
		return this.attLaaBenCodeRej;
	}

	public void setAttLaaBenCodeRej(String attLaaBenCodeRej) {
		this.attLaaBenCodeRej = attLaaBenCodeRej;
	}

	@Column(name = "ATT_LAA_BEN_CODE_AC_REJ", length = 20)
	public String getAttLaaBenCodeAcRej() {
		return this.attLaaBenCodeAcRej;
	}

	public void setAttLaaBenCodeAcRej(String attLaaBenCodeAcRej) {
		this.attLaaBenCodeAcRej = attLaaBenCodeAcRej;
	}

	@Column(name = "ATT_DTE_STA_COUR", length = 7)
	public Date getAttDteStaCour() {
		return this.attDteStaCour;
	}

	public void setAttDteStaCour(Date attDteStaCour) {
		this.attDteStaCour = attDteStaCour;
	}

	@Column(name = "ATT_DTE_REC_PHYS_RECVBL_PROV", length = 7)
	public Date getAttDteRecPhysRecvblProv() {
		return this.attDteRecPhysRecvblProv;
	}

	public void setAttDteRecPhysRecvblProv(Date attDteRecPhysRecvblProv) {
		this.attDteRecPhysRecvblProv = attDteRecPhysRecvblProv;
	}

	@Column(name = "ATT_DTE_REC_ATTRIB_PROV", length = 7)
	public Date getAttDteRecAttribProv() {
		return this.attDteRecAttribProv;
	}

	public void setAttDteRecAttribProv(Date attDteRecAttribProv) {
		this.attDteRecAttribProv = attDteRecAttribProv;
	}

	@Column(name = "ATT_DTE_RET_ATTRIB_PROV", length = 7)
	public Date getAttDteRetAttribProv() {
		return this.attDteRetAttribProv;
	}

	public void setAttDteRetAttribProv(Date attDteRetAttribProv) {
		this.attDteRetAttribProv = attDteRetAttribProv;
	}

	@Column(name = "ATT_FON_CODE_REC", length = 50)
	public String getAttFonCodeRec() {
		return this.attFonCodeRec;
	}

	public void setAttFonCodeRec(String attFonCodeRec) {
		this.attFonCodeRec = attFonCodeRec;
	}

	@Column(name = "ATT_FON_CODE_RET", length = 50)
	public String getAttFonCodeRet() {
		return this.attFonCodeRet;
	}

	public void setAttFonCodeRet(String attFonCodeRet) {
		this.attFonCodeRet = attFonCodeRet;
	}

	@Column(name = "ATT_OBS_REC", length = 240)
	public String getAttObsRec() {
		return this.attObsRec;
	}

	public void setAttObsRec(String attObsRec) {
		this.attObsRec = attObsRec;
	}

	@Column(name = "ATT_MOTIF_RET", length = 240)
	public String getAttMotifRet() {
		return this.attMotifRet;
	}

	public void setAttMotifRet(String attMotifRet) {
		this.attMotifRet = attMotifRet;
	}

	@Column(name = "ATT_DMP", length = 1)
	public String getAttDmp() {
		return this.attDmp;
	}

	public void setAttDmp(String attDmp) {
		this.attDmp = attDmp;
	}

	@Column(name = "ATT_BAI", length = 1)
	public String getAttBai() {
		return this.attBai;
	}

	public void setAttBai(String attBai) {
		this.attBai = attBai;
	}

	@Column(name = "ATT_COM", length = 1)
	public String getAttCom() {
		return this.attCom;
	}

	public void setAttCom(String attCom) {
		this.attCom = attCom;
	}

	@Column(name = "ATT_DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAttDofNum() {
		return this.attDofNum;
	}

	public void setAttDofNum(BigDecimal attDofNum) {
		this.attDofNum = attDofNum;
	}

	@Column(name = "ATT_FON_CODE_ATT_ACT", length = 50)
	public String getAttFonCodeAttAct() {
		return this.attFonCodeAttAct;
	}

	public void setAttFonCodeAttAct(String attFonCodeAttAct) {
		this.attFonCodeAttAct = attFonCodeAttAct;
	}

	@Column(name = "ATT_GROUP_NUM", precision = 5, scale = 0)
	public Integer getAttGroupNum() {
		return this.attGroupNum;
	}

	public void setAttGroupNum(Integer attGroupNum) {
		this.attGroupNum = attGroupNum;
	}

	@Column(name = "ATT_DEM_NUM_DEROG", precision = 10, scale = 0)
	public Long getAttDemNumDerog() {
		return this.attDemNumDerog;
	}

	public void setAttDemNumDerog(Long attDemNumDerog) {
		this.attDemNumDerog = attDemNumDerog;
	}

	@Column(name = "ATT_LAA_ID", precision = 22, scale = 0)
	public BigDecimal getAttLaaId() {
		return this.attLaaId;
	}

	public void setAttLaaId(BigDecimal attLaaId) {
		this.attLaaId = attLaaId;
	}

	@Column(name = "ATT_OPE_MATRICULE", length = 25)
	public String getAttOpeMatricule() {
		return this.attOpeMatricule;
	}

	public void setAttOpeMatricule(String attOpeMatricule) {
		this.attOpeMatricule = attOpeMatricule;
	}

	@Column(name = "ATT_MT_ATTR", precision = 22, scale = 0)
	public BigDecimal getAttMtAttr() {
		return this.attMtAttr;
	}

	public void setAttMtAttr(BigDecimal attMtAttr) {
		this.attMtAttr = attMtAttr;
	}

	@Column(name = "ATT_COMMENTAIRE", length = 4000)
	public String getAttCommentaire() {
		return this.attCommentaire;
	}

	public void setAttCommentaire(String attCommentaire) {
		this.attCommentaire = attCommentaire;
	}

	@Column(name = "ATT_RESERVE", length = 20)
	public String getAttReserve() {
		return this.attReserve;
	}

	public void setAttReserve(String attReserve) {
		this.attReserve = attReserve;
	}

}
