package com.sndi.model;
// Generated 30 nov. 2019 13:40:49 by Hibernate Tools 4.3.5.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCharge generated by hbm2java
 */
@Entity
@Table(name = "T_CHARGE", schema = "EMAP")
public class TCharge implements java.io.Serializable {

	private long chrId;
	private TDetailPlanPassation TDetailPlanPassation;
	private TTypeCharge TTypeCharge;
	private TStructure TStructure;
	private String chrCommentaire;
	private String chrStatut;

	public TCharge() {
	}
	
	public TCharge(long chrId) {
		this.chrId = chrId;
	}

	public TCharge(long chrId, TDetailPlanPassation TDetailPlanPassation, TTypeCharge TTypeCharge,
			TStructure TStructure) {
		this.chrId = chrId;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TTypeCharge = TTypeCharge;
		this.TStructure = TStructure;
	}

	public TCharge(long chrId, TDetailPlanPassation TDetailPlanPassation, TTypeCharge TTypeCharge,
			TStructure TStructure, String chrCommentaire, String chrStatut) {
		this.chrId = chrId;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TTypeCharge = TTypeCharge;
		this.TStructure = TStructure;
		this.chrCommentaire = chrCommentaire;
		this.chrStatut = chrStatut;
	}

	@Id
	@SequenceGenerator(name = "SEQ_CHR_Sequence", sequenceName = "SEQ_CHR", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_CHR_Sequence")
	@Column(name = "CHR_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getChrId() {
		return this.chrId;
	}

	public void setChrId(long chrId) {
		this.chrId = chrId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CHR_DPP_ID", nullable = false)
	public TDetailPlanPassation getTDetailPlanPassation() {
		return this.TDetailPlanPassation;
	}

	public void setTDetailPlanPassation(TDetailPlanPassation TDetailPlanPassation) {
		this.TDetailPlanPassation = TDetailPlanPassation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CHR_TYC_CODE", nullable = false)
	public TTypeCharge getTTypeCharge() {
		return this.TTypeCharge;
	}

	public void setTTypeCharge(TTypeCharge TTypeCharge) {
		this.TTypeCharge = TTypeCharge;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CHR_STR_CODE", nullable = false)
	public TStructure getTStructure() {
		return this.TStructure;
	}

	public void setTStructure(TStructure TStructure) {
		this.TStructure = TStructure;
	}

	@Column(name = "CHR_COMMENTAIRE", length = 1000)
	public String getChrCommentaire() {
		return this.chrCommentaire;
	}

	public void setChrCommentaire(String chrCommentaire) {
		this.chrCommentaire = chrCommentaire;
	}

	@Column(name = "CHR_STATUT", length = 1)
	public String getChrStatut() {
		return this.chrStatut;
	}

	public void setChrStatut(String chrStatut) {
		this.chrStatut = chrStatut;
	}

}
