package com.sndi.model;
// Generated 23 janv. 2020 16:59:48 by Hibernate Tools 4.3.5.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * TDacSpecsId generated by hbm2java
 */
@Entity
@Table(name = "T_DAC_SPECS", schema = "EMAP")
public class TDacSpecs implements java.io.Serializable {

	private String dacCode;
	private TFonction TFonctionByDacFonCodeCpmp;
	private TFonction TFonctionByDacFonCodAc;
	private TModePassation TModePassation;
	private TStatut TStatut;
	private TStructure TStructure;
	private TGestion TGestion;
	private TTypeMarche TTypeMarche;
	private TModeleDacType TModeleDacType;
	private TTypeDacSpecs TTypeDacSpecs;
	private String dacObjet;
	private Date dacDteSaisi;
	private Long dacNbrOuv;
	private Date dacDteValCpmp;
	private Date dacDteValDmp;
	private Date dacDateReception;
	private String dacStatutRetour;
	private String dacMention;
	private Date dacDateValAc;
	private String dacAvisBailleur;
	private Date dacDateAvisBailleur;
	private String dacBailleur;
	private Long dacCout;
	private String dacTypePlan;
	private String dacRecherche;
	private String dacFonCodeDmp;
	private String dacFonCodePf;
	private long dacFactoriseCrit;
	private Long dacNbreAchat;
	private String dacAutComSpec;
	private BigDecimal dacNbrCopieOff;
	private String dacFinancement;
	private String dacCraCodeExclus;
	private String dacMargePrefCom;
	private String dacMargePrefSou;
	private String dacMargePrefArt;
	private BigDecimal dacMargePrefComVal;
	private BigDecimal dacMargePrefSouVal;
	private BigDecimal dacMargePrefArtVal;
	private String dacMargePref;
	private String dacMotif;
	private Set<TAvisAppelOffre> TAvisAppelOffres = new HashSet<TAvisAppelOffre>(0);
	private Set<TDossierDacs> TDossierDacses = new HashSet<TDossierDacs>(0);
	private Set<TDetailCorrection> TDetailCorrections = new HashSet<TDetailCorrection>(0);
	private Set<TCorrectionDac> TCorrectionDacs = new HashSet<TCorrectionDac>(0);
	private Set<TDetailAvis> TDetailAvises = new HashSet<TDetailAvis>(0);
	private Set<TDetCommissionSeance> TDetCommissionSeances = new HashSet<TDetCommissionSeance>(0);
	private Set<THistoDac> THistoDacs = new HashSet<THistoDac>(0);
	private Set<TPiecesOffres> TPiecesOffres = new HashSet<TPiecesOffres>(0);

	public TDacSpecs() {
	}

	public TDacSpecs(String dacCode) {
		this.dacCode = dacCode;
	}

	public TDacSpecs(String dacCode, TFonction TFonctionByDacFonCodeCpmp, TFonction TFonctionByDacFonCodAc,
			TModePassation TModePassation, TStatut TStatut, TStructure TStructure,
			TGestion TGestion, TTypeMarche TTypeMarche, TModeleDacType TModeleDacType, TTypeDacSpecs TTypeDacSpecs, String dacObjet, Date dacDteSaisi, 
			Long dacNbrOuv,  Date dacDteValCpmp, Date dacDteValDmp,  Date dacDateReception,
			String dacStatutRetour,String dacMention,Date dacDateValAc, String dacAvisBailleur,
			Date dacDateAvisBailleur,String dacBailleur,String dacRecherche,String dacFonCodeDmp, String dacFonCodePf, Long dacCout,String dacTypePlan,
			long dacFactoriseCrit, Long dacNbreAchat,String dacAutComSpec,BigDecimal dacNbrCopieOff,String dacFinancement,String dacCraCodeExclus,
			String dacMargePrefCom, String dacMargePrefSou, String dacMargePrefArt, BigDecimal dacMargePrefComVal,
			BigDecimal dacMargePrefSouVal, BigDecimal dacMargePrefArtVal, String dacMargePref,
			Set<TAvisAppelOffre> TAvisAppelOffres, Set<TDossierDacs> TDossierDacses, String dacMotif,
			Set<TDetailCorrection> TDetailCorrections, Set<TPiecesOffres> TPiecesOffres, Set<TCorrectionDac> TCorrectionDacs,
			Set<TDetailAvis> TDetailAvises, Set<TDetCommissionSeance> TDetCommissionSeances,Set<THistoDac> THistoDacs) {
		this.dacCode = dacCode;
		this.TFonctionByDacFonCodeCpmp = TFonctionByDacFonCodeCpmp;
		this.TFonctionByDacFonCodAc = TFonctionByDacFonCodAc;
		this.TModePassation = TModePassation;
		this.TStatut = TStatut;
		this.TStructure = TStructure;
		this.TGestion = TGestion;
		this.TTypeMarche = TTypeMarche;
		this.TModeleDacType = TModeleDacType;
		this.TTypeDacSpecs = TTypeDacSpecs;
		this.dacObjet = dacObjet;
		this.dacDteSaisi = dacDteSaisi;
		this.dacNbrOuv = dacNbrOuv;
		this.dacDteValCpmp = dacDteValCpmp;
		this.dacDteValDmp = dacDteValDmp;
		this.dacDateReception = dacDateReception;
		this.dacStatutRetour = dacStatutRetour;
		this.dacMention = dacMention;
		this.dacDateValAc = dacDateValAc;
		this.dacAvisBailleur = dacAvisBailleur;
		this.dacDateAvisBailleur = dacDateAvisBailleur;
		this.dacBailleur = dacBailleur;
		this.dacCout = dacCout;
		this.dacTypePlan = dacTypePlan;
		this.dacFactoriseCrit = dacFactoriseCrit;
		this.dacNbreAchat = dacNbreAchat;
		this.dacAutComSpec = dacAutComSpec;
		this.dacNbrCopieOff = dacNbrCopieOff;
		this.dacFinancement = dacFinancement;
		this.dacCraCodeExclus = dacCraCodeExclus;
		this.dacRecherche = dacRecherche;
		this.dacFonCodeDmp = dacFonCodeDmp;
		this.dacFonCodePf = dacFonCodePf;
		this.dacMargePrefCom = dacMargePrefCom;
		this.dacMargePrefSou = dacMargePrefSou;
		this.dacMargePrefArt = dacMargePrefArt;
		this.dacMargePrefComVal = dacMargePrefComVal;
		this.dacMargePrefSouVal = dacMargePrefSouVal;
		this.dacMargePrefArtVal = dacMargePrefArtVal;
		this.dacMargePref = dacMargePref;
		this.dacMotif = dacMotif;
		this.TAvisAppelOffres = TAvisAppelOffres;
		this.TDossierDacses = TDossierDacses;
		this.TDetailCorrections = TDetailCorrections;
		this.TCorrectionDacs = TCorrectionDacs;
		this.TDetailAvises = TDetailAvises;
		this.TDetCommissionSeances = TDetCommissionSeances;
		this.THistoDacs = THistoDacs;
		this.setTPiecesOffres(TPiecesOffres);
	}

	@Id
	@Column(name = "DAC_CODE", unique = true, nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_FON_CODE_CPMP")
	public TFonction getTFonctionByDacFonCodeCpmp() {
		return this.TFonctionByDacFonCodeCpmp;
	}

	public void setTFonctionByDacFonCodeCpmp(TFonction TFonctionByDacFonCodeCpmp) {
		this.TFonctionByDacFonCodeCpmp = TFonctionByDacFonCodeCpmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_FON_COD_AC")
	public TFonction getTFonctionByDacFonCodAc() {
		return this.TFonctionByDacFonCodAc;
	}

	public void setTFonctionByDacFonCodAc(TFonction TFonctionByDacFonCodAc) {
		this.TFonctionByDacFonCodAc = TFonctionByDacFonCodAc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_MOP_CODE")
	public TModePassation getTModePassation() {
		return this.TModePassation;
	}

	public void setTModePassation(TModePassation TModePassation) {
		this.TModePassation = TModePassation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_STA_CODE")
	public TStatut getTStatut() {
		return this.TStatut;
	}

	public void setTStatut(TStatut TStatut) {
		this.TStatut = TStatut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_STR_CODE")
	public TStructure getTStructure() {
		return this.TStructure;
	}

	public void setTStructure(TStructure TStructure) {
		this.TStructure = TStructure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_GES_CODE")
	public TGestion getTGestion() {
		return this.TGestion;
	}

	public void setTGestion(TGestion TGestion) {
		this.TGestion = TGestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_TYM_CODE")
	public TTypeMarche getTTypeMarche() {
		return this.TTypeMarche;
	}

	public void setTTypeMarche(TTypeMarche TTypeMarche) {
		this.TTypeMarche = TTypeMarche;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_MOD_TYPE")
	public TModeleDacType getTModeleDacType() {
		return this.TModeleDacType;
	}

	public void setTModeleDacType(TModeleDacType TModeleDacType) {
		this.TModeleDacType = TModeleDacType;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAC_TD_CODE")
	public TTypeDacSpecs getTTypeDacSpecs() {
		return this.TTypeDacSpecs;
	}

	public void setTTypeDacSpecs(TTypeDacSpecs TTypeDacSpecs) {
		this.TTypeDacSpecs = TTypeDacSpecs;
	}

	@Column(name = "DAC_OBJET", length = 1000)
	public String getDacObjet() {
		return this.dacObjet;
	}

	public void setDacObjet(String dacObjet) {
		this.dacObjet = dacObjet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAC_DTE_SAISI", length = 7)
	public Date getDacDteSaisi() {
		return this.dacDteSaisi;
	}

	public void setDacDteSaisi(Date dacDteSaisi) {
		this.dacDteSaisi = dacDteSaisi;
	}


	@Column(name = "DAC_NBR_OUV", precision = 22, scale = 0)
	public Long getDacNbrOuv() {
		return this.dacNbrOuv;
	}

	public void setDacNbrOuv(Long dacNbrOuv) {
		this.dacNbrOuv = dacNbrOuv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAC_DTE_VAL_CPMP", length = 7)
	public Date getDacDteValCpmp() {
		return this.dacDteValCpmp;
	}

	public void setDacDteValCpmp(Date dacDteValCpmp) {
		this.dacDteValCpmp = dacDteValCpmp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAC_DTE_VAL_DMP", length = 7)
	public Date getDacDteValDmp() {
		return this.dacDteValDmp;
	}

	public void setDacDteValDmp(Date dacDteValDmp) {
		this.dacDteValDmp = dacDteValDmp;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DAC_DATE_RECEPTION", length = 7)
	public Date getDacDateReception() {
		return this.dacDateReception;
	}

	public void setDacDateReception(Date dacDateReception) {
		this.dacDateReception = dacDateReception;
	}
	
	@Column(name = "DAC_STATUT_RETOUR", length = 2)
	public String getDacStatutRetour() {
		return this.dacStatutRetour;
	}

	public void setDacStatutRetour(String dacStatutRetour) {
		this.dacStatutRetour = dacStatutRetour;
	}
	
	@Column(name = "DAC_MENTION", length = 100)
	public String getDacMention() {
		return this.dacMention;
	}

	public void setDacMention(String dacMention) {
		this.dacMention = dacMention;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DAC_DATE_VAL_AC", length = 7)
	public Date getDacDateValAc() {
		return this.dacDateValAc;
	}

	public void setDacDateValAc(Date dacDateValAc) {
		this.dacDateValAc = dacDateValAc;
	}
	
	@Column(name = "DAC_AVIS_BAILLEUR", length = 4000)
	public String getDacAvisBailleur() {
		return this.dacAvisBailleur;
	}

	public void setDacAvisBailleur(String dacAvisBailleur) {
		this.dacAvisBailleur = dacAvisBailleur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAC_DATE_AVIS_BAILLEUR", length = 7)
	public Date getDacDateAvisBailleur() {
		return this.dacDateAvisBailleur;
	}

	public void setDacDateAvisBailleur(Date dacDateAvisBailleur) {
		this.dacDateAvisBailleur = dacDateAvisBailleur;
	}
	
	@Column(name = "DAC_BAILLEUR", length = 1)
	public String getDacBailleur() {
		return this.dacBailleur;
	}

	public void setDacBailleur(String dacBailleur) {
		this.dacBailleur = dacBailleur;
	}
	
	@Column(name = "DAC_TYPE_PLAN", length = 4)
	public String getDacTypePlan() {
		return this.dacTypePlan;
	}

	public void setDacTypePlan(String dacTypePlan) {
		this.dacTypePlan = dacTypePlan;
	}
	
	@Column(name = "DAC_FACTORISE_CRIT", precision = 1, scale = 0)
	public long getDacFactoriseCrit() {
		return this.dacFactoriseCrit;
	}

	public void setDacFactoriseCrit(long dacFactoriseCrit) {
		this.dacFactoriseCrit = dacFactoriseCrit;
	}
	
	@Column(name = "DAC_NBRE_ACHAT")
	public Long getDacNbreAchat() {
		return this.dacNbreAchat;
	}

	public void setDacNbreAchat(Long dacNbreAchat) {
		this.dacNbreAchat = dacNbreAchat;
	}
	
	@Column(name = "DAC_AUT_COM_SPEC", length = 200)
	public String getDacAutComSpec() {
		return this.dacAutComSpec;
	}

	public void setDacAutComSpec(String dacAutComSpec) {
		this.dacAutComSpec = dacAutComSpec;
	}
	
	@Column(name = "DAC_RECHERCHE", length = 4000)
	public String getDacRecherche() {
		return this.dacRecherche;
	}

	public void setDacRecherche(String dacRecherche) {
		this.dacRecherche = dacRecherche;
	}
    
	@Column(name = "DAC_FON_CODE_DMP", length = 20)
	public String getDacFonCodeDmp() {
		return this.dacFonCodeDmp;
	}

	public void setDacFonCodeDmp(String dacFonCodeDmp) {
		this.dacFonCodeDmp = dacFonCodeDmp;
	}
	
	@Column(name = "DAC_FON_CODE_PF", length = 20)
	public String getDacFonCodePf() {
		return this.dacFonCodePf;
	}

	public void setDacFonCodePf(String dacFonCodePf) {
		this.dacFonCodePf = dacFonCodePf;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TAvisAppelOffre> getTAvisAppelOffres() {
		return this.TAvisAppelOffres;
	}

	public void setTAvisAppelOffres(Set<TAvisAppelOffre> TAvisAppelOffres) {
		this.TAvisAppelOffres = TAvisAppelOffres;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TDossierDacs> getTDossierDacses() {
		return this.TDossierDacses;
	}

	public void setTDossierDacses(Set<TDossierDacs> TDossierDacses) {
		this.TDossierDacses = TDossierDacses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TDetailCorrection> getTDetailCorrections() {
		return this.TDetailCorrections;
	}

	public void setTDetailCorrections(Set<TDetailCorrection> TDetailCorrections) {
		this.TDetailCorrections = TDetailCorrections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TCorrectionDac> getTCorrectionDacs() {
		return this.TCorrectionDacs;
	}

	public void setTCorrectionDacs(Set<TCorrectionDac> TCorrectionDacs) {
		this.TCorrectionDacs = TCorrectionDacs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TDetailAvis> getTDetailAvises() {
		return this.TDetailAvises;
	}

	public void setTDetailAvises(Set<TDetailAvis> TDetailAvises) {
		this.TDetailAvises = TDetailAvises;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TDetCommissionSeance> getTDetCommissionSeances() {
		return this.TDetCommissionSeances;
	}

	public void setTDetCommissionSeances(Set<TDetCommissionSeance> TDetCommissionSeances) {
		this.TDetCommissionSeances = TDetCommissionSeances;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<THistoDac> getTHistoDacs() {
		return this.THistoDacs;
	}

	public void setTHistoDacs(Set<THistoDac> THistoDacs) {
		this.THistoDacs = THistoDacs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDacSpecs")
	public Set<TPiecesOffres> getTPiecesOffres() {
		return TPiecesOffres;
	}

	public void setTPiecesOffres(Set<TPiecesOffres> tPiecesOffres) {
		TPiecesOffres = tPiecesOffres;
	}

	@Column(name = "DAC_COUT", precision = 11, scale = 0)
	public Long getDacCout() {
		return dacCout;
	}

	public void setDacCout(Long dacCout) {
		this.dacCout = dacCout;
	}
	
	@Column(name = "DAC_NBR_COPIE_OFF", precision = 22, scale = 0)
	public BigDecimal getDacNbrCopieOff() {
		return this.dacNbrCopieOff;
	}

	public void setDacNbrCopieOff(BigDecimal dacNbrCopieOff) {
		this.dacNbrCopieOff = dacNbrCopieOff;
	}

	@Column(name = "DAC_FINANCEMENT", length = 4000)
	public String getDacFinancement() {
		return this.dacFinancement;
	}

	public void setDacFinancement(String dacFinancement) {
		this.dacFinancement = dacFinancement;
	}
	

	@Column(name = "DAC_CRA_CODE_EXCLUS", length = 50)
	public String getDacCraCodeExclus() {
		return this.dacCraCodeExclus;
	}

	public void setDacCraCodeExclus(String dacCraCodeExclus) {
		this.dacCraCodeExclus = dacCraCodeExclus;
	}
	

	@Column(name = "DAC_MARGE_PREF_COM", length = 1)
	public String getDacMargePrefCom() {
		return this.dacMargePrefCom;
	}

	public void setDacMargePrefCom(String dacMargePrefCom) {
		this.dacMargePrefCom = dacMargePrefCom;
	}

	@Column(name = "DAC_MARGE_PREF_SOU", length = 1)
	public String getDacMargePrefSou() {
		return this.dacMargePrefSou;
	}

	public void setDacMargePrefSou(String dacMargePrefSou) {
		this.dacMargePrefSou = dacMargePrefSou;
	}

	@Column(name = "DAC_MARGE_PREF_ART", length = 1)
	public String getDacMargePrefArt() {
		return this.dacMargePrefArt;
	}

	public void setDacMargePrefArt(String dacMargePrefArt) {
		this.dacMargePrefArt = dacMargePrefArt;
	}

	@Column(name = "DAC_MARGE_PREF_COM_VAL", precision = 22, scale = 0)
	public BigDecimal getDacMargePrefComVal() {
		return this.dacMargePrefComVal;
	}

	public void setDacMargePrefComVal(BigDecimal dacMargePrefComVal) {
		this.dacMargePrefComVal = dacMargePrefComVal;
	}

	@Column(name = "DAC_MARGE_PREF_SOU_VAL", precision = 22, scale = 0)
	public BigDecimal getDacMargePrefSouVal() {
		return this.dacMargePrefSouVal;
	}

	public void setDacMargePrefSouVal(BigDecimal dacMargePrefSouVal) {
		this.dacMargePrefSouVal = dacMargePrefSouVal;
	}

	@Column(name = "DAC_MARGE_PREF_ART_VAL", precision = 22, scale = 0)
	public BigDecimal getDacMargePrefArtVal() {
		return this.dacMargePrefArtVal;
	}

	public void setDacMargePrefArtVal(BigDecimal dacMargePrefArtVal) {
		this.dacMargePrefArtVal = dacMargePrefArtVal;
	}

	@Column(name = "DAC_MARGE_PREF", length = 1)
	public String getDacMargePref() {
		return this.dacMargePref;
	}

	public void setDacMargePref(String dacMargePref) {
		this.dacMargePref = dacMargePref;
	}
	
	@Column(name = "DAC_MOTIF", length = 2000)
	public String getDacMotif() {
		return this.dacMotif;
	}

	public void setDacMotif(String dacMotif) {
		this.dacMotif = dacMotif;
	}
}
