package com.sndi.model;
// Generated 21 juin 2021 18:06:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDatePlan generated by hbm2java
 */
@Entity
@Table(name = "T_DATE_PLAN")
public class TDatePlan implements java.io.Serializable {

	private long dplNum;
	private TDetailPlanPassation TDetailPlanPassation;
	private TOperateur TOperateur;
	private String dplPadCode;
	private Date dplDteValeur;
	private Date dplDteSaisie;
	private Date dplDteModif;
	private String dplObser;
	private String dplActif;

	public TDatePlan() {
	}

	public TDatePlan(long dplNum) {
		this.dplNum = dplNum;
	}

	public TDatePlan(long dplNum, TDetailPlanPassation TDetailPlanPassation, TOperateur TOperateur,
			String dplPadCode, Date dplDteValeur, Date dplDteSaisie, Date dplDteModif, String dplObser,
			String dplActif) {
		this.dplNum = dplNum;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TOperateur = TOperateur;
		this.dplPadCode = dplPadCode;
		this.dplDteValeur = dplDteValeur;
		this.dplDteSaisie = dplDteSaisie;
		this.dplDteModif = dplDteModif;
		this.dplObser = dplObser;
		this.dplActif = dplActif;
	}

	@Id

	@Column(name = "DPL_NUM", unique = true, nullable = false, precision = 22, scale = 0)
	public long getDplNum() {
		return this.dplNum;
	}

	public void setDplNum(long dplNum) {
		this.dplNum = dplNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPL_DDP_ID")
	public TDetailPlanPassation getTDetailPlanPassation() {
		return this.TDetailPlanPassation;
	}

	public void setTDetailPlanPassation(TDetailPlanPassation TDetailPlanPassation) {
		this.TDetailPlanPassation = TDetailPlanPassation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPL_OPE_MATRICULE")
	public TOperateur getTOperateur() {
		return this.TOperateur;
	}

	public void setTOperateur(TOperateur TOperateur) {
		this.TOperateur = TOperateur;
	}

	@Column(name = "DPL_PAD_CODE", length = 500)
	public String getDplPadCode() {
		return this.dplPadCode;
	}

	public void setDplPadCode(String dplPadCode) {
		this.dplPadCode = dplPadCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPL_DTE_VALEUR", length = 7)
	public Date getDplDteValeur() {
		return this.dplDteValeur;
	}

	public void setDplDteValeur(Date dplDteValeur) {
		this.dplDteValeur = dplDteValeur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPL_DTE_SAISIE", length = 7)
	public Date getDplDteSaisie() {
		return this.dplDteSaisie;
	}

	public void setDplDteSaisie(Date dplDteSaisie) {
		this.dplDteSaisie = dplDteSaisie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPL_DTE_MODIF", length = 7)
	public Date getDplDteModif() {
		return this.dplDteModif;
	}

	public void setDplDteModif(Date dplDteModif) {
		this.dplDteModif = dplDteModif;
	}

	@Column(name = "DPL_OBSER", length = 200)
	public String getDplObser() {
		return this.dplObser;
	}

	public void setDplObser(String dplObser) {
		this.dplObser = dplObser;
	}

	@Column(name = "DPL_ACTIF", length = 3)
	public String getDplActif() {
		return this.dplActif;
	}

	public void setDplActif(String dplActif) {
		this.dplActif = dplActif;
	}

}
