package com.sndi.model;
// Generated 20 juin 2020 11:42:45 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDetCritAnalyse generated by hbm2java
 */
@Entity
@Table(name = "T_DET_CRIT_ANALYSE", schema = "EMAP")
public class TDetCritAnalyse implements java.io.Serializable {

	private String danCode;
	private TCritereAnalyse TCritereAnalyse;
	private TFonction TFonction;
	private TOperateur TOperateurByDanOpeSaisie;
	private TOperateur TOperateurByDanOpeModif;
	private String danLibelle;
	private Date danDteSaisie;
	private String danStatut;
	private String danAutre;
	private Date danDteModif;
	private Set<TDetCritAnalyseDac> TDetCritAnalyseDacs = new HashSet<TDetCritAnalyseDac>(0);

	public TDetCritAnalyse() {
	}

	public TDetCritAnalyse(String danCode, TCritereAnalyse TCritereAnalyse) {
		this.danCode = danCode;
		this.TCritereAnalyse = TCritereAnalyse;
	}

	public TDetCritAnalyse(String danCode, TCritereAnalyse TCritereAnalyse, TFonction TFonction,
			TOperateur TOperateurByDanOpeSaisie, TOperateur TOperateurByDanOpeModif, String danLibelle,
			Date danDteSaisie, String danStatut, String danAutre, Date danDteModif,
			Set<TDetCritAnalyseDac> TDetCritAnalyseDacs) {
		this.danCode = danCode;
		this.TCritereAnalyse = TCritereAnalyse;
		this.TFonction = TFonction;
		this.TOperateurByDanOpeSaisie = TOperateurByDanOpeSaisie;
		this.TOperateurByDanOpeModif = TOperateurByDanOpeModif;
		this.danLibelle = danLibelle;
		this.danDteSaisie = danDteSaisie;
		this.danStatut = danStatut;
		this.danAutre = danAutre;
		this.danDteModif = danDteModif;
		this.TDetCritAnalyseDacs = TDetCritAnalyseDacs;
	}

	@Id

	@Column(name = "DAN_CODE", unique = true, nullable = false)
	public String getDanCode() {
		return this.danCode;
	}

	public void setDanCode(String danCode) {
		this.danCode = danCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAN_CRA_CODE", nullable = false)
	public TCritereAnalyse getTCritereAnalyse() {
		return this.TCritereAnalyse;
	}

	public void setTCritereAnalyse(TCritereAnalyse TCritereAnalyse) {
		this.TCritereAnalyse = TCritereAnalyse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAN_FON_CODE_AC")
	public TFonction getTFonction() {
		return this.TFonction;
	}

	public void setTFonction(TFonction TFonction) {
		this.TFonction = TFonction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAN_OPE_SAISIE")
	public TOperateur getTOperateurByDanOpeSaisie() {
		return this.TOperateurByDanOpeSaisie;
	}

	public void setTOperateurByDanOpeSaisie(TOperateur TOperateurByDanOpeSaisie) {
		this.TOperateurByDanOpeSaisie = TOperateurByDanOpeSaisie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAN_OPE_MODIF")
	public TOperateur getTOperateurByDanOpeModif() {
		return this.TOperateurByDanOpeModif;
	}

	public void setTOperateurByDanOpeModif(TOperateur TOperateurByDanOpeModif) {
		this.TOperateurByDanOpeModif = TOperateurByDanOpeModif;
	}

	@Column(name = "DAN_LIBELLE")
	public String getDanLibelle() {
		return this.danLibelle;
	}

	public void setDanLibelle(String danLibelle) {
		this.danLibelle = danLibelle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAN_DTE_SAISIE")
	public Date getDanDteSaisie() {
		return this.danDteSaisie;
	}

	public void setDanDteSaisie(Date danDteSaisie) {
		this.danDteSaisie = danDteSaisie;
	}

	@Column(name = "DAN_STATUT")
	public String getDanStatut() {
		return this.danStatut;
	}

	public void setDanStatut(String danStatut) {
		this.danStatut = danStatut;
	}

	@Column(name = "DAN_AUTRE")
	public String getDanAutre() {
		return this.danAutre;
	}

	public void setDanAutre(String danAutre) {
		this.danAutre = danAutre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAN_DTE_MODIF")
	public Date getDanDteModif() {
		return this.danDteModif;
	}

	public void setDanDteModif(Date danDteModif) {
		this.danDteModif = danDteModif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDetCritAnalyse")
	public Set<TDetCritAnalyseDac> getTDetCritAnalyseDacs() {
		return this.TDetCritAnalyseDacs;
	}

	public void setTDetCritAnalyseDacs(Set<TDetCritAnalyseDac> TDetCritAnalyseDacs) {
		this.TDetCritAnalyseDacs = TDetCritAnalyseDacs;
	}

}
