package com.sndi.model;
// Generated 30 nov. 2019 13:40:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;




/**
 * TDetailPlanPassation generated by hbm2java
 */
@Entity
@Table(name = "T_DETAIL_PLAN_PASSATION", schema = "EMAP")
public class TDetailPlanPassation implements java.io.Serializable {

	private long dppId;
	private TLBudgets TLBudgets;
	private TTypeProcedure TTypeProcedure;
	private TStructure TStructure;
	private TDacSpecs TDacSpecs;
	private TModePassation TModePassation;
	private TDetailPlanGeneral TDetailPlanGeneral;
	private TPlanPassation TPlanPassation;
	private TStatut TStatut;
	private TTypeMarche TTypeMarche;
	private TModeleDacType TModeleDacType;
	private String dppTypePlan;
	private String dppCode;
	private Integer dppNumeroOrdre;
	private Date dppDate;
	private String dppObjet;
	private String dppSourceFin;
	private Date dppDateDaoTrans;
	private Date dppDateDaoApprobDmp;
	private Date dppDateDaoApprobBail;
	private Date dppDateAvisAoPublication;
	private Date dppDateOuvertOt;
	private Date dppDateOuvertOf;
	private Date dppDateElabRapport;
	private Date dppDateJugementOffre;
	private Date dppDateAttApprobDmp;
	private Date dppDateAttApproBail;
	private Date dppDateNegociation;
	private Date dppDateSignatAttrib;
	private Date dppDateSignatAc;
	private Date dppDateMarcheApprob;
	private Date dppDateExecDebut;
	private Date dppDateExecFin;
	private String dppActeurSaisie;
	private String dppStatutRetour;
	private Date dppDateSaisie;
	private String dppStructureConduc;
	private String dppStructureBenefi;
	private String dppPartiePmePmi;
	private String dppStatutDao;
	private Date dppInvEntre;
	private Date dppDateAttApprobCpmp;
	private Date dppDateJugementOffreTec;
	private Date dppDateValAc;
	private Date dppDateValCpmp;
	private Date dppDateValDmp;
	private String dppBailleur;
	private String dppTypeFinance;
	private Date dppApprobAno;
	private Date dppDteModif;
	private String dppRecherche;
	private String dppFonCodPf;
	private String dppFonCodDmp;
	private Set<THistoPlanPassation> THistoPlanPassations = new HashSet<THistoPlanPassation>(0);
	private Set<TCharge> TCharges = new HashSet<TCharge>(0);
	private Set<TFinancementPpm> TFinancementPpms = new HashSet<TFinancementPpm>(0);

	public TDetailPlanPassation() {
	}
	
	public TDetailPlanPassation(long dppId) {
		this.dppId = dppId;
	}

	public TDetailPlanPassation(long dppId, TModePassation TModePassation, TDetailPlanGeneral TDetailPlanGeneral,
			 TPlanPassation TPlanPassation, TStatut TStatut, TTypeMarche TTypeMarche,
			String dppTypePlan) {
		this.dppId = dppId;
		this.TModePassation = TModePassation;
		this.TDetailPlanGeneral = TDetailPlanGeneral;
		this.TPlanPassation = TPlanPassation;
		this.TStatut = TStatut;
		this.TTypeMarche = TTypeMarche;
		this.dppTypePlan = dppTypePlan;
	}

	public TDetailPlanPassation(long dppId,TLBudgets TLBudgets,TTypeProcedure TTypeProcedure, TStructure TStructure,TDacSpecs TDacSpecs, TModePassation TModePassation, TDetailPlanGeneral TDetailPlanGeneral,
			 TPlanPassation TPlanPassation, TStatut TStatut, TTypeMarche TTypeMarche, TModeleDacType TModeleDacType,
			String dppTypePlan, String dppCode, Integer dppNumeroOrdre, Date dppDate, String dppObjet,
			String dppSourceFin, Date dppDateDaoTrans, Date dppDateDaoApprobDmp, Date dppDateDaoApprobBail,
			Date dppDateAvisAoPublication, Date dppDateOuvertOt, Date dppDateOuvertOf, Date dppDateElabRapport,
			Date dppDateJugementOffre, Date dppDateAttApprobDmp, Date dppDateAttApproBail, Date dppDateNegociation,
			Date dppDateSignatAttrib, Date dppDateSignatAc, Date dppDateMarcheApprob, Date dppDateExecDebut, String dppStatutRetour,
			Date dppDateExecFin, String dppActeurSaisie, Date dppDateSaisie, String dppStructureConduc, String dppStructureBenefi, String dppPartiePmePmi,String dppStatutDao,Date dppInvEntre, Date dppDateAttApprobCpmp,Date dppDateJugementOffreTec,Date dppDateValAc,
			Date dppDateValCpmp, Date dppDateValDmp,String dppBailleur,String dppTypeFinance,Date dppApprobAno,
			Date dppDteModif,String dppRecherche,String dppFonCodPf, String dppFonCodDmp,Set<THistoPlanPassation> THistoPlanPassations, Set<TCharge> TCharges, Set<TDacSpecs> TDacSpecses,
			Set<TFinancementPpm> TFinancementPpms) {
		this.dppId = dppId;
		this.TLBudgets = TLBudgets;
		this.TTypeProcedure = TTypeProcedure;
		this.TStructure = TStructure;
		this.TDacSpecs = TDacSpecs;
		this.TModePassation = TModePassation;
		this.TDetailPlanGeneral = TDetailPlanGeneral;
		this.TPlanPassation = TPlanPassation;
		this.TStatut = TStatut;
		this.TTypeMarche = TTypeMarche;
		this.TModeleDacType = TModeleDacType;
		this.dppTypePlan = dppTypePlan;
		this.dppCode = dppCode;
		this.dppNumeroOrdre = dppNumeroOrdre;
		this.dppDate = dppDate;
		this.dppObjet = dppObjet;
		this.dppSourceFin = dppSourceFin;
		this.dppDateDaoTrans = dppDateDaoTrans;
		this.dppDateDaoApprobDmp = dppDateDaoApprobDmp;
		this.dppDateDaoApprobBail = dppDateDaoApprobBail;
		this.dppDateAvisAoPublication = dppDateAvisAoPublication;
		this.dppDateOuvertOt = dppDateOuvertOt;
		this.dppDateOuvertOf = dppDateOuvertOf;
		this.dppDateElabRapport = dppDateElabRapport;
		this.dppDateJugementOffre = dppDateJugementOffre;
		this.dppDateAttApprobDmp = dppDateAttApprobDmp;
		this.dppDateAttApproBail = dppDateAttApproBail;
		this.dppDateNegociation = dppDateNegociation;
		this.dppDateSignatAttrib = dppDateSignatAttrib;
		this.dppDateSignatAc = dppDateSignatAc;
		this.dppDateMarcheApprob = dppDateMarcheApprob;
		this.dppDateExecDebut = dppDateExecDebut;
		this.dppDateExecFin = dppDateExecFin;
		this.dppActeurSaisie = dppActeurSaisie;
		this.dppStatutRetour = dppStatutRetour;
		this.dppDateSaisie = dppDateSaisie;
		this.dppStructureConduc = dppStructureConduc;
		this.dppStructureBenefi = dppStructureBenefi;
		this.dppPartiePmePmi = dppPartiePmePmi;
		this.dppStatutDao = dppStatutDao;
		this.dppInvEntre = dppInvEntre;
		this.dppDateAttApprobCpmp = dppDateAttApprobCpmp;
		this.dppDateJugementOffreTec = dppDateJugementOffreTec;
		this.dppDateValAc = dppDateValAc;
		this.dppDateValCpmp = dppDateValCpmp;
		this.dppDateValDmp = dppDateValDmp;
		this.dppBailleur = dppBailleur;
		this.dppTypeFinance = dppTypeFinance;
		this.dppApprobAno = dppApprobAno;
		this.dppDteModif = dppDteModif;
		this.dppRecherche = dppRecherche;
		this.dppFonCodPf = dppFonCodPf;
		this.dppFonCodDmp = dppFonCodDmp;
		this.THistoPlanPassations = THistoPlanPassations;
		this.TCharges = TCharges;
		this.TFinancementPpms = TFinancementPpms;
	}

	@Id
	@SequenceGenerator(name = "SEQ_DPP_Sequence", sequenceName = "SEQ_DPP", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_DPP_Sequence")
	@Column(name = "DPP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDppId() {
		return this.dppId;
	}

	public void setDppId(long dppId) {
		this.dppId = dppId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_LBG_CODE")
	public TLBudgets getTLBudgets() {
		return this.TLBudgets;
	}

	public void setTLBudgets(TLBudgets TLBudgets) {
		this.TLBudgets = TLBudgets;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPP_TYP_ID")
	public TTypeProcedure getTTypeProcedure() {
		return this.TTypeProcedure;
	}

	public void setTTypeProcedure(TTypeProcedure TTypeProcedure) {
		this.TTypeProcedure = TTypeProcedure;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_STR_CODE")
	public TStructure getTStructure() {
		return this.TStructure;
	}

	public void setTStructure(TStructure TStructure) {
		this.TStructure = TStructure;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_DAC_CODE")
	public TDacSpecs getTDacSpecs() {
		return this.TDacSpecs;
	}

	public void setTDacSpecs(TDacSpecs TDacSpecs) {
		this.TDacSpecs = TDacSpecs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_MOP_CODE", nullable = false)
	public TModePassation getTModePassation() {
		return this.TModePassation;
	}

	public void setTModePassation(TModePassation TModePassation) {
		this.TModePassation = TModePassation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_GPG_ID", nullable = false)
	public TDetailPlanGeneral getTDetailPlanGeneral() {
		return this.TDetailPlanGeneral;
	}

	public void setTDetailPlanGeneral(TDetailPlanGeneral TDetailPlanGeneral) {
		this.TDetailPlanGeneral = TDetailPlanGeneral;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_PLP_ID", nullable = false)
	public TPlanPassation getTPlanPassation() {
		return this.TPlanPassation;
	}

	public void setTPlanPassation(TPlanPassation TPlanPassation) {
		this.TPlanPassation = TPlanPassation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPP_STA_CODE", nullable = false)
	public TStatut getTStatut() {
		return this.TStatut;
	}

	public void setTStatut(TStatut TStatut) {
		this.TStatut = TStatut;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DPP_TYM_CODE", nullable = false)
	public TTypeMarche getTTypeMarche() {
		return this.TTypeMarche;
	}

	public void setTTypeMarche(TTypeMarche TTypeMarche) {
		this.TTypeMarche = TTypeMarche;
	}
	

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPP_PIECE_DAO")
	public TModeleDacType getTModeleDacType() {
		return this.TModeleDacType;
	}

	public void setTModeleDacType(TModeleDacType TModeleDacType) {
		this.TModeleDacType = TModeleDacType;
	}
	

	@Column(name = "DPP_TYPE_PLAN", nullable = false, length = 3)
	public String getDppTypePlan() {
		return this.dppTypePlan;
	}

	public void setDppTypePlan(String dppTypePlan) {
		this.dppTypePlan = dppTypePlan;
	}

	@Column(name = "DPP_CODE", length = 50)
	public String getDppCode() {
		return this.dppCode;
	}

	public void setDppCode(String dppCode) {
		this.dppCode = dppCode;
	}

	@Column(name = "DPP_NUMERO_ORDRE", precision = 8, scale = 0)
	public Integer getDppNumeroOrdre() {
		return this.dppNumeroOrdre;
	}

	public void setDppNumeroOrdre(Integer dppNumeroOrdre) {
		this.dppNumeroOrdre = dppNumeroOrdre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE", length = 7)
	public Date getDppDate() {
		return this.dppDate;
	}

	public void setDppDate(Date dppDate) {
		this.dppDate = dppDate;
	}

	@Column(name = "DPP_OBJET", length = 1000)
	public String getDppObjet() {
		return this.dppObjet;
	}

	public void setDppObjet(String dppObjet) {
		this.dppObjet = dppObjet;
	}

	@Column(name = "DPP_SOURCE_FIN", length = 1000)
	public String getDppSourceFin() {
		return this.dppSourceFin;
	}

	public void setDppSourceFin(String dppSourceFin) {
		this.dppSourceFin = dppSourceFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_DAO_TRANS", length = 7)
	public Date getDppDateDaoTrans() {
		return this.dppDateDaoTrans;
	}

	public void setDppDateDaoTrans(Date dppDateDaoTrans) {
		this.dppDateDaoTrans = dppDateDaoTrans;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_DAO_APPROB_DMP", length = 7)
	public Date getDppDateDaoApprobDmp() {
		return this.dppDateDaoApprobDmp;
	}

	public void setDppDateDaoApprobDmp(Date dppDateDaoApprobDmp) {
		this.dppDateDaoApprobDmp = dppDateDaoApprobDmp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_DAO_APPROB_BAIL", length = 7)
	public Date getDppDateDaoApprobBail() {
		return this.dppDateDaoApprobBail;
	}

	public void setDppDateDaoApprobBail(Date dppDateDaoApprobBail) {
		this.dppDateDaoApprobBail = dppDateDaoApprobBail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_AVIS_AO_PUBLICATION", length = 7)
	public Date getDppDateAvisAoPublication() {
		return this.dppDateAvisAoPublication;
	}

	public void setDppDateAvisAoPublication(Date dppDateAvisAoPublication) {
		this.dppDateAvisAoPublication = dppDateAvisAoPublication;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_OUVERT_OT", length = 7)
	public Date getDppDateOuvertOt() {
		return this.dppDateOuvertOt;
	}

	public void setDppDateOuvertOt(Date dppDateOuvertOt) {
		this.dppDateOuvertOt = dppDateOuvertOt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_OUVERT_OF", length = 7)
	public Date getDppDateOuvertOf() {
		return this.dppDateOuvertOf;
	}

	public void setDppDateOuvertOf(Date dppDateOuvertOf) {
		this.dppDateOuvertOf = dppDateOuvertOf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_ELAB_RAPPORT", length = 7)
	public Date getDppDateElabRapport() {
		return this.dppDateElabRapport;
	}

	public void setDppDateElabRapport(Date dppDateElabRapport) {
		this.dppDateElabRapport = dppDateElabRapport;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_JUGEMENT_OFFRE", length = 7)
	public Date getDppDateJugementOffre() {
		return this.dppDateJugementOffre;
	}

	public void setDppDateJugementOffre(Date dppDateJugementOffre) {
		this.dppDateJugementOffre = dppDateJugementOffre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_ATT_APPROB_DMP", length = 7)
	public Date getDppDateAttApprobDmp() {
		return this.dppDateAttApprobDmp;
	}

	public void setDppDateAttApprobDmp(Date dppDateAttApprobDmp) {
		this.dppDateAttApprobDmp = dppDateAttApprobDmp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_ATT_APPRO_BAIL", length = 7)
	public Date getDppDateAttApproBail() {
		return this.dppDateAttApproBail;
	}

	public void setDppDateAttApproBail(Date dppDateAttApproBail) {
		this.dppDateAttApproBail = dppDateAttApproBail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_NEGOCIATION", length = 7)
	public Date getDppDateNegociation() {
		return this.dppDateNegociation;
	}

	public void setDppDateNegociation(Date dppDateNegociation) {
		this.dppDateNegociation = dppDateNegociation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_SIGNAT_ATTRIB", length = 7)
	public Date getDppDateSignatAttrib() {
		return this.dppDateSignatAttrib;
	}

	public void setDppDateSignatAttrib(Date dppDateSignatAttrib) {
		this.dppDateSignatAttrib = dppDateSignatAttrib;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_SIGNAT_AC", length = 7)
	public Date getDppDateSignatAc() {
		return this.dppDateSignatAc;
	}

	public void setDppDateSignatAc(Date dppDateSignatAc) {
		this.dppDateSignatAc = dppDateSignatAc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_MARCHE_APPROB", length = 7)
	public Date getDppDateMarcheApprob() {
		return this.dppDateMarcheApprob;
	}

	public void setDppDateMarcheApprob(Date dppDateMarcheApprob) {
		this.dppDateMarcheApprob = dppDateMarcheApprob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_EXEC_DEBUT", length = 7)
	public Date getDppDateExecDebut() {
		return this.dppDateExecDebut;
	}

	public void setDppDateExecDebut(Date dppDateExecDebut) {
		this.dppDateExecDebut = dppDateExecDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_EXEC_FIN", length = 7)
	public Date getDppDateExecFin() {
		return this.dppDateExecFin;
	}

	public void setDppDateExecFin(Date dppDateExecFin) {
		this.dppDateExecFin = dppDateExecFin;
	}
	
	@Column(name = "DPP_ACTEUR_SAISIE", length = 12)
	public String getDppActeurSaisie() {
		return this.dppActeurSaisie;
	}

	public void setDppActeurSaisie(String dppActeurSaisie) {
		this.dppActeurSaisie = dppActeurSaisie;
	}
	
	@Column(name = "DPP_STATUT_RETOUR", length = 4)
	public String getDppStatutRetour() {
		return this.dppStatutRetour;
	}

	public void setDppStatutRetour(String dppStatutRetour) {
		this.dppStatutRetour = dppStatutRetour;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_SAISIE", length = 7)
	public Date getDppDateSaisie() {
		return this.dppDateSaisie;
	}

	public void setDppDateSaisie(Date dppDateSaisie) {
		this.dppDateSaisie = dppDateSaisie;
	}
	
	@Column(name = "DPP_STRUCTURE_CONDUC", length = 500)
	public String getDppStructureConduc() {
		return this.dppStructureConduc;
	}

	public void setDppStructureConduc(String dppStructureConduc) {
		this.dppStructureConduc = dppStructureConduc;
	}

	@Column(name = "DPP_STRUCTURE_BENEFI", length = 500)
	public String getDppStructureBenefi() {
		return this.dppStructureBenefi;
	}

	public void setDppStructureBenefi(String dppStructureBenefi) {
		this.dppStructureBenefi = dppStructureBenefi;
	}
	
	@Column(name = "DPP_PARTIE_PME_PMI", length = 1)
	public String getDppPartiePmePmi() {
		return this.dppPartiePmePmi;
	}

	public void setDppPartiePmePmi(String dppPartiePmePmi) {
		this.dppPartiePmePmi = dppPartiePmePmi;
	}
	
	@Column(name = "DPP_STATUT_DAO", length = 2)
	public String getDppStatutDao() {
		return this.dppStatutDao;
	}

	public void setDppStatutDao(String dppStatutDao) {
		this.dppStatutDao = dppStatutDao;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_INV_ENTRE", length = 7)
	public Date getDppInvEntre() {
		return this.dppInvEntre;
	}

	public void setDppInvEntre(Date dppInvEntre) {
		this.dppInvEntre = dppInvEntre;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_ATT_APPROB_CPMP", length = 7)
	public Date getDppDateAttApprobCpmp() {
		return this.dppDateAttApprobCpmp;
	}

	public void setDppDateAttApprobCpmp(Date dppDateAttApprobCpmp) {
		this.dppDateAttApprobCpmp = dppDateAttApprobCpmp;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_JUGEMENT_OFFRE_TEC", length = 7)
	public Date getDppDateJugementOffreTec() {
		return this.dppDateJugementOffreTec;
	}

	public void setDppDateJugementOffreTec(Date dppDateJugementOffreTec) {
		this.dppDateJugementOffreTec = dppDateJugementOffreTec;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_VAL_AC", length = 7)
	public Date getDppDateValAc() {
		return this.dppDateValAc;
	}

	public void setDppDateValAc(Date dppDateValAc) {
		this.dppDateValAc = dppDateValAc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_VAL_CPMP", length = 7)
	public Date getDppDateValCpmp() {
		return this.dppDateValCpmp;
	}

	public void setDppDateValCpmp(Date dppDateValCpmp) {
		this.dppDateValCpmp = dppDateValCpmp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DATE_VAL_DMP", length = 7)
	public Date getDppDateValDmp() {
		return this.dppDateValDmp;
	}

	public void setDppDateValDmp(Date dppDateValDmp) {
		this.dppDateValDmp = dppDateValDmp;
	}
	

	@Column(name = "DPP_BAILLEUR", length = 1)
	public String getDppBailleur() {
		return this.dppBailleur;
	}

	public void setDppBailleur(String dppBailleur) {
		this.dppBailleur = dppBailleur;
	}
	
	@Column(name = "DPP_TYPE_FINANCE", length = 20)
	public String getDppTypeFinance() {
		return this.dppTypeFinance;
	}

	public void setDppTypeFinance(String dppTypeFinance) {
		this.dppTypeFinance = dppTypeFinance;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_APPROB_ANO", length = 7)
	public Date getDppApprobAno() {
		return this.dppApprobAno;
	}

	public void setDppApprobAno(Date dppApprobAno) {
		this.dppApprobAno = dppApprobAno;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DPP_DTE_MODIF", length = 7)
	public Date getDppDteModif() {
		return this.dppDteModif;
	}

	public void setDppDteModif(Date dppDteModif) {
		this.dppDteModif = dppDteModif;
	}
	
	@Column(name = "DPP_RECHERCHE", length = 4000)
	public String getDppRecherche() {
		return this.dppRecherche;
	}

	public void setDppRecherche(String dppRecherche) {
		this.dppRecherche = dppRecherche;
	}
	
	@Column(name = "DPP_FON_COD_PF", length = 20)
	public String getDppFonCodPf() {
		return this.dppFonCodPf;
	}

	public void setDppFonCodPf(String dppFonCodPf) {
		this.dppFonCodPf = dppFonCodPf;
	}

	@Column(name = "DPP_FON_COD_DMP", length = 20)
	public String getDppFonCodDmp() {
		return this.dppFonCodDmp;
	}

	public void setDppFonCodDmp(String dppFonCodDmp) {
		this.dppFonCodDmp = dppFonCodDmp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDetailPlanPassation")
	public Set<THistoPlanPassation> getTHistoPlanPassations() {
		return this.THistoPlanPassations;
	}

	public void setTHistoPlanPassations(Set<THistoPlanPassation> THistoPlanPassations) {
		this.THistoPlanPassations = THistoPlanPassations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDetailPlanPassation")
	public Set<TCharge> getTCharges() {
		return this.TCharges;
	}

	public void setTCharges(Set<TCharge> TCharges) {
		this.TCharges = TCharges;
	}
	


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDetailPlanPassation")
	public Set<TFinancementPpm> getTFinancementPpms() {
		return this.TFinancementPpms;
	}

	public void setTFinancementPpms(Set<TFinancementPpm> TFinancementPpms) {
		this.TFinancementPpms = TFinancementPpms;
	}

}
