package com.sndi.model;
// Generated 16 mai 2020 17:34:21 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDossierDemande generated by hbm2java
 */
@Entity
@Table(name = "T_DOSSIER_DEMANDE", schema = "EMAP")
public class TDossierDemande implements java.io.Serializable {

	private BigDecimal dodId;
	private TPieceDemande TPieceDemande;
	private TDemande TDemande;
	private String dodLibelle;
	private String dodReference;
	private String dodCode;
	private Date dodDteSaisi;
	private String dodType;
	private TNatureDocuments TNatureDocuments;

	public TDossierDemande() {
	}

	public TDossierDemande(BigDecimal dodId, TPieceDemande TPieceDemande, TDemande TDemande) {
		this.dodId = dodId;
		this.TPieceDemande = TPieceDemande;
		this.TDemande = TDemande;
	}

	public TDossierDemande(BigDecimal dodId, TPieceDemande TPieceDemande, TDemande TDemande,
			String dodLibelle, String dodReference,String dodType,String dodCode,Date dodDteSaisi,TNatureDocuments TNatureDocuments) {
		this.dodId = dodId;
		this.TPieceDemande = TPieceDemande;
		this.TDemande = TDemande;
		this.dodLibelle = dodLibelle;
		this.dodReference = dodReference;
		this.dodCode = dodCode;
		this.dodDteSaisi = dodDteSaisi;
		this.TNatureDocuments = TNatureDocuments;
		this.dodType = dodType;
	}

	@Id
	@SequenceGenerator(name = "SEQ_DOS_DEM_Sequence", sequenceName = "SEQ_DOS_DEM", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_DOS_DEM_Sequence")
	@Column(name = "DOD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDodId() {
		return this.dodId;
	}

	public void setDodId(BigDecimal dodId) {
		this.dodId = dodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOD_PDM_NUM", nullable = false)
	public TPieceDemande getTPieceDemande() {
		return this.TPieceDemande;
	}

	public void setTPieceDemande(TPieceDemande TPieceDemande) {
		this.TPieceDemande = TPieceDemande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOD_DEM_NUM", nullable = false)
	public TDemande getTDemande() {
		return this.TDemande;
	}

	public void setTDemande(TDemande TDemande) {
		this.TDemande = TDemande;
	}

	@Column(name = "DOD_LIBELLE", length = 500)
	public String getDodLibelle() {
		return this.dodLibelle;
	}

	public void setDodLibelle(String dodLibelle) {
		this.dodLibelle = dodLibelle;
	}

	@Column(name = "DOD_REFERENCE", length = 500)
	public String getDodReference() {
		return this.dodReference;
	}

	public void setDodReference(String dodReference) {
		this.dodReference = dodReference;
	}

	@Column(name = "DOD_CODE")
	public String getDodCode() {
		return dodCode;
	}

	public void setDodCode(String dodCode) {
		this.dodCode = dodCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOD_DTE_SAISI", length = 7)
	public Date getDodDteSaisi() {
		return dodDteSaisi;
	}

	public void setDodDteSaisi(Date dodDteSaisi) {
		this.dodDteSaisi = dodDteSaisi;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DOD_NAD_CODE")
	public TNatureDocuments getTNatureDocuments() {
		return this.TNatureDocuments;
	}

	public void setTNatureDocuments(TNatureDocuments TNatureDocuments) {
		this.TNatureDocuments = TNatureDocuments;
	}

	@Column(name = "DOD_TYPE")
	public String getDodType() {
		return dodType;
	}

	public void setDodType(String dodType) {
		this.dodType = dodType;
	}


}
