package com.sndi.model;
// Generated 30 nov. 2019 13:40:49 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TFinancementPpm generated by hbm2java
 */
@Entity
@Table(name = "T_FINANCEMENT_PPM", schema = "EMAP")
public class TFinancementPpm implements java.io.Serializable {

	private long fppId;
	private TDetailPlanPassation TDetailPlanPassation;
	private TBailleur TBailleur;
	private TSourceFinancement TSourceFinancement;
	private TDevise TDevise;
	private long fppMontantCfa;
	private BigDecimal fppMontantDevise;
	private String fppCommentaire;
	private String fppTypeFinance;
	public long fppPartTresor;

	public TFinancementPpm() {
	}

	public TFinancementPpm(long fppId, TDetailPlanPassation TDetailPlanPassation, TBailleur TBailleur,
			TSourceFinancement TSourceFinancement, TDevise TDevise) {
		this.fppId = fppId;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TBailleur = TBailleur;
		this.TSourceFinancement = TSourceFinancement;
		this.TDevise = TDevise;
	}

	public TFinancementPpm(long fppId, TDetailPlanPassation TDetailPlanPassation, TBailleur TBailleur,
			TSourceFinancement TSourceFinancement, TDevise TDevise, long fppMontantCfa,
			BigDecimal fppMontantDevise, String fppCommentaire, String fppTypeFinance, long fppPartTresor) {
		this.fppId = fppId;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TBailleur = TBailleur;
		this.TSourceFinancement = TSourceFinancement;
		this.TDevise = TDevise;
		this.fppMontantCfa = fppMontantCfa;
		this.fppMontantDevise = fppMontantDevise;
		this.fppCommentaire = fppCommentaire;
		this.fppTypeFinance = fppTypeFinance;
		this.fppPartTresor = fppPartTresor;
	}

	@Id
	@SequenceGenerator(name = "SEQ_FPP_Sequence", sequenceName = "SEQ_FPP", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_FPP_Sequence")
	@Column(name = "FPP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getFppId() {
		return this.fppId;
	}

	public void setFppId(long fppId) {
		this.fppId = fppId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FPP_DPP_ID", nullable = false)
	public TDetailPlanPassation getTDetailPlanPassation() {
		return this.TDetailPlanPassation;
	}

	public void setTDetailPlanPassation(TDetailPlanPassation TDetailPlanPassation) {
		this.TDetailPlanPassation = TDetailPlanPassation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FPP_BAI_CODE")
	public TBailleur getTBailleur() {
		return this.TBailleur;
	}

	public void setTBailleur(TBailleur TBailleur) {
		this.TBailleur = TBailleur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FPP_SOU_CODE", nullable = false)
	public TSourceFinancement getTSourceFinancement() {
		return this.TSourceFinancement;
	}

	public void setTSourceFinancement(TSourceFinancement TSourceFinancement) {
		this.TSourceFinancement = TSourceFinancement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FPP_DEV_CODE", nullable = false)
	public TDevise getTDevise() {
		return this.TDevise;
	}

	public void setTDevise(TDevise TDevise) {
		this.TDevise = TDevise;
	}

	@Column(name = "FPP_MONTANT_CFA", precision = 15)
	public long getFppMontantCfa() {
		return this.fppMontantCfa;
	}

	public void setFppMontantCfa(long fppMontantCfa) {
		this.fppMontantCfa = fppMontantCfa;
	}

	@Column(name = "FPP_MONTANT_DEVISE", precision = 15)
	public BigDecimal getFppMontantDevise() {
		return this.fppMontantDevise;
	}

	public void setFppMontantDevise(BigDecimal fppMontantDevise) {
		this.fppMontantDevise = fppMontantDevise;
	}

	@Column(name = "FPP_COMMENTAIRE", length = 500)
	public String getFppCommentaire() {
		return this.fppCommentaire;
	}

	public void setFppCommentaire(String fppCommentaire) {
		this.fppCommentaire = fppCommentaire;
	}
	
	@Column(name = "FPP_TYPE_FINANCE", length = 20)
	public String getFppTypeFinance() {
		return this.fppTypeFinance;
	}

	public void setFppTypeFinance(String fppTypeFinance) {
		this.fppTypeFinance = fppTypeFinance;
	}
	
	@Column(name = "FPP_PART_TRESOR", precision = 10, scale = 0)
	public long getFppPartTresor() {
		return this.fppPartTresor;
	}

	public void setFppPartTresor(long fppPartTresor) {
		this.fppPartTresor = fppPartTresor;
	}


}
