package com.sndi.model;
// Generated 4 déc. 2019 12:32:22 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * TGestion generated by hbm2java
 */
@Entity
@Table(name = "T_GESTION", schema = "EMAP")
public class TGestion implements java.io.Serializable {

	private long gesCode;
	private Date gesDateDebut;
	private Date gesDateFin;
	private Set<TPlanGeneral> TPlanGenerals = new HashSet<TPlanGeneral>(0);
	private Set<TAgpm> TAgpms = new HashSet<TAgpm>(0);
	private Set<TLBudgets> TLBudgetses = new HashSet<TLBudgets>(0);
	private Set<TAffichageAgpm> TAffichageAgpms = new HashSet<TAffichageAgpm>(0);
	private Set<TPlanPassation> TPlanPassations = new HashSet<TPlanPassation>(0);

	public TGestion() {
	}

	public TGestion(long gesCode) {
		this.gesCode = gesCode;
	}

	public TGestion(long gesCode, Date gesDateDebut, Date gesDateFin, Set<TPlanGeneral> TPlanGenerals,
			Set<TAgpm> TAgpms, Set<TLBudgets> TLBudgetses, Set<TAffichageAgpm> TAffichageAgpms,
			Set<TPlanPassation> TPlanPassations) {
		this.gesCode = gesCode;
		this.gesDateDebut = gesDateDebut;
		this.gesDateFin = gesDateFin;
		this.TPlanGenerals = TPlanGenerals;
		this.TAgpms = TAgpms;
		this.TLBudgetses = TLBudgetses;
		this.TAffichageAgpms = TAffichageAgpms;
		this.TPlanPassations = TPlanPassations;
	}

	@Id
	@Column(name = "GES_CODE", unique = true, nullable = false, precision = 4, scale = 0)
	public long getGesCode() {
		return this.gesCode;
	}

	public void setGesCode(long gesCode) {
		this.gesCode = gesCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GES_DATE_DEBUT", length = 7)
	public Date getGesDateDebut() {
		return this.gesDateDebut;
	}

	public void setGesDateDebut(Date gesDateDebut) {
		this.gesDateDebut = gesDateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GES_DATE_FIN", length = 7)
	public Date getGesDateFin() {
		return this.gesDateFin;
	}

	public void setGesDateFin(Date gesDateFin) {
		this.gesDateFin = gesDateFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGestion")
	public Set<TPlanGeneral> getTPlanGenerals() {
		return this.TPlanGenerals;
	}

	public void setTPlanGenerals(Set<TPlanGeneral> TPlanGenerals) {
		this.TPlanGenerals = TPlanGenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGestion")
	public Set<TAgpm> getTAgpms() {
		return this.TAgpms;
	}

	public void setTAgpms(Set<TAgpm> TAgpms) {
		this.TAgpms = TAgpms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGestion")
	public Set<TLBudgets> getTLBudgetses() {
		return this.TLBudgetses;
	}

	public void setTLBudgetses(Set<TLBudgets> TLBudgetses) {
		this.TLBudgetses = TLBudgetses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGestion")
	public Set<TAffichageAgpm> getTAffichageAgpms() {
		return this.TAffichageAgpms;
	}

	public void setTAffichageAgpms(Set<TAffichageAgpm> TAffichageAgpms) {
		this.TAffichageAgpms = TAffichageAgpms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGestion")
	public Set<TPlanPassation> getTPlanPassations() {
		return this.TPlanPassations;
	}

	public void setTPlanPassations(Set<TPlanPassation> TPlanPassations) {
		this.TPlanPassations = TPlanPassations;
	}

}
