package com.sndi.model;
// Generated 30 nov. 2019 13:40:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * THistoPlanPassation generated by hbm2java
 */
@Entity
@Table(name = "T_HISTO_PLAN_PASSATION", schema = "EMAP")
public class THistoPlanPassation implements java.io.Serializable {

	private long hppId;
	private TFonction TFonction;
	private TDetailPlanPassation TDetailPlanPassation;
	private TStatut TStatut;
	private Date hppDate;
	private String hppMotif;

	public THistoPlanPassation() {
	}

	public THistoPlanPassation(long hppId, TFonction TFonction, TDetailPlanPassation TDetailPlanPassation,
			TStatut TStatut) {
		this.hppId = hppId;
		this.TFonction = TFonction;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TStatut = TStatut;
	}

	public THistoPlanPassation(long hppId, TFonction TFonction, TDetailPlanPassation TDetailPlanPassation,
			TStatut TStatut, Date hppDate, String hppMotif) {
		this.hppId = hppId;
		this.TFonction = TFonction;
		this.TDetailPlanPassation = TDetailPlanPassation;
		this.TStatut = TStatut;
		this.hppDate = hppDate;
		this.hppMotif = hppMotif;
	}

	@Id
	@SequenceGenerator(name = "SEQ_HPP_Sequence", sequenceName = "SEQ_HPP", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_HPP_Sequence")
	@Column(name = "HPP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getHppId() {
		return this.hppId;
	}

	public void setHppId(long hppId) {
		this.hppId = hppId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HPP_FON_COD", nullable = false)
	public TFonction getTFonction() {
		return this.TFonction;
	}

	public void setTFonction(TFonction TFonction) {
		this.TFonction = TFonction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HPP_DPP_ID", nullable = false)
	public TDetailPlanPassation getTDetailPlanPassation() {
		return this.TDetailPlanPassation;
	}

	public void setTDetailPlanPassation(TDetailPlanPassation TDetailPlanPassation) {
		this.TDetailPlanPassation = TDetailPlanPassation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HPP_STA_CODE", nullable = false)
	public TStatut getTStatut() {
		return this.TStatut;
	}

	public void setTStatut(TStatut TStatut) {
		this.TStatut = TStatut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HPP_DATE", length = 7)
	public Date getHppDate() {
		return this.hppDate;
	}

	public void setHppDate(Date hppDate) {
		this.hppDate = hppDate;
	}

	@Column(name = "HPP_MOTIF", length = 1000)
	public String getHppMotif() {
		return this.hppMotif;
	}

	public void setHppMotif(String hppMotif) {
		this.hppMotif = hppMotif;
	}

}
