package com.sndi.model;
// Generated 19 nov. 2020 11:49:25 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * TMotifs generated by hbm2java
 */
@Entity
@Table(name = "T_MOTIFS")
public class TMotifs implements java.io.Serializable {

	private BigDecimal mtfNum;
	private TOperateur TOperateur;
	private TMotifs TMotifs;
	private String mtfLibelle;
	private String mtfLibelleCrt;
	private String mtfType;
	private String mtfOpeModif;
	private Date mtfDteSaisi;
	private Date mtfDteModif;
	private Set<TMotifs> TMotifses = new HashSet<TMotifs>(0);

	public TMotifs() {
	}

	public TMotifs(BigDecimal mtfNum) {
		this.mtfNum = mtfNum;
	}

	public TMotifs(BigDecimal mtfNum, TOperateur TOperateur, String mtfLibelle, String mtfLibelleCrt, String mtfType,
			String mtfOpeModif, Date mtfDteSaisi, Date mtfDteModif) {
		this.mtfNum = mtfNum;
		this.TOperateur = TOperateur;
		this.mtfLibelle = mtfLibelle;
		this.mtfLibelleCrt = mtfLibelleCrt;
		this.mtfType = mtfType;
		this.mtfOpeModif = mtfOpeModif;
		this.mtfDteSaisi = mtfDteSaisi;
		this.mtfDteModif = mtfDteModif;
	}

	@Id
	@SequenceGenerator(name = "SEQ_MTF_NUM_Sequence", sequenceName = "SEQ_MTF_NUM", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_MTF_NUM_Sequence")
	@Column(name = "MTF_NUM", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMtfNum() {
		return this.mtfNum;
	}

	public void setMtfNum(BigDecimal mtfNum) {
		this.mtfNum = mtfNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTF_OPE_MATRICULE")
	public TOperateur getTOperateur() {
		return this.TOperateur;
	}

	public void setTOperateur(TOperateur TOperateur) {
		this.TOperateur = TOperateur;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTF_MTF_NUM")
	public TMotifs getTMotifs() {
		return this.TMotifs;
	}

	public void setTMotifs(TMotifs TMotifs) {
		this.TMotifs = TMotifs;
	}

	@Column(name = "MTF_LIBELLE", length = 500)
	public String getMtfLibelle() {
		return this.mtfLibelle;
	}

	public void setMtfLibelle(String mtfLibelle) {
		this.mtfLibelle = mtfLibelle;
	}

	@Column(name = "MTF_LIBELLE_CRT", length = 200)
	public String getMtfLibelleCrt() {
		return this.mtfLibelleCrt;
	}

	public void setMtfLibelleCrt(String mtfLibelleCrt) {
		this.mtfLibelleCrt = mtfLibelleCrt;
	}

	@Column(name = "MTF_TYPE", length = 10)
	public String getMtfType() {
		return this.mtfType;
	}

	public void setMtfType(String mtfType) {
		this.mtfType = mtfType;
	}

	@Column(name = "MTF_OPE_MODIF", length = 25)
	public String getMtfOpeModif() {
		return this.mtfOpeModif;
	}

	public void setMtfOpeModif(String mtfOpeModif) {
		this.mtfOpeModif = mtfOpeModif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MTF_DTE_SAISI", length = 7)
	public Date getMtfDteSaisi() {
		return this.mtfDteSaisi;
	}

	public void setMtfDteSaisi(Date mtfDteSaisi) {
		this.mtfDteSaisi = mtfDteSaisi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MTF_DTE_MODIF", length = 7)
	public Date getMtfDteModif() {
		return this.mtfDteModif;
	}

	public void setMtfDteModif(Date mtfDteModif) {
		this.mtfDteModif = mtfDteModif;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMotifs")
	public Set<TMotifs> getTMotifses() {
		return this.TMotifses;
	}

	public void setTMotifses(Set<TMotifs> TMotifses) {
		this.TMotifses = TMotifses;
	}

}
