package com.sndi.model;
// Generated 3 févr. 2020 13:07:31 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TNatures generated by hbm2java
 */
@Entity
@Table(name = "T_NATURES", schema = "EMAP")
public class TNatures implements java.io.Serializable {

	private String natCode;
	private String natLibelle;
	private String natUtilSaisi;
	private String natUtilModif;
	private Date natDteSaisi;
	private Date natDteModif;
	private String natCClasse;
	private Set<TLBudgets> TLBudgetses = new HashSet<TLBudgets>(0);

	public TNatures() {
	}

	public TNatures(String natCode) {
		this.natCode = natCode;
	}

	public TNatures(String natCode, String natLibelle, String natUtilSaisi, String natUtilModif, Date natDteSaisi,
			Date natDteModif, String natCClasse, Set<TLBudgets> TLBudgetses) {
		this.natCode = natCode;
		this.natLibelle = natLibelle;
		this.natUtilSaisi = natUtilSaisi;
		this.natUtilModif = natUtilModif;
		this.natDteSaisi = natDteSaisi;
		this.natDteModif = natDteModif;
		this.natCClasse = natCClasse;
		this.TLBudgetses = TLBudgetses;
	}

	
	@Id
	@Column(name = "NAT_CODE", unique = true, nullable = false, length = 10)
	public String getNatCode() {
		return this.natCode;
	}

	public void setNatCode(String natCode) {
		this.natCode = natCode;
	}

	@Column(name = "NAT_LIBELLE", length = 200)
	public String getNatLibelle() {
		return this.natLibelle;
	}

	public void setNatLibelle(String natLibelle) {
		this.natLibelle = natLibelle;
	}

	@Column(name = "NAT_UTIL_SAISI", length = 10)
	public String getNatUtilSaisi() {
		return this.natUtilSaisi;
	}

	public void setNatUtilSaisi(String natUtilSaisi) {
		this.natUtilSaisi = natUtilSaisi;
	}

	@Column(name = "NAT_UTIL_MODIF", length = 10)
	public String getNatUtilModif() {
		return this.natUtilModif;
	}

	public void setNatUtilModif(String natUtilModif) {
		this.natUtilModif = natUtilModif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NAT_DTE_SAISI", length = 7)
	public Date getNatDteSaisi() {
		return this.natDteSaisi;
	}

	public void setNatDteSaisi(Date natDteSaisi) {
		this.natDteSaisi = natDteSaisi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NAT_DTE_MODIF", length = 7)
	public Date getNatDteModif() {
		return this.natDteModif;
	}

	public void setNatDteModif(Date natDteModif) {
		this.natDteModif = natDteModif;
	}

	@Column(name = "NAT_C_CLASSE", length = 1)
	public String getNatCClasse() {
		return this.natCClasse;
	}

	public void setNatCClasse(String natCClasse) {
		this.natCClasse = natCClasse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TNatures")
	public Set<TLBudgets> getTLBudgetses() {
		return this.TLBudgetses;
	}

	public void setTLBudgetses(Set<TLBudgets> TLBudgetses) {
		this.TLBudgetses = TLBudgetses;
	}

}
