package com.sndi.model;
// Generated 27 janv. 2020 12:51:40 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPiecesDacs generated by hbm2java
 */
@Entity
@Table(name = "T_PIECES_DACS", schema = "EMAP")
public class TPiecesDacs implements java.io.Serializable {

	private long pidCode;
	private TDacSpecs TDacSpecs;
	private TTypePiecesDac TTypePiecesDac;
	private String pidLibelle;
	private String pidStaCode;
	private Date pidDteSaisi;
	private Set<TDetailCorrection> TDetailCorrections = new HashSet<TDetailCorrection>(0);
	private Set<TDossierDacs> TDossierDacses = new HashSet<TDossierDacs>(0);

	public TPiecesDacs() {
	}

	public TPiecesDacs(long pidCode) {
		this.pidCode = pidCode;
	}

	public TPiecesDacs(long pidCode, TDacSpecs TDacSpecs, TTypePiecesDac TTypePiecesDac, String pidLibelle,
			String pidStaCode, Date pidDteSaisi, Set<TDetailCorrection> TDetailCorrections,
			Set<TDossierDacs> TDossierDacses) {
		this.pidCode = pidCode;
		this.TDacSpecs = TDacSpecs;
		this.TTypePiecesDac = TTypePiecesDac;
		this.pidLibelle = pidLibelle;
		this.pidStaCode = pidStaCode;
		this.pidDteSaisi = pidDteSaisi;
		this.TDetailCorrections = TDetailCorrections;
		this.TDossierDacses = TDossierDacses;
	}

	@Id
	@SequenceGenerator(name = "SEQ_PID_Sequence", sequenceName = "SEQ_PID", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_PID_Sequence")
	@Column(name = "PID_CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public long getPidCode() {
		return this.pidCode;
	}

	public void setPidCode(long pidCode) {
		this.pidCode = pidCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID_DAC_CODE")
	public TDacSpecs getTDacSpecs() {
		return this.TDacSpecs;
	}

	public void setTDacSpecs(TDacSpecs TDacSpecs) {
		this.TDacSpecs = TDacSpecs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID_TPI_CODE")
	public TTypePiecesDac getTTypePiecesDac() {
		return this.TTypePiecesDac;
	}

	public void setTTypePiecesDac(TTypePiecesDac TTypePiecesDac) {
		this.TTypePiecesDac = TTypePiecesDac;
	}

	@Column(name = "PID_LIBELLE", length = 1000)
	public String getPidLibelle() {
		return this.pidLibelle;
	}

	public void setPidLibelle(String pidLibelle) {
		this.pidLibelle = pidLibelle;
	}

	@Column(name = "PID_STA_CODE", length = 3)
	public String getPidStaCode() {
		return this.pidStaCode;
	}

	public void setPidStaCode(String pidStaCode) {
		this.pidStaCode = pidStaCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PID_DTE_SAISI", length = 7)
	public Date getPidDteSaisi() {
		return this.pidDteSaisi;
	}

	public void setPidDteSaisi(Date pidDteSaisi) {
		this.pidDteSaisi = pidDteSaisi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPiecesDacs")
	public Set<TDetailCorrection> getTDetailCorrections() {
		return this.TDetailCorrections;
	}

	public void setTDetailCorrections(Set<TDetailCorrection> TDetailCorrections) {
		this.TDetailCorrections = TDetailCorrections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPiecesDacs")
	public Set<TDossierDacs> getTDossierDacses() {
		return this.TDossierDacses;
	}

	public void setTDossierDacses(Set<TDossierDacs> TDossierDacses) {
		this.TDossierDacses = TDossierDacses;
	}

}
