package com.sndi.model;
// Generated 14 mai 2020 22:45:23 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.sndi.model.TParamPieceDemande;

/**
 * TPieceDemande generated by hbm2java
 */
@Entity
@Table(name = "T_PIECE_DEMANDE", schema = "EMAP")
public class TPieceDemande implements java.io.Serializable {

	private BigDecimal pdmNum;
	private BigDecimal TParamPieceDemande;
	private TDemande TDemande;
	private String pdmLibeleCourt;
	private String pdmLibeleLong;

	public TPieceDemande() {
	}

	public TPieceDemande(BigDecimal pdmNum, BigDecimal TParamPieceDemande, TDemande TDemande) {
		this.pdmNum = pdmNum;
		this.TParamPieceDemande = TParamPieceDemande;
		this.TDemande = TDemande;
	}

	public TPieceDemande(BigDecimal pdmNum, BigDecimal TParamPieceDemande, TDemande TDemande,
			String pdmLibeleCourt, String pdmLibeleLong) {
		this.pdmNum = pdmNum;
		this.TParamPieceDemande = TParamPieceDemande;
		this.TDemande = TDemande;
		this.pdmLibeleCourt = pdmLibeleCourt;
		this.pdmLibeleLong = pdmLibeleLong;
	}

	@Id
	@SequenceGenerator(name = "SEQ_PIECE_DEM_Sequence", sequenceName = "SEQ_PIECE_DEM", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_PIECE_DEM_Sequence")
	@Column(name = "PDM_NUM", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPdmNum() {
		return this.pdmNum;
	}

	public void setPdmNum(BigDecimal pdmNum) {
		this.pdmNum = pdmNum;
	}

	@Column(name = "PDM_PID_NUM", nullable = false)
	public BigDecimal getTParamPieceDemande() {
		return this.TParamPieceDemande;
	}

	public void setTParamPieceDemande(BigDecimal TParamPieceDemande) {
		this.TParamPieceDemande = TParamPieceDemande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PDM_DEM_NUM", nullable = false)
	public TDemande getTDemande() {
		return this.TDemande;
	}

	public void setTDemande(TDemande TDemande) {
		this.TDemande = TDemande;
	}

	@Column(name = "PDM_LIBELE_COURT", length = 100)
	public String getPdmLibeleCourt() {
		return this.pdmLibeleCourt;
	}

	public void setPdmLibeleCourt(String pdmLibeleCourt) {
		this.pdmLibeleCourt = pdmLibeleCourt;
	}

	@Column(name = "PDM_LIBELE_LONG", length = 500)
	public String getPdmLibeleLong() {
		return this.pdmLibeleLong;
	}

	public void setPdmLibeleLong(String pdmLibeleLong) {
		this.pdmLibeleLong = pdmLibeleLong;
	}

}
