package com.sndi.model;
// Generated 4 déc. 2019 12:32:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TStatut generated by hbm2java
 */
@Entity
@Table(name = "T_STATUT", schema = "EMAP")
public class TStatut implements java.io.Serializable {

	private String staCode;
	private String staLibelleCourt;
	private String staLibelleLong;
	private String acLibelle;
	private String sodeLibelle;
	private String cpmpLibelle;
	private String drmpLibelle;
	private String dgmpLibelle;
	private Set<THistoPlanGeneral> THistoPlanGenerals = new HashSet<THistoPlanGeneral>(0);
	private Set<TAffichageAgpm> TAffichageAgpms = new HashSet<TAffichageAgpm>(0);
	private Set<THistoPlanPassation> THistoPlanPassations = new HashSet<THistoPlanPassation>(0);
	private Set<TDetailPlanPassation> TDetailPlanPassations = new HashSet<TDetailPlanPassation>(0);
	private Set<TAgpm> TAgpms = new HashSet<TAgpm>(0);
	private Set<THistoAgpm> THistoAgpms = new HashSet<THistoAgpm>(0);
	private Set<TDetailPlanGeneral> TDetailPlanGenerals = new HashSet<TDetailPlanGeneral>(0);

	public TStatut() {
	}

	public TStatut(String staCode) {
		this.staCode = staCode;
	}

	public TStatut(String staCode, String staLibelleCourt, String staLibelleLong,
			Set<THistoPlanGeneral> THistoPlanGenerals, Set<TAffichageAgpm> TAffichageAgpms,
			Set<THistoPlanPassation> THistoPlanPassations, Set<TDetailPlanPassation> TDetailPlanPassations,
			Set<TAgpm> TAgpms, Set<THistoAgpm> THistoAgpms, Set<TDetailPlanGeneral> TDetailPlanGenerals) {
		this.staCode = staCode;
		this.staLibelleCourt = staLibelleCourt;
		this.staLibelleLong = staLibelleLong;
		this.THistoPlanGenerals = THistoPlanGenerals;
		this.TAffichageAgpms = TAffichageAgpms;
		this.THistoPlanPassations = THistoPlanPassations;
		this.TDetailPlanPassations = TDetailPlanPassations;
		this.TAgpms = TAgpms;
		this.THistoAgpms = THistoAgpms;
		this.TDetailPlanGenerals = TDetailPlanGenerals;
	}

	@Id

	@Column(name = "STA_CODE", unique = true, nullable = false, length = 3)
	public String getStaCode() {
		return this.staCode;
	}

	public void setStaCode(String staCode) {
		this.staCode = staCode;
	}

	@Column(name = "STA_LIBELLE_COURT", length = 500)
	public String getStaLibelleCourt() {
		return this.staLibelleCourt;
	}
	
	
	@Column(name = "AC_LIBELLE", length = 500)
	public String getAcLibelle() {
		return acLibelle;
	}

	public void setAcLibelle(String acLibelle) {
		this.acLibelle = acLibelle;
	}
	
	@Column(name = "SODE_LIBELLE", length = 500)
	public String getSodeLibelle() {
		return sodeLibelle;
	}

	public void setSodeLibelle(String sodeLibelle) {
		this.sodeLibelle = sodeLibelle;
	}

	@Column(name = "CPMP_LIBELLE", length = 500)
	public String getCpmpLibelle() {
		return cpmpLibelle;
	}

	public void setCpmpLibelle(String cpmpLibelle) {
		this.cpmpLibelle = cpmpLibelle;
	}

	@Column(name = "DRMP_LIBELLE", length = 500)
	public String getDrmpLibelle() {
		return drmpLibelle;
	}

	public void setDrmpLibelle(String drmpLibelle) {
		this.drmpLibelle = drmpLibelle;
	}

	@Column(name = "DGMP_LIBELLE", length = 500)
	public String getDgmpLibelle() {
		return dgmpLibelle;
	}

	public void setDgmpLibelle(String dgmpLibelle) {
		this.dgmpLibelle = dgmpLibelle;
	}

	public void setStaLibelleCourt(String staLibelleCourt) {
		this.staLibelleCourt = staLibelleCourt;
	}

	@Column(name = "STA_LIBELLE_LONG", length = 1000)
	public String getStaLibelleLong() {
		return this.staLibelleLong;
	}

	public void setStaLibelleLong(String staLibelleLong) {
		this.staLibelleLong = staLibelleLong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<THistoPlanGeneral> getTHistoPlanGenerals() {
		return this.THistoPlanGenerals;
	}

	public void setTHistoPlanGenerals(Set<THistoPlanGeneral> THistoPlanGenerals) {
		this.THistoPlanGenerals = THistoPlanGenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<TAffichageAgpm> getTAffichageAgpms() {
		return this.TAffichageAgpms;
	}

	public void setTAffichageAgpms(Set<TAffichageAgpm> TAffichageAgpms) {
		this.TAffichageAgpms = TAffichageAgpms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<THistoPlanPassation> getTHistoPlanPassations() {
		return this.THistoPlanPassations;
	}

	public void setTHistoPlanPassations(Set<THistoPlanPassation> THistoPlanPassations) {
		this.THistoPlanPassations = THistoPlanPassations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<TDetailPlanPassation> getTDetailPlanPassations() {
		return this.TDetailPlanPassations;
	}

	public void setTDetailPlanPassations(Set<TDetailPlanPassation> TDetailPlanPassations) {
		this.TDetailPlanPassations = TDetailPlanPassations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<TAgpm> getTAgpms() {
		return this.TAgpms;
	}

	public void setTAgpms(Set<TAgpm> TAgpms) {
		this.TAgpms = TAgpms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<THistoAgpm> getTHistoAgpms() {
		return this.THistoAgpms;
	}

	public void setTHistoAgpms(Set<THistoAgpm> THistoAgpms) {
		this.THistoAgpms = THistoAgpms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStatut")
	public Set<TDetailPlanGeneral> getTDetailPlanGenerals() {
		return this.TDetailPlanGenerals;
	}

	public void setTDetailPlanGenerals(Set<TDetailPlanGeneral> TDetailPlanGenerals) {
		this.TDetailPlanGenerals = TDetailPlanGenerals;
	}

}
