package com.sndi.model;
// Generated 7 mars 2020 16:13:16 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TVenteDac generated by hbm2java
 */
@Entity
@Table(name = "T_VENTE_DAC", schema = "EMAP")
public class TVenteDac implements java.io.Serializable {

	private long venNum;
	private TCandidats TCandidats;
	private TOperateur TOperateur;
	private TModeReglement TModeReglement;
	private Date venDteSaisi;
	private String venPaieCode;
	private Set<TDetailVente> TDetailVentes = new HashSet<TDetailVente>(0);

	public TVenteDac() {
	}

	public TVenteDac(long venNum, TCandidats TCandidats, TOperateur TOperateur, TModeReglement TModeReglement) {
		this.venNum = venNum;
		this.TCandidats = TCandidats;
		this.TOperateur = TOperateur;
		this.TModeReglement = TModeReglement;
	}

	public TVenteDac(long venNum, TCandidats TCandidats, TOperateur TOperateur, TModeReglement TModeReglement,
			Date venDteSaisi,String venPaieCode, Set<TDetailVente> TDetailVentes) {
		this.venNum = venNum;
		this.TCandidats = TCandidats;
		this.TOperateur = TOperateur;
		this.TModeReglement = TModeReglement;
		this.venDteSaisi = venDteSaisi;
		this.venPaieCode = venPaieCode;
		this.TDetailVentes = TDetailVentes;
	}

	@Id
	@SequenceGenerator(name = "SEQ_VEN_NUM_Sequence", sequenceName = "SEQ_VEN_NUM", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_VEN_NUM_Sequence")
	@Column(name = "VEN_NUM", unique = true, nullable = false, precision = 2, scale = 0)
	public long getVenNum() {
		return this.venNum;
	}

	public void setVenNum(long venNum) {
		this.venNum = venNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEN_CAN_CODE", nullable = false)
	public TCandidats getTCandidats() {
		return this.TCandidats;
	}

	public void setTCandidats(TCandidats TCandidats) {
		this.TCandidats = TCandidats;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEN_OPE_MATRICULE", nullable = false)
	public TOperateur getTOperateur() {
		return this.TOperateur;
	}

	public void setTOperateur(TOperateur TOperateur) {
		this.TOperateur = TOperateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEN_MRG_COD", nullable = false)
	public TModeReglement getTModeReglement() {
		return this.TModeReglement;
	}

	public void setTModeReglement(TModeReglement TModeReglement) {
		this.TModeReglement = TModeReglement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VEN_DTE_SAISI", length = 7)
	public Date getVenDteSaisi() {
		return this.venDteSaisi;
	}

	public void setVenDteSaisi(Date venDteSaisi) {
		this.venDteSaisi = venDteSaisi;
	}
	
	@Column(name = "VEN_PAIE_CODE", length = 15)
	public String getVenPaieCode() {
		return this.venPaieCode;
	}

	public void setVenPaieCode(String venPaieCode) {
		this.venPaieCode = venPaieCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TVenteDac")
	public Set<TDetailVente> getTDetailVentes() {
		return this.TDetailVentes;
	}

	public void setTDetailVentes(Set<TDetailVente> TDetailVentes) {
		this.TDetailVentes = TDetailVentes;
	}

}
