package com.sndi.model;
// Generated 22 oct. 2020 13:02:55 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VAcDmpId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_AC_DMP")
public class VAcDmp implements java.io.Serializable {

	private BigDecimal RIddmp;
	private String fonCodeDmp;
	private String libdmp;
	private String fonTyfCodac;
	private String fonTyfCodpf;
	private String fonTyfCoddmp;

	public VAcDmp() {
	}

	public VAcDmp(BigDecimal RIddmp, String fonCodeDmp, String libdmp, String fonTyfCodac, String fonTyfCodpf,
			String fonTyfCoddmp) {
		this.RIddmp = RIddmp;
		this.fonCodeDmp = fonCodeDmp;
		this.libdmp = libdmp;
		this.fonTyfCodac = fonTyfCodac;
		this.fonTyfCodpf = fonTyfCodpf;
		this.fonTyfCoddmp = fonTyfCoddmp;
	}

	@Id
	@Column(name = "R_IDDMP", precision = 22, scale = 0)
	public BigDecimal getRIddmp() {
		return this.RIddmp;
	}

	public void setRIddmp(BigDecimal RIddmp) {
		this.RIddmp = RIddmp;
	}

	@Column(name = "FON_CODE_DMP", length = 20)
	public String getFonCodeDmp() {
		return this.fonCodeDmp;
	}

	public void setFonCodeDmp(String fonCodeDmp) {
		this.fonCodeDmp = fonCodeDmp;
	}

	@Column(name = "LIBDMP", length = 525)
	public String getLibdmp() {
		return this.libdmp;
	}

	public void setLibdmp(String libdmp) {
		this.libdmp = libdmp;
	}

	@Column(name = "FON_TYF_CODAC", length = 3)
	public String getFonTyfCodac() {
		return this.fonTyfCodac;
	}

	public void setFonTyfCodac(String fonTyfCodac) {
		this.fonTyfCodac = fonTyfCodac;
	}

	@Column(name = "FON_TYF_CODPF", length = 3)
	public String getFonTyfCodpf() {
		return this.fonTyfCodpf;
	}

	public void setFonTyfCodpf(String fonTyfCodpf) {
		this.fonTyfCodpf = fonTyfCodpf;
	}

	@Column(name = "FON_TYF_CODDMP", length = 3)
	public String getFonTyfCoddmp() {
		return this.fonTyfCoddmp;
	}

	public void setFonTyfCoddmp(String fonTyfCoddmp) {
		this.fonTyfCoddmp = fonTyfCoddmp;
	}
}
