package com.sndi.model;
// Generated 7 mars 2020 14:29:23 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VAgpmBailleur generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_AGPM_BAILLEUR")
public class VAgpmBailleur implements java.io.Serializable {

	private long agpId;
	private long proId;
	private String proTitre;
	private String baiCode;
	private String baiLibelle;
	private String baiAdresse;
	private String baiTelephone;

	public VAgpmBailleur() {
	}

	public VAgpmBailleur(long agpId, long proId, String proTitre, String baiCode, String baiLibelle) {
		this.agpId = agpId;
		this.proId = proId;
		this.proTitre = proTitre;
		this.baiCode = baiCode;
		this.baiLibelle = baiLibelle;
	}

	public VAgpmBailleur(long agpId, long proId, String proTitre, String baiCode, String baiLibelle,
			String baiAdresse, String baiTelephone) {
		this.agpId = agpId;
		this.proId = proId;
		this.proTitre = proTitre;
		this.baiCode = baiCode;
		this.baiLibelle = baiLibelle;
		this.baiAdresse = baiAdresse;
		this.baiTelephone = baiTelephone;
	}

	
	@Id
	@Column(name = "AGP_ID", nullable = false, precision = 10, scale = 0)
	public long getAgpId() {
		return this.agpId;
	}

	public void setAgpId(long agpId) {
		this.agpId = agpId;
	}

	@Column(name = "PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getProId() {
		return this.proId;
	}

	public void setProId(long proId) {
		this.proId = proId;
	}

	@Column(name = "PRO_TITRE", nullable = false, length = 500)
	public String getProTitre() {
		return this.proTitre;
	}

	public void setProTitre(String proTitre) {
		this.proTitre = proTitre;
	}

	@Column(name = "BAI_CODE", nullable = false, length = 5)
	public String getBaiCode() {
		return this.baiCode;
	}

	public void setBaiCode(String baiCode) {
		this.baiCode = baiCode;
	}

	@Column(name = "BAI_LIBELLE", nullable = false, length = 1000)
	public String getBaiLibelle() {
		return this.baiLibelle;
	}

	public void setBaiLibelle(String baiLibelle) {
		this.baiLibelle = baiLibelle;
	}

	@Column(name = "BAI_ADRESSE", length = 500)
	public String getBaiAdresse() {
		return this.baiAdresse;
	}

	public void setBaiAdresse(String baiAdresse) {
		this.baiAdresse = baiAdresse;
	}

	@Column(name = "BAI_TELEPHONE", length = 500)
	public String getBaiTelephone() {
		return this.baiTelephone;
	}

	public void setBaiTelephone(String baiTelephone) {
		this.baiTelephone = baiTelephone;
	}

}
