package com.sndi.model;
// Generated 21 déc. 2019 13:26:18 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VAgpmDetails generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_AGPM_DETAILS")
public class VAgpmDetails implements java.io.Serializable {

	private long affProId;
	private long proId;
	private String proLibelle;
	private String proDescription;
	private String proTitre;
	private Long proMontantTotCfa;
	private String minLibelle;
	private String minDescription;
	private Date gesDateDebut;
	private Date gesDateFin;
	private String decPersNomPrenom;
	private String decPersFonction;
	private String decTelephone;
	private String decOrganExecLibelle;
	private String decOrganExecAdresse;
	private String decNumeroPorte;
	private String decLocalisation;
	private String decEmail;
	private String decBp;
	private String decCel;
	private long affAgpId;
	private long affGesCode;
	private String affAgpCommentaire;
	private String affAgpActif;
	private String affAgpTypeDao;
	private String affAgpStaCode;
	private String regLibelleLong;
	private String regLibelleCourt;
	private String fonLibelle;

	public VAgpmDetails() {
	}
	
	public VAgpmDetails( long affAgpId) {
		this.affAgpId = affAgpId;
	}

	public VAgpmDetails(long affProId, long proId, String proTitre, long affAgpId, long affGesCode,
			String affAgpStaCode) {
		this.affProId = affProId;
		this.proId = proId;
		this.proTitre = proTitre;
		this.affAgpId = affAgpId;
		this.affGesCode = affGesCode;
		this.affAgpStaCode = affAgpStaCode;
	}

	public VAgpmDetails(long affProId, long proId, String proLibelle, String proDescription, String proTitre,
			Long proMontantTotCfa, String minLibelle, String minDescription, Date gesDateDebut, Date gesDateFin,
			String decPersNomPrenom, String decPersFonction, String decTelephone, String decOrganExecLibelle,
			String decOrganExecAdresse, String decNumeroPorte, String decLocalisation, String decEmail, String decBp,String decCel,
			long affAgpId, long affGesCode, String affAgpCommentaire, String affAgpActif, String affAgpTypeDao,
			String affAgpStaCode, String regLibelleLong, String regLibelleCourt, String fonLibelle) {
		this.affProId = affProId;
		this.proId = proId;
		this.proLibelle = proLibelle;
		this.proDescription = proDescription;
		this.proTitre = proTitre;
		this.proMontantTotCfa = proMontantTotCfa;
		this.minLibelle = minLibelle;
		this.minDescription = minDescription;
		this.gesDateDebut = gesDateDebut;
		this.gesDateFin = gesDateFin;
		this.decPersNomPrenom = decPersNomPrenom;
		this.decPersFonction = decPersFonction;
		this.decTelephone = decTelephone;
		this.decOrganExecLibelle = decOrganExecLibelle;
		this.decOrganExecAdresse = decOrganExecAdresse;
		this.decNumeroPorte = decNumeroPorte;
		this.decLocalisation = decLocalisation;
		this.decEmail = decEmail;
		this.decBp = decBp;
		this.decCel = decCel;
		this.affAgpId = affAgpId;
		this.affGesCode = affGesCode;
		this.affAgpCommentaire = affAgpCommentaire;
		this.affAgpActif = affAgpActif;
		this.affAgpTypeDao = affAgpTypeDao;
		this.affAgpStaCode = affAgpStaCode;
		this.regLibelleLong = regLibelleLong;
		this.regLibelleCourt = regLibelleCourt;
		this.fonLibelle = fonLibelle;
	}

	
	@Id
	@Column(name = "AFF_PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getAffProId() {
		return this.affProId;
	}

	public void setAffProId(long affProId) {
		this.affProId = affProId;
	}

	@Column(name = "PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getProId() {
		return this.proId;
	}

	public void setProId(long proId) {
		this.proId = proId;
	}

	@Column(name = "PRO_LIBELLE", length = 500)
	public String getProLibelle() {
		return this.proLibelle;
	}

	public void setProLibelle(String proLibelle) {
		this.proLibelle = proLibelle;
	}

	@Column(name = "PRO_DESCRIPTION", length = 1000)
	public String getProDescription() {
		return this.proDescription;
	}

	public void setProDescription(String proDescription) {
		this.proDescription = proDescription;
	}

	@Column(name = "PRO_TITRE", nullable = false, length = 500)
	public String getProTitre() {
		return this.proTitre;
	}

	public void setProTitre(String proTitre) {
		this.proTitre = proTitre;
	}

	@Column(name = "PRO_MONTANT_TOT_CFA", precision = 15)
	public Long getProMontantTotCfa() {
		return this.proMontantTotCfa;
	}

	public void setProMontantTotCfa(Long proMontantTotCfa) {
		this.proMontantTotCfa = proMontantTotCfa;
	}

	@Column(name = "MIN_LIBELLE", length = 1000)
	public String getMinLibelle() {
		return this.minLibelle;
	}

	public void setMinLibelle(String minLibelle) {
		this.minLibelle = minLibelle;
	}

	@Column(name = "MIN_DESCRIPTION", length = 1000)
	public String getMinDescription() {
		return this.minDescription;
	}

	public void setMinDescription(String minDescription) {
		this.minDescription = minDescription;
	}

	@Column(name = "GES_DATE_DEBUT", length = 7)
	public Date getGesDateDebut() {
		return this.gesDateDebut;
	}

	public void setGesDateDebut(Date gesDateDebut) {
		this.gesDateDebut = gesDateDebut;
	}

	@Column(name = "GES_DATE_FIN", length = 7)
	public Date getGesDateFin() {
		return this.gesDateFin;
	}

	public void setGesDateFin(Date gesDateFin) {
		this.gesDateFin = gesDateFin;
	}

	@Column(name = "DEC_PERS_NOM_PRENOM", length = 500)
	public String getDecPersNomPrenom() {
		return this.decPersNomPrenom;
	}

	public void setDecPersNomPrenom(String decPersNomPrenom) {
		this.decPersNomPrenom = decPersNomPrenom;
	}

	@Column(name = "DEC_PERS_FONCTION", length = 500)
	public String getDecPersFonction() {
		return this.decPersFonction;
	}

	public void setDecPersFonction(String decPersFonction) {
		this.decPersFonction = decPersFonction;
	}

	@Column(name = "DEC_TELEPHONE", length = 500)
	public String getDecTelephone() {
		return this.decTelephone;
	}

	public void setDecTelephone(String decTelephone) {
		this.decTelephone = decTelephone;
	}

	@Column(name = "DEC_ORGAN_EXEC_LIBELLE", length = 500)
	public String getDecOrganExecLibelle() {
		return this.decOrganExecLibelle;
	}

	public void setDecOrganExecLibelle(String decOrganExecLibelle) {
		this.decOrganExecLibelle = decOrganExecLibelle;
	}

	@Column(name = "DEC_ORGAN_EXEC_ADRESSE", length = 500)
	public String getDecOrganExecAdresse() {
		return this.decOrganExecAdresse;
	}

	public void setDecOrganExecAdresse(String decOrganExecAdresse) {
		this.decOrganExecAdresse = decOrganExecAdresse;
	}

	@Column(name = "DEC_NUMERO_PORTE", length = 500)
	public String getDecNumeroPorte() {
		return this.decNumeroPorte;
	}

	public void setDecNumeroPorte(String decNumeroPorte) {
		this.decNumeroPorte = decNumeroPorte;
	}

	@Column(name = "DEC_LOCALISATION", length = 500)
	public String getDecLocalisation() {
		return this.decLocalisation;
	}

	public void setDecLocalisation(String decLocalisation) {
		this.decLocalisation = decLocalisation;
	}

	@Column(name = "DEC_EMAIL", length = 500)
	public String getDecEmail() {
		return this.decEmail;
	}

	public void setDecEmail(String decEmail) {
		this.decEmail = decEmail;
	}

	@Column(name = "DEC_BP", length = 500)
	public String getDecBp() {
		return this.decBp;
	}

	public void setDecBp(String decBp) {
		this.decBp = decBp;
	}
	
	@Column(name = "DEC_CEL", length = 500)
	public String getDecCel() {
		return this.decCel;
	}

	public void setDecCel(String decCel) {
		this.decCel = decCel;
	}

	@Column(name = "AFF_AGP_ID", nullable = false, precision = 10, scale = 0)
	public long getAffAgpId() {
		return this.affAgpId;
	}

	public void setAffAgpId(long affAgpId) {
		this.affAgpId = affAgpId;
	}

	@Column(name = "AFF_GES_CODE", nullable = false, precision = 4, scale = 0)
	public long getAffGesCode() {
		return this.affGesCode;
	}

	public void setAffGesCode(long affGesCode) {
		this.affGesCode = affGesCode;
	}

	@Column(name = "AFF_AGP_COMMENTAIRE", length = 1000)
	public String getAffAgpCommentaire() {
		return this.affAgpCommentaire;
	}

	public void setAffAgpCommentaire(String affAgpCommentaire) {
		this.affAgpCommentaire = affAgpCommentaire;
	}

	@Column(name = "AFF_AGP_ACTIF", length = 1)
	public String getAffAgpActif() {
		return this.affAgpActif;
	}

	public void setAffAgpActif(String affAgpActif) {
		this.affAgpActif = affAgpActif;
	}

	@Column(name = "AFF_AGP_TYPE_DAO", length = 1000)
	public String getAffAgpTypeDao() {
		return this.affAgpTypeDao;
	}

	public void setAffAgpTypeDao(String affAgpTypeDao) {
		this.affAgpTypeDao = affAgpTypeDao;
	}

	@Column(name = "AFF_AGP_STA_CODE", nullable = false, length = 3)
	public String getAffAgpStaCode() {
		return this.affAgpStaCode;
	}

	public void setAffAgpStaCode(String affAgpStaCode) {
		this.affAgpStaCode = affAgpStaCode;
	}

	@Column(name = "REG_LIBELLE_LONG", length = 1000)
	public String getRegLibelleLong() {
		return this.regLibelleLong;
	}

	public void setRegLibelleLong(String regLibelleLong) {
		this.regLibelleLong = regLibelleLong;
	}

	@Column(name = "REG_LIBELLE_COURT", length = 500)
	public String getRegLibelleCourt() {
		return this.regLibelleCourt;
	}

	public void setRegLibelleCourt(String regLibelleCourt) {
		this.regLibelleCourt = regLibelleCourt;
	}

	@Column(name = "FON_LIBELLE", length = 240)
	public String getFonLibelle() {
		return this.fonLibelle;
	}

	public void setFonLibelle(String fonLibelle) {
		this.fonLibelle = fonLibelle;
	}

}
