package com.sndi.model;
// Generated 14 déc. 2020 17:22:06 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VAmiDpId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_AMI_DP")
public class VAmiDp implements java.io.Serializable {

	private long dppId;
	private String dppObjet;
	private String dppTypePlan;

	public VAmiDp() {
	}

	public VAmiDp(long dppId) {
		this.dppId = dppId;
	}

	public VAmiDp(long dppId, String dppObjet, String dppTypePlan) {
		this.dppId = dppId;
		this.dppObjet = dppObjet;
		this.dppTypePlan = dppTypePlan;
	}

	@Id
	@Column(name = "DPP_ID", nullable = false, precision = 10, scale = 0)
	public long getDppId() {
		return this.dppId;
	}

	public void setDppId(long dppId) {
		this.dppId = dppId;
	}

	@Column(name = "DPP_OBJET", length = 1000)
	public String getDppObjet() {
		return this.dppObjet;
	}

	public void setDppObjet(String dppObjet) {
		this.dppObjet = dppObjet;
	}
	
	@Column(name = "DPP_TYPE_PLAN", nullable = false, length = 3)
	public String getDppTypePlan() {
		return this.dppTypePlan;
	}

	public void setDppTypePlan(String dppTypePlan) {
		this.dppTypePlan = dppTypePlan;
	}
}
