package com.sndi.model;
// Generated 29 juin 2021 17:31:04 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VAvisPublieId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_AVIS_PUBLIE")
public class VAvisPublie implements java.io.Serializable {

	private BigDecimal RId;
	private String pubAaoNumFtp;
	private String pubBulCode;
	private String pubObjetJournal;
	private Date pubBulDtePub;
	private String pubDacCode;
	private String pubObjetDac;
	private String dacStatutRetour;
	private String tymLibelleCourt;
	private String dacCode;
	private String dacStaCode;
	private Date dacDteModif;
	private String dacFonCodAc;
	private String dacFonCodeCpmp;
	private String fonCodeCsv;
	private String mopLibelleLong;
	private String dacTypePlan;
	private BigDecimal dacGesCode;
	private String strLibelleLong;
	private String tymCode;
	private String mopCode;
	private Date dacDateAvisBailleur;
	private String dacAvisBailleur;
	private String critere;
	private String mois;

	public VAvisPublie() {
	}

	public VAvisPublie(BigDecimal RId, String pubAaoNumFtp, String pubBulCode, String pubObjetJournal,
			Date pubBulDtePub, String pubDacCode, String pubObjetDac, String dacStatutRetour, String tymLibelleCourt,
			String dacCode, String dacStaCode, Date dacDteModif, String dacFonCodAc, String dacFonCodeCpmp,
			String fonCodeCsv, String mopLibelleLong, String dacTypePlan, BigDecimal dacGesCode, String strLibelleLong,
			String tymCode, String mopCode, Date dacDateAvisBailleur, String dacAvisBailleur, String critere,
			String mois) {
		this.RId = RId;
		this.pubAaoNumFtp = pubAaoNumFtp;
		this.pubBulCode = pubBulCode;
		this.pubObjetJournal = pubObjetJournal;
		this.pubBulDtePub = pubBulDtePub;
		this.pubDacCode = pubDacCode;
		this.pubObjetDac = pubObjetDac;
		this.dacStatutRetour = dacStatutRetour;
		this.tymLibelleCourt = tymLibelleCourt;
		this.dacCode = dacCode;
		this.dacStaCode = dacStaCode;
		this.dacDteModif = dacDteModif;
		this.dacFonCodAc = dacFonCodAc;
		this.dacFonCodeCpmp = dacFonCodeCpmp;
		this.fonCodeCsv = fonCodeCsv;
		this.mopLibelleLong = mopLibelleLong;
		this.dacTypePlan = dacTypePlan;
		this.dacGesCode = dacGesCode;
		this.strLibelleLong = strLibelleLong;
		this.tymCode = tymCode;
		this.mopCode = mopCode;
		this.dacDateAvisBailleur = dacDateAvisBailleur;
		this.dacAvisBailleur = dacAvisBailleur;
		this.critere = critere;
		this.mois = mois;
	}

	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "PUB_AAO_NUM_FTP", length = 18)
	public String getPubAaoNumFtp() {
		return this.pubAaoNumFtp;
	}

	public void setPubAaoNumFtp(String pubAaoNumFtp) {
		this.pubAaoNumFtp = pubAaoNumFtp;
	}

	@Column(name = "PUB_BUL_CODE", length = 19)
	public String getPubBulCode() {
		return this.pubBulCode;
	}

	public void setPubBulCode(String pubBulCode) {
		this.pubBulCode = pubBulCode;
	}

	@Column(name = "PUB_OBJET_JOURNAL", length = 40)
	public String getPubObjetJournal() {
		return this.pubObjetJournal;
	}

	public void setPubObjetJournal(String pubObjetJournal) {
		this.pubObjetJournal = pubObjetJournal;
	}

	@Column(name = "PUB_BUL_DTE_PUB", length = 8)
	public Date getPubBulDtePub() {
		return this.pubBulDtePub;
	}

	public void setPubBulDtePub(Date pubBulDtePub) {
		this.pubBulDtePub = pubBulDtePub;
	}

	@Column(name = "PUB_DAC_CODE", length = 10)
	public String getPubDacCode() {
		return this.pubDacCode;
	}

	public void setPubDacCode(String pubDacCode) {
		this.pubDacCode = pubDacCode;
	}

	@Column(name = "PUB_OBJET_DAC", length = 11)
	public String getPubObjetDac() {
		return this.pubObjetDac;
	}

	public void setPubObjetDac(String pubObjetDac) {
		this.pubObjetDac = pubObjetDac;
	}

	@Column(name = "DAC_STATUT_RETOUR", length = 19)
	public String getDacStatutRetour() {
		return this.dacStatutRetour;
	}

	public void setDacStatutRetour(String dacStatutRetour) {
		this.dacStatutRetour = dacStatutRetour;
	}

	@Column(name = "TYM_LIBELLE_COURT", length = 19)
	public String getTymLibelleCourt() {
		return this.tymLibelleCourt;
	}

	public void setTymLibelleCourt(String tymLibelleCourt) {
		this.tymLibelleCourt = tymLibelleCourt;
	}

	@Column(name = "DAC_CODE", length = 10)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "DAC_STA_CODE", length = 14)
	public String getDacStaCode() {
		return this.dacStaCode;
	}

	public void setDacStaCode(String dacStaCode) {
		this.dacStaCode = dacStaCode;
	}

	@Column(name = "DAC_DTE_MODIF", length = 8)
	public Date getDacDteModif() {
		return this.dacDteModif;
	}

	public void setDacDteModif(Date dacDteModif) {
		this.dacDteModif = dacDteModif;
	}

	@Column(name = "DAC_FON_COD_AC", length = 16)
	public String getDacFonCodAc() {
		return this.dacFonCodAc;
	}

	public void setDacFonCodAc(String dacFonCodAc) {
		this.dacFonCodAc = dacFonCodAc;
	}

	@Column(name = "DAC_FON_CODE_CPMP", length = 19)
	public String getDacFonCodeCpmp() {
		return this.dacFonCodeCpmp;
	}

	public void setDacFonCodeCpmp(String dacFonCodeCpmp) {
		this.dacFonCodeCpmp = dacFonCodeCpmp;
	}

	@Column(name = "FON_CODE_CSV", length = 14)
	public String getFonCodeCsv() {
		return this.fonCodeCsv;
	}

	public void setFonCodeCsv(String fonCodeCsv) {
		this.fonCodeCsv = fonCodeCsv;
	}

	@Column(name = "MOP_LIBELLE_LONG", length = 18)
	public String getMopLibelleLong() {
		return this.mopLibelleLong;
	}

	public void setMopLibelleLong(String mopLibelleLong) {
		this.mopLibelleLong = mopLibelleLong;
	}

	@Column(name = "DAC_TYPE_PLAN", length = 15)
	public String getDacTypePlan() {
		return this.dacTypePlan;
	}

	public void setDacTypePlan(String dacTypePlan) {
		this.dacTypePlan = dacTypePlan;
	}
	
	@Column(name = "DAC_GES_CODE", precision = 22, scale = 0)
	public BigDecimal getDacGesCode() {
		return this.dacGesCode;
	}

	public void setDacGesCode(BigDecimal dacGesCode) {
		this.dacGesCode = dacGesCode;
	}

	@Column(name = "STR_LIBELLE_LONG", length = 200)
	public String getStrLibelleLong() {
		return this.strLibelleLong;
	}

	public void setStrLibelleLong(String strLibelleLong) {
		this.strLibelleLong = strLibelleLong;
	}

	@Column(name = "TYM_CODE", length = 10)
	public String getTymCode() {
		return this.tymCode;
	}

	public void setTymCode(String tymCode) {
		this.tymCode = tymCode;
	}

	@Column(name = "MOP_CODE", length = 10)
	public String getMopCode() {
		return this.mopCode;
	}

	public void setMopCode(String mopCode) {
		this.mopCode = mopCode;
	}

	@Column(name = "DAC_DATE_AVIS_BAILLEUR", length = 7)
	public Date getDacDateAvisBailleur() {
		return this.dacDateAvisBailleur;
	}

	public void setDacDateAvisBailleur(Date dacDateAvisBailleur) {
		this.dacDateAvisBailleur = dacDateAvisBailleur;
	}

	@Column(name = "DAC_AVIS_BAILLEUR", length = 20)
	public String getDacAvisBailleur() {
		return this.dacAvisBailleur;
	}

	public void setDacAvisBailleur(String dacAvisBailleur) {
		this.dacAvisBailleur = dacAvisBailleur;
	}

	@Column(name = "CRITERE", length = 300)
	public String getCritere() {
		return this.critere;
	}

	public void setCritere(String critere) {
		this.critere = critere;
	}
	
	@Column(name = "MOIS", length = 36)
	public String getMois() {
		return this.mois;
	}

	public void setMois(String mois) {
		this.mois = mois;
	}

}
