package com.sndi.model;
// Generated 13 févr. 2020 11:47:53 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbCorrectionDac generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_CORRECTION_DAC")
public class VbCorrectionDac implements java.io.Serializable {

	private long corNum;
	private String corDacCode;
	private String corLieblle;
	private Date corDteSaisi;
	private String corOpeMatricule;

	public VbCorrectionDac() {
	}

	public VbCorrectionDac(long corNum) {
		this.corNum = corNum;
	}

	public VbCorrectionDac(long corNum, String corDacCode, String corLieblle, Date corDteSaisi,
			String corOpeMatricule) {
		this.corNum = corNum;
		this.corDacCode = corDacCode;
		this.corLieblle = corLieblle;
		this.corDteSaisi = corDteSaisi;
		this.corOpeMatricule = corOpeMatricule;
	}

	
	@Id
	@Column(name = "COR_NUM", nullable = false, precision = 22, scale = 0)
	public long getCorNum() {
		return this.corNum;
	}

	public void setCorNum(long corNum) {
		this.corNum = corNum;
	}

	@Column(name = "COR_DAC_CODE", length = 20)
	public String getCorDacCode() {
		return this.corDacCode;
	}

	public void setCorDacCode(String corDacCode) {
		this.corDacCode = corDacCode;
	}

	@Column(name = "COR_LIEBLLE", length = 200)
	public String getCorLieblle() {
		return this.corLieblle;
	}

	public void setCorLieblle(String corLieblle) {
		this.corLieblle = corLieblle;
	}

	@Column(name = "COR_DTE_SAISI", length = 7)
	public Date getCorDteSaisi() {
		return this.corDteSaisi;
	}

	public void setCorDteSaisi(Date corDteSaisi) {
		this.corDteSaisi = corDteSaisi;
	}

	@Column(name = "COR_OPE_MATRICULE", length = 25)
	public String getCorOpeMatricule() {
		return this.corOpeMatricule;
	}

	public void setCorOpeMatricule(String corOpeMatricule) {
		this.corOpeMatricule = corOpeMatricule;
	}

}
