package com.sndi.model;
// Generated 5 mars 2020 11:43:41 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VbDetOffresSaisiId generated by hbm2java
 */
@Embeddable
public class VbDetOffresSaisi implements java.io.Serializable {

	private BigDecimal dofNum;
	private long dofLaaId;
	private String dofLaaAaoCode;
	private BigDecimal dofOffNum;
	private String dofTyp;
	private BigDecimal dofDelai;
	private BigDecimal dofDelai2;
	private String dofOffRc;
	private String dofOffImpot;
	private String dofOffCnps;
	private String dofCaut;
	private Long dofRangOfr;
	private BigDecimal dofMtCor;
	private long dofMtOfr;
	private String dofRab;
	private BigDecimal dofEstimRab;
	private String dofBanCode;
	private String dofSeuil;
	private Short dofScore;
	private String dofRecevabl;
	private String dofRet;
	private String dofRetBai;
	private String dofRetDmp;
	private BigDecimal dofMtAtt;
	private String dofTot;
	private Date dofDteSaisi;
	private String dofFonCodeAc;
	private String dofOpeMatricule;
	private String dofConfTecP;
	private String dofConfTecC;

	public VbDetOffresSaisi() {
	}

	public VbDetOffresSaisi(BigDecimal dofNum, long dofLaaId, String dofLaaAaoCode, BigDecimal dofOffNum,
			BigDecimal dofDelai) {
		this.dofNum = dofNum;
		this.dofLaaId = dofLaaId;
		this.dofLaaAaoCode = dofLaaAaoCode;
		this.dofOffNum = dofOffNum;
		this.dofDelai = dofDelai;
	}

	public VbDetOffresSaisi(BigDecimal dofNum, long dofLaaId, String dofLaaAaoCode, BigDecimal dofOffNum,
			String dofTyp, BigDecimal dofDelai, BigDecimal dofDelai2, String dofOffRc, String dofOffImpot,
			String dofOffCnps, String dofCaut, Long dofRangOfr, BigDecimal dofMtCor, long dofMtOfr, String dofRab,
			BigDecimal dofEstimRab, String dofBanCode, String dofSeuil, Short dofScore, String dofRecevabl,
			String dofRet, String dofRetBai, String dofRetDmp, BigDecimal dofMtAtt, String dofTot, Date dofDteSaisi,
			String dofFonCodeAc, String dofOpeMatricule, String dofConfTecP, String dofConfTecC) {
		this.dofNum = dofNum;
		this.dofLaaId = dofLaaId;
		this.dofLaaAaoCode = dofLaaAaoCode;
		this.dofOffNum = dofOffNum;
		this.dofTyp = dofTyp;
		this.dofDelai = dofDelai;
		this.dofDelai2 = dofDelai2;
		this.dofOffRc = dofOffRc;
		this.dofOffImpot = dofOffImpot;
		this.dofOffCnps = dofOffCnps;
		this.dofCaut = dofCaut;
		this.dofRangOfr = dofRangOfr;
		this.dofMtCor = dofMtCor;
		this.dofMtOfr = dofMtOfr;
		this.dofRab = dofRab;
		this.dofEstimRab = dofEstimRab;
		this.dofBanCode = dofBanCode;
		this.dofSeuil = dofSeuil;
		this.dofScore = dofScore;
		this.dofRecevabl = dofRecevabl;
		this.dofRet = dofRet;
		this.dofRetBai = dofRetBai;
		this.dofRetDmp = dofRetDmp;
		this.dofMtAtt = dofMtAtt;
		this.dofTot = dofTot;
		this.dofDteSaisi = dofDteSaisi;
		this.dofFonCodeAc = dofFonCodeAc;
		this.dofOpeMatricule = dofOpeMatricule;
		this.dofConfTecP = dofConfTecP;
		this.dofConfTecC = dofConfTecC;
	}

	@Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	@Column(name = "DOF_LAA_ID", nullable = false, precision = 22, scale = 0)
	public long getDofLaaId() {
		return this.dofLaaId;
	}

	public void setDofLaaId(long dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	@Column(name = "DOF_LAA_AAO_CODE", nullable = false, length = 20)
	public String getDofLaaAaoCode() {
		return this.dofLaaAaoCode;
	}

	public void setDofLaaAaoCode(String dofLaaAaoCode) {
		this.dofLaaAaoCode = dofLaaAaoCode;
	}

	@Column(name = "DOF_OFF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofOffNum() {
		return this.dofOffNum;
	}

	public void setDofOffNum(BigDecimal dofOffNum) {
		this.dofOffNum = dofOffNum;
	}

	@Column(name = "DOF_TYP", length = 1)
	public String getDofTyp() {
		return this.dofTyp;
	}

	public void setDofTyp(String dofTyp) {
		this.dofTyp = dofTyp;
	}

	@Column(name = "DOF_DELAI", nullable = false, precision = 20, scale = 0)
	public BigDecimal getDofDelai() {
		return this.dofDelai;
	}

	public void setDofDelai(BigDecimal dofDelai) {
		this.dofDelai = dofDelai;
	}

	@Column(name = "DOF_DELAI2", precision = 20, scale = 0)
	public BigDecimal getDofDelai2() {
		return this.dofDelai2;
	}

	public void setDofDelai2(BigDecimal dofDelai2) {
		this.dofDelai2 = dofDelai2;
	}

	@Column(name = "DOF_OFF_RC", length = 1)
	public String getDofOffRc() {
		return this.dofOffRc;
	}

	public void setDofOffRc(String dofOffRc) {
		this.dofOffRc = dofOffRc;
	}

	@Column(name = "DOF_OFF_IMPOT", length = 1)
	public String getDofOffImpot() {
		return this.dofOffImpot;
	}

	public void setDofOffImpot(String dofOffImpot) {
		this.dofOffImpot = dofOffImpot;
	}

	@Column(name = "DOF_OFF_CNPS", length = 1)
	public String getDofOffCnps() {
		return this.dofOffCnps;
	}

	public void setDofOffCnps(String dofOffCnps) {
		this.dofOffCnps = dofOffCnps;
	}

	@Column(name = "DOF_CAUT", length = 1)
	public String getDofCaut() {
		return this.dofCaut;
	}

	public void setDofCaut(String dofCaut) {
		this.dofCaut = dofCaut;
	}

	@Column(name = "DOF_RANG_OFR", precision = 10, scale = 0)
	public Long getDofRangOfr() {
		return this.dofRangOfr;
	}

	public void setDofRangOfr(Long dofRangOfr) {
		this.dofRangOfr = dofRangOfr;
	}

	@Column(name = "DOF_MT_COR", precision = 20, scale = 0)
	public BigDecimal getDofMtCor() {
		return this.dofMtCor;
	}

	public void setDofMtCor(BigDecimal dofMtCor) {
		this.dofMtCor = dofMtCor;
	}

	@Column(name = "DOF_MT_OFR", precision = 20, scale = 0)
	public long getDofMtOfr() {
		return this.dofMtOfr;
	}

	public void setDofMtOfr(long dofMtOfr) {
		this.dofMtOfr = dofMtOfr;
	}

	@Column(name = "DOF_RAB", length = 5)
	public String getDofRab() {
		return this.dofRab;
	}

	public void setDofRab(String dofRab) {
		this.dofRab = dofRab;
	}

	@Column(name = "DOF_ESTIM_RAB", precision = 20, scale = 0)
	public BigDecimal getDofEstimRab() {
		return this.dofEstimRab;
	}

	public void setDofEstimRab(BigDecimal dofEstimRab) {
		this.dofEstimRab = dofEstimRab;
	}

	@Column(name = "DOF_BAN_CODE", length = 10)
	public String getDofBanCode() {
		return this.dofBanCode;
	}

	public void setDofBanCode(String dofBanCode) {
		this.dofBanCode = dofBanCode;
	}

	@Column(name = "DOF_SEUIL", length = 1)
	public String getDofSeuil() {
		return this.dofSeuil;
	}

	public void setDofSeuil(String dofSeuil) {
		this.dofSeuil = dofSeuil;
	}

	@Column(name = "DOF_SCORE", precision = 3, scale = 0)
	public Short getDofScore() {
		return this.dofScore;
	}

	public void setDofScore(Short dofScore) {
		this.dofScore = dofScore;
	}

	@Column(name = "DOF_RECEVABL", length = 1)
	public String getDofRecevabl() {
		return this.dofRecevabl;
	}

	public void setDofRecevabl(String dofRecevabl) {
		this.dofRecevabl = dofRecevabl;
	}

	@Column(name = "DOF_RET", length = 1)
	public String getDofRet() {
		return this.dofRet;
	}

	public void setDofRet(String dofRet) {
		this.dofRet = dofRet;
	}

	@Column(name = "DOF_RET_BAI", length = 1)
	public String getDofRetBai() {
		return this.dofRetBai;
	}

	public void setDofRetBai(String dofRetBai) {
		this.dofRetBai = dofRetBai;
	}

	@Column(name = "DOF_RET_DMP", length = 1)
	public String getDofRetDmp() {
		return this.dofRetDmp;
	}

	public void setDofRetDmp(String dofRetDmp) {
		this.dofRetDmp = dofRetDmp;
	}

	@Column(name = "DOF_MT_ATT", precision = 20, scale = 0)
	public BigDecimal getDofMtAtt() {
		return this.dofMtAtt;
	}

	public void setDofMtAtt(BigDecimal dofMtAtt) {
		this.dofMtAtt = dofMtAtt;
	}

	@Column(name = "DOF_TOT", length = 2)
	public String getDofTot() {
		return this.dofTot;
	}

	public void setDofTot(String dofTot) {
		this.dofTot = dofTot;
	}

	@Column(name = "DOF_DTE_SAISI", length = 7)
	public Date getDofDteSaisi() {
		return this.dofDteSaisi;
	}

	public void setDofDteSaisi(Date dofDteSaisi) {
		this.dofDteSaisi = dofDteSaisi;
	}

	@Column(name = "DOF_FON_CODE_AC", length = 25)
	public String getDofFonCodeAc() {
		return this.dofFonCodeAc;
	}

	public void setDofFonCodeAc(String dofFonCodeAc) {
		this.dofFonCodeAc = dofFonCodeAc;
	}

	@Column(name = "DOF_OPE_MATRICULE", length = 25)
	public String getDofOpeMatricule() {
		return this.dofOpeMatricule;
	}

	public void setDofOpeMatricule(String dofOpeMatricule) {
		this.dofOpeMatricule = dofOpeMatricule;
	}

	@Column(name = "DOF_CONF_TEC_P", length = 1)
	public String getDofConfTecP() {
		return this.dofConfTecP;
	}

	public void setDofConfTecP(String dofConfTecP) {
		this.dofConfTecP = dofConfTecP;
	}

	@Column(name = "DOF_CONF_TEC_C", length = 1)
	public String getDofConfTecC() {
		return this.dofConfTecC;
	}

	public void setDofConfTecC(String dofConfTecC) {
		this.dofConfTecC = dofConfTecC;
	}
}
