package com.sndi.model;
// Generated 13 févr. 2020 11:47:53 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbDetailCorrectionId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_DETAIL_CORRECTION")
public class VbDetailCorrection implements java.io.Serializable {

	private BigDecimal dcoNum;
	private String dcoTitre;
	private String dcoLibelle;
	private Date dcoDteSaisi;
	private BigDecimal dcoPidCode;
	private String dcoDacCode;
	private String dcoFonCodSaisi;
	private String dcoOpeMatricule;
	private String dcoObservation;
	private BigDecimal dcoCorNum;

	public VbDetailCorrection() {
	}

	public VbDetailCorrection(BigDecimal dcoNum) {
		this.dcoNum = dcoNum;
	}

	public VbDetailCorrection(BigDecimal dcoNum, String dcoTitre, String dcoLibelle, Date dcoDteSaisi,
			BigDecimal dcoPidCode, String dcoDacCode, String dcoFonCodSaisi, String dcoOpeMatricule,
			String dcoObservation, BigDecimal dcoCorNum) {
		this.dcoNum = dcoNum;
		this.dcoTitre = dcoTitre;
		this.dcoLibelle = dcoLibelle;
		this.dcoDteSaisi = dcoDteSaisi;
		this.dcoPidCode = dcoPidCode;
		this.dcoDacCode = dcoDacCode;
		this.dcoFonCodSaisi = dcoFonCodSaisi;
		this.dcoOpeMatricule = dcoOpeMatricule;
		this.dcoObservation = dcoObservation;
		this.dcoCorNum = dcoCorNum;
	}

	
	@Id
	@Column(name = "DCO_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDcoNum() {
		return this.dcoNum;
	}

	public void setDcoNum(BigDecimal dcoNum) {
		this.dcoNum = dcoNum;
	}

	@Column(name = "DCO_TITRE", length = 200)
	public String getDcoTitre() {
		return this.dcoTitre;
	}

	public void setDcoTitre(String dcoTitre) {
		this.dcoTitre = dcoTitre;
	}

	@Column(name = "DCO_LIBELLE", length = 1000)
	public String getDcoLibelle() {
		return this.dcoLibelle;
	}

	public void setDcoLibelle(String dcoLibelle) {
		this.dcoLibelle = dcoLibelle;
	}

	@Column(name = "DCO_DTE_SAISI", length = 7)
	public Date getDcoDteSaisi() {
		return this.dcoDteSaisi;
	}

	public void setDcoDteSaisi(Date dcoDteSaisi) {
		this.dcoDteSaisi = dcoDteSaisi;
	}

	@Column(name = "DCO_PID_CODE", precision = 22, scale = 0)
	public BigDecimal getDcoPidCode() {
		return this.dcoPidCode;
	}

	public void setDcoPidCode(BigDecimal dcoPidCode) {
		this.dcoPidCode = dcoPidCode;
	}

	@Column(name = "DCO_DAC_CODE", length = 20)
	public String getDcoDacCode() {
		return this.dcoDacCode;
	}

	public void setDcoDacCode(String dcoDacCode) {
		this.dcoDacCode = dcoDacCode;
	}

	@Column(name = "DCO_FON_COD_SAISI", length = 12)
	public String getDcoFonCodSaisi() {
		return this.dcoFonCodSaisi;
	}

	public void setDcoFonCodSaisi(String dcoFonCodSaisi) {
		this.dcoFonCodSaisi = dcoFonCodSaisi;
	}

	@Column(name = "DCO_OPE_MATRICULE", length = 25)
	public String getDcoOpeMatricule() {
		return this.dcoOpeMatricule;
	}

	public void setDcoOpeMatricule(String dcoOpeMatricule) {
		this.dcoOpeMatricule = dcoOpeMatricule;
	}

	@Column(name = "DCO_OBSERVATION", length = 1000)
	public String getDcoObservation() {
		return this.dcoObservation;
	}

	public void setDcoObservation(String dcoObservation) {
		this.dcoObservation = dcoObservation;
	}

	@Column(name = "DCO_COR_NUM", precision = 22, scale = 0)
	public BigDecimal getDcoCorNum() {
		return this.dcoCorNum;
	}

	public void setDcoCorNum(BigDecimal dcoCorNum) {
		this.dcoCorNum = dcoCorNum;
	}


}
