package com.sndi.model;
// Generated 15 nov. 2019 18:38:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VBesoin generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_BESOIN")
public class VBesoin implements java.io.Serializable {

	private long besId;
	private String besLibelle;
	private long besProId;
	private String besStatut;
	private String regLibelleLong;
	private String regLibelleCourt;

	public VBesoin() {
	}

	public VBesoin(long besId, long besProId) {
		this.besId = besId;
		this.besProId = besProId;
	}

	public VBesoin(long besId, String besLibelle, long besProId, String besStatut, String regLibelleLong,
			String regLibelleCourt) {
		this.besId = besId;
		this.besLibelle = besLibelle;
		this.besProId = besProId;
		this.besStatut = besStatut;
		this.regLibelleLong = regLibelleLong;
		this.regLibelleCourt = regLibelleCourt;
	}

	@Id
	@Column(name = "BES_ID", nullable = false, precision = 10, scale = 0)
	public long getBesId() {
		return this.besId;
	}

	public void setBesId(long besId) {
		this.besId = besId;
	}

	@Column(name = "BES_LIBELLE", length = 1000)
	public String getBesLibelle() {
		return this.besLibelle;
	}

	public void setBesLibelle(String besLibelle) {
		this.besLibelle = besLibelle;
	}

	@Column(name = "BES_PRO_ID", nullable = false, precision = 5, scale = 0)
	public long getBesProId() {
		return this.besProId;
	}

	public void setBesProId(long besProId) {
		this.besProId = besProId;
	}

	@Column(name = "BES_STATUT", length = 1)
	public String getBesStatut() {
		return this.besStatut;
	}

	public void setBesStatut(String besStatut) {
		this.besStatut = besStatut;
	}

	@Column(name = "REG_LIBELLE_LONG", length = 1000)
	public String getRegLibelleLong() {
		return this.regLibelleLong;
	}

	public void setRegLibelleLong(String regLibelleLong) {
		this.regLibelleLong = regLibelleLong;
	}

	@Column(name = "REG_LIBELLE_COURT", length = 500)
	public String getRegLibelleCourt() {
		return this.regLibelleCourt;
	}

	public void setRegLibelleCourt(String regLibelleCourt) {
		this.regLibelleCourt = regLibelleCourt;
	}

}
