package com.sndi.model;
// Generated 20 nov. 2020 11:03:55 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbObservations generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_OBSERVATIONS")
public class VbObservations implements java.io.Serializable {

	private BigDecimal obsNum;
	private long obsMtfNum;
	private String obsLibelle;
	private BigDecimal obsLaaNum;
	private String obsDacCode;
	private String obsAaoCode;
	private Date obsDate;
	private String obsOpeMatricule;
	private String obsSouNcc;
	private String obsType;

	public VbObservations() {
	}

	public VbObservations(BigDecimal obsNum) {
		this.obsNum = obsNum;
	}

	public VbObservations(BigDecimal obsNum, long obsMtfNum, String obsLibelle, BigDecimal obsLaaNum,
			String obsDacCode, String obsAaoCode, Date obsDate, String obsOpeMatricule, String obsSouNcc,
			String obsType) {
		this.obsNum = obsNum;
		this.obsMtfNum = obsMtfNum;
		this.obsLibelle = obsLibelle;
		this.obsLaaNum = obsLaaNum;
		this.obsDacCode = obsDacCode;
		this.obsAaoCode = obsAaoCode;
		this.obsDate = obsDate;
		this.obsOpeMatricule = obsOpeMatricule;
		this.obsSouNcc = obsSouNcc;
		this.obsType = obsType;
	}
	
	@Id
	@SequenceGenerator(name = "SEQ_OBS_NUM_Sequence", sequenceName = "SEQ_OBS_NUM", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_OBS_NUM_Sequence")
	@Column(name = "OBS_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getObsNum() {
		return this.obsNum;
	}

	public void setObsNum(BigDecimal obsNum) {
		this.obsNum = obsNum;
	}

	@Column(name = "OBS_MTF_NUM", precision = 22, scale = 0)
	public long getObsMtfNum() {
		return this.obsMtfNum;
	}

	public void setObsMtfNum(long obsMtfNum) {
		this.obsMtfNum = obsMtfNum;
	}

	@Column(name = "OBS_LIBELLE", length = 2000)
	public String getObsLibelle() {
		return this.obsLibelle;
	}

	public void setObsLibelle(String obsLibelle) {
		this.obsLibelle = obsLibelle;
	}

	@Column(name = "OBS_LAA_NUM", precision = 22, scale = 0)
	public BigDecimal getObsLaaNum() {
		return this.obsLaaNum;
	}

	public void setObsLaaNum(BigDecimal obsLaaNum) {
		this.obsLaaNum = obsLaaNum;
	}

	@Column(name = "OBS_DAC_CODE", length = 25)
	public String getObsDacCode() {
		return this.obsDacCode;
	}

	public void setObsDacCode(String obsDacCode) {
		this.obsDacCode = obsDacCode;
	}

	@Column(name = "OBS_AAO_CODE", length = 25)
	public String getObsAaoCode() {
		return this.obsAaoCode;
	}

	public void setObsAaoCode(String obsAaoCode) {
		this.obsAaoCode = obsAaoCode;
	}

	@Column(name = "OBS_DATE", length = 7)
	public Date getObsDate() {
		return this.obsDate;
	}

	public void setObsDate(Date obsDate) {
		this.obsDate = obsDate;
	}

	@Column(name = "OBS_OPE_MATRICULE", length = 25)
	public String getObsOpeMatricule() {
		return this.obsOpeMatricule;
	}

	public void setObsOpeMatricule(String obsOpeMatricule) {
		this.obsOpeMatricule = obsOpeMatricule;
	}

	@Column(name = "OBS_SOU_NCC", length = 20)
	public String getObsSouNcc() {
		return this.obsSouNcc;
	}

	public void setObsSouNcc(String obsSouNcc) {
		this.obsSouNcc = obsSouNcc;
	}

	@Column(name = "OBS_TYPE", length = 10)
	public String getObsType() {
		return this.obsType;
	}

	public void setObsType(String obsType) {
		this.obsType = obsType;
	}
}
