package com.sndi.model;
// Generated 18 juin 2020 15:43:04 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbPaysReference generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_PAYS_REFERENCE")
public class VbPaysReference implements java.io.Serializable {

	private String repCode;
	private String repLibelle;
	private String repLibelleCourt;
	private String repStatut;
	private String repIndicatif;

	public VbPaysReference() {
	}

	public VbPaysReference(String repCode) {
		this.repCode = repCode;
	}

	public VbPaysReference(String repCode, String repLibelle, String repLibelleCourt, String repStatut,
			String repIndicatif) {
		this.repCode = repCode;
		this.repLibelle = repLibelle;
		this.repLibelleCourt = repLibelleCourt;
		this.repStatut = repStatut;
		this.repIndicatif = repIndicatif;
	}

	@Id
	@Column(name = "REP_CODE", nullable = false, length = 10)
	public String getRepCode() {
		return this.repCode;
	}

	public void setRepCode(String repCode) {
		this.repCode = repCode;
	}

	@Column(name = "REP_LIBELLE", length = 200)
	public String getRepLibelle() {
		return this.repLibelle;
	}

	public void setRepLibelle(String repLibelle) {
		this.repLibelle = repLibelle;
	}

	@Column(name = "REP_LIBELLE_COURT", length = 100)
	public String getRepLibelleCourt() {
		return this.repLibelleCourt;
	}

	public void setRepLibelleCourt(String repLibelleCourt) {
		this.repLibelleCourt = repLibelleCourt;
	}

	@Column(name = "REP_STATUT", length = 1)
	public String getRepStatut() {
		return this.repStatut;
	}

	public void setRepStatut(String repStatut) {
		this.repStatut = repStatut;
	}

	@Column(name = "REP_INDICATIF", length = 50)
	public String getRepIndicatif() {
		return this.repIndicatif;
	}

	public void setRepIndicatif(String repIndicatif) {
		this.repIndicatif = repIndicatif;
	}

}
