package com.sndi.model;
// Generated 9 sept. 2020 18:16:49 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;
/**
 * VbTempParamTabBord generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_TEMP_PARAM_TAB_BORD")
public class VbTempParamTabBord implements java.io.Serializable {

	private BigDecimal tempNum;
	private String tempType;
	private String tabTypOpe;
	private String tabOpeStaCode;
	private String tabFonCodeAc;
	private String tabFonCodePf;
	private Date tabDateSaisi;
	private String tabOpeMatricule;
	private String tabCodeOperation;
	private String tabTypeProc;
	private String tabBaiBailleur;
	private String tabCh1;
	private String tabCh2;

	public VbTempParamTabBord() {
	}

	public VbTempParamTabBord(BigDecimal tempNum) {
		this.tempNum = tempNum;
	}

	public VbTempParamTabBord(BigDecimal tempNum, String tempType, String tabTypOpe, String tabOpeStaCode,
			String tabFonCodeAc, String tabFonCodePf, Date tabDateSaisi, String tabOpeMatricule,
			String tabCodeOperation, String tabTypeProc, String tabBaiBailleur, String tabCh1, String tabCh2) {
		this.tempNum = tempNum;
		this.tempType = tempType;
		this.tabTypOpe = tabTypOpe;
		this.tabOpeStaCode = tabOpeStaCode;
		this.tabFonCodeAc = tabFonCodeAc;
		this.tabFonCodePf = tabFonCodePf;
		this.tabDateSaisi = tabDateSaisi;
		this.tabOpeMatricule = tabOpeMatricule;
		this.tabCodeOperation = tabCodeOperation;
		this.tabTypeProc = tabTypeProc;
		this.tabBaiBailleur = tabBaiBailleur;
		this.tabCh1 = tabCh1;
		this.tabCh2 = tabCh2;
	}

	@Id
	@SequenceGenerator(name = "SEQ_VB_TAB_BORD_Sequence", sequenceName = "SEQ_VB_TAB_BORD", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_VB_TAB_BORD_Sequence")
	@Column(name = "TEMP_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTempNum() {
		return this.tempNum;
	}

	public void setTempNum(BigDecimal tempNum) {
		this.tempNum = tempNum;
	}

	@Column(name = "TEMP_TYPE", length = 500)
	public String getTempType() {
		return this.tempType;
	}

	public void setTempType(String tempType) {
		this.tempType = tempType;
	}

	@Column(name = "TAB_TYP_OPE", length = 500)
	public String getTabTypOpe() {
		return this.tabTypOpe;
	}

	public void setTabTypOpe(String tabTypOpe) {
		this.tabTypOpe = tabTypOpe;
	}

	@Column(name = "TAB_OPE_STA_CODE", length = 500)
	public String getTabOpeStaCode() {
		return this.tabOpeStaCode;
	}

	public void setTabOpeStaCode(String tabOpeStaCode) {
		this.tabOpeStaCode = tabOpeStaCode;
	}

	@Column(name = "TAB_FON_CODE_AC", length = 500)
	public String getTabFonCodeAc() {
		return this.tabFonCodeAc;
	}

	public void setTabFonCodeAc(String tabFonCodeAc) {
		this.tabFonCodeAc = tabFonCodeAc;
	}

	@Column(name = "TAB_FON_CODE_PF", length = 500)
	public String getTabFonCodePf() {
		return this.tabFonCodePf;
	}

	public void setTabFonCodePf(String tabFonCodePf) {
		this.tabFonCodePf = tabFonCodePf;
	}

	@Column(name = "TAB_DATE_SAISI", length = 7)
	public Date getTabDateSaisi() {
		return this.tabDateSaisi;
	}

	public void setTabDateSaisi(Date tabDateSaisi) {
		this.tabDateSaisi = tabDateSaisi;
	}

	@Column(name = "TAB_OPE_MATRICULE", length = 500)
	public String getTabOpeMatricule() {
		return this.tabOpeMatricule;
	}

	public void setTabOpeMatricule(String tabOpeMatricule) {
		this.tabOpeMatricule = tabOpeMatricule;
	}

	@Column(name = "TAB_CODE_OPERATION", length = 500)
	public String getTabCodeOperation() {
		return this.tabCodeOperation;
	}

	public void setTabCodeOperation(String tabCodeOperation) {
		this.tabCodeOperation = tabCodeOperation;
	}

	@Column(name = "TAB_TYPE_PROC", length = 500)
	public String getTabTypeProc() {
		return this.tabTypeProc;
	}

	public void setTabTypeProc(String tabTypeProc) {
		this.tabTypeProc = tabTypeProc;
	}

	@Column(name = "TAB_BAI_BAILLEUR", length = 500)
	public String getTabBaiBailleur() {
		return this.tabBaiBailleur;
	}

	public void setTabBaiBailleur(String tabBaiBailleur) {
		this.tabBaiBailleur = tabBaiBailleur;
	}

	@Column(name = "TAB_CH1", length = 500)
	public String getTabCh1() {
		return this.tabCh1;
	}

	public void setTabCh1(String tabCh1) {
		this.tabCh1 = tabCh1;
	}

	@Column(name = "TAB_CH2", length = 500)
	public String getTabCh2() {
		return this.tabCh2;
	}

	public void setTabCh2(String tabCh2) {
		this.tabCh2 = tabCh2;
	}

}
