package com.sndi.model;
// Generated 16 mars 2021 13:17:59 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbTempOperateurId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_TEMP_OPERATEUR")
public class VbTempOperateur implements java.io.Serializable {

	private BigDecimal tempNum2;
	private String tempType;
	private String tempOpeMatricule;
	private String tempChamp01;
	private String tempChamp02;
	private String tempChamp03;

	public VbTempOperateur() {
	}

	public VbTempOperateur(BigDecimal tempNum2) {
		this.tempNum2 = tempNum2;
	}

	public VbTempOperateur(BigDecimal tempNum2, String tempType, String tempOpeMatricule, String tempChamp01,
			String tempChamp02, String tempChamp03) {
		this.tempNum2 = tempNum2;
		this.tempType = tempType;
		this.tempOpeMatricule = tempOpeMatricule;
		this.tempChamp01 = tempChamp01;
		this.tempChamp02 = tempChamp02;
		this.tempChamp03 = tempChamp03;
	}
	
	@Id
	@SequenceGenerator(name = "SEQ_TEM_PAR2_NUM_Sequence", sequenceName = "SEQ_TEM_PAR2_NUM", allocationSize=1)
	@Column(name = "TEMP_NUM2", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTempNum2() {
		return this.tempNum2;
	}

	public void setTempNum2(BigDecimal tempNum2) {
		this.tempNum2 = tempNum2;
	}

	@Column(name = "TEMP_TYPE", length = 500)
	public String getTempType() {
		return this.tempType;
	}

	public void setTempType(String tempType) {
		this.tempType = tempType;
	}

	@Column(name = "TEMP_OPE_MATRICULE", length = 500)
	public String getTempOpeMatricule() {
		return this.tempOpeMatricule;
	}

	public void setTempOpeMatricule(String tempOpeMatricule) {
		this.tempOpeMatricule = tempOpeMatricule;
	}

	@Column(name = "TEMP_CHAMP_01", length = 500)
	public String getTempChamp01() {
		return this.tempChamp01;
	}

	public void setTempChamp01(String tempChamp01) {
		this.tempChamp01 = tempChamp01;
	}

	@Column(name = "TEMP_CHAMP_02", length = 500)
	public String getTempChamp02() {
		return this.tempChamp02;
	}

	public void setTempChamp02(String tempChamp02) {
		this.tempChamp02 = tempChamp02;
	}

	@Column(name = "TEMP_CHAMP_03", length = 500)
	public String getTempChamp03() {
		return this.tempChamp03;
	}

	public void setTempChamp03(String tempChamp03) {
		this.tempChamp03 = tempChamp03;
	}

}
