package com.sndi.model;
// Generated 22 juin 2021 15:26:36 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbTempParametreDateplanId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_TEMP_PARAMETRE_DATEPLAN")
public class VbTempParametreDateplan implements java.io.Serializable {

	private BigDecimal dplTempNum;
	private String dplTempType;
	private String dplOpeMatricule;
	private Date dplDteValeur;
	private BigDecimal dplNum;
	private String dplPadCode;
	private String dplObser;

	public VbTempParametreDateplan() {
	}

	public VbTempParametreDateplan(BigDecimal dplTempNum) {
		this.dplTempNum = dplTempNum;
	}

	public VbTempParametreDateplan(BigDecimal dplTempNum, String dplTempType, String dplOpeMatricule,
			Date dplDteValeur, BigDecimal dplNum, String dplPadCode, String dplObser) {
		this.dplTempNum = dplTempNum;
		this.dplTempType = dplTempType;
		this.dplOpeMatricule = dplOpeMatricule;
		this.dplDteValeur = dplDteValeur;
		this.dplNum = dplNum;
		this.dplPadCode = dplPadCode;
		this.dplObser = dplObser;
	}

	@Id
	@SequenceGenerator(name = "SEQ_TEMP_PARAMETRE_Sequence", sequenceName = "SEQ_TEMP_PARAMETRE", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_TEMP_PARAMETRE_Sequence")
	@Column(name = "DPL_TEMP_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDplTempNum() {
		return this.dplTempNum;
	}

	public void setDplTempNum(BigDecimal dplTempNum) {
		this.dplTempNum = dplTempNum;
	}

	@Column(name = "DPL_TEMP_TYPE", length = 500)
	public String getDplTempType() {
		return this.dplTempType;
	}

	public void setDplTempType(String dplTempType) {
		this.dplTempType = dplTempType;
	}

	@Column(name = "DPL_OPE_MATRICULE", length = 500)
	public String getDplOpeMatricule() {
		return this.dplOpeMatricule;
	}

	public void setDplOpeMatricule(String dplOpeMatricule) {
		this.dplOpeMatricule = dplOpeMatricule;
	}

	@Column(name = "DPL_DTE_VALEUR", length = 7)
	public Date getDplDteValeur() {
		return this.dplDteValeur;
	}

	public void setDplDteValeur(Date dplDteValeur) {
		this.dplDteValeur = dplDteValeur;
	}

	@Column(name = "DPL_NUM", precision = 22, scale = 0)
	public BigDecimal getDplNum() {
		return this.dplNum;
	}

	public void setDplNum(BigDecimal dplNum) {
		this.dplNum = dplNum;
	}

	@Column(name = "DPL_PAD_CODE", length = 500)
	public String getDplPadCode() {
		return this.dplPadCode;
	}

	public void setDplPadCode(String dplPadCode) {
		this.dplPadCode = dplPadCode;
	}

	@Column(name = "DPL_OBSER", length = 500)
	public String getDplObser() {
		return this.dplObser;
	}

	public void setDplObser(String dplObser) {
		this.dplObser = dplObser;
	}

}
