package com.sndi.model;
// Generated 15 août 2020 19:16:51 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbTempParamEnteteCriId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VB_TEMP_PARAM_ENTETE_CRI")
public class VbTempParamEnteteCri implements java.io.Serializable {

	private String dcadDacCode;
	private String dcadDanCode;
	private String dcadDanCraCode;
	private String dcadLaaId;
	private Date criDteSaisi;
	private String criLibelle;
	private String criOpeMatricule;
	private String criDcadStatut;
	private String dcadNumDcad;
	private String dcadCraAuCode;
	private String tempType;

	public VbTempParamEnteteCri() {
	}

	public VbTempParamEnteteCri(String dcadDacCode, String dcadDanCode, String dcadDanCraCode, String dcadLaaId,
			Date criDteSaisi, String criLibelle, String criOpeMatricule, String criDcadStatut, String dcadNumDcad,
			String dcadCraAuCode, String tempType) {
		this.dcadDacCode = dcadDacCode;
		this.dcadDanCode = dcadDanCode;
		this.dcadDanCraCode = dcadDanCraCode;
		this.dcadLaaId = dcadLaaId;
		this.criDteSaisi = criDteSaisi;
		this.criLibelle = criLibelle;
		this.criOpeMatricule = criOpeMatricule;
		this.criDcadStatut = criDcadStatut;
		this.dcadNumDcad = dcadNumDcad;
		this.dcadCraAuCode = dcadCraAuCode;
		this.tempType = tempType;
	}

	@Column(name = "DCAD_DAC_CODE", length = 500)
	public String getDcadDacCode() {
		return this.dcadDacCode;
	}

	public void setDcadDacCode(String dcadDacCode) {
		this.dcadDacCode = dcadDacCode;
	}

	@Column(name = "DCAD_DAN_CODE", length = 500)
	public String getDcadDanCode() {
		return this.dcadDanCode;
	}

	public void setDcadDanCode(String dcadDanCode) {
		this.dcadDanCode = dcadDanCode;
	}

	@Id
	@Column(name = "DCAD_DAN_CRA_CODE", length = 500)
	public String getDcadDanCraCode() {
		return this.dcadDanCraCode;
	}

	public void setDcadDanCraCode(String dcadDanCraCode) {
		this.dcadDanCraCode = dcadDanCraCode;
	}

	@Column(name = "DCAD_LAA_ID", length = 500)
	public String getDcadLaaId() {
		return this.dcadLaaId;
	}

	public void setDcadLaaId(String dcadLaaId) {
		this.dcadLaaId = dcadLaaId;
	}

	@Column(name = "CRI_DTE_SAISI", length = 7)
	public Date getCriDteSaisi() {
		return this.criDteSaisi;
	}

	public void setCriDteSaisi(Date criDteSaisi) {
		this.criDteSaisi = criDteSaisi;
	}

	@Column(name = "CRI_LIBELLE", length = 500)
	public String getCriLibelle() {
		return this.criLibelle;
	}

	public void setCriLibelle(String criLibelle) {
		this.criLibelle = criLibelle;
	}

	@Column(name = "CRI_OPE_MATRICULE", length = 500)
	public String getCriOpeMatricule() {
		return this.criOpeMatricule;
	}

	public void setCriOpeMatricule(String criOpeMatricule) {
		this.criOpeMatricule = criOpeMatricule;
	}

	@Column(name = "CRI_DCAD_STATUT", length = 500)
	public String getCriDcadStatut() {
		return this.criDcadStatut;
	}

	public void setCriDcadStatut(String criDcadStatut) {
		this.criDcadStatut = criDcadStatut;
	}

	@Column(name = "DCAD_NUM_DCAD", length = 500)
	public String getDcadNumDcad() {
		return this.dcadNumDcad;
	}

	public void setDcadNumDcad(String dcadNumDcad) {
		this.dcadNumDcad = dcadNumDcad;
	}

	@Column(name = "DCAD_CRA_AU_CODE", length = 500)
	public String getDcadCraAuCode() {
		return this.dcadCraAuCode;
	}

	public void setDcadCraAuCode(String dcadCraAuCode) {
		this.dcadCraAuCode = dcadCraAuCode;
	}

	@Column(name = "TEMP_TYPE", length = 500)
	public String getTempType() {
		return this.tempType;
	}

	public void setTempType(String tempType) {
		this.tempType = tempType;
	}

}
