package com.sndi.model;
// Generated 16 nov. 2020 16:18:15 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VbxDocCommissionId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VBX_DOC_COMMISSION", schema = "EMAP")
public class VbxDocCommission implements java.io.Serializable {

	private BigDecimal RId;
	private String dacCode;
	private String comTctLibelle;
	private String comTctTitre;

	public VbxDocCommission() {
	}

	public VbxDocCommission(String dacCode) {
		this.dacCode = dacCode;
	}

	public VbxDocCommission(BigDecimal RId, String dacCode, String comTctLibelle, String comTctTitre) {
		this.RId = RId;
		this.dacCode = dacCode;
		this.comTctLibelle = comTctLibelle;
		this.comTctTitre = comTctTitre;
	}
	
	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "DAC_CODE", nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "COM_TCT_LIBELLE", length = 500)
	public String getComTctLibelle() {
		return this.comTctLibelle;
	}

	public void setComTctLibelle(String comTctLibelle) {
		this.comTctLibelle = comTctLibelle;
	}

	@Column(name = "COM_TCT_TITRE", length = 200)
	public String getComTctTitre() {
		return this.comTctTitre;
	}

	public void setComTctTitre(String comTctTitre) {
		this.comTctTitre = comTctTitre;
	}
}
