package com.sndi.model;
// Generated 17 avr. 2021 15:14:43 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VChargeEtudeDacId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_CHARGE_ETUDE_DAC")
public class VChargeEtudeDac implements java.io.Serializable {

	private BigDecimal id;
	private String dafDacCode;
	private String dafDacObjet;
	private String dafDcsMbmRespo;
	private String dafOpeMatricule;
	private String opeNom;
	private String dafStaCode;
	private String dafStatutRetour;

	public VChargeEtudeDac() {
	}

	public VChargeEtudeDac(BigDecimal id, String dafDacCode, String dafDacObjet, String dafDcsMbmRespo,
			String dafOpeMatricule, String opeNom, String dafStaCode, String dafStatutRetour) {
		this.id = id;
		this.dafDacCode = dafDacCode;
		this.dafDacObjet = dafDacObjet;
		this.dafDcsMbmRespo = dafDcsMbmRespo;
		this.dafOpeMatricule = dafOpeMatricule;
		this.opeNom = opeNom;
		this.dafStaCode = dafStaCode;
		this.dafStatutRetour = dafStatutRetour;
	}

	@Id
	@Column(name = "ID", precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "DAF_DAC_CODE", length = 20)
	public String getDafDacCode() {
		return this.dafDacCode;
	}

	public void setDafDacCode(String dafDacCode) {
		this.dafDacCode = dafDacCode;
	}

	@Column(name = "DAF_DAC_OBJET", length = 2000)
	public String getDafDacObjet() {
		return this.dafDacObjet;
	}

	public void setDafDacObjet(String dafDacObjet) {
		this.dafDacObjet = dafDacObjet;
	}

	@Column(name = "DAF_DCS_MBM_RESPO", length = 1)
	public String getDafDcsMbmRespo() {
		return this.dafDcsMbmRespo;
	}

	public void setDafDcsMbmRespo(String dafDcsMbmRespo) {
		this.dafDcsMbmRespo = dafDcsMbmRespo;
	}

	@Column(name = "DAF_OPE_MATRICULE", length = 25)
	public String getDafOpeMatricule() {
		return this.dafOpeMatricule;
	}

	public void setDafOpeMatricule(String dafOpeMatricule) {
		this.dafOpeMatricule = dafOpeMatricule;
	}

	@Column(name = "OPE_NOM")
	public String getOpeNom() {
		return this.opeNom;
	}

	public void setOpeNom(String opeNom) {
		this.opeNom = opeNom;
	}

	@Column(name = "DAF_STA_CODE", length = 3)
	public String getDafStaCode() {
		return this.dafStaCode;
	}

	public void setDafStaCode(String dafStaCode) {
		this.dafStaCode = dafStaCode;
	}

	@Column(name = "DAF_STATUT_RETOUR", length = 1)
	public String getDafStatutRetour() {
		return this.dafStatutRetour;
	}

	public void setDafStatutRetour(String dafStatutRetour) {
		this.dafStatutRetour = dafStatutRetour;
	}

}
