package com.sndi.model;
// Generated 25 sept. 2020 16:38:40 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VCritereAnalyseDacOuv generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_CRITERE_ANALYSE_DAC_OUV")
public class VCritereAnalyseDacOuv implements java.io.Serializable {

	private BigDecimal RId;
	private String craCode;
	private String craLibelle;
	private String codparent;
	private String analyseStatut;
	private String codep;
	private String codepx;
	private String craTymCodex;
	private String craTypProc;
	private String craTypDac;
	private String craBailleurx;
	private String dcadDacCode;
	private String statutCre;
	private String aaoRegQual;
	private BigDecimal valRegQual;
	private BigDecimal dcadNum;
	private String dcadCommentaire;
	private BigDecimal dcadLaaId;
	private BigDecimal laaNum;
	private String laaObjet;
	private String laaLbgImputation;
	private String laaAaoCode;
	private BigDecimal dcadNumDcad;
	private String dcadCraAuCode;
	private String dcadPetitCra;
	private String dcadPresence;
	private String anfValeurConf;
	private String anfTypeActeur;
	private BigDecimal anfValeurScore;

	public VCritereAnalyseDacOuv() {
	}

	public VCritereAnalyseDacOuv(String codep, BigDecimal dcadNum, BigDecimal laaNum, String laaObjet) {
		this.codep = codep;
		this.dcadNum = dcadNum;
		this.laaNum = laaNum;
		this.laaObjet = laaObjet;
	}

	public VCritereAnalyseDacOuv(BigDecimal RId, String craCode, String craLibelle, String codparent,
			String analyseStatut, String codep, String codepx, String craTymCodex, String craTypProc, String craTypDac,
			String craBailleurx, String dcadDacCode, String statutCre, String aaoRegQual, BigDecimal valRegQual,
			BigDecimal dcadNum, String dcadCommentaire, BigDecimal dcadLaaId, BigDecimal laaNum, String laaObjet,
			String laaLbgImputation, String laaAaoCode, BigDecimal dcadNumDcad, String dcadCraAuCode,
			String dcadPetitCra, String dcadPresence,String anfValeurConf, String anfTypeActeur,
			BigDecimal anfValeurScore) {
		this.RId = RId;
		this.craCode = craCode;
		this.craLibelle = craLibelle;
		this.codparent = codparent;
		this.analyseStatut = analyseStatut;
		this.codep = codep;
		this.codepx = codepx;
		this.craTymCodex = craTymCodex;
		this.craTypProc = craTypProc;
		this.craTypDac = craTypDac;
		this.craBailleurx = craBailleurx;
		this.dcadDacCode = dcadDacCode;
		this.statutCre = statutCre;
		this.aaoRegQual = aaoRegQual;
		this.valRegQual = valRegQual;
		this.dcadNum = dcadNum;
		this.dcadCommentaire = dcadCommentaire;
		this.dcadLaaId = dcadLaaId;
		this.laaNum = laaNum;
		this.laaObjet = laaObjet;
		this.laaLbgImputation = laaLbgImputation;
		this.laaAaoCode = laaAaoCode;
		this.dcadNumDcad = dcadNumDcad;
		this.dcadCraAuCode = dcadCraAuCode;
		this.dcadPetitCra = dcadPetitCra;
		this.dcadPresence = dcadPresence;
		this.anfValeurConf = anfValeurConf;
		this.anfTypeActeur = anfTypeActeur;
		this.anfValeurScore = anfValeurScore;
	}

	
	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "CRA_CODE", length = 50)
	public String getCraCode() {
		return this.craCode;
	}

	public void setCraCode(String craCode) {
		this.craCode = craCode;
	}

	@Column(name = "CRA_LIBELLE", length = 4000)
	public String getCraLibelle() {
		return this.craLibelle;
	}

	public void setCraLibelle(String craLibelle) {
		this.craLibelle = craLibelle;
	}

	@Column(name = "CODPARENT", length = 50)
	public String getCodparent() {
		return this.codparent;
	}

	public void setCodparent(String codparent) {
		this.codparent = codparent;
	}

	@Column(name = "ANALYSE_STATUT", length = 1)
	public String getAnalyseStatut() {
		return this.analyseStatut;
	}

	public void setAnalyseStatut(String analyseStatut) {
		this.analyseStatut = analyseStatut;
	}

	@Column(name = "CODEP", nullable = false, length = 50)
	public String getCodep() {
		return this.codep;
	}

	public void setCodep(String codep) {
		this.codep = codep;
	}

	@Column(name = "CODEPX", length = 50)
	public String getCodepx() {
		return this.codepx;
	}

	public void setCodepx(String codepx) {
		this.codepx = codepx;
	}

	@Column(name = "CRA_TYM_CODEX", length = 4)
	public String getCraTymCodex() {
		return this.craTymCodex;
	}

	public void setCraTymCodex(String craTymCodex) {
		this.craTymCodex = craTymCodex;
	}

	@Column(name = "CRA_TYP_PROC", length = 3)
	public String getCraTypProc() {
		return this.craTypProc;
	}

	public void setCraTypProc(String craTypProc) {
		this.craTypProc = craTypProc;
	}

	@Column(name = "CRA_TYP_DAC", length = 3)
	public String getCraTypDac() {
		return this.craTypDac;
	}

	public void setCraTypDac(String craTypDac) {
		this.craTypDac = craTypDac;
	}

	@Column(name = "CRA_BAILLEURX", length = 20)
	public String getCraBailleurx() {
		return this.craBailleurx;
	}

	public void setCraBailleurx(String craBailleurx) {
		this.craBailleurx = craBailleurx;
	}

	@Column(name = "DCAD_DAC_CODE", length = 50)
	public String getDcadDacCode() {
		return this.dcadDacCode;
	}

	public void setDcadDacCode(String dcadDacCode) {
		this.dcadDacCode = dcadDacCode;
	}

	@Column(name = "STATUT_CRE", length = 1)
	public String getStatutCre() {
		return this.statutCre;
	}

	public void setStatutCre(String statutCre) {
		this.statutCre = statutCre;
	}

	@Column(name = "AAO_REG_QUAL", length = 100)
	public String getAaoRegQual() {
		return this.aaoRegQual;
	}

	public void setAaoRegQual(String aaoRegQual) {
		this.aaoRegQual = aaoRegQual;
	}

	@Column(name = "VAL_REG_QUAL", precision = 22, scale = 0)
	public BigDecimal getValRegQual() {
		return this.valRegQual;
	}

	public void setValRegQual(BigDecimal valRegQual) {
		this.valRegQual = valRegQual;
	}

	@Column(name = "DCAD_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDcadNum() {
		return this.dcadNum;
	}

	public void setDcadNum(BigDecimal dcadNum) {
		this.dcadNum = dcadNum;
	}

	@Column(name = "DCAD_COMMENTAIRE", length = 1000)
	public String getDcadCommentaire() {
		return this.dcadCommentaire;
	}

	public void setDcadCommentaire(String dcadCommentaire) {
		this.dcadCommentaire = dcadCommentaire;
	}

	@Column(name = "DCAD_LAA_ID", precision = 22, scale = 0)
	public BigDecimal getDcadLaaId() {
		return this.dcadLaaId;
	}

	public void setDcadLaaId(BigDecimal dcadLaaId) {
		this.dcadLaaId = dcadLaaId;
	}

	@Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_OBJET", nullable = false, length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "LAA_LBG_IMPUTATION", length = 50)
	public String getLaaLbgImputation() {
		return this.laaLbgImputation;
	}

	public void setLaaLbgImputation(String laaLbgImputation) {
		this.laaLbgImputation = laaLbgImputation;
	}

	@Column(name = "LAA_AAO_CODE", length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "DCAD_NUM_DCAD", precision = 22, scale = 0)
	public BigDecimal getDcadNumDcad() {
		return this.dcadNumDcad;
	}

	public void setDcadNumDcad(BigDecimal dcadNumDcad) {
		this.dcadNumDcad = dcadNumDcad;
	}

	@Column(name = "DCAD_CRA_AU_CODE", length = 50)
	public String getDcadCraAuCode() {
		return this.dcadCraAuCode;
	}

	public void setDcadCraAuCode(String dcadCraAuCode) {
		this.dcadCraAuCode = dcadCraAuCode;
	}

	@Column(name = "DCAD_PETIT_CRA", length = 50)
	public String getDcadPetitCra() {
		return this.dcadPetitCra;
	}

	public void setDcadPetitCra(String dcadPetitCra) {
		this.dcadPetitCra = dcadPetitCra;
	}

	@Column(name = "DCAD_PRESENCE")
	public String getDcadPresence() {
		return this.dcadPresence;
	}

	public void setDcadPresence(String dcadPresence) {
		this.dcadPresence = dcadPresence;
	}
	
	@Column(name = "ANF_VALEUR_CONF", length = 100)
	public String getAnfValeurConf() {
		return this.anfValeurConf;
	}

	public void setAnfValeurConf(String anfValeurConf) {
		this.anfValeurConf = anfValeurConf;
	}

	@Column(name = "ANF_TYPE_ACTEUR", length = 2)
	public String getAnfTypeActeur() {
		return this.anfTypeActeur;
	}

	public void setAnfTypeActeur(String anfTypeActeur) {
		this.anfTypeActeur = anfTypeActeur;
	}

	@Column(name = "ANF_VALEUR_SCORE", precision = 22, scale = 0)
	public BigDecimal getAnfValeurScore() {
		return this.anfValeurScore;
	}

	public void setAnfValeurScore(BigDecimal anfValeurScore) {
		this.anfValeurScore = anfValeurScore;
	}
	
}
