package com.sndi.model;
// Generated 3 juil. 2020 15:29:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VCritAnalDacEnteteId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_CRIT_ANAL_DAC_ENTETE")
public class VCritAnalDacEntete implements java.io.Serializable {

	private String craCode;
	private String craLibelle;
	private String mdtCode;
	private String mdtTymCode;

	public VCritAnalDacEntete() {
	}

	public VCritAnalDacEntete(String craCode, String craLibelle, String mdtCode, String mdtTymCode) {
		this.craCode = craCode;
		this.craLibelle = craLibelle;
		this.mdtCode = mdtCode;
		this.mdtTymCode = mdtTymCode;
	}

	@Id
	@Column(name = "CRA_CODE", length = 36)
	public String getCraCode() {
		return this.craCode;
	}

	public void setCraCode(String craCode) {
		this.craCode = craCode;
	}

	@Column(name = "CRA_LIBELLE", length = 512)
	public String getCraLibelle() {
		return this.craLibelle;
	}

	public void setCraLibelle(String craLibelle) {
		this.craLibelle = craLibelle;
	}

	@Column(name = "MDT_CODE", length = 15)
	public String getMdtCode() {
		return this.mdtCode;
	}

	public void setMdtCode(String mdtCode) {
		this.mdtCode = mdtCode;
	}

	@Column(name = "MDT_TYM_CODE", length = 10)
	public String getMdtTymCode() {
		return this.mdtTymCode;
	}

	public void setMdtTymCode(String mdtTymCode) {
		this.mdtTymCode = mdtTymCode;
	}
}
