package com.sndi.model;
// Generated 18 juil. 2020 16:53:34 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VCritereAnalyseDacOff generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_CRITERE_ANALYSE_DAC_OFF")
public class VCritereAnalyseDacOff implements java.io.Serializable {

	private BigDecimal RId;
	private String craCode;
	private String craLibelle;
	private BigDecimal RTri;
	private BigDecimal offNum;
	private BigDecimal dofNum;
	private String codparent;
	private String codep;
	private String craTymCodex;
	private String craTypProc;
	private String craTypDac;
	private String craBailleurx;
	private String dcadDacCode;
	private String aaoRegQual;
	private long valRegQual;
	private BigDecimal dcadNum;
	private String dcadCommentaire;
	private BigDecimal dcadLaaId;
	private BigDecimal dcadNumDcad;
	private String dcadCraAuCode;
	private String dcadPetitCra;

	public VCritereAnalyseDacOff() {
	}

	public VCritereAnalyseDacOff(BigDecimal RId,  BigDecimal RTri, BigDecimal offNum, BigDecimal dofNum, String craCode, String craLibelle, String codparent, String codep,
			String craTymCodex, String craTypProc, String craTypDac, String craBailleurx, String dcadDacCode,
			String aaoRegQual, long valRegQual, BigDecimal dcadNum, String dcadCommentaire, BigDecimal dcadLaaId,
			BigDecimal dcadNumDcad, String dcadCraAuCode, String dcadPetitCra) {
		this.RId = RId;
		this.RTri = RTri;
		this.offNum = offNum;
		this.dofNum = dofNum;
		this.craCode = craCode;
		this.craLibelle = craLibelle;
		this.codparent = codparent;
		this.codep = codep;
		this.craTymCodex = craTymCodex;
		this.craTypProc = craTypProc;
		this.craTypDac = craTypDac;
		this.craBailleurx = craBailleurx;
		this.dcadDacCode = dcadDacCode;
		this.aaoRegQual = aaoRegQual;
		this.valRegQual = valRegQual;
		this.dcadNum = dcadNum;
		this.dcadCommentaire = dcadCommentaire;
		this.dcadLaaId = dcadLaaId;
		this.dcadNumDcad = dcadNumDcad;
		this.dcadCraAuCode = dcadCraAuCode;
		this.dcadPetitCra = dcadPetitCra;
	}

	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}
	
	@Column(name = "R_TRI", precision = 22, scale = 0)
	public BigDecimal getRTri() {
		return this.RTri;
	}

	public void setRTri(BigDecimal RTri) {
		this.RTri = RTri;
	}

	@Column(name = "OFF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOffNum() {
		return this.offNum;
	}

	public void setOffNum(BigDecimal offNum) {
		this.offNum = offNum;
	}

	@Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}
	
	@Column(name = "CRA_CODE", length = 100)
	public String getCraCode() {
		return this.craCode;
	}

	public void setCraCode(String craCode) {
		this.craCode = craCode;
	}

	@Column(name = "CRA_LIBELLE", length = 4000)
	public String getCraLibelle() {
		return this.craLibelle;
	}

	public void setCraLibelle(String craLibelle) {
		this.craLibelle = craLibelle;
	}

	@Column(name = "CODPARENT", length = 50)
	public String getCodparent() {
		return this.codparent;
	}

	public void setCodparent(String codparent) {
		this.codparent = codparent;
	}

	@Column(name = "CODEP", length = 50)
	public String getCodep() {
		return this.codep;
	}

	public void setCodep(String codep) {
		this.codep = codep;
	}

	@Column(name = "CRA_TYM_CODEX", length = 4)
	public String getCraTymCodex() {
		return this.craTymCodex;
	}

	public void setCraTymCodex(String craTymCodex) {
		this.craTymCodex = craTymCodex;
	}

	@Column(name = "CRA_TYP_PROC", length = 3)
	public String getCraTypProc() {
		return this.craTypProc;
	}

	public void setCraTypProc(String craTypProc) {
		this.craTypProc = craTypProc;
	}

	@Column(name = "CRA_TYP_DAC", length = 3)
	public String getCraTypDac() {
		return this.craTypDac;
	}

	public void setCraTypDac(String craTypDac) {
		this.craTypDac = craTypDac;
	}

	@Column(name = "CRA_BAILLEURX", length = 20)
	public String getCraBailleurx() {
		return this.craBailleurx;
	}

	public void setCraBailleurx(String craBailleurx) {
		this.craBailleurx = craBailleurx;
	}

	@Column(name = "DCAD_DAC_CODE", length = 50)
	public String getDcadDacCode() {
		return this.dcadDacCode;
	}

	public void setDcadDacCode(String dcadDacCode) {
		this.dcadDacCode = dcadDacCode;
	}

	@Column(name = "AAO_REG_QUAL", length = 100)
	public String getAaoRegQual() {
		return this.aaoRegQual;
	}

	public void setAaoRegQual(String aaoRegQual) {
		this.aaoRegQual = aaoRegQual;
	}

	@Column(name = "VAL_REG_QUAL", precision = 22, scale = 0)
	public long getValRegQual() {
		return this.valRegQual;
	}

	public void setValRegQual(long valRegQual) {
		this.valRegQual = valRegQual;
	}

	@Column(name = "DCAD_NUM", precision = 22, scale = 0)
	public BigDecimal getDcadNum() {
		return this.dcadNum;
	}

	public void setDcadNum(BigDecimal dcadNum) {
		this.dcadNum = dcadNum;
	}

	@Column(name = "DCAD_COMMENTAIRE", length = 1000)
	public String getDcadCommentaire() {
		return this.dcadCommentaire;
	}

	public void setDcadCommentaire(String dcadCommentaire) {
		this.dcadCommentaire = dcadCommentaire;
	}

	@Column(name = "DCAD_LAA_ID", precision = 22, scale = 0)
	public BigDecimal getDcadLaaId() {
		return this.dcadLaaId;
	}

	public void setDcadLaaId(BigDecimal dcadLaaId) {
		this.dcadLaaId = dcadLaaId;
	}

	@Column(name = "DCAD_NUM_DCAD", precision = 22, scale = 0)
	public BigDecimal getDcadNumDcad() {
		return this.dcadNumDcad;
	}

	public void setDcadNumDcad(BigDecimal dcadNumDcad) {
		this.dcadNumDcad = dcadNumDcad;
	}

	@Column(name = "DCAD_CRA_AU_CODE", length = 50)
	public String getDcadCraAuCode() {
		return this.dcadCraAuCode;
	}

	public void setDcadCraAuCode(String dcadCraAuCode) {
		this.dcadCraAuCode = dcadCraAuCode;
	}

	@Column(name = "DCAD_PETIT_CRA", length = 50)
	public String getDcadPetitCra() {
		return this.dcadPetitCra;
	}

	public void setDcadPetitCra(String dcadPetitCra) {
		this.dcadPetitCra = dcadPetitCra;
	}

}
