package com.sndi.model;
// Generated 26 août 2020 17:42:42 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VdAaoId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VD_AAO")
public class VdAao implements java.io.Serializable {

	private String dacCode;
	private String laaObjet;
	private String laaLbgImputation;
	private BigDecimal laaNum;
	private BigDecimal laaDelaiExe;
	private BigDecimal laaMtCaut;

	public VdAao() {
	}

	public VdAao(String dacCode, String laaObjet, BigDecimal laaNum) {
		this.dacCode = dacCode;
		this.laaObjet = laaObjet;
		this.laaNum = laaNum;
	}

	public VdAao(String dacCode, String laaObjet, String laaLbgImputation, BigDecimal laaNum,
			BigDecimal laaDelaiExe) {
		this.dacCode = dacCode;
		this.laaObjet = laaObjet;
		this.laaLbgImputation = laaLbgImputation;
		this.laaNum = laaNum;
		this.laaDelaiExe = laaDelaiExe;
	}

	@Id
	@Column(name = "DAC_CODE", nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "LAA_OBJET", nullable = false, length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "LAA_LBG_IMPUTATION", length = 50)
	public String getLaaLbgImputation() {
		return this.laaLbgImputation;
	}

	public void setLaaLbgImputation(String laaLbgImputation) {
		this.laaLbgImputation = laaLbgImputation;
	}

	@Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}
	
	@Column(name = "LAA_MT_CAUT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaMtCaut() {
		return this.laaMtCaut;
	}

	public void setLaaMtCaut(BigDecimal laaMtCaut) {
		this.laaMtCaut = laaMtCaut;
	}

	@Column(name = "LAA_DELAI_EXE", precision = 22, scale = 0)
	public BigDecimal getLaaDelaiExe() {
		return this.laaDelaiExe;
	}

	public void setLaaDelaiExe(BigDecimal laaDelaiExe) {
		this.laaDelaiExe = laaDelaiExe;
	}
}
