package com.sndi.model;
// Generated 17 avr. 2020 08:37:58 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Immutable;

/**
 * VDatePub generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_DATE_PUB")
public class VDatePub implements java.io.Serializable {
	//private BigDecimal RId;
	private Date datepub;
	private String libelle;

	public VDatePub() {
	}

	public VDatePub(/*BigDecimal RId,*/Date datepub, String libelle) {
		//this.RId = RId;
		this.datepub = datepub;
		this.libelle = libelle;
	}
	

	@Id
/*	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}
	*/
	@Temporal(TemporalType.DATE)
	@Column(name = "DATEPUB", length = 8)
	public Date getDatepub() {
		return this.datepub;
	}

	public void setDatepub(Date datepub) {
		this.datepub = datepub;
	}

	@Column(name = "LIBELLE", length = 120)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
