package com.sndi.model;
// Generated 26 août 2020 17:42:42 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VdDaoId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VD_DAO")
public class VdDao implements java.io.Serializable {

	private String dacCode;
	private String dacObjet;
	private Long dacCout;
	private String strLibelleLong;
	private String minLibelle;
	private short gesCode;
	private String aaoLibelle;
	private Date aaoDteOuvTec;
	private String aaoDteHeurOuv;
	private Date aaoDteOuvFin;
	private BigDecimal aaoNbrLot;
	private BigDecimal aaoNbrOuv;
	private BigDecimal aaoDelaiVal;
	private String aaoLieuExe;
	private BigDecimal aaoCoutDac;
	private String aaoLieuRecep;
	private Date aaoDateRecep;
	private String aaoHeureRecep;
	private String aaoNatPrix;
	private String aaoRegQual;
	private String laaLbgImputation;
	private Long laaDelaiExe;
	private String tymCode;
	private String DacNbrCopieOff;

	public VdDao() {
	}

	public VdDao(String dacCode, short gesCode) {
		this.dacCode = dacCode;
		this.gesCode = gesCode;
	}

	public VdDao(String dacCode, String dacObjet, Long dacCout, String strLibelleLong, String minLibelle,
			short gesCode, String aaoLibelle, Date aaoDteOuvTec, String aaoDteHeurOuv, Date aaoDteOuvFin,
			BigDecimal aaoNbrLot, BigDecimal aaoNbrOuv, BigDecimal aaoDelaiVal, String aaoLieuExe,
			BigDecimal aaoCoutDac, String aaoLieuRecep, Date aaoDateRecep, String aaoHeureRecep, String aaoNatPrix,
			String aaoRegQual, String laaLbgImputation, Long laaDelaiExe) {
		this.dacCode = dacCode;
		this.dacObjet = dacObjet;
		this.dacCout = dacCout;
		this.strLibelleLong = strLibelleLong;
		this.minLibelle = minLibelle;
		this.gesCode = gesCode;
		this.aaoLibelle = aaoLibelle;
		this.aaoDteOuvTec = aaoDteOuvTec;
		this.aaoDteHeurOuv = aaoDteHeurOuv;
		this.aaoDteOuvFin = aaoDteOuvFin;
		this.aaoNbrLot = aaoNbrLot;
		this.aaoNbrOuv = aaoNbrOuv;
		this.aaoDelaiVal = aaoDelaiVal;
		this.aaoLieuExe = aaoLieuExe;
		this.aaoCoutDac = aaoCoutDac;
		this.aaoLieuRecep = aaoLieuRecep;
		this.aaoDateRecep = aaoDateRecep;
		this.aaoHeureRecep = aaoHeureRecep;
		this.aaoNatPrix = aaoNatPrix;
		this.aaoRegQual = aaoRegQual;
		this.laaLbgImputation = laaLbgImputation;
		this.laaDelaiExe = laaDelaiExe;
	}

	@Id
	@Column(name = "DAC_CODE", nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "DAC_OBJET", length = 1000)
	public String getDacObjet() {
		return this.dacObjet;
	}

	public void setDacObjet(String dacObjet) {
		this.dacObjet = dacObjet;
	}

	@Column(name = "DAC_COUT", precision = 11, scale = 0)
	public Long getDacCout() {
		return this.dacCout;
	}

	public void setDacCout(Long dacCout) {
		this.dacCout = dacCout;
	}

	@Column(name = "STR_LIBELLE_LONG", length = 1000)
	public String getStrLibelleLong() {
		return this.strLibelleLong;
	}

	public void setStrLibelleLong(String strLibelleLong) {
		this.strLibelleLong = strLibelleLong;
	}

	@Column(name = "MIN_LIBELLE", length = 1000)
	public String getMinLibelle() {
		return this.minLibelle;
	}

	public void setMinLibelle(String minLibelle) {
		this.minLibelle = minLibelle;
	}

	@Column(name = "GES_CODE", nullable = false, precision = 4, scale = 0)
	public short getGesCode() {
		return this.gesCode;
	}

	public void setGesCode(short gesCode) {
		this.gesCode = gesCode;
	}

	@Column(name = "AAO_LIBELLE", length = 1000)
	public String getAaoLibelle() {
		return this.aaoLibelle;
	}

	public void setAaoLibelle(String aaoLibelle) {
		this.aaoLibelle = aaoLibelle;
	}

	@Column(name = "AAO_DTE_OUV_TEC", length = 7)
	public Date getAaoDteOuvTec() {
		return this.aaoDteOuvTec;
	}

	public void setAaoDteOuvTec(Date aaoDteOuvTec) {
		this.aaoDteOuvTec = aaoDteOuvTec;
	}

	@Column(name = "AAO_DTE_HEUR_OUV", length = 20)
	public String getAaoDteHeurOuv() {
		return this.aaoDteHeurOuv;
	}

	public void setAaoDteHeurOuv(String aaoDteHeurOuv) {
		this.aaoDteHeurOuv = aaoDteHeurOuv;
	}

	@Column(name = "AAO_DTE_OUV_FIN", length = 7)
	public Date getAaoDteOuvFin() {
		return this.aaoDteOuvFin;
	}

	public void setAaoDteOuvFin(Date aaoDteOuvFin) {
		this.aaoDteOuvFin = aaoDteOuvFin;
	}

	@Column(name = "AAO_NBR_LOT", precision = 22, scale = 0)
	public BigDecimal getAaoNbrLot() {
		return this.aaoNbrLot;
	}

	public void setAaoNbrLot(BigDecimal aaoNbrLot) {
		this.aaoNbrLot = aaoNbrLot;
	}

	@Column(name = "AAO_NBR_OUV", precision = 22, scale = 0)
	public BigDecimal getAaoNbrOuv() {
		return this.aaoNbrOuv;
	}

	public void setAaoNbrOuv(BigDecimal aaoNbrOuv) {
		this.aaoNbrOuv = aaoNbrOuv;
	}

	@Column(name = "AAO_DELAI_VAL", precision = 22, scale = 0)
	public BigDecimal getAaoDelaiVal() {
		return this.aaoDelaiVal;
	}

	public void setAaoDelaiVal(BigDecimal aaoDelaiVal) {
		this.aaoDelaiVal = aaoDelaiVal;
	}

	@Column(name = "AAO_LIEU_EXE", length = 200)
	public String getAaoLieuExe() {
		return this.aaoLieuExe;
	}

	public void setAaoLieuExe(String aaoLieuExe) {
		this.aaoLieuExe = aaoLieuExe;
	}

	@Column(name = "AAO_COUT_DAC", precision = 22, scale = 0)
	public BigDecimal getAaoCoutDac() {
		return this.aaoCoutDac;
	}

	public void setAaoCoutDac(BigDecimal aaoCoutDac) {
		this.aaoCoutDac = aaoCoutDac;
	}

	@Column(name = "AAO_LIEU_RECEP", length = 1000)
	public String getAaoLieuRecep() {
		return this.aaoLieuRecep;
	}

	public void setAaoLieuRecep(String aaoLieuRecep) {
		this.aaoLieuRecep = aaoLieuRecep;
	}

	@Column(name = "AAO_DATE_RECEP", length = 7)
	public Date getAaoDateRecep() {
		return this.aaoDateRecep;
	}

	public void setAaoDateRecep(Date aaoDateRecep) {
		this.aaoDateRecep = aaoDateRecep;
	}

	@Column(name = "AAO_HEURE_RECEP", length = 20)
	public String getAaoHeureRecep() {
		return this.aaoHeureRecep;
	}

	public void setAaoHeureRecep(String aaoHeureRecep) {
		this.aaoHeureRecep = aaoHeureRecep;
	}

	@Column(name = "AAO_NAT_PRIX", length = 20)
	public String getAaoNatPrix() {
		return this.aaoNatPrix;
	}

	public void setAaoNatPrix(String aaoNatPrix) {
		this.aaoNatPrix = aaoNatPrix;
	}

	@Column(name = "AAO_REG_QUAL", length = 100)
	public String getAaoRegQual() {
		return this.aaoRegQual;
	}

	public void setAaoRegQual(String aaoRegQual) {
		this.aaoRegQual = aaoRegQual;
	}

	@Column(name = "LAA_LBG_IMPUTATION", length = 50)
	public String getLaaLbgImputation() {
		return this.laaLbgImputation;
	}

	public void setLaaLbgImputation(String laaLbgImputation) {
		this.laaLbgImputation = laaLbgImputation;
	}

	@Column(name = "LAA_DELAI_EXE", precision = 10, scale = 0)
	public Long getLaaDelaiExe() {
		return this.laaDelaiExe;
	}

	public void setLaaDelaiExe(Long laaDelaiExe) {
		this.laaDelaiExe = laaDelaiExe;
	}
	
	@Column(name = "TYM_CODE", precision = 10, scale = 0)
	public String getTymCode() {
		return this.tymCode;
	}

	public void setTymCode(String tymCode) {
		this.tymCode = tymCode;
	}
	
	@Column(name = "DAC_NBR_COPIE_OFF", precision = 10, scale = 0)
	public String getDacNbrCopieOff() {
		return this.DacNbrCopieOff;
	}

	public void setDacNbrCopieOff(String DacNbrCopieOff) {
		this.DacNbrCopieOff = DacNbrCopieOff;
	}

}
