package com.sndi.model;
// Generated 9 juil. 2020 10:03:16 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VDetTabBordPpm generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_DET_TAB_BORD_PPM")
public class VDetTabBordPpm implements java.io.Serializable {

	private BigDecimal ppmDetid;
	private String codeAc;
	private BigDecimal saisi;
	private BigDecimal transAc;
	private BigDecimal valPf;
	private BigDecimal difPf;
	private BigDecimal valDmp;
	private BigDecimal difDmp;
	private BigDecimal pub;
	private BigDecimal ppmSaisi;
	private BigDecimal ppmTransAc;
	private BigDecimal ppmValPf;
	private BigDecimal ppmDifPf;
	private BigDecimal ppmValDmp;
	private BigDecimal ppmDifDmp;
	private BigDecimal ppmPub;
	private String typ;
	private String typProc;
	private String typDac;
	private String codePf;
	private long dppId;
	private long dppPlpId;
	private long dppGpgId;
	private String dppStaCode;
	private String dppTymCode;
	private String dppMopCode;
	private String dppLbgCode;
	private String dppTypePlan;
	private String dppCode;
	private Integer dppNumeroOrdre;
	private Date dppDate;
	private String dppObjet;
	private String dppSourceFin;
	private Date dppDateDaoTrans;
	private Date dppDateDaoApprobDmp;
	private Date dppDateDaoApprobBail;
	private Date dppDateAvisAoPublication;
	private Date dppDateOuvertOt;
	private Date dppDateOuvertOf;
	private Date dppDateElabRapport;
	private Date dppDateJugementOffre;
	private Date dppDateAttApprobDmp;
	private Date dppDateAttApproBail;
	private Date dppDateNegociation;
	private Date dppDateSignatAttrib;
	private Date dppDateSignatAc;
	private Date dppDateMarcheApprob;
	private Date dppDateExecDebut;
	private Date dppDateExecFin;
	private String dppActeurSaisie;
	private String dppStrCode;
	private String dppStatutRetour;
	private Date dppDateSaisie;
	private String dppStructureConduc;
	private String dppStructureBenefi;
	private String dppPartiePmePmi;
	private String dppTypId;
	private String dppStatutDao;
	private String dppPieceDao;
	private String dppDacCode;
	private Date dppInvEntre;
	private Date dppDateAttApprobCpmp;
	private Date dppDateJugementOffreTec;
	private Date dppDateValAc;
	private Date dppDateValCpmp;
	private Date dppDateValDmp;
	private String dppBailleur;
	private String dppTypeFinance;
	private Date dppApprobAno;
	private Date dppDteModif;

	public VDetTabBordPpm() {
	}

	public VDetTabBordPpm(String typProc, long dppId, long dppPlpId, long dppGpgId, String dppStaCode,
			String dppTymCode, String dppMopCode, String dppTypePlan) {
		this.typProc = typProc;
		this.dppId = dppId;
		this.dppPlpId = dppPlpId;
		this.dppGpgId = dppGpgId;
		this.dppStaCode = dppStaCode;
		this.dppTymCode = dppTymCode;
		this.dppMopCode = dppMopCode;
		this.dppTypePlan = dppTypePlan;
	}

	public VDetTabBordPpm(BigDecimal ppmDetid, String codeAc, BigDecimal saisi, BigDecimal transAc, BigDecimal valPf,
			BigDecimal difPf, BigDecimal valDmp, BigDecimal difDmp, BigDecimal pub, BigDecimal ppmSaisi,
			BigDecimal ppmTransAc, BigDecimal ppmValPf, BigDecimal ppmDifPf, BigDecimal ppmValDmp, BigDecimal ppmDifDmp,
			BigDecimal ppmPub, String typ, String typProc, String typDac, String codePf, long dppId, long dppPlpId,
			long dppGpgId, String dppStaCode, String dppTymCode, String dppMopCode, String dppLbgCode,
			String dppTypePlan, String dppCode, Integer dppNumeroOrdre, Date dppDate, String dppObjet,
			String dppSourceFin, Date dppDateDaoTrans, Date dppDateDaoApprobDmp, Date dppDateDaoApprobBail,
			Date dppDateAvisAoPublication, Date dppDateOuvertOt, Date dppDateOuvertOf, Date dppDateElabRapport,
			Date dppDateJugementOffre, Date dppDateAttApprobDmp, Date dppDateAttApproBail, Date dppDateNegociation,
			Date dppDateSignatAttrib, Date dppDateSignatAc, Date dppDateMarcheApprob, Date dppDateExecDebut,
			Date dppDateExecFin, String dppActeurSaisie, String dppStrCode, String dppStatutRetour, Date dppDateSaisie,
			String dppStructureConduc, String dppStructureBenefi, String dppPartiePmePmi, String dppTypId,
			String dppStatutDao, String dppPieceDao, String dppDacCode, Date dppInvEntre, Date dppDateAttApprobCpmp,
			Date dppDateJugementOffreTec, Date dppDateValAc, Date dppDateValCpmp, Date dppDateValDmp,
			String dppBailleur, String dppTypeFinance, Date dppApprobAno, Date dppDteModif) {
		this.ppmDetid = ppmDetid;
		this.codeAc = codeAc;
		this.saisi = saisi;
		this.transAc = transAc;
		this.valPf = valPf;
		this.difPf = difPf;
		this.valDmp = valDmp;
		this.difDmp = difDmp;
		this.pub = pub;
		this.ppmSaisi = ppmSaisi;
		this.ppmTransAc = ppmTransAc;
		this.ppmValPf = ppmValPf;
		this.ppmDifPf = ppmDifPf;
		this.ppmValDmp = ppmValDmp;
		this.ppmDifDmp = ppmDifDmp;
		this.ppmPub = ppmPub;
		this.typ = typ;
		this.typProc = typProc;
		this.typDac = typDac;
		this.codePf = codePf;
		this.dppId = dppId;
		this.dppPlpId = dppPlpId;
		this.dppGpgId = dppGpgId;
		this.dppStaCode = dppStaCode;
		this.dppTymCode = dppTymCode;
		this.dppMopCode = dppMopCode;
		this.dppLbgCode = dppLbgCode;
		this.dppTypePlan = dppTypePlan;
		this.dppCode = dppCode;
		this.dppNumeroOrdre = dppNumeroOrdre;
		this.dppDate = dppDate;
		this.dppObjet = dppObjet;
		this.dppSourceFin = dppSourceFin;
		this.dppDateDaoTrans = dppDateDaoTrans;
		this.dppDateDaoApprobDmp = dppDateDaoApprobDmp;
		this.dppDateDaoApprobBail = dppDateDaoApprobBail;
		this.dppDateAvisAoPublication = dppDateAvisAoPublication;
		this.dppDateOuvertOt = dppDateOuvertOt;
		this.dppDateOuvertOf = dppDateOuvertOf;
		this.dppDateElabRapport = dppDateElabRapport;
		this.dppDateJugementOffre = dppDateJugementOffre;
		this.dppDateAttApprobDmp = dppDateAttApprobDmp;
		this.dppDateAttApproBail = dppDateAttApproBail;
		this.dppDateNegociation = dppDateNegociation;
		this.dppDateSignatAttrib = dppDateSignatAttrib;
		this.dppDateSignatAc = dppDateSignatAc;
		this.dppDateMarcheApprob = dppDateMarcheApprob;
		this.dppDateExecDebut = dppDateExecDebut;
		this.dppDateExecFin = dppDateExecFin;
		this.dppActeurSaisie = dppActeurSaisie;
		this.dppStrCode = dppStrCode;
		this.dppStatutRetour = dppStatutRetour;
		this.dppDateSaisie = dppDateSaisie;
		this.dppStructureConduc = dppStructureConduc;
		this.dppStructureBenefi = dppStructureBenefi;
		this.dppPartiePmePmi = dppPartiePmePmi;
		this.dppTypId = dppTypId;
		this.dppStatutDao = dppStatutDao;
		this.dppPieceDao = dppPieceDao;
		this.dppDacCode = dppDacCode;
		this.dppInvEntre = dppInvEntre;
		this.dppDateAttApprobCpmp = dppDateAttApprobCpmp;
		this.dppDateJugementOffreTec = dppDateJugementOffreTec;
		this.dppDateValAc = dppDateValAc;
		this.dppDateValCpmp = dppDateValCpmp;
		this.dppDateValDmp = dppDateValDmp;
		this.dppBailleur = dppBailleur;
		this.dppTypeFinance = dppTypeFinance;
		this.dppApprobAno = dppApprobAno;
		this.dppDteModif = dppDteModif;
	}

	
	@Id
	@Column(name = "PPM_DETID", precision = 22, scale = 0)
	public BigDecimal getPpmDetid() {
		return this.ppmDetid;
	}

	public void setPpmDetid(BigDecimal ppmDetid) {
		this.ppmDetid = ppmDetid;
	}

	@Column(name = "CODE_AC", length = 12)
	public String getCodeAc() {
		return this.codeAc;
	}

	public void setCodeAc(String codeAc) {
		this.codeAc = codeAc;
	}

	@Column(name = "SAISI", precision = 22, scale = 0)
	public BigDecimal getSaisi() {
		return this.saisi;
	}

	public void setSaisi(BigDecimal saisi) {
		this.saisi = saisi;
	}

	@Column(name = "TRANS_AC", precision = 22, scale = 0)
	public BigDecimal getTransAc() {
		return this.transAc;
	}

	public void setTransAc(BigDecimal transAc) {
		this.transAc = transAc;
	}

	@Column(name = "VAL_PF", precision = 22, scale = 0)
	public BigDecimal getValPf() {
		return this.valPf;
	}

	public void setValPf(BigDecimal valPf) {
		this.valPf = valPf;
	}

	@Column(name = "DIF_PF", precision = 22, scale = 0)
	public BigDecimal getDifPf() {
		return this.difPf;
	}

	public void setDifPf(BigDecimal difPf) {
		this.difPf = difPf;
	}

	@Column(name = "VAL_DMP", precision = 22, scale = 0)
	public BigDecimal getValDmp() {
		return this.valDmp;
	}

	public void setValDmp(BigDecimal valDmp) {
		this.valDmp = valDmp;
	}

	@Column(name = "DIF_DMP", precision = 22, scale = 0)
	public BigDecimal getDifDmp() {
		return this.difDmp;
	}

	public void setDifDmp(BigDecimal difDmp) {
		this.difDmp = difDmp;
	}

	@Column(name = "PUB", precision = 22, scale = 0)
	public BigDecimal getPub() {
		return this.pub;
	}

	public void setPub(BigDecimal pub) {
		this.pub = pub;
	}

	@Column(name = "PPM_SAISI", precision = 22, scale = 0)
	public BigDecimal getPpmSaisi() {
		return this.ppmSaisi;
	}

	public void setPpmSaisi(BigDecimal ppmSaisi) {
		this.ppmSaisi = ppmSaisi;
	}

	@Column(name = "PPM_TRANS_AC", precision = 22, scale = 0)
	public BigDecimal getPpmTransAc() {
		return this.ppmTransAc;
	}

	public void setPpmTransAc(BigDecimal ppmTransAc) {
		this.ppmTransAc = ppmTransAc;
	}

	@Column(name = "PPM_VAL_PF", precision = 22, scale = 0)
	public BigDecimal getPpmValPf() {
		return this.ppmValPf;
	}

	public void setPpmValPf(BigDecimal ppmValPf) {
		this.ppmValPf = ppmValPf;
	}

	@Column(name = "PPM_DIF_PF", precision = 22, scale = 0)
	public BigDecimal getPpmDifPf() {
		return this.ppmDifPf;
	}

	public void setPpmDifPf(BigDecimal ppmDifPf) {
		this.ppmDifPf = ppmDifPf;
	}

	@Column(name = "PPM_VAL_DMP", precision = 22, scale = 0)
	public BigDecimal getPpmValDmp() {
		return this.ppmValDmp;
	}

	public void setPpmValDmp(BigDecimal ppmValDmp) {
		this.ppmValDmp = ppmValDmp;
	}

	@Column(name = "PPM_DIF_DMP", precision = 22, scale = 0)
	public BigDecimal getPpmDifDmp() {
		return this.ppmDifDmp;
	}

	public void setPpmDifDmp(BigDecimal ppmDifDmp) {
		this.ppmDifDmp = ppmDifDmp;
	}

	@Column(name = "PPM_PUB", precision = 22, scale = 0)
	public BigDecimal getPpmPub() {
		return this.ppmPub;
	}

	public void setPpmPub(BigDecimal ppmPub) {
		this.ppmPub = ppmPub;
	}

	@Column(name = "TYP", length = 3)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Column(name = "TYP_PROC", nullable = false, length = 3)
	public String getTypProc() {
		return this.typProc;
	}

	public void setTypProc(String typProc) {
		this.typProc = typProc;
	}

	@Column(name = "TYP_DAC", length = 3)
	public String getTypDac() {
		return this.typDac;
	}

	public void setTypDac(String typDac) {
		this.typDac = typDac;
	}

	@Column(name = "CODE_PF", length = 30)
	public String getCodePf() {
		return this.codePf;
	}

	public void setCodePf(String codePf) {
		this.codePf = codePf;
	}

	@Column(name = "DPP_ID", nullable = false, precision = 10, scale = 0)
	public long getDppId() {
		return this.dppId;
	}

	public void setDppId(long dppId) {
		this.dppId = dppId;
	}

	@Column(name = "DPP_PLP_ID", nullable = false, precision = 10, scale = 0)
	public long getDppPlpId() {
		return this.dppPlpId;
	}

	public void setDppPlpId(long dppPlpId) {
		this.dppPlpId = dppPlpId;
	}

	@Column(name = "DPP_GPG_ID", nullable = false, precision = 10, scale = 0)
	public long getDppGpgId() {
		return this.dppGpgId;
	}

	public void setDppGpgId(long dppGpgId) {
		this.dppGpgId = dppGpgId;
	}

	@Column(name = "DPP_STA_CODE", nullable = false, length = 3)
	public String getDppStaCode() {
		return this.dppStaCode;
	}

	public void setDppStaCode(String dppStaCode) {
		this.dppStaCode = dppStaCode;
	}

	@Column(name = "DPP_TYM_CODE", nullable = false, length = 3)
	public String getDppTymCode() {
		return this.dppTymCode;
	}

	public void setDppTymCode(String dppTymCode) {
		this.dppTymCode = dppTymCode;
	}

	@Column(name = "DPP_MOP_CODE", nullable = false, length = 3)
	public String getDppMopCode() {
		return this.dppMopCode;
	}

	public void setDppMopCode(String dppMopCode) {
		this.dppMopCode = dppMopCode;
	}

	@Column(name = "DPP_LBG_CODE", length = 50)
	public String getDppLbgCode() {
		return this.dppLbgCode;
	}

	public void setDppLbgCode(String dppLbgCode) {
		this.dppLbgCode = dppLbgCode;
	}

	@Column(name = "DPP_TYPE_PLAN", nullable = false, length = 3)
	public String getDppTypePlan() {
		return this.dppTypePlan;
	}

	public void setDppTypePlan(String dppTypePlan) {
		this.dppTypePlan = dppTypePlan;
	}

	@Column(name = "DPP_CODE", length = 50)
	public String getDppCode() {
		return this.dppCode;
	}

	public void setDppCode(String dppCode) {
		this.dppCode = dppCode;
	}

	@Column(name = "DPP_NUMERO_ORDRE", precision = 8, scale = 0)
	public Integer getDppNumeroOrdre() {
		return this.dppNumeroOrdre;
	}

	public void setDppNumeroOrdre(Integer dppNumeroOrdre) {
		this.dppNumeroOrdre = dppNumeroOrdre;
	}

	@Column(name = "DPP_DATE", length = 7)
	public Date getDppDate() {
		return this.dppDate;
	}

	public void setDppDate(Date dppDate) {
		this.dppDate = dppDate;
	}

	@Column(name = "DPP_OBJET", length = 1000)
	public String getDppObjet() {
		return this.dppObjet;
	}

	public void setDppObjet(String dppObjet) {
		this.dppObjet = dppObjet;
	}

	@Column(name = "DPP_SOURCE_FIN", length = 1000)
	public String getDppSourceFin() {
		return this.dppSourceFin;
	}

	public void setDppSourceFin(String dppSourceFin) {
		this.dppSourceFin = dppSourceFin;
	}

	@Column(name = "DPP_DATE_DAO_TRANS", length = 7)
	public Date getDppDateDaoTrans() {
		return this.dppDateDaoTrans;
	}

	public void setDppDateDaoTrans(Date dppDateDaoTrans) {
		this.dppDateDaoTrans = dppDateDaoTrans;
	}

	@Column(name = "DPP_DATE_DAO_APPROB_DMP", length = 7)
	public Date getDppDateDaoApprobDmp() {
		return this.dppDateDaoApprobDmp;
	}

	public void setDppDateDaoApprobDmp(Date dppDateDaoApprobDmp) {
		this.dppDateDaoApprobDmp = dppDateDaoApprobDmp;
	}

	@Column(name = "DPP_DATE_DAO_APPROB_BAIL", length = 7)
	public Date getDppDateDaoApprobBail() {
		return this.dppDateDaoApprobBail;
	}

	public void setDppDateDaoApprobBail(Date dppDateDaoApprobBail) {
		this.dppDateDaoApprobBail = dppDateDaoApprobBail;
	}

	@Column(name = "DPP_DATE_AVIS_AO_PUBLICATION", length = 7)
	public Date getDppDateAvisAoPublication() {
		return this.dppDateAvisAoPublication;
	}

	public void setDppDateAvisAoPublication(Date dppDateAvisAoPublication) {
		this.dppDateAvisAoPublication = dppDateAvisAoPublication;
	}

	@Column(name = "DPP_DATE_OUVERT_OT", length = 7)
	public Date getDppDateOuvertOt() {
		return this.dppDateOuvertOt;
	}

	public void setDppDateOuvertOt(Date dppDateOuvertOt) {
		this.dppDateOuvertOt = dppDateOuvertOt;
	}

	@Column(name = "DPP_DATE_OUVERT_OF", length = 7)
	public Date getDppDateOuvertOf() {
		return this.dppDateOuvertOf;
	}

	public void setDppDateOuvertOf(Date dppDateOuvertOf) {
		this.dppDateOuvertOf = dppDateOuvertOf;
	}

	@Column(name = "DPP_DATE_ELAB_RAPPORT", length = 7)
	public Date getDppDateElabRapport() {
		return this.dppDateElabRapport;
	}

	public void setDppDateElabRapport(Date dppDateElabRapport) {
		this.dppDateElabRapport = dppDateElabRapport;
	}

	@Column(name = "DPP_DATE_JUGEMENT_OFFRE", length = 7)
	public Date getDppDateJugementOffre() {
		return this.dppDateJugementOffre;
	}

	public void setDppDateJugementOffre(Date dppDateJugementOffre) {
		this.dppDateJugementOffre = dppDateJugementOffre;
	}

	@Column(name = "DPP_DATE_ATT_APPROB_DMP", length = 7)
	public Date getDppDateAttApprobDmp() {
		return this.dppDateAttApprobDmp;
	}

	public void setDppDateAttApprobDmp(Date dppDateAttApprobDmp) {
		this.dppDateAttApprobDmp = dppDateAttApprobDmp;
	}

	@Column(name = "DPP_DATE_ATT_APPRO_BAIL", length = 7)
	public Date getDppDateAttApproBail() {
		return this.dppDateAttApproBail;
	}

	public void setDppDateAttApproBail(Date dppDateAttApproBail) {
		this.dppDateAttApproBail = dppDateAttApproBail;
	}

	@Column(name = "DPP_DATE_NEGOCIATION", length = 7)
	public Date getDppDateNegociation() {
		return this.dppDateNegociation;
	}

	public void setDppDateNegociation(Date dppDateNegociation) {
		this.dppDateNegociation = dppDateNegociation;
	}

	@Column(name = "DPP_DATE_SIGNAT_ATTRIB", length = 7)
	public Date getDppDateSignatAttrib() {
		return this.dppDateSignatAttrib;
	}

	public void setDppDateSignatAttrib(Date dppDateSignatAttrib) {
		this.dppDateSignatAttrib = dppDateSignatAttrib;
	}

	@Column(name = "DPP_DATE_SIGNAT_AC", length = 7)
	public Date getDppDateSignatAc() {
		return this.dppDateSignatAc;
	}

	public void setDppDateSignatAc(Date dppDateSignatAc) {
		this.dppDateSignatAc = dppDateSignatAc;
	}

	@Column(name = "DPP_DATE_MARCHE_APPROB", length = 7)
	public Date getDppDateMarcheApprob() {
		return this.dppDateMarcheApprob;
	}

	public void setDppDateMarcheApprob(Date dppDateMarcheApprob) {
		this.dppDateMarcheApprob = dppDateMarcheApprob;
	}

	@Column(name = "DPP_DATE_EXEC_DEBUT", length = 7)
	public Date getDppDateExecDebut() {
		return this.dppDateExecDebut;
	}

	public void setDppDateExecDebut(Date dppDateExecDebut) {
		this.dppDateExecDebut = dppDateExecDebut;
	}

	@Column(name = "DPP_DATE_EXEC_FIN", length = 7)
	public Date getDppDateExecFin() {
		return this.dppDateExecFin;
	}

	public void setDppDateExecFin(Date dppDateExecFin) {
		this.dppDateExecFin = dppDateExecFin;
	}

	@Column(name = "DPP_ACTEUR_SAISIE", length = 12)
	public String getDppActeurSaisie() {
		return this.dppActeurSaisie;
	}

	public void setDppActeurSaisie(String dppActeurSaisie) {
		this.dppActeurSaisie = dppActeurSaisie;
	}

	@Column(name = "DPP_STR_CODE", length = 20)
	public String getDppStrCode() {
		return this.dppStrCode;
	}

	public void setDppStrCode(String dppStrCode) {
		this.dppStrCode = dppStrCode;
	}

	@Column(name = "DPP_STATUT_RETOUR", length = 4)
	public String getDppStatutRetour() {
		return this.dppStatutRetour;
	}

	public void setDppStatutRetour(String dppStatutRetour) {
		this.dppStatutRetour = dppStatutRetour;
	}

	@Column(name = "DPP_DATE_SAISIE", length = 7)
	public Date getDppDateSaisie() {
		return this.dppDateSaisie;
	}

	public void setDppDateSaisie(Date dppDateSaisie) {
		this.dppDateSaisie = dppDateSaisie;
	}

	@Column(name = "DPP_STRUCTURE_CONDUC", length = 500)
	public String getDppStructureConduc() {
		return this.dppStructureConduc;
	}

	public void setDppStructureConduc(String dppStructureConduc) {
		this.dppStructureConduc = dppStructureConduc;
	}

	@Column(name = "DPP_STRUCTURE_BENEFI", length = 500)
	public String getDppStructureBenefi() {
		return this.dppStructureBenefi;
	}

	public void setDppStructureBenefi(String dppStructureBenefi) {
		this.dppStructureBenefi = dppStructureBenefi;
	}

	@Column(name = "DPP_PARTIE_PME_PMI", length = 1)
	public String getDppPartiePmePmi() {
		return this.dppPartiePmePmi;
	}

	public void setDppPartiePmePmi(String dppPartiePmePmi) {
		this.dppPartiePmePmi = dppPartiePmePmi;
	}

	@Column(name = "DPP_TYP_ID", length = 5)
	public String getDppTypId() {
		return this.dppTypId;
	}

	public void setDppTypId(String dppTypId) {
		this.dppTypId = dppTypId;
	}

	@Column(name = "DPP_STATUT_DAO", length = 2)
	public String getDppStatutDao() {
		return this.dppStatutDao;
	}

	public void setDppStatutDao(String dppStatutDao) {
		this.dppStatutDao = dppStatutDao;
	}

	@Column(name = "DPP_PIECE_DAO", length = 15)
	public String getDppPieceDao() {
		return this.dppPieceDao;
	}

	public void setDppPieceDao(String dppPieceDao) {
		this.dppPieceDao = dppPieceDao;
	}

	@Column(name = "DPP_DAC_CODE", length = 20)
	public String getDppDacCode() {
		return this.dppDacCode;
	}

	public void setDppDacCode(String dppDacCode) {
		this.dppDacCode = dppDacCode;
	}

	@Column(name = "DPP_INV_ENTRE", length = 7)
	public Date getDppInvEntre() {
		return this.dppInvEntre;
	}

	public void setDppInvEntre(Date dppInvEntre) {
		this.dppInvEntre = dppInvEntre;
	}

	@Column(name = "DPP_DATE_ATT_APPROB_CPMP", length = 7)
	public Date getDppDateAttApprobCpmp() {
		return this.dppDateAttApprobCpmp;
	}

	public void setDppDateAttApprobCpmp(Date dppDateAttApprobCpmp) {
		this.dppDateAttApprobCpmp = dppDateAttApprobCpmp;
	}

	@Column(name = "DPP_DATE_JUGEMENT_OFFRE_TEC", length = 7)
	public Date getDppDateJugementOffreTec() {
		return this.dppDateJugementOffreTec;
	}

	public void setDppDateJugementOffreTec(Date dppDateJugementOffreTec) {
		this.dppDateJugementOffreTec = dppDateJugementOffreTec;
	}

	@Column(name = "DPP_DATE_VAL_AC", length = 7)
	public Date getDppDateValAc() {
		return this.dppDateValAc;
	}

	public void setDppDateValAc(Date dppDateValAc) {
		this.dppDateValAc = dppDateValAc;
	}

	@Column(name = "DPP_DATE_VAL_CPMP", length = 7)
	public Date getDppDateValCpmp() {
		return this.dppDateValCpmp;
	}

	public void setDppDateValCpmp(Date dppDateValCpmp) {
		this.dppDateValCpmp = dppDateValCpmp;
	}

	@Column(name = "DPP_DATE_VAL_DMP", length = 7)
	public Date getDppDateValDmp() {
		return this.dppDateValDmp;
	}

	public void setDppDateValDmp(Date dppDateValDmp) {
		this.dppDateValDmp = dppDateValDmp;
	}

	@Column(name = "DPP_BAILLEUR", length = 1)
	public String getDppBailleur() {
		return this.dppBailleur;
	}

	public void setDppBailleur(String dppBailleur) {
		this.dppBailleur = dppBailleur;
	}

	@Column(name = "DPP_TYPE_FINANCE", length = 20)
	public String getDppTypeFinance() {
		return this.dppTypeFinance;
	}

	public void setDppTypeFinance(String dppTypeFinance) {
		this.dppTypeFinance = dppTypeFinance;
	}

	@Column(name = "DPP_APPROB_ANO", length = 7)
	public Date getDppApprobAno() {
		return this.dppApprobAno;
	}

	public void setDppApprobAno(Date dppApprobAno) {
		this.dppApprobAno = dppApprobAno;
	}

	@Column(name = "DPP_DTE_MODIF", length = 7)
	public Date getDppDteModif() {
		return this.dppDteModif;
	}

	public void setDppDteModif(Date dppDteModif) {
		this.dppDteModif = dppDteModif;
	}

}
