package com.sndi.model;
// Generated 4 févr. 2020 12:07:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VDetailDao generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_DETAIL_DAO")
public class VDetailDao implements java.io.Serializable {

	private String dacCode;
	private String dacObjet;
	private Date dacDteSaisi;
	private String dacStaCode;
	private String dacTymCode;
	private String dacMopCode;
	private long dacNbrOuv;
	private long dacGesCode;
	private String dacFonCodAc;
	private String dacStrCode;
	private String dacFonCodeCpmp;
	private Date dacDteValCpmp;
	private Date dacDteValDmp;
	private String dacTdCode;
	private Long dacDppId;
	private Date dacDateReception;
	private String dacStatutRetour;
	private String aaoCode;
	private String aaoLibelle;
	private String aaoDacCode;
	private Date aaoDteSaisi;
	private String aaoStaCode;
	private Date aaoDtePub;
	private Date aaoDteOuvTec;
	private Date aaoDteHeurOuv;
	private Date aaoDteOuvFin;
	private long aaoNbrLot;
	private long aaoNbrOuv;
	private long aaoDelaiVal;
	private String aaoFonCodAc;
	private String aaoFonCodeCpmp;
	private String aaoNatInt;
	private String aaoTaux;
	private String aaoLieuExe;
	private String aaoNomResp;
	private String aaoInterPub;
	private String aaoCautDefExig;
	private String aaoBompPub;
	private String aaoVenteParLot;
	private String aaoAvisBail;
	private long aaoMtCaut;
	private String aaoModePaiement;
	private long aaoCoutDac;
	private String aaoLieuRecep;
	private Date aaoDateRecep;
	private Date aaoHeureRecep;
	private long laaId;
	private String laaAaoCode;
	private String laaObjet;
	private String laaObservation;
	private long laaMtCaut;
	private long laaMtEst;
	private Date laaDteSaisi;
	private String laaStaCode;
	private String laaFonCodSaisi;
	private String laaFonCodCpmp;
	private String laaLieuExe;
	private String laaLbgImputation;
	private long laaNum;
	private long laaCoutLot;
	private long ddaId;
	private String ddaNom;
	private Date ddaDteSaisi;
	private String ddaStaCode;
	private String ddaDacCode;
	private long ddaPidCode;
	private String ddaReference;
	private String ddaCommentaire;
	private String tymLibelleCourt;
	private String mopLibelleLong;
	private String strCode;
	private String strLibelleCourt;
	private String strLibelleLong;
	private String minLibelle;
	private long plpGesCode;

	public VDetailDao() {
	}

	public VDetailDao(String dacCode, String aaoCode, long laaId, long ddaId, String tymLibelleCourt,
			String strCode, String strLibelleCourt, long plpGesCode) {
		this.dacCode = dacCode;
		this.aaoCode = aaoCode;
		this.laaId = laaId;
		this.ddaId = ddaId;
		this.tymLibelleCourt = tymLibelleCourt;
		this.strCode = strCode;
		this.strLibelleCourt = strLibelleCourt;
		this.plpGesCode = plpGesCode;
	}

	public VDetailDao(String dacCode, String dacObjet, Date dacDteSaisi, String dacStaCode, String dacTymCode,
			String dacMopCode, long dacNbrOuv, long dacGesCode, String dacFonCodAc, String dacStrCode,
			String dacFonCodeCpmp, Date dacDteValCpmp, Date dacDteValDmp, String dacTdCode, Long dacDppId,
			Date dacDateReception, String dacStatutRetour, String aaoCode, String aaoLibelle, String aaoDacCode,
			Date aaoDteSaisi, String aaoStaCode, Date aaoDtePub, Date aaoDteOuvTec, Date aaoDteHeurOuv,
			Date aaoDteOuvFin, long aaoNbrLot, long aaoNbrOuv, long aaoDelaiVal, String aaoFonCodAc,
			String aaoFonCodeCpmp, String aaoNatInt, String aaoTaux, String aaoLieuExe, String aaoNomResp,
			String aaoInterPub, String aaoCautDefExig, String aaoBompPub, String aaoVenteParLot, String aaoAvisBail,
			long aaoMtCaut, String aaoModePaiement, long aaoCoutDac, String aaoLieuRecep, Date aaoDateRecep,
			Date aaoHeureRecep, long laaId, String laaAaoCode, String laaObjet, String laaObservation,
			long laaMtCaut, long laaMtEst, Date laaDteSaisi, String laaStaCode, String laaFonCodSaisi,
			String laaFonCodCpmp, String laaLieuExe, String laaLbgImputation, long laaNum, long laaCoutLot,
			long ddaId, String ddaNom, Date ddaDteSaisi, String ddaStaCode, String ddaDacCode,
			long ddaPidCode, String ddaReference, String ddaCommentaire, String tymLibelleCourt,
			String mopLibelleLong, String strCode, String strLibelleCourt, String strLibelleLong, String minLibelle,
			long plpGesCode) {
		this.dacCode = dacCode;
		this.dacObjet = dacObjet;
		this.dacDteSaisi = dacDteSaisi;
		this.dacStaCode = dacStaCode;
		this.dacTymCode = dacTymCode;
		this.dacMopCode = dacMopCode;
		this.dacNbrOuv = dacNbrOuv;
		this.dacGesCode = dacGesCode;
		this.dacFonCodAc = dacFonCodAc;
		this.dacStrCode = dacStrCode;
		this.dacFonCodeCpmp = dacFonCodeCpmp;
		this.dacDteValCpmp = dacDteValCpmp;
		this.dacDteValDmp = dacDteValDmp;
		this.dacTdCode = dacTdCode;
		this.dacDppId = dacDppId;
		this.dacDateReception = dacDateReception;
		this.dacStatutRetour = dacStatutRetour;
		this.aaoCode = aaoCode;
		this.aaoLibelle = aaoLibelle;
		this.aaoDacCode = aaoDacCode;
		this.aaoDteSaisi = aaoDteSaisi;
		this.aaoStaCode = aaoStaCode;
		this.aaoDtePub = aaoDtePub;
		this.aaoDteOuvTec = aaoDteOuvTec;
		this.aaoDteHeurOuv = aaoDteHeurOuv;
		this.aaoDteOuvFin = aaoDteOuvFin;
		this.aaoNbrLot = aaoNbrLot;
		this.aaoNbrOuv = aaoNbrOuv;
		this.aaoDelaiVal = aaoDelaiVal;
		this.aaoFonCodAc = aaoFonCodAc;
		this.aaoFonCodeCpmp = aaoFonCodeCpmp;
		this.aaoNatInt = aaoNatInt;
		this.aaoTaux = aaoTaux;
		this.aaoLieuExe = aaoLieuExe;
		this.aaoNomResp = aaoNomResp;
		this.aaoInterPub = aaoInterPub;
		this.aaoCautDefExig = aaoCautDefExig;
		this.aaoBompPub = aaoBompPub;
		this.aaoVenteParLot = aaoVenteParLot;
		this.aaoAvisBail = aaoAvisBail;
		this.aaoMtCaut = aaoMtCaut;
		this.aaoModePaiement = aaoModePaiement;
		this.aaoCoutDac = aaoCoutDac;
		this.aaoLieuRecep = aaoLieuRecep;
		this.aaoDateRecep = aaoDateRecep;
		this.aaoHeureRecep = aaoHeureRecep;
		this.laaId = laaId;
		this.laaAaoCode = laaAaoCode;
		this.laaObjet = laaObjet;
		this.laaObservation = laaObservation;
		this.laaMtCaut = laaMtCaut;
		this.laaMtEst = laaMtEst;
		this.laaDteSaisi = laaDteSaisi;
		this.laaStaCode = laaStaCode;
		this.laaFonCodSaisi = laaFonCodSaisi;
		this.laaFonCodCpmp = laaFonCodCpmp;
		this.laaLieuExe = laaLieuExe;
		this.laaLbgImputation = laaLbgImputation;
		this.laaNum = laaNum;
		this.laaCoutLot = laaCoutLot;
		this.ddaId = ddaId;
		this.ddaNom = ddaNom;
		this.ddaDteSaisi = ddaDteSaisi;
		this.ddaStaCode = ddaStaCode;
		this.ddaDacCode = ddaDacCode;
		this.ddaPidCode = ddaPidCode;
		this.ddaReference = ddaReference;
		this.ddaCommentaire = ddaCommentaire;
		this.tymLibelleCourt = tymLibelleCourt;
		this.mopLibelleLong = mopLibelleLong;
		this.strCode = strCode;
		this.strLibelleCourt = strLibelleCourt;
		this.strLibelleLong = strLibelleLong;
		this.minLibelle = minLibelle;
		this.plpGesCode = plpGesCode;
	}

	
	@Id
	@Column(name = "DAC_CODE", nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "DAC_OBJET", length = 1000)
	public String getDacObjet() {
		return this.dacObjet;
	}

	public void setDacObjet(String dacObjet) {
		this.dacObjet = dacObjet;
	}

	@Column(name = "DAC_DTE_SAISI", length = 7)
	public Date getDacDteSaisi() {
		return this.dacDteSaisi;
	}

	public void setDacDteSaisi(Date dacDteSaisi) {
		this.dacDteSaisi = dacDteSaisi;
	}

	@Column(name = "DAC_STA_CODE", length = 3)
	public String getDacStaCode() {
		return this.dacStaCode;
	}

	public void setDacStaCode(String dacStaCode) {
		this.dacStaCode = dacStaCode;
	}

	@Column(name = "DAC_TYM_CODE", length = 5)
	public String getDacTymCode() {
		return this.dacTymCode;
	}

	public void setDacTymCode(String dacTymCode) {
		this.dacTymCode = dacTymCode;
	}

	@Column(name = "DAC_MOP_CODE", length = 3)
	public String getDacMopCode() {
		return this.dacMopCode;
	}

	public void setDacMopCode(String dacMopCode) {
		this.dacMopCode = dacMopCode;
	}

	@Column(name = "DAC_NBR_OUV", precision = 22, scale = 0)
	public long getDacNbrOuv() {
		return this.dacNbrOuv;
	}

	public void setDacNbrOuv(long dacNbrOuv) {
		this.dacNbrOuv = dacNbrOuv;
	}

	@Column(name = "DAC_GES_CODE", precision = 22, scale = 0)
	public long getDacGesCode() {
		return this.dacGesCode;
	}

	public void setDacGesCode(long dacGesCode) {
		this.dacGesCode = dacGesCode;
	}

	@Column(name = "DAC_FON_COD_AC", length = 12)
	public String getDacFonCodAc() {
		return this.dacFonCodAc;
	}

	public void setDacFonCodAc(String dacFonCodAc) {
		this.dacFonCodAc = dacFonCodAc;
	}

	@Column(name = "DAC_STR_CODE", length = 3)
	public String getDacStrCode() {
		return this.dacStrCode;
	}

	public void setDacStrCode(String dacStrCode) {
		this.dacStrCode = dacStrCode;
	}

	@Column(name = "DAC_FON_CODE_CPMP", length = 12)
	public String getDacFonCodeCpmp() {
		return this.dacFonCodeCpmp;
	}

	public void setDacFonCodeCpmp(String dacFonCodeCpmp) {
		this.dacFonCodeCpmp = dacFonCodeCpmp;
	}

	@Column(name = "DAC_DTE_VAL_CPMP", length = 7)
	public Date getDacDteValCpmp() {
		return this.dacDteValCpmp;
	}

	public void setDacDteValCpmp(Date dacDteValCpmp) {
		this.dacDteValCpmp = dacDteValCpmp;
	}

	@Column(name = "DAC_DTE_VAL_DMP", length = 7)
	public Date getDacDteValDmp() {
		return this.dacDteValDmp;
	}

	public void setDacDteValDmp(Date dacDteValDmp) {
		this.dacDteValDmp = dacDteValDmp;
	}

	@Column(name = "DAC_TD_CODE", length = 3)
	public String getDacTdCode() {
		return this.dacTdCode;
	}

	public void setDacTdCode(String dacTdCode) {
		this.dacTdCode = dacTdCode;
	}

	@Column(name = "DAC_DPP_ID", precision = 10, scale = 0)
	public Long getDacDppId() {
		return this.dacDppId;
	}

	public void setDacDppId(Long dacDppId) {
		this.dacDppId = dacDppId;
	}

	@Column(name = "DAC_DATE_RECEPTION", length = 7)
	public Date getDacDateReception() {
		return this.dacDateReception;
	}

	public void setDacDateReception(Date dacDateReception) {
		this.dacDateReception = dacDateReception;
	}

	@Column(name = "DAC_STATUT_RETOUR", length = 2)
	public String getDacStatutRetour() {
		return this.dacStatutRetour;
	}

	public void setDacStatutRetour(String dacStatutRetour) {
		this.dacStatutRetour = dacStatutRetour;
	}

	@Column(name = "AAO_CODE", nullable = false, length = 20)
	public String getAaoCode() {
		return this.aaoCode;
	}

	public void setAaoCode(String aaoCode) {
		this.aaoCode = aaoCode;
	}

	@Column(name = "AAO_LIBELLE", length = 1000)
	public String getAaoLibelle() {
		return this.aaoLibelle;
	}

	public void setAaoLibelle(String aaoLibelle) {
		this.aaoLibelle = aaoLibelle;
	}

	@Column(name = "AAO_DAC_CODE", length = 20)
	public String getAaoDacCode() {
		return this.aaoDacCode;
	}

	public void setAaoDacCode(String aaoDacCode) {
		this.aaoDacCode = aaoDacCode;
	}

	@Column(name = "AAO_DTE_SAISI", length = 7)
	public Date getAaoDteSaisi() {
		return this.aaoDteSaisi;
	}

	public void setAaoDteSaisi(Date aaoDteSaisi) {
		this.aaoDteSaisi = aaoDteSaisi;
	}

	@Column(name = "AAO_STA_CODE", length = 3)
	public String getAaoStaCode() {
		return this.aaoStaCode;
	}

	public void setAaoStaCode(String aaoStaCode) {
		this.aaoStaCode = aaoStaCode;
	}

	@Column(name = "AAO_DTE_PUB", length = 7)
	public Date getAaoDtePub() {
		return this.aaoDtePub;
	}

	public void setAaoDtePub(Date aaoDtePub) {
		this.aaoDtePub = aaoDtePub;
	}

	@Column(name = "AAO_DTE_OUV_TEC", length = 7)
	public Date getAaoDteOuvTec() {
		return this.aaoDteOuvTec;
	}

	public void setAaoDteOuvTec(Date aaoDteOuvTec) {
		this.aaoDteOuvTec = aaoDteOuvTec;
	}

	@Column(name = "AAO_DTE_HEUR_OUV", length = 7)
	public Date getAaoDteHeurOuv() {
		return this.aaoDteHeurOuv;
	}

	public void setAaoDteHeurOuv(Date aaoDteHeurOuv) {
		this.aaoDteHeurOuv = aaoDteHeurOuv;
	}

	@Column(name = "AAO_DTE_OUV_FIN", length = 7)
	public Date getAaoDteOuvFin() {
		return this.aaoDteOuvFin;
	}

	public void setAaoDteOuvFin(Date aaoDteOuvFin) {
		this.aaoDteOuvFin = aaoDteOuvFin;
	}

	@Column(name = "AAO_NBR_LOT", precision = 22, scale = 0)
	public long getAaoNbrLot() {
		return this.aaoNbrLot;
	}

	public void setAaoNbrLot(long aaoNbrLot) {
		this.aaoNbrLot = aaoNbrLot;
	}

	@Column(name = "AAO_NBR_OUV", precision = 22, scale = 0)
	public long getAaoNbrOuv() {
		return this.aaoNbrOuv;
	}

	public void setAaoNbrOuv(long aaoNbrOuv) {
		this.aaoNbrOuv = aaoNbrOuv;
	}

	@Column(name = "AAO_DELAI_VAL", precision = 22, scale = 0)
	public long getAaoDelaiVal() {
		return this.aaoDelaiVal;
	}

	public void setAaoDelaiVal(long aaoDelaiVal) {
		this.aaoDelaiVal = aaoDelaiVal;
	}

	@Column(name = "AAO_FON_COD_AC", length = 12)
	public String getAaoFonCodAc() {
		return this.aaoFonCodAc;
	}

	public void setAaoFonCodAc(String aaoFonCodAc) {
		this.aaoFonCodAc = aaoFonCodAc;
	}

	@Column(name = "AAO_FON_CODE_CPMP", length = 12)
	public String getAaoFonCodeCpmp() {
		return this.aaoFonCodeCpmp;
	}

	public void setAaoFonCodeCpmp(String aaoFonCodeCpmp) {
		this.aaoFonCodeCpmp = aaoFonCodeCpmp;
	}

	@Column(name = "AAO_NAT_INT", length = 1)
	public String getAaoNatInt() {
		return this.aaoNatInt;
	}

	public void setAaoNatInt(String aaoNatInt) {
		this.aaoNatInt = aaoNatInt;
	}

	@Column(name = "AAO_TAUX", length = 3)
	public String getAaoTaux() {
		return this.aaoTaux;
	}

	public void setAaoTaux(String aaoTaux) {
		this.aaoTaux = aaoTaux;
	}

	@Column(name = "AAO_LIEU_EXE", length = 200)
	public String getAaoLieuExe() {
		return this.aaoLieuExe;
	}

	public void setAaoLieuExe(String aaoLieuExe) {
		this.aaoLieuExe = aaoLieuExe;
	}

	@Column(name = "AAO_NOM_RESP", length = 200)
	public String getAaoNomResp() {
		return this.aaoNomResp;
	}

	public void setAaoNomResp(String aaoNomResp) {
		this.aaoNomResp = aaoNomResp;
	}

	@Column(name = "AAO_INTER_PUB", length = 1)
	public String getAaoInterPub() {
		return this.aaoInterPub;
	}

	public void setAaoInterPub(String aaoInterPub) {
		this.aaoInterPub = aaoInterPub;
	}

	@Column(name = "AAO_CAUT_DEF_EXIG", length = 1)
	public String getAaoCautDefExig() {
		return this.aaoCautDefExig;
	}

	public void setAaoCautDefExig(String aaoCautDefExig) {
		this.aaoCautDefExig = aaoCautDefExig;
	}

	@Column(name = "AAO_BOMP_PUB", length = 1)
	public String getAaoBompPub() {
		return this.aaoBompPub;
	}

	public void setAaoBompPub(String aaoBompPub) {
		this.aaoBompPub = aaoBompPub;
	}

	@Column(name = "AAO_VENTE_PAR_LOT", length = 1)
	public String getAaoVenteParLot() {
		return this.aaoVenteParLot;
	}

	public void setAaoVenteParLot(String aaoVenteParLot) {
		this.aaoVenteParLot = aaoVenteParLot;
	}

	@Column(name = "AAO_AVIS_BAIL", length = 1)
	public String getAaoAvisBail() {
		return this.aaoAvisBail;
	}

	public void setAaoAvisBail(String aaoAvisBail) {
		this.aaoAvisBail = aaoAvisBail;
	}

	@Column(name = "AAO_MT_CAUT", precision = 22, scale = 0)
	public long getAaoMtCaut() {
		return this.aaoMtCaut;
	}

	public void setAaoMtCaut(long aaoMtCaut) {
		this.aaoMtCaut = aaoMtCaut;
	}

	@Column(name = "AAO_MODE_PAIEMENT", length = 20)
	public String getAaoModePaiement() {
		return this.aaoModePaiement;
	}

	public void setAaoModePaiement(String aaoModePaiement) {
		this.aaoModePaiement = aaoModePaiement;
	}

	@Column(name = "AAO_COUT_DAC", precision = 22, scale = 0)
	public long getAaoCoutDac() {
		return this.aaoCoutDac;
	}

	public void setAaoCoutDac(long aaoCoutDac) {
		this.aaoCoutDac = aaoCoutDac;
	}

	@Column(name = "AAO_LIEU_RECEP", length = 1000)
	public String getAaoLieuRecep() {
		return this.aaoLieuRecep;
	}

	public void setAaoLieuRecep(String aaoLieuRecep) {
		this.aaoLieuRecep = aaoLieuRecep;
	}

	@Column(name = "AAO_DATE_RECEP", length = 7)
	public Date getAaoDateRecep() {
		return this.aaoDateRecep;
	}

	public void setAaoDateRecep(Date aaoDateRecep) {
		this.aaoDateRecep = aaoDateRecep;
	}

	@Column(name = "AAO_HEURE_RECEP", length = 7)
	public Date getAaoHeureRecep() {
		return this.aaoHeureRecep;
	}

	public void setAaoHeureRecep(Date aaoHeureRecep) {
		this.aaoHeureRecep = aaoHeureRecep;
	}

	@Column(name = "LAA_ID", nullable = false, precision = 22, scale = 0)
	public long getLaaId() {
		return this.laaId;
	}

	public void setLaaId(long laaId) {
		this.laaId = laaId;
	}

	@Column(name = "LAA_AAO_CODE", length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "LAA_OBJET", length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "LAA_OBSERVATION", length = 200)
	public String getLaaObservation() {
		return this.laaObservation;
	}

	public void setLaaObservation(String laaObservation) {
		this.laaObservation = laaObservation;
	}

	@Column(name = "LAA_MT_CAUT", precision = 22, scale = 0)
	public long getLaaMtCaut() {
		return this.laaMtCaut;
	}

	public void setLaaMtCaut(long laaMtCaut) {
		this.laaMtCaut = laaMtCaut;
	}

	@Column(name = "LAA_MT_EST", precision = 22, scale = 0)
	public long getLaaMtEst() {
		return this.laaMtEst;
	}

	public void setLaaMtEst(long laaMtEst) {
		this.laaMtEst = laaMtEst;
	}

	@Column(name = "LAA_DTE_SAISI", length = 7)
	public Date getLaaDteSaisi() {
		return this.laaDteSaisi;
	}

	public void setLaaDteSaisi(Date laaDteSaisi) {
		this.laaDteSaisi = laaDteSaisi;
	}

	@Column(name = "LAA_STA_CODE", length = 3)
	public String getLaaStaCode() {
		return this.laaStaCode;
	}

	public void setLaaStaCode(String laaStaCode) {
		this.laaStaCode = laaStaCode;
	}

	@Column(name = "LAA_FON_COD_SAISI", length = 20)
	public String getLaaFonCodSaisi() {
		return this.laaFonCodSaisi;
	}

	public void setLaaFonCodSaisi(String laaFonCodSaisi) {
		this.laaFonCodSaisi = laaFonCodSaisi;
	}

	@Column(name = "LAA_FON_COD_CPMP", length = 20)
	public String getLaaFonCodCpmp() {
		return this.laaFonCodCpmp;
	}

	public void setLaaFonCodCpmp(String laaFonCodCpmp) {
		this.laaFonCodCpmp = laaFonCodCpmp;
	}

	@Column(name = "LAA_LIEU_EXE", length = 1000)
	public String getLaaLieuExe() {
		return this.laaLieuExe;
	}

	public void setLaaLieuExe(String laaLieuExe) {
		this.laaLieuExe = laaLieuExe;
	}

	@Column(name = "LAA_LBG_IMPUTATION", length = 50)
	public String getLaaLbgImputation() {
		return this.laaLbgImputation;
	}

	public void setLaaLbgImputation(String laaLbgImputation) {
		this.laaLbgImputation = laaLbgImputation;
	}

	@Column(name = "LAA_NUM", precision = 22, scale = 0)
	public long getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(long laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_COUT_LOT", precision = 22, scale = 0)
	public long getLaaCoutLot() {
		return this.laaCoutLot;
	}

	public void setLaaCoutLot(long laaCoutLot) {
		this.laaCoutLot = laaCoutLot;
	}

	@Column(name = "DDA_ID", nullable = false, precision = 22, scale = 0)
	public long getDdaId() {
		return this.ddaId;
	}

	public void setDdaId(long ddaId) {
		this.ddaId = ddaId;
	}

	@Column(name = "DDA_NOM", length = 200)
	public String getDdaNom() {
		return this.ddaNom;
	}

	public void setDdaNom(String ddaNom) {
		this.ddaNom = ddaNom;
	}

	@Column(name = "DDA_DTE_SAISI", length = 7)
	public Date getDdaDteSaisi() {
		return this.ddaDteSaisi;
	}

	public void setDdaDteSaisi(Date ddaDteSaisi) {
		this.ddaDteSaisi = ddaDteSaisi;
	}

	@Column(name = "DDA_STA_CODE", length = 3)
	public String getDdaStaCode() {
		return this.ddaStaCode;
	}

	public void setDdaStaCode(String ddaStaCode) {
		this.ddaStaCode = ddaStaCode;
	}

	@Column(name = "DDA_DAC_CODE", length = 20)
	public String getDdaDacCode() {
		return this.ddaDacCode;
	}

	public void setDdaDacCode(String ddaDacCode) {
		this.ddaDacCode = ddaDacCode;
	}

	@Column(name = "DDA_PID_CODE", precision = 22, scale = 0)
	public long getDdaPidCode() {
		return this.ddaPidCode;
	}

	public void setDdaPidCode(long ddaPidCode) {
		this.ddaPidCode = ddaPidCode;
	}

	@Column(name = "DDA_REFERENCE", length = 500)
	public String getDdaReference() {
		return this.ddaReference;
	}

	public void setDdaReference(String ddaReference) {
		this.ddaReference = ddaReference;
	}

	@Column(name = "DDA_COMMENTAIRE", length = 500)
	public String getDdaCommentaire() {
		return this.ddaCommentaire;
	}

	public void setDdaCommentaire(String ddaCommentaire) {
		this.ddaCommentaire = ddaCommentaire;
	}

	@Column(name = "TYM_LIBELLE_COURT", nullable = false, length = 500)
	public String getTymLibelleCourt() {
		return this.tymLibelleCourt;
	}

	public void setTymLibelleCourt(String tymLibelleCourt) {
		this.tymLibelleCourt = tymLibelleCourt;
	}

	@Column(name = "MOP_LIBELLE_LONG", length = 1000)
	public String getMopLibelleLong() {
		return this.mopLibelleLong;
	}

	public void setMopLibelleLong(String mopLibelleLong) {
		this.mopLibelleLong = mopLibelleLong;
	}

	@Column(name = "STR_CODE", nullable = false, length = 3)
	public String getStrCode() {
		return this.strCode;
	}

	public void setStrCode(String strCode) {
		this.strCode = strCode;
	}

	@Column(name = "STR_LIBELLE_COURT", nullable = false, length = 500)
	public String getStrLibelleCourt() {
		return this.strLibelleCourt;
	}

	public void setStrLibelleCourt(String strLibelleCourt) {
		this.strLibelleCourt = strLibelleCourt;
	}

	@Column(name = "STR_LIBELLE_LONG", length = 1000)
	public String getStrLibelleLong() {
		return this.strLibelleLong;
	}

	public void setStrLibelleLong(String strLibelleLong) {
		this.strLibelleLong = strLibelleLong;
	}

	@Column(name = "MIN_LIBELLE", length = 1000)
	public String getMinLibelle() {
		return this.minLibelle;
	}

	public void setMinLibelle(String minLibelle) {
		this.minLibelle = minLibelle;
	}

	@Column(name = "PLP_GES_CODE", nullable = false, precision = 4, scale = 0)
	public long getPlpGesCode() {
		return this.plpGesCode;
	}

	public void setPlpGesCode(long plpGesCode) {
		this.plpGesCode = plpGesCode;
	}

}
