package com.sndi.model;
// Generated 9 juil. 2020 10:03:16 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VDetTabBordAgpm generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_DET_TAB_BORD_AGPM")
public class VDetTabBordAgpm implements java.io.Serializable {

	private BigDecimal agpmDetid;
	private String codeAc;
	private BigDecimal saisi;
	private BigDecimal transAc;
	private BigDecimal valPf;
	private BigDecimal difPf;
	private BigDecimal valDmp;
	private BigDecimal difDmp;
	private BigDecimal pub;
	private BigDecimal agpmSaisi;
	private BigDecimal agpmTransAc;
	private BigDecimal agpmValPf;
	private BigDecimal agpmDifPf;
	private BigDecimal agpmValDmp;
	private BigDecimal agpmDifDmp;
	private String typ;
	private String typProc;
	private String typDac;
	private BigDecimal agpmPub;
	private String codePf;
	private long agpId;
	private String agpStrCode;
	private String agpFonCod;
	private short agpGesCode;
	private String agpStaCode;
	private long agpProId;
	private Long agpDecId;
	private String agpCommentaire;
	private String agpTypeDao;
	private String agpModePassation;
	private String agpActif;
	private String agpStatutRetour;
	private String agpActeurSaisie;
	private Date agpDateValAc;
	private Date agpDateValCpmp;
	private Date agpDateValDmp;
	private String agpCode;
	private Date agpDteModif;
	private String agpFonCodPf;
	private String agpFonCodDmp;
	private String agpRecherche;
	private String finNumeroAccord;
	private String proTitre;
	private String baiLibelle;
	private String fonctionAc;
	private String decOrganExecLibelle;
	private String minLibelleCourt;
	private String strTstCode;
	private Long finId;
	private long proId;
	private Long decId;

	public VDetTabBordAgpm() {
	}

	public VDetTabBordAgpm(String codePf, long agpId, String agpStrCode, String agpFonCod, short agpGesCode,
			String agpStaCode, long agpProId, String proTitre, long proId) {
		this.codePf = codePf;
		this.agpId = agpId;
		this.agpStrCode = agpStrCode;
		this.agpFonCod = agpFonCod;
		this.agpGesCode = agpGesCode;
		this.agpStaCode = agpStaCode;
		this.agpProId = agpProId;
		this.proTitre = proTitre;
		this.proId = proId;
	}

	public VDetTabBordAgpm(BigDecimal agpmDetid, String codeAc, BigDecimal saisi, BigDecimal transAc,
			BigDecimal valPf, BigDecimal difPf, BigDecimal valDmp, BigDecimal difDmp, BigDecimal pub,
			BigDecimal agpmSaisi, BigDecimal agpmTransAc, BigDecimal agpmValPf, BigDecimal agpmDifPf,
			BigDecimal agpmValDmp, BigDecimal agpmDifDmp, String typ, String typProc, String typDac, BigDecimal agpmPub,
			String codePf, long agpId, String agpStrCode, String agpFonCod, short agpGesCode, String agpStaCode,
			long agpProId, Long agpDecId, String agpCommentaire, String agpTypeDao, String agpModePassation,
			String agpActif, String agpStatutRetour, String agpActeurSaisie, Date agpDateValAc, Date agpDateValCpmp,
			Date agpDateValDmp, String agpCode, Date agpDteModif, String agpFonCodPf, String agpFonCodDmp,
			String agpRecherche, String finNumeroAccord, String proTitre, String baiLibelle, String fonctionAc,
			String decOrganExecLibelle, String minLibelleCourt, String strTstCode, Long finId, long proId, Long decId) {
		this.agpmDetid = agpmDetid;
		this.codeAc = codeAc;
		this.saisi = saisi;
		this.transAc = transAc;
		this.valPf = valPf;
		this.difPf = difPf;
		this.valDmp = valDmp;
		this.difDmp = difDmp;
		this.pub = pub;
		this.agpmSaisi = agpmSaisi;
		this.agpmTransAc = agpmTransAc;
		this.agpmValPf = agpmValPf;
		this.agpmDifPf = agpmDifPf;
		this.agpmValDmp = agpmValDmp;
		this.agpmDifDmp = agpmDifDmp;
		this.typ = typ;
		this.typProc = typProc;
		this.typDac = typDac;
		this.agpmPub = agpmPub;
		this.codePf = codePf;
		this.agpId = agpId;
		this.agpStrCode = agpStrCode;
		this.agpFonCod = agpFonCod;
		this.agpGesCode = agpGesCode;
		this.agpStaCode = agpStaCode;
		this.agpProId = agpProId;
		this.agpDecId = agpDecId;
		this.agpCommentaire = agpCommentaire;
		this.agpTypeDao = agpTypeDao;
		this.agpModePassation = agpModePassation;
		this.agpActif = agpActif;
		this.agpStatutRetour = agpStatutRetour;
		this.agpActeurSaisie = agpActeurSaisie;
		this.agpDateValAc = agpDateValAc;
		this.agpDateValCpmp = agpDateValCpmp;
		this.agpDateValDmp = agpDateValDmp;
		this.agpCode = agpCode;
		this.agpDteModif = agpDteModif;
		this.agpFonCodPf = agpFonCodPf;
		this.agpFonCodDmp = agpFonCodDmp;
		this.agpRecherche = agpRecherche;
		this.finNumeroAccord = finNumeroAccord;
		this.proTitre = proTitre;
		this.baiLibelle = baiLibelle;
		this.fonctionAc = fonctionAc;
		this.decOrganExecLibelle = decOrganExecLibelle;
		this.minLibelleCourt = minLibelleCourt;
		this.strTstCode = strTstCode;
		this.finId = finId;
		this.proId = proId;
		this.decId = decId;
	}

	@Id
	@Column(name = "AGPM_DETID", precision = 22, scale = 0)
	public BigDecimal getAgpmDetid() {
		return this.agpmDetid;
	}

	public void setAgpmDetid(BigDecimal agpmDetid) {
		this.agpmDetid = agpmDetid;
	}

	@Column(name = "CODE_AC", length = 12)
	public String getCodeAc() {
		return this.codeAc;
	}

	public void setCodeAc(String codeAc) {
		this.codeAc = codeAc;
	}

	@Column(name = "SAISI", precision = 22, scale = 0)
	public BigDecimal getSaisi() {
		return this.saisi;
	}

	public void setSaisi(BigDecimal saisi) {
		this.saisi = saisi;
	}

	@Column(name = "TRANS_AC", precision = 22, scale = 0)
	public BigDecimal getTransAc() {
		return this.transAc;
	}

	public void setTransAc(BigDecimal transAc) {
		this.transAc = transAc;
	}

	@Column(name = "VAL_PF", precision = 22, scale = 0)
	public BigDecimal getValPf() {
		return this.valPf;
	}

	public void setValPf(BigDecimal valPf) {
		this.valPf = valPf;
	}

	@Column(name = "DIF_PF", precision = 22, scale = 0)
	public BigDecimal getDifPf() {
		return this.difPf;
	}

	public void setDifPf(BigDecimal difPf) {
		this.difPf = difPf;
	}

	@Column(name = "VAL_DMP", precision = 22, scale = 0)
	public BigDecimal getValDmp() {
		return this.valDmp;
	}

	public void setValDmp(BigDecimal valDmp) {
		this.valDmp = valDmp;
	}

	@Column(name = "DIF_DMP", precision = 22, scale = 0)
	public BigDecimal getDifDmp() {
		return this.difDmp;
	}

	public void setDifDmp(BigDecimal difDmp) {
		this.difDmp = difDmp;
	}

	@Column(name = "PUB", precision = 22, scale = 0)
	public BigDecimal getPub() {
		return this.pub;
	}

	public void setPub(BigDecimal pub) {
		this.pub = pub;
	}

	@Column(name = "AGPM_SAISI", precision = 22, scale = 0)
	public BigDecimal getAgpmSaisi() {
		return this.agpmSaisi;
	}

	public void setAgpmSaisi(BigDecimal agpmSaisi) {
		this.agpmSaisi = agpmSaisi;
	}

	@Column(name = "AGPM_TRANS_AC", precision = 22, scale = 0)
	public BigDecimal getAgpmTransAc() {
		return this.agpmTransAc;
	}

	public void setAgpmTransAc(BigDecimal agpmTransAc) {
		this.agpmTransAc = agpmTransAc;
	}

	@Column(name = "AGPM_VAL_PF", precision = 22, scale = 0)
	public BigDecimal getAgpmValPf() {
		return this.agpmValPf;
	}

	public void setAgpmValPf(BigDecimal agpmValPf) {
		this.agpmValPf = agpmValPf;
	}

	@Column(name = "AGPM_DIF_PF", precision = 22, scale = 0)
	public BigDecimal getAgpmDifPf() {
		return this.agpmDifPf;
	}

	public void setAgpmDifPf(BigDecimal agpmDifPf) {
		this.agpmDifPf = agpmDifPf;
	}

	@Column(name = "AGPM_VAL_DMP", precision = 22, scale = 0)
	public BigDecimal getAgpmValDmp() {
		return this.agpmValDmp;
	}

	public void setAgpmValDmp(BigDecimal agpmValDmp) {
		this.agpmValDmp = agpmValDmp;
	}

	@Column(name = "AGPM_DIF_DMP", precision = 22, scale = 0)
	public BigDecimal getAgpmDifDmp() {
		return this.agpmDifDmp;
	}

	public void setAgpmDifDmp(BigDecimal agpmDifDmp) {
		this.agpmDifDmp = agpmDifDmp;
	}

	@Column(name = "TYP", length = 4)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Column(name = "TYP_PROC", length = 2)
	public String getTypProc() {
		return this.typProc;
	}

	public void setTypProc(String typProc) {
		this.typProc = typProc;
	}

	@Column(name = "TYP_DAC", length = 3)
	public String getTypDac() {
		return this.typDac;
	}

	public void setTypDac(String typDac) {
		this.typDac = typDac;
	}

	@Column(name = "AGPM_PUB", precision = 22, scale = 0)
	public BigDecimal getAgpmPub() {
		return this.agpmPub;
	}

	public void setAgpmPub(BigDecimal agpmPub) {
		this.agpmPub = agpmPub;
	}

	@Column(name = "CODE_PF", nullable = false, length = 20)
	public String getCodePf() {
		return this.codePf;
	}

	public void setCodePf(String codePf) {
		this.codePf = codePf;
	}

	@Column(name = "AGP_ID", nullable = false, precision = 10, scale = 0)
	public long getAgpId() {
		return this.agpId;
	}

	public void setAgpId(long agpId) {
		this.agpId = agpId;
	}

	@Column(name = "AGP_STR_CODE", nullable = false, length = 20)
	public String getAgpStrCode() {
		return this.agpStrCode;
	}

	public void setAgpStrCode(String agpStrCode) {
		this.agpStrCode = agpStrCode;
	}

	@Column(name = "AGP_FON_COD", nullable = false, length = 20)
	public String getAgpFonCod() {
		return this.agpFonCod;
	}

	public void setAgpFonCod(String agpFonCod) {
		this.agpFonCod = agpFonCod;
	}

	@Column(name = "AGP_GES_CODE", nullable = false, precision = 4, scale = 0)
	public short getAgpGesCode() {
		return this.agpGesCode;
	}

	public void setAgpGesCode(short agpGesCode) {
		this.agpGesCode = agpGesCode;
	}

	@Column(name = "AGP_STA_CODE", nullable = false, length = 3)
	public String getAgpStaCode() {
		return this.agpStaCode;
	}

	public void setAgpStaCode(String agpStaCode) {
		this.agpStaCode = agpStaCode;
	}

	@Column(name = "AGP_PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getAgpProId() {
		return this.agpProId;
	}

	public void setAgpProId(long agpProId) {
		this.agpProId = agpProId;
	}

	@Column(name = "AGP_DEC_ID", precision = 10, scale = 0)
	public Long getAgpDecId() {
		return this.agpDecId;
	}

	public void setAgpDecId(Long agpDecId) {
		this.agpDecId = agpDecId;
	}

	@Column(name = "AGP_COMMENTAIRE", length = 1000)
	public String getAgpCommentaire() {
		return this.agpCommentaire;
	}

	public void setAgpCommentaire(String agpCommentaire) {
		this.agpCommentaire = agpCommentaire;
	}

	@Column(name = "AGP_TYPE_DAO", length = 1000)
	public String getAgpTypeDao() {
		return this.agpTypeDao;
	}

	public void setAgpTypeDao(String agpTypeDao) {
		this.agpTypeDao = agpTypeDao;
	}

	@Column(name = "AGP_MODE_PASSATION", length = 1000)
	public String getAgpModePassation() {
		return this.agpModePassation;
	}

	public void setAgpModePassation(String agpModePassation) {
		this.agpModePassation = agpModePassation;
	}

	@Column(name = "AGP_ACTIF", length = 1)
	public String getAgpActif() {
		return this.agpActif;
	}

	public void setAgpActif(String agpActif) {
		this.agpActif = agpActif;
	}

	@Column(name = "AGP_STATUT_RETOUR", length = 2)
	public String getAgpStatutRetour() {
		return this.agpStatutRetour;
	}

	public void setAgpStatutRetour(String agpStatutRetour) {
		this.agpStatutRetour = agpStatutRetour;
	}

	@Column(name = "AGP_ACTEUR_SAISIE", length = 12)
	public String getAgpActeurSaisie() {
		return this.agpActeurSaisie;
	}

	public void setAgpActeurSaisie(String agpActeurSaisie) {
		this.agpActeurSaisie = agpActeurSaisie;
	}

	@Column(name = "AGP_DATE_VAL_AC", length = 7)
	public Date getAgpDateValAc() {
		return this.agpDateValAc;
	}

	public void setAgpDateValAc(Date agpDateValAc) {
		this.agpDateValAc = agpDateValAc;
	}

	@Column(name = "AGP_DATE_VAL_CPMP", length = 7)
	public Date getAgpDateValCpmp() {
		return this.agpDateValCpmp;
	}

	public void setAgpDateValCpmp(Date agpDateValCpmp) {
		this.agpDateValCpmp = agpDateValCpmp;
	}

	@Column(name = "AGP_DATE_VAL_DMP", length = 7)
	public Date getAgpDateValDmp() {
		return this.agpDateValDmp;
	}

	public void setAgpDateValDmp(Date agpDateValDmp) {
		this.agpDateValDmp = agpDateValDmp;
	}

	@Column(name = "AGP_CODE", length = 50)
	public String getAgpCode() {
		return this.agpCode;
	}

	public void setAgpCode(String agpCode) {
		this.agpCode = agpCode;
	}

	@Column(name = "AGP_DTE_MODIF", length = 7)
	public Date getAgpDteModif() {
		return this.agpDteModif;
	}

	public void setAgpDteModif(Date agpDteModif) {
		this.agpDteModif = agpDteModif;
	}

	@Column(name = "AGP_FON_COD_PF", length = 20)
	public String getAgpFonCodPf() {
		return this.agpFonCodPf;
	}

	public void setAgpFonCodPf(String agpFonCodPf) {
		this.agpFonCodPf = agpFonCodPf;
	}

	@Column(name = "AGP_FON_COD_DMP", length = 20)
	public String getAgpFonCodDmp() {
		return this.agpFonCodDmp;
	}

	public void setAgpFonCodDmp(String agpFonCodDmp) {
		this.agpFonCodDmp = agpFonCodDmp;
	}

	@Column(name = "AGP_RECHERCHE", length = 4000)
	public String getAgpRecherche() {
		return this.agpRecherche;
	}

	public void setAgpRecherche(String agpRecherche) {
		this.agpRecherche = agpRecherche;
	}

	@Column(name = "FIN_NUMERO_ACCORD", length = 500)
	public String getFinNumeroAccord() {
		return this.finNumeroAccord;
	}

	public void setFinNumeroAccord(String finNumeroAccord) {
		this.finNumeroAccord = finNumeroAccord;
	}

	@Column(name = "PRO_TITRE", nullable = false, length = 500)
	public String getProTitre() {
		return this.proTitre;
	}

	public void setProTitre(String proTitre) {
		this.proTitre = proTitre;
	}

	@Column(name = "BAI_LIBELLE", length = 1000)
	public String getBaiLibelle() {
		return this.baiLibelle;
	}

	public void setBaiLibelle(String baiLibelle) {
		this.baiLibelle = baiLibelle;
	}

	@Column(name = "FONCTION_AC", length = 523)
	public String getFonctionAc() {
		return this.fonctionAc;
	}

	public void setFonctionAc(String fonctionAc) {
		this.fonctionAc = fonctionAc;
	}

	@Column(name = "DEC_ORGAN_EXEC_LIBELLE", length = 500)
	public String getDecOrganExecLibelle() {
		return this.decOrganExecLibelle;
	}

	public void setDecOrganExecLibelle(String decOrganExecLibelle) {
		this.decOrganExecLibelle = decOrganExecLibelle;
	}

	@Column(name = "MIN_LIBELLE_COURT", length = 500)
	public String getMinLibelleCourt() {
		return this.minLibelleCourt;
	}

	public void setMinLibelleCourt(String minLibelleCourt) {
		this.minLibelleCourt = minLibelleCourt;
	}

	@Column(name = "STR_TST_CODE", length = 3)
	public String getStrTstCode() {
		return this.strTstCode;
	}

	public void setStrTstCode(String strTstCode) {
		this.strTstCode = strTstCode;
	}

	@Column(name = "FIN_ID", precision = 10, scale = 0)
	public Long getFinId() {
		return this.finId;
	}

	public void setFinId(Long finId) {
		this.finId = finId;
	}

	@Column(name = "PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getProId() {
		return this.proId;
	}

	public void setProId(long proId) {
		this.proId = proId;
	}

	@Column(name = "DEC_ID", precision = 10, scale = 0)
	public Long getDecId() {
		return this.decId;
	}

	public void setDecId(Long decId) {
		this.decId = decId;
	}

}
