package com.sndi.model;
// Generated 28 juil. 2020 17:10:33 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VDetailOffres generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_DETAIL_OFFRES")
public class VDetailOffres implements java.io.Serializable {

	private BigDecimal RId;
	private BigDecimal dofNum;
	private BigDecimal laaNum;
	private String laaObjet;
	private BigDecimal dofLaaId;
	private String aaoCode;
	private String offSouSigleSte;
	private BigDecimal dofMtOfr;
	private String dofTyp;
	private String dofStatut;
	private String dofObsVariante;

	public VDetailOffres() {
	}

	public VDetailOffres(BigDecimal dofNum, BigDecimal laaNum, BigDecimal dofLaaId, String aaoCode) {
		this.dofNum = dofNum;
		this.laaNum = laaNum;
		this.dofLaaId = dofLaaId;
		this.aaoCode = aaoCode;
	}

	public VDetailOffres(BigDecimal RId, BigDecimal dofNum, BigDecimal laaNum, String laaObjet, BigDecimal dofLaaId,
			String aaoCode, String offSouSigleSte, BigDecimal dofMtOfr, String dofTyp, String dofStatut,String dofObsVariante) {
		this.RId = RId;
		this.dofNum = dofNum;
		this.laaNum = laaNum;
		this.laaObjet = laaObjet;
		this.dofLaaId = dofLaaId;
		this.aaoCode = aaoCode;
		this.offSouSigleSte = offSouSigleSte;
		this.dofMtOfr = dofMtOfr;
		this.dofTyp = dofTyp;
		this.dofStatut = dofStatut;
		this.dofObsVariante = dofObsVariante;
	}

	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	@Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_OBJET", length = 1047)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "DOF_LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofLaaId() {
		return this.dofLaaId;
	}

	public void setDofLaaId(BigDecimal dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	@Column(name = "AAO_CODE", nullable = false, length = 20)
	public String getAaoCode() {
		return this.aaoCode;
	}

	public void setAaoCode(String aaoCode) {
		this.aaoCode = aaoCode;
	}

	@Column(name = "OFF_SOU_SIGLE_STE", length = 523)
	public String getOffSouSigleSte() {
		return this.offSouSigleSte;
	}

	public void setOffSouSigleSte(String offSouSigleSte) {
		this.offSouSigleSte = offSouSigleSte;
	}

	@Column(name = "DOF_MT_OFR", precision = 20, scale = 0)
	public BigDecimal getDofMtOfr() {
		return this.dofMtOfr;
	}

	public void setDofMtOfr(BigDecimal dofMtOfr) {
		this.dofMtOfr = dofMtOfr;
	}

	@Column(name = "DOF_TYP", length = 1)
	public String getDofTyp() {
		return this.dofTyp;
	}

	public void setDofTyp(String dofTyp) {
		this.dofTyp = dofTyp;
	}

	@Column(name = "DOF_STATUT", length = 1)
	public String getDofStatut() {
		return this.dofStatut;
	}

	public void setDofStatut(String dofStatut) {
		this.dofStatut = dofStatut;
	}
	
	@Column(name = "DOF_OBS_VARIANTE", length = 500)
	public String getDofObsVariante() {
		return this.dofObsVariante;
	}

	public void setDofObsVariante(String dofObsVariante) {
		this.dofObsVariante = dofObsVariante;
	}

}
