package com.sndi.model;
// Generated 9 mai 2020 22:05:43 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VDetailOffresId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_DETAIL_OFFRES")
public class VDetailOffres implements java.io.Serializable {

	private BigDecimal dofNum;
	private BigDecimal laaNum;
	private String laaObjet;
	private BigDecimal dofLaaId;
	private String aaoCode;
	private String offSouSigleSte;
	private BigDecimal dofMtOfr;
	private String dofTyp;
	private String dofStaut;

	public VDetailOffres() {
	}

	public VDetailOffres(BigDecimal dofNum, BigDecimal dofLaaId, String aaoCode) {
		this.dofNum = dofNum;
		this.dofLaaId = dofLaaId;
		this.aaoCode = aaoCode;
	}

	public VDetailOffres(BigDecimal dofNum, BigDecimal laaNum, String laaObjet, BigDecimal dofLaaId, String aaoCode,
			String offSouSigleSte, BigDecimal dofMtOfr, String dofTyp,String dofStaut) {
		this.dofNum = dofNum;
		this.laaNum = laaNum;
		this.laaObjet = laaObjet;
		this.dofLaaId = dofLaaId;
		this.aaoCode = aaoCode;
		this.offSouSigleSte = offSouSigleSte;
		this.dofMtOfr = dofMtOfr;
		this.dofTyp = dofTyp;
		this.dofStaut= dofStaut;
	}

	@Id
	@Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	@Column(name = "LAA_NUM", precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_OBJET", length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "DOF_LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofLaaId() {
		return this.dofLaaId;
	}

	public void setDofLaaId(BigDecimal dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	@Column(name = "AAO_CODE", nullable = false, length = 20)
	public String getAaoCode() {
		return this.aaoCode;
	}

	public void setAaoCode(String aaoCode) {
		this.aaoCode = aaoCode;
	}

	@Column(name = "OFF_SOU_SIGLE_STE", length = 500)
	public String getOffSouSigleSte() {
		return offSouSigleSte;
	}

	public void setOffSouSigleSte(String offSouSigleSte) {
		this.offSouSigleSte = offSouSigleSte;
	}
	
	@Column(name = "DOF_MT_OFR", precision = 20, scale = 0)
	public BigDecimal getDofMtOfr() {
		return this.dofMtOfr;
	}

	public void setDofMtOfr(BigDecimal dofMtOfr) {
		this.dofMtOfr = dofMtOfr;
	}

	@Column(name = "DOF_TYP", length = 1)
	public String getDofTyp() {
		return this.dofTyp;
	}

	public void setDofTyp(String dofTyp) {
		this.dofTyp = dofTyp;
	}
	
	@Column(name = "DOF_STATUT")
	public String getDofStaut() {
		return dofStaut;
	}

	public void setDofStaut(String dofStaut) {
		this.dofStaut = dofStaut;
	}

	
}
