package com.sndi.model;
// Generated 4 févr. 2020 11:43:36 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VFonctionMinistere generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_FONCTION_MINISTERE")
public class VFonctionMinistere implements java.io.Serializable {

	private String fonCod;
	private String fonStrCode;
	private String fonLibelle;
	private Date fonDatDeb;
	private Date fonDatFin;
	private String fonTel;
	private String fonTyfCod;
	private String tyfLibelle;
	private String minLibelle;
	private String strLibelleLong;

	public VFonctionMinistere() {
	}

	public VFonctionMinistere(String fonCod) {
		this.fonCod = fonCod;
	}

	public VFonctionMinistere(String fonCod, String fonStrCode, String fonLibelle, Date fonDatDeb, Date fonDatFin,
			String fonTel, String fonTyfCod, String tyfLibelle, String minLibelle, String strLibelleLong) {
		this.fonCod = fonCod;
		this.fonStrCode = fonStrCode;
		this.fonLibelle = fonLibelle;
		this.fonDatDeb = fonDatDeb;
		this.fonDatFin = fonDatFin;
		this.fonTel = fonTel;
		this.fonTyfCod = fonTyfCod;
		this.tyfLibelle = tyfLibelle;
		this.minLibelle = minLibelle;
		this.strLibelleLong = strLibelleLong;
	}

	
	@Id
	@Column(name = "FON_COD", nullable = false, length = 12)
	public String getFonCod() {
		return this.fonCod;
	}

	public void setFonCod(String fonCod) {
		this.fonCod = fonCod;
	}

	@Column(name = "FON_STR_CODE", length = 3)
	public String getFonStrCode() {
		return this.fonStrCode;
	}

	public void setFonStrCode(String fonStrCode) {
		this.fonStrCode = fonStrCode;
	}

	@Column(name = "FON_LIBELLE", length = 240)
	public String getFonLibelle() {
		return this.fonLibelle;
	}

	public void setFonLibelle(String fonLibelle) {
		this.fonLibelle = fonLibelle;
	}

	@Column(name = "FON_DAT_DEB", length = 7)
	public Date getFonDatDeb() {
		return this.fonDatDeb;
	}

	public void setFonDatDeb(Date fonDatDeb) {
		this.fonDatDeb = fonDatDeb;
	}

	@Column(name = "FON_DAT_FIN", length = 7)
	public Date getFonDatFin() {
		return this.fonDatFin;
	}

	public void setFonDatFin(Date fonDatFin) {
		this.fonDatFin = fonDatFin;
	}

	@Column(name = "FON_TEL", length = 240)
	public String getFonTel() {
		return this.fonTel;
	}

	public void setFonTel(String fonTel) {
		this.fonTel = fonTel;
	}

	@Column(name = "FON_TYF_COD", length = 3)
	public String getFonTyfCod() {
		return this.fonTyfCod;
	}

	public void setFonTyfCod(String fonTyfCod) {
		this.fonTyfCod = fonTyfCod;
	}

	@Column(name = "TYF_LIBELLE", length = 100)
	public String getTyfLibelle() {
		return this.tyfLibelle;
	}

	public void setTyfLibelle(String tyfLibelle) {
		this.tyfLibelle = tyfLibelle;
	}

	@Column(name = "MIN_LIBELLE", length = 1000)
	public String getMinLibelle() {
		return this.minLibelle;
	}

	public void setMinLibelle(String minLibelle) {
		this.minLibelle = minLibelle;
	}

	@Column(name = "STR_LIBELLE_LONG", length = 1000)
	public String getStrLibelleLong() {
		return this.strLibelleLong;
	}

	public void setStrLibelleLong(String strLibelleLong) {
		this.strLibelleLong = strLibelleLong;
	}

}
