package com.sndi.model;
// Generated 28 mars 2020 01:30:08 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VFonctionAssignationId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_FONCTION_ASSIGNATION")
public class VFonctionAssignation implements java.io.Serializable {

	private String fonCod;
	private String fonTyfCod;
	private String fonStrCode;
	private Date fonDatDeb;
	private Date fonDatFin;
	private String fonLibelle;
	private String fonOpeMatricule;

	public VFonctionAssignation() {
	}

	public VFonctionAssignation(String fonCod) {
		this.fonCod = fonCod;
	}

	public VFonctionAssignation(String fonCod, String fonTyfCod, String fonStrCode, Date fonDatDeb, Date fonDatFin,
			String fonLibelle, String fonOpeMatricule) {
		this.fonCod = fonCod;
		this.fonTyfCod = fonTyfCod;
		this.fonStrCode = fonStrCode;
		this.fonDatDeb = fonDatDeb;
		this.fonDatFin = fonDatFin;
		this.fonLibelle = fonLibelle;
		this.fonOpeMatricule = fonOpeMatricule;
	}

	@Id
	@Column(name = "FON_COD", nullable = false, length = 20)
	public String getFonCod() {
		return this.fonCod;
	}

	public void setFonCod(String fonCod) {
		this.fonCod = fonCod;
	}

	@Column(name = "FON_TYF_COD", length = 3)
	public String getFonTyfCod() {
		return this.fonTyfCod;
	}

	public void setFonTyfCod(String fonTyfCod) {
		this.fonTyfCod = fonTyfCod;
	}

	@Column(name = "FON_STR_CODE", length = 20)
	public String getFonStrCode() {
		return this.fonStrCode;
	}

	public void setFonStrCode(String fonStrCode) {
		this.fonStrCode = fonStrCode;
	}

	@Column(name = "FON_DAT_DEB", length = 7)
	public Date getFonDatDeb() {
		return this.fonDatDeb;
	}

	public void setFonDatDeb(Date fonDatDeb) {
		this.fonDatDeb = fonDatDeb;
	}

	@Column(name = "FON_DAT_FIN", length = 7)
	public Date getFonDatFin() {
		return this.fonDatFin;
	}

	public void setFonDatFin(Date fonDatFin) {
		this.fonDatFin = fonDatFin;
	}

	@Column(name = "FON_LIBELLE", length = 500)
	public String getFonLibelle() {
		return this.fonLibelle;
	}

	public void setFonLibelle(String fonLibelle) {
		this.fonLibelle = fonLibelle;
	}
	
	@Column(name = "FON_OPE_MATRICULE", length = 25)
	public String getFonOpeMatricule() {
		return this.fonOpeMatricule;
	}

	public void setFonOpeMatricule(String fonOpeMatricule) {
		this.fonOpeMatricule = fonOpeMatricule;
	}

}
