package com.sndi.model;
// Generated 18 mars 2021 12:10:20 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VLinkId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_LINK")
public class VLink implements java.io.Serializable {

	private BigDecimal linkId;
	private String linkLibele;
	private String linkType;
	private String linkStatut;
	private String linkName;

	public VLink() {
	}

	public VLink(BigDecimal linkId) {
		this.linkId = linkId;
	}

	public VLink(BigDecimal linkId, String linkLibele, String linkType, String linkStatut, String linkName) {
		this.linkId = linkId;
		this.linkLibele = linkLibele;
		this.linkType = linkType;
		this.linkStatut = linkStatut;
		this.linkName = linkName;
	}

	@Id
	@Column(name = "LINK_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLinkId() {
		return this.linkId;
	}

	public void setLinkId(BigDecimal linkId) {
		this.linkId = linkId;
	}

	@Column(name = "LINK_LIBELE", length = 400)
	public String getLinkLibele() {
		return this.linkLibele;
	}

	public void setLinkLibele(String linkLibele) {
		this.linkLibele = linkLibele;
	}

	@Column(name = "LINK_TYPE", length = 10)
	public String getLinkType() {
		return this.linkType;
	}

	public void setLinkType(String linkType) {
		this.linkType = linkType;
	}

	@Column(name = "LINK_STATUT", length = 1)
	public String getLinkStatut() {
		return this.linkStatut;
	}

	public void setLinkStatut(String linkStatut) {
		this.linkStatut = linkStatut;
	}

	@Column(name = "LINK_NAME", length = 200)
	public String getLinkName() {
		return this.linkName;
	}

	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}
}
