package com.sndi.model;
// Generated 4 juil. 2020 18:05:44 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VListeSouOffBasseId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_LISTE_SOU_OFF_BASSE")
public class VListeSouOffBasse implements java.io.Serializable {

	private BigDecimal RId;
	private BigDecimal ordre;
	private BigDecimal dofLaaId;
	private BigDecimal laaMtEst;
	private BigDecimal moyOffFinQualtech;
	private BigDecimal moyPonderee;
	private BigDecimal sf1;
	private BigDecimal sf2;
	private BigDecimal laaNum;
	private BigDecimal dofNum;
	private String offSouNcc;
	private BigDecimal dofMtCor;
	private String offSouSigleSte;
	private String laaAaoCode;
	private String laaDacCode;
	private String laaObjet;
	private String commentaire;
	private String seuilAnormal;
	private BigDecimal flag;
	private BigDecimal mtMoinsDisant;
	private String commentaireOffin;
	private String commentaireAnormal;
	private String commentaireOffret;
	private String dofRepeche;

	public VListeSouOffBasse() {
	}

	public VListeSouOffBasse(BigDecimal dofLaaId, BigDecimal dofNum) {
		this.dofLaaId = dofLaaId;
		this.dofNum = dofNum;
	}

	public VListeSouOffBasse(BigDecimal RId, BigDecimal ordre, BigDecimal dofLaaId, BigDecimal laaMtEst,
			BigDecimal moyOffFinQualtech, BigDecimal moyPonderee, BigDecimal sf1, BigDecimal sf2, BigDecimal laaNum,
			BigDecimal dofNum, String offSouNcc, BigDecimal dofMtCor, String offSouSigleSte, String laaAaoCode,
			String laaDacCode, String laaObjet, String commentaire, String seuilAnormal, BigDecimal flag,
			BigDecimal mtMoinsDisant, String commentaireOffin, String commentaireAnormal, String commentaireOffret,
			String dofRepeche) {
		this.RId = RId;
		this.ordre = ordre;
		this.dofLaaId = dofLaaId;
		this.laaMtEst = laaMtEst;
		this.moyOffFinQualtech = moyOffFinQualtech;
		this.moyPonderee = moyPonderee;
		this.sf1 = sf1;
		this.sf2 = sf2;
		this.laaNum = laaNum;
		this.dofNum = dofNum;
		this.offSouNcc = offSouNcc;
		this.dofMtCor = dofMtCor;
		this.offSouSigleSte = offSouSigleSte;
		this.laaAaoCode = laaAaoCode;
		this.laaDacCode = laaDacCode;
		this.laaObjet = laaObjet;
		this.commentaire = commentaire;
		this.seuilAnormal = seuilAnormal;
		this.flag = flag;
		this.mtMoinsDisant = mtMoinsDisant;
		this.commentaireOffin = commentaireOffin;
		this.commentaireAnormal = commentaireAnormal;
		this.commentaireOffret = commentaireOffret;
		this.dofRepeche = dofRepeche;
	}

	
	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "ORDRE", precision = 22, scale = 0)
	public BigDecimal getOrdre() {
		return this.ordre;
	}

	public void setOrdre(BigDecimal ordre) {
		this.ordre = ordre;
	}

	@Column(name = "DOF_LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofLaaId() {
		return this.dofLaaId;
	}

	public void setDofLaaId(BigDecimal dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	@Column(name = "LAA_MT_EST", precision = 22, scale = 0)
	public BigDecimal getLaaMtEst() {
		return this.laaMtEst;
	}

	public void setLaaMtEst(BigDecimal laaMtEst) {
		this.laaMtEst = laaMtEst;
	}

	@Column(name = "MOY_OFF_FIN_QUALTECH", precision = 22, scale = 0)
	public BigDecimal getMoyOffFinQualtech() {
		return this.moyOffFinQualtech;
	}

	public void setMoyOffFinQualtech(BigDecimal moyOffFinQualtech) {
		this.moyOffFinQualtech = moyOffFinQualtech;
	}

	@Column(name = "MOY_PONDEREE", precision = 22, scale = 0)
	public BigDecimal getMoyPonderee() {
		return this.moyPonderee;
	}

	public void setMoyPonderee(BigDecimal moyPonderee) {
		this.moyPonderee = moyPonderee;
	}

	@Column(name = "SF1", precision = 22, scale = 0)
	public BigDecimal getSf1() {
		return this.sf1;
	}

	public void setSf1(BigDecimal sf1) {
		this.sf1 = sf1;
	}

	@Column(name = "SF2", precision = 22, scale = 0)
	public BigDecimal getSf2() {
		return this.sf2;
	}

	public void setSf2(BigDecimal sf2) {
		this.sf2 = sf2;
	}

	@Column(name = "LAA_NUM", precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	@Column(name = "OFF_SOU_NCC", length = 20)
	public String getOffSouNcc() {
		return this.offSouNcc;
	}

	public void setOffSouNcc(String offSouNcc) {
		this.offSouNcc = offSouNcc;
	}

	@Column(name = "DOF_MT_COR", precision = 20, scale = 0)
	public BigDecimal getDofMtCor() {
		return this.dofMtCor;
	}

	public void setDofMtCor(BigDecimal dofMtCor) {
		this.dofMtCor = dofMtCor;
	}

	@Column(name = "OFF_SOU_SIGLE_STE", length = 500)
	public String getOffSouSigleSte() {
		return this.offSouSigleSte;
	}

	public void setOffSouSigleSte(String offSouSigleSte) {
		this.offSouSigleSte = offSouSigleSte;
	}

	@Column(name = "LAA_AAO_CODE", length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "LAA_DAC_CODE", length = 20)
	public String getLaaDacCode() {
		return this.laaDacCode;
	}

	public void setLaaDacCode(String laaDacCode) {
		this.laaDacCode = laaDacCode;
	}

	@Column(name = "LAA_OBJET", length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "COMMENTAIRE", length = 1158)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "SEUIL_ANORMAL", length = 2)
	public String getSeuilAnormal() {
		return this.seuilAnormal;
	}

	public void setSeuilAnormal(String seuilAnormal) {
		this.seuilAnormal = seuilAnormal;
	}

	@Column(name = "FLAG", precision = 22, scale = 0)
	public BigDecimal getFlag() {
		return this.flag;
	}

	public void setFlag(BigDecimal flag) {
		this.flag = flag;
	}

	@Column(name = "MT_MOINS_DISANT", precision = 22, scale = 0)
	public BigDecimal getMtMoinsDisant() {
		return this.mtMoinsDisant;
	}

	public void setMtMoinsDisant(BigDecimal mtMoinsDisant) {
		this.mtMoinsDisant = mtMoinsDisant;
	}

	@Column(name = "COMMENTAIRE_OFFIN", length = 500)
	public String getCommentaireOffin() {
		return this.commentaireOffin;
	}

	public void setCommentaireOffin(String commentaireOffin) {
		this.commentaireOffin = commentaireOffin;
	}

	@Column(name = "COMMENTAIRE_ANORMAL", length = 500)
	public String getCommentaireAnormal() {
		return this.commentaireAnormal;
	}

	public void setCommentaireAnormal(String commentaireAnormal) {
		this.commentaireAnormal = commentaireAnormal;
	}

	@Column(name = "COMMENTAIRE_OFFRET", length = 500)
	public String getCommentaireOffret() {
		return this.commentaireOffret;
	}

	public void setCommentaireOffret(String commentaireOffret) {
		this.commentaireOffret = commentaireOffret;
	}

	@Column(name = "DOF_REPECHE", length = 1)
	public String getDofRepeche() {
		return this.dofRepeche;
	}

	public void setDofRepeche(String dofRepeche) {
		this.dofRepeche = dofRepeche;
	}
}
