package com.sndi.model;
// Generated 12 août 2021 15:51:53 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VLotNumerotationId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_LOT_NUMEROTATION")
public class VLotNumerotation implements java.io.Serializable {

	private BigDecimal attNum;
	private BigDecimal laaId;
	private String laaAaoCode;
	private String laaObjet;
	private String laaObservation;
	private BigDecimal laaMtCaut;
	private BigDecimal laaMtEst;
	private Date laaDteSaisi;
	private String laaStaCode;
	private String laaFonCodSaisi;
	private String laaFonCodCpmp;
	private String laaOpeMatricule;
	private String attStaCode;
	private String laaLieuExe;
	private String laaLbgImputation;
	private BigDecimal laaNum;
	private BigDecimal laaCoutLot;
	private String laaDacCode;
	private String attSouNcc;
	private BigDecimal attMtAttr;
	private String souSigleSte;
	private Date attDteSaisi;
	private String attFonCodeSaisi;
	private String critere;

	public VLotNumerotation() {
	}

	public VLotNumerotation(BigDecimal attNum,BigDecimal laaId, String laaAaoCode,String attStaCode, String laaObjet, BigDecimal laaNum) {
		this.attNum = attNum;
		this.laaId = laaId;
		this.laaAaoCode = laaAaoCode;
		this.laaObjet = laaObjet;
		this.attStaCode = attStaCode;
		this.laaNum = laaNum;
	}

	public VLotNumerotation(BigDecimal attNum,BigDecimal laaId, String laaAaoCode, String laaObjet, String laaObservation,
			BigDecimal laaMtCaut, BigDecimal laaMtEst, Date laaDteSaisi, String laaStaCode, String laaFonCodSaisi,
			String laaFonCodCpmp, String laaOpeMatricule, String attStaCode, String laaLieuExe, String laaLbgImputation, BigDecimal laaNum,
			BigDecimal laaCoutLot, String laaDacCode, String attSouNcc, BigDecimal attMtAttr, String souSigleSte, Date attDteSaisi, String attFonCodeSaisi, String critere) {
		this.attNum = attNum;
		this.laaId = laaId;
		this.laaAaoCode = laaAaoCode;
		this.laaObjet = laaObjet;
		this.laaObservation = laaObservation;
		this.laaMtCaut = laaMtCaut;
		this.laaMtEst = laaMtEst;
		this.laaDteSaisi = laaDteSaisi;
		this.laaStaCode = laaStaCode;
		this.laaFonCodSaisi = laaFonCodSaisi;
		this.laaFonCodCpmp = laaFonCodCpmp;
		this.laaOpeMatricule = laaOpeMatricule;
		this.attStaCode = attStaCode;
		this.laaLieuExe = laaLieuExe;
		this.laaLbgImputation = laaLbgImputation;
		this.laaNum = laaNum;
		this.laaCoutLot = laaCoutLot;
		this.laaDacCode = laaDacCode;
		this.attSouNcc = attSouNcc;
		this.attMtAttr = attMtAttr;
		this.souSigleSte = souSigleSte;
		this.attDteSaisi = attDteSaisi;
		this.attFonCodeSaisi = attFonCodeSaisi;
		this.critere = critere;
		
	}

	@Id
	@Column(name = "ATT_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAttNum() {
		return this.attNum;
	}

	public void setAttNum(BigDecimal attNum) {
		this.attNum = attNum;
	}
	
	@Column(name = "LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaId() {
		return this.laaId;
	}

	public void setLaaId(BigDecimal laaId) {
		this.laaId = laaId;
	}

	@Column(name = "LAA_AAO_CODE", nullable = false, length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "LAA_OBJET", nullable = false, length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "LAA_OBSERVATION", length = 200)
	public String getLaaObservation() {
		return this.laaObservation;
	}

	public void setLaaObservation(String laaObservation) {
		this.laaObservation = laaObservation;
	}

	@Column(name = "LAA_MT_CAUT", precision = 22, scale = 0)
	public BigDecimal getLaaMtCaut() {
		return this.laaMtCaut;
	}

	public void setLaaMtCaut(BigDecimal laaMtCaut) {
		this.laaMtCaut = laaMtCaut;
	}

	@Column(name = "LAA_MT_EST", precision = 22, scale = 0)
	public BigDecimal getLaaMtEst() {
		return this.laaMtEst;
	}

	public void setLaaMtEst(BigDecimal laaMtEst) {
		this.laaMtEst = laaMtEst;
	}

	@Column(name = "LAA_DTE_SAISI", length = 7)
	public Date getLaaDteSaisi() {
		return this.laaDteSaisi;
	}

	public void setLaaDteSaisi(Date laaDteSaisi) {
		this.laaDteSaisi = laaDteSaisi;
	}

	@Column(name = "LAA_STA_CODE", length = 3)
	public String getLaaStaCode() {
		return this.laaStaCode;
	}

	public void setLaaStaCode(String laaStaCode) {
		this.laaStaCode = laaStaCode;
	}

	@Column(name = "LAA_FON_COD_SAISI", length = 20)
	public String getLaaFonCodSaisi() {
		return this.laaFonCodSaisi;
	}

	public void setLaaFonCodSaisi(String laaFonCodSaisi) {
		this.laaFonCodSaisi = laaFonCodSaisi;
	}

	@Column(name = "LAA_FON_COD_CPMP", length = 20)
	public String getLaaFonCodCpmp() {
		return this.laaFonCodCpmp;
	}

	public void setLaaFonCodCpmp(String laaFonCodCpmp) {
		this.laaFonCodCpmp = laaFonCodCpmp;
	}

	@Column(name = "LAA_OPE_MATRICULE", length = 20)
	public String getLaaOpeMatricule() {
		return this.laaOpeMatricule;
	}

	public void setLaaOpeMatricule(String laaOpeMatricule) {
		this.laaOpeMatricule = laaOpeMatricule;
	}

	@Column(name = "ATT_STA_CODE", nullable = false, length = 3)
	public String getAttStaCode() {
		return this.attStaCode;
	}

	public void setAttStaCode(String attStaCode) {
		this.attStaCode = attStaCode;
	}

	@Column(name = "LAA_LIEU_EXE", length = 1000)
	public String getLaaLieuExe() {
		return this.laaLieuExe;
	}

	public void setLaaLieuExe(String laaLieuExe) {
		this.laaLieuExe = laaLieuExe;
	}

	@Column(name = "LAA_LBG_IMPUTATION", length = 50)
	public String getLaaLbgImputation() {
		return this.laaLbgImputation;
	}

	public void setLaaLbgImputation(String laaLbgImputation) {
		this.laaLbgImputation = laaLbgImputation;
	}

	@Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_COUT_LOT", precision = 22, scale = 0)
	public BigDecimal getLaaCoutLot() {
		return this.laaCoutLot;
	}

	public void setLaaCoutLot(BigDecimal laaCoutLot) {
		this.laaCoutLot = laaCoutLot;
	}

	@Column(name = "LAA_DAC_CODE", length = 20)
	public String getLaaDacCode() {
		return this.laaDacCode;
	}

	public void setLaaDacCode(String laaDacCode) {
		this.laaDacCode = laaDacCode;
	}

	@Column(name = "ATT_SOU_NCC", length = 20)
	public String getAttSouNcc() {
		return this.attSouNcc;
	}

	public void setAttSouNcc(String attSouNcc) {
		this.attSouNcc = attSouNcc;
	}

	@Column(name = "ATT_MT_ATTR", precision = 22, scale = 0)
	public BigDecimal getAttMtAttr() {
		return this.attMtAttr;
	}

	public void setAttMtAttr(BigDecimal attMtAttr) {
		this.attMtAttr = attMtAttr;
	}

	@Column(name = "SOU_SIGLE_STE", length = 500)
	public String getSouSigleSte() {
		return this.souSigleSte;
	}

	public void setSouSigleSte(String souSigleSte) {
		this.souSigleSte = souSigleSte;
	}
	
	@Column(name = "ATT_DTE_SAISI", length = 7)
	public Date getAttDteSaisi() {
		return this.attDteSaisi;
	}

	public void setAttDteSaisi(Date attDteSaisi) {
		this.attDteSaisi = attDteSaisi;
	}
	@Column(name = "ATT_FON_CODE_SAISI", length = 50)
	public String getAttFonCodeSaisi() {
		return this.attFonCodeSaisi;
	}

	public void setAttFonCodeSaisi(String attFonCodeSaisi) {
		this.attFonCodeSaisi = attFonCodeSaisi;
	}
	
	@Column(name = "CRITERE", length = 3672)
	public String getCritere() {
		return this.critere;
	}

	public void setCritere(String critere) {
		this.critere = critere;
	}
}
