package com.sndi.model;
// Generated 22 août 2020 15:53:52 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VLotCritereId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_LOT_CRITERE")
public class VLotCritere implements java.io.Serializable {

	private String laaObjet;
	private BigDecimal laaId;
	private String laaAaoCode;
	private BigDecimal laaNum;
	private String laaDacCode;

	public VLotCritere() {
	}

	public VLotCritere(BigDecimal laaId, BigDecimal laaNum) {
		this.laaId = laaId;
		this.laaNum = laaNum;
	}

	public VLotCritere(String laaObjet, BigDecimal laaId, String laaAaoCode, BigDecimal laaNum, String laaDacCode) {
		this.laaObjet = laaObjet;
		this.laaId = laaId;
		this.laaAaoCode = laaAaoCode;
		this.laaNum = laaNum;
		this.laaDacCode = laaDacCode;
	}

	@Column(name = "LAA_OBJET", length = 1025)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Id
	@Column(name = "LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaId() {
		return this.laaId;
	}

	public void setLaaId(BigDecimal laaId) {
		this.laaId = laaId;
	}

	@Column(name = "LAA_AAO_CODE", length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_DAC_CODE", length = 20)
	public String getLaaDacCode() {
		return this.laaDacCode;
	}

	public void setLaaDacCode(String laaDacCode) {
		this.laaDacCode = laaDacCode;
	}

}
