package com.sndi.model;
// Generated 26 juil. 2020 20:04:08 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VLotCandidatId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_LOT_CANDIDAT")
public class VLotCandidat implements java.io.Serializable {

	private BigDecimal laaId;
	private BigDecimal laaNum;
	private String laaObjet;
	private String laaAaoCode;
	private String canSouNcc;

	public VLotCandidat() {
	}

	public VLotCandidat(BigDecimal laaId, BigDecimal laaNum, String laaObjet) {
		this.laaId = laaId;
		this.laaNum = laaNum;
		this.laaObjet = laaObjet;
	}

	public VLotCandidat(BigDecimal laaId, BigDecimal laaNum, String laaObjet, String laaAaoCode, String canSouNcc) {
		this.laaId = laaId;
		this.laaNum = laaNum;
		this.laaObjet = laaObjet;
		this.laaAaoCode = laaAaoCode;
		this.canSouNcc = canSouNcc;
	}

	
	@Id
	@Column(name = "LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaId() {
		return this.laaId;
	}

	public void setLaaId(BigDecimal laaId) {
		this.laaId = laaId;
	}

	@Column(name = "LAA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_OBJET", nullable = false, length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "LAA_AAO_CODE", length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "CAN_SOU_NCC", length = 20)
	public String getCanSouNcc() {
		return this.canSouNcc;
	}

	public void setCanSouNcc(String canSouNcc) {
		this.canSouNcc = canSouNcc;
	}
}
