package com.sndi.model;
// Generated 24 juil. 2020 12:35:37 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VMargeDePreferenceId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_MARGE_DE_PREFERENCE")
public class VMargeDePreference implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal margePrefMin;
	private BigDecimal margePefMax;
	private String margePefText;
	private BigDecimal tauxMargePref;

	public VMargeDePreference() {
	}

	public VMargeDePreference(BigDecimal id, BigDecimal margePrefMin, BigDecimal margePefMax, String margePefText,
			BigDecimal tauxMargePref) {
		this.id = id;
		this.margePrefMin = margePrefMin;
		this.margePefMax = margePefMax;
		this.margePefText = margePefText;
		this.tauxMargePref = tauxMargePref;
	}

	@Id
	@Column(name = "ID", precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "MARGE_PREF_MIN", precision = 22, scale = 0)
	public BigDecimal getMargePrefMin() {
		return this.margePrefMin;
	}

	public void setMargePrefMin(BigDecimal margePrefMin) {
		this.margePrefMin = margePrefMin;
	}

	@Column(name = "MARGE_PEF_MAX", precision = 22, scale = 0)
	public BigDecimal getMargePefMax() {
		return this.margePefMax;
	}

	public void setMargePefMax(BigDecimal margePefMax) {
		this.margePefMax = margePefMax;
	}

	@Column(name = "MARGE_PEF_TEXT", length = 4000)
	public String getMargePefText() {
		return this.margePefText;
	}

	public void setMargePefText(String margePefText) {
		this.margePefText = margePefText;
	}

	@Column(name = "TAUX_MARGE_PREF", precision = 22, scale = 0)
	public BigDecimal getTauxMargePref() {
		return this.tauxMargePref;
	}

	public void setTauxMargePref(BigDecimal tauxMargePref) {
		this.tauxMargePref = tauxMargePref;
	}

}
