package com.sndi.model;
// Generated 24 juil. 2020 11:10:04 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VMargeDePreferenceId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_MARGE_DE_PREFERENCE")
public class VMargeDePreference implements java.io.Serializable {

	private BigDecimal parId;
	private String parLibelle;
	private String parVal;

	public VMargeDePreference() {
	}

	public VMargeDePreference(BigDecimal parId, String parLibelle, String parVal) {
		this.parId = parId;
		this.parLibelle = parLibelle;
		this.parVal = parVal;
	}

	@Id
	@Column(name = "PAR_ID", precision = 22, scale = 0)
	public BigDecimal getParId() {
		return this.parId;
	}

	public void setParId(BigDecimal parId) {
		this.parId = parId;
	}

	@Column(name = "PAR_LIBELLE", length = 200)
	public String getParLibelle() {
		return this.parLibelle;
	}

	public void setParLibelle(String parLibelle) {
		this.parLibelle = parLibelle;
	}

	@Column(name = "PAR_VAL", length = 200)
	public String getParVal() {
		return this.parVal;
	}

	public void setParVal(String parVal) {
		this.parVal = parVal;
	}
	
}
