package com.sndi.model;
// Generated 19 mars 2020 18:39:08 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VModeleAmi generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_MODELE_AMI")
public class VModeleAmi implements java.io.Serializable {

	private long gpgId;
	private String mdtCode;
	private String mdtLibelleLong;
	private String mdtLibelleCourt;
	private Date mdtDteSaisi;
	private String mdtOpeMatricule;
	private String mdtTymCode;

	public VModeleAmi() {
	}

	public VModeleAmi(long gpgId, String mdtCode) {
		this.gpgId = gpgId;
		this.mdtCode = mdtCode;
	}

	public VModeleAmi(long gpgId, String mdtCode, String mdtLibelleLong, String mdtLibelleCourt, Date mdtDteSaisi,
			String mdtOpeMatricule, String mdtTymCode) {
		this.gpgId = gpgId;
		this.mdtCode = mdtCode;
		this.mdtLibelleLong = mdtLibelleLong;
		this.mdtLibelleCourt = mdtLibelleCourt;
		this.mdtDteSaisi = mdtDteSaisi;
		this.mdtOpeMatricule = mdtOpeMatricule;
		this.mdtTymCode = mdtTymCode;
	}

	
	@Id
	@Column(name = "GPG_ID", nullable = false, precision = 10, scale = 0)
	public long getGpgId() {
		return this.gpgId;
	}

	public void setGpgId(long gpgId) {
		this.gpgId = gpgId;
	}

	@Column(name = "MDT_CODE", nullable = false, length = 15)
	public String getMdtCode() {
		return this.mdtCode;
	}

	public void setMdtCode(String mdtCode) {
		this.mdtCode = mdtCode;
	}

	@Column(name = "MDT_LIBELLE_LONG", length = 500)
	public String getMdtLibelleLong() {
		return this.mdtLibelleLong;
	}

	public void setMdtLibelleLong(String mdtLibelleLong) {
		this.mdtLibelleLong = mdtLibelleLong;
	}

	@Column(name = "MDT_LIBELLE_COURT", length = 500)
	public String getMdtLibelleCourt() {
		return this.mdtLibelleCourt;
	}

	public void setMdtLibelleCourt(String mdtLibelleCourt) {
		this.mdtLibelleCourt = mdtLibelleCourt;
	}

	@Column(name = "MDT_DTE_SAISI", length = 7)
	public Date getMdtDteSaisi() {
		return this.mdtDteSaisi;
	}

	public void setMdtDteSaisi(Date mdtDteSaisi) {
		this.mdtDteSaisi = mdtDteSaisi;
	}

	@Column(name = "MDT_OPE_MATRICULE", length = 25)
	public String getMdtOpeMatricule() {
		return this.mdtOpeMatricule;
	}

	public void setMdtOpeMatricule(String mdtOpeMatricule) {
		this.mdtOpeMatricule = mdtOpeMatricule;
	}

	@Column(name = "MDT_TYM_CODE", length = 3)
	public String getMdtTymCode() {
		return this.mdtTymCode;
	}

	public void setMdtTymCode(String mdtTymCode) {
		this.mdtTymCode = mdtTymCode;
	}

	

}
