package com.sndi.model;
// Generated 6 août 2021 15:23:21 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * VMotifId generated by hbm2java
 */

@Data 
@NoArgsConstructor 
@AllArgsConstructor 
@Builder

@Entity
@Immutable
@Table(name = "V_MOTIF")
public class VMotif {

	public TMotifs gettMotifs() {
		TMotifs tMotifs = new TMotifs();
		TOperateur tOperateur = new TOperateur();
		tOperateur.setOpeMatricule(mtfOpeMatricule);
		tMotifs.setMtfNum(mtfNum);
		tMotifs.setTOperateur(tOperateur);
		tMotifs.setMtfLibelle(mtfLibelle);
		tMotifs.setMtfLibelleCrt(mtfLibelleCrt);
		tMotifs.setMtfType(mtfType);
		tMotifs.setMtfOpeModif(mtfOpeModif);
		tMotifs.setMtfDteSaisi(mtfDteSaisi);
		tMotifs.setMtfDteModif(mtfDteModif);
		
		tMotifs.setTMotifs(new TMotifs(this.mtfMtfNum));
		
		return tMotifs;
	}

	@Id
	@Column(name = "MTF_NUM", nullable = false, precision = 22, scale = 0)
	private BigDecimal mtfNum;

	@Column(name = "MTF_LIBELLE", length = 500)
	private String mtfLibelle;

	@Column(name = "MTF_LIBELLE_CRT", length = 200)
	private String mtfLibelleCrt;

	@Column(name = "MTF_TYPE", length = 10)
	private String mtfType;

	@Column(name = "MTF_OPE_MATRICULE", length = 25)
	private String mtfOpeMatricule;

	@Column(name = "MTF_OPE_MODIF", length = 25)
	private String mtfOpeModif;

	@Column(name = "MTF_DTE_SAISI", length = 7)
	private Date mtfDteSaisi;

	@Column(name = "MTF_DTE_MODIF", length = 7)
	private Date mtfDteModif;

	@Column(name = "CRITERE", length = 816)
	private String critere;
	
	@Column(name = "MTF_MTF_NUM", precision = 22, scale = 0)
	private BigDecimal mtfMtfNum;

}
