package com.sndi.model;
// Generated 21 sept. 2020 16:41:57 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VNatureDocAnoId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_NATURE_DOC_ANO")
public class VNatureDocAno implements java.io.Serializable {

	private short nadCode;
	private String nadLibelle;
	private String nadAbrege;
	private String nadType;

	public VNatureDocAno() {
	}

	public VNatureDocAno(short nadCode) {
		this.nadCode = nadCode;
	}

	public VNatureDocAno(short nadCode, String nadLibelle, String nadAbrege, String nadType) {
		this.nadCode = nadCode;
		this.nadLibelle = nadLibelle;
		this.nadAbrege = nadAbrege;
		this.nadType = nadType;
	}

	@Id
	@Column(name = "NAD_CODE", nullable = false, length = 3)
	public short getNadCode() {
		return this.nadCode;
	}

	public void setNadCode(short nadCode) {
		this.nadCode = nadCode;
	}

	@Column(name = "NAD_LIBELLE", length = 500)
	public String getNadLibelle() {
		return this.nadLibelle;
	}

	public void setNadLibelle(String nadLibelle) {
		this.nadLibelle = nadLibelle;
	}

	@Column(name = "NAD_ABREGE", length = 20)
	public String getNadAbrege() {
		return this.nadAbrege;
	}

	public void setNadAbrege(String nadAbrege) {
		this.nadAbrege = nadAbrege;
	}

	@Column(name = "NAD_TYPE", length = 3)
	public String getNadType() {
		return this.nadType;
	}

	public void setNadType(String nadType) {
		this.nadType = nadType;
	}
}
