package com.sndi.model;
// Generated 2 oct. 2020 19:54:19 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VPieces generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PIECES")
public class VPieces implements java.io.Serializable {

	private BigDecimal VPi;
	private long pidCode;
	private String pidLibelle;
	private String pidTpiCode;
	private String pidStaCode;
	private Date pidDteSaisi;
	private String pidDacCode;
	private String pidObservation;
	private String pidConforme;
	private String pidPresente;
	private String btnPidConforme;
	private String btnPidPresente;

	public VPieces() {
	}

	public VPieces(long pidCode) {
		this.pidCode = pidCode;
	}

	public VPieces(BigDecimal VPi, long pidCode, String pidLibelle, String pidTpiCode, String pidStaCode,
			Date pidDteSaisi, String pidDacCode, String pidObservation, String pidConforme, String pidPresente,
			String btnPidConforme, String btnPidPresente) {
		this.VPi = VPi;
		this.pidCode = pidCode;
		this.pidLibelle = pidLibelle;
		this.pidTpiCode = pidTpiCode;
		this.pidStaCode = pidStaCode;
		this.pidDteSaisi = pidDteSaisi;
		this.pidDacCode = pidDacCode;
		this.pidObservation = pidObservation;
		this.pidConforme = pidConforme;
		this.pidPresente = pidPresente;
		this.btnPidConforme = btnPidConforme;
		this.btnPidPresente = btnPidPresente;
	}

	
	@Id
	@Column(name = "V_PI", precision = 22, scale = 0)
	public BigDecimal getVPi() {
		return this.VPi;
	}

	public void setVPi(BigDecimal VPi) {
		this.VPi = VPi;
	}

	@Column(name = "PID_CODE", nullable = false, precision = 22, scale = 0)
	public long getPidCode() {
		return this.pidCode;
	}

	public void setPidCode(long pidCode) {
		this.pidCode = pidCode;
	}

	@Column(name = "PID_LIBELLE", length = 1000)
	public String getPidLibelle() {
		return this.pidLibelle;
	}

	public void setPidLibelle(String pidLibelle) {
		this.pidLibelle = pidLibelle;
	}

	@Column(name = "PID_TPI_CODE", length = 10)
	public String getPidTpiCode() {
		return this.pidTpiCode;
	}

	public void setPidTpiCode(String pidTpiCode) {
		this.pidTpiCode = pidTpiCode;
	}

	@Column(name = "PID_STA_CODE", length = 3)
	public String getPidStaCode() {
		return this.pidStaCode;
	}

	public void setPidStaCode(String pidStaCode) {
		this.pidStaCode = pidStaCode;
	}

	@Column(name = "PID_DTE_SAISI", length = 7)
	public Date getPidDteSaisi() {
		return this.pidDteSaisi;
	}

	public void setPidDteSaisi(Date pidDteSaisi) {
		this.pidDteSaisi = pidDteSaisi;
	}

	@Column(name = "PID_DAC_CODE", length = 20)
	public String getPidDacCode() {
		return this.pidDacCode;
	}

	public void setPidDacCode(String pidDacCode) {
		this.pidDacCode = pidDacCode;
	}

	@Column(name = "PID_OBSERVATION", length = 2000)
	public String getPidObservation() {
		return this.pidObservation;
	}

	public void setPidObservation(String pidObservation) {
		this.pidObservation = pidObservation;
	}

	@Column(name = "PID_CONFORME", length = 3)
	public String getPidConforme() {
		return this.pidConforme;
	}

	public void setPidConforme(String pidConforme) {
		this.pidConforme = pidConforme;
	}

	@Column(name = "PID_PRESENTE", length = 3)
	public String getPidPresente() {
		return this.pidPresente;
	}

	public void setPidPresente(String pidPresente) {
		this.pidPresente = pidPresente;
	}

	@Column(name = "BTN_PID_CONFORME", precision = 22, scale = 0)
	public String getBtnPidConforme() {
		return this.btnPidConforme;
	}

	public void setBtnPidConforme(String btnPidConforme) {
		this.btnPidConforme = btnPidConforme;
	}

	@Column(name = "BTN_PID_PRESENTE", precision = 22, scale = 0)
	public String getBtnPidPresente() {
		return this.btnPidPresente;
	}

	public void setBtnPidPresente(String btnPidPresente) {
		this.btnPidPresente = btnPidPresente;
	}

}
