package com.sndi.model;
// Generated 14 mars 2020 11:44:28 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VPiecesOffreAnalyseId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PIECES_OFFRE_ANALYSE")
public class VPiecesOffreAnalyse implements java.io.Serializable {
	
	private BigDecimal pofNum;
	private BigDecimal pofDofNum;
	private String tpoCode;
	private String pofLaaId;
	private String tpoLibelle;
	private String pofConforme;
	private String pofObs;

	public VPiecesOffreAnalyse() {
	}

	public VPiecesOffreAnalyse( String tpoCode) {
		this.tpoCode = tpoCode;
	}

	public VPiecesOffreAnalyse(BigDecimal pofNum,BigDecimal pofDofNum, String tpoCode, String pofLaaId,
			String tpoLibelle, String pofConforme, String pofObs) {
		this.pofNum = pofNum;
		this.tpoCode = tpoCode;
		this.pofLaaId = pofLaaId;
		this.tpoLibelle = tpoLibelle;
		this.pofConforme = pofConforme;
		this.pofDofNum = pofDofNum;
		this.pofObs = pofObs;
		
	}
    @Id
    @Column(name = "POF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPofNum() {
		return this.pofNum;
	}

	public void setPofNum(BigDecimal pofNum) {
		this.pofNum = pofNum;
	}
	
	@Column(name = "POF_DOF_NUM")
	public BigDecimal getPofDofNum() {
		return pofDofNum;
	}

	public void setPofDofNum(BigDecimal pofDofNum) {
		this.pofDofNum = pofDofNum;
	}

	@Column(name = "TPO_CODE", nullable = false, length = 10)
	public String getTpoCode() {
		return this.tpoCode;
	}

	public void setTpoCode(String tpoCode) {
		this.tpoCode = tpoCode;
	}

	@Column(name = "POF_LAA_ID", precision = 22, scale = 0)
	public String getPofLaaId() {
		return this.pofLaaId;
	}

	public void setPofLaaId(String pofLaaId) {
		this.pofLaaId = pofLaaId;
	}

	@Column(name = "TPO_LIBELLE", length = 200)
	public String getTpoLibelle() {
		return this.tpoLibelle;
	}

	public void setTpoLibelle(String tpoLibelle) {
		this.tpoLibelle = tpoLibelle;
	}

	@Column(name = "POF_CONFORME", length = 1)
	public String getPofConforme() {
		return this.pofConforme;
	}

	public void setPofConforme(String pofConforme) {
		this.pofConforme = pofConforme;
	}
	
	@Column(name = "POF_OBS")
	public String getPofObs() {
		return this.pofObs;
	}

	public void setPofObs(String pofObs) {
		this.pofObs = pofObs;
	}

}
