package com.sndi.model;
// Generated 12 avr. 2020 22:59:10 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VPieceDacId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PIECE_DAC")
public class VPieceDac implements java.io.Serializable {

	private BigDecimal pidCode;
	private String pidTpiCode;
	private String pidLibelle;
	private String pidDacCode;
	private String tpiMdtCode;

	public VPieceDac() {
	}

	public VPieceDac(BigDecimal pidCode) {
		this.pidCode = pidCode;
	}

	public VPieceDac(BigDecimal pidCode, String pidTpiCode, String pidLibelle, String pidDacCode, String tpiMdtCode) {
		this.pidCode = pidCode;
		this.pidTpiCode = pidTpiCode;
		this.pidLibelle = pidLibelle;
		this.pidDacCode = pidDacCode;
		this.tpiMdtCode = tpiMdtCode;
	}

	@Id
	@Column(name = "PID_CODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPidCode() {
		return this.pidCode;
	}

	public void setPidCode(BigDecimal pidCode) {
		this.pidCode = pidCode;
	}

	@Column(name = "PID_TPI_CODE", length = 10)
	public String getPidTpiCode() {
		return this.pidTpiCode;
	}

	public void setPidTpiCode(String pidTpiCode) {
		this.pidTpiCode = pidTpiCode;
	}

	@Column(name = "PID_LIBELLE", length = 1008)
	public String getPidLibelle() {
		return this.pidLibelle;
	}

	public void setPidLibelle(String pidLibelle) {
		this.pidLibelle = pidLibelle;
	}

	@Column(name = "PID_DAC_CODE", length = 20)
	public String getPidDacCode() {
		return this.pidDacCode;
	}

	public void setPidDacCode(String pidDacCode) {
		this.pidDacCode = pidDacCode;
	}

	@Column(name = "TPI_MDT_CODE", length = 10)
	public String getTpiMdtCode() {
		return this.tpiMdtCode;
	}

	public void setTpiMdtCode(String tpiMdtCode) {
		this.tpiMdtCode = tpiMdtCode;
	}

}
