package com.sndi.model;
// Generated 2 oct. 2020 20:58:51 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VPiecesOffreAnalyse generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PIECES_OFFRE_ANALYSE")
public class VPiecesOffreAnalyse implements java.io.Serializable {

	private BigDecimal pofNum;
	private String craCode;
	private BigDecimal dofNum;
	private BigDecimal dcadNum;
	private String analyseStatut;
	private BigDecimal dcadLaaId;
	private String pofLibelle;
	private String pofConforme;
	private Long pofScore;
	private String pofObs;
	private String anfPresence;
	private BigDecimal anfNum;
	private String dcadDacCode;
	private String btnAnfValeurConf;
	private String btnAnfPresence;

	public VPiecesOffreAnalyse() {
	}

	public VPiecesOffreAnalyse(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	public VPiecesOffreAnalyse(BigDecimal pofNum, String craCode, BigDecimal dofNum, BigDecimal dcadNum,
			String analyseStatut, BigDecimal dcadLaaId, String pofLibelle, String pofConforme, Long pofScore,
			String pofObs, String anfPresence, BigDecimal anfNum, String dcadDacCode, String btnAnfValeurConf,
			String btnAnfPresence) {
		this.pofNum = pofNum;
		this.craCode = craCode;
		this.dofNum = dofNum;
		this.dcadNum = dcadNum;
		this.analyseStatut = analyseStatut;
		this.dcadLaaId = dcadLaaId;
		this.pofLibelle = pofLibelle;
		this.pofConforme = pofConforme;
		this.pofScore = pofScore;
		this.pofObs = pofObs;
		this.anfPresence = anfPresence;
		this.anfNum = anfNum;
		this.dcadDacCode = dcadDacCode;
		this.btnAnfValeurConf = btnAnfValeurConf;
		this.btnAnfPresence = btnAnfPresence;
	}

	
	@Id
	@Column(name = "POF_NUM", precision = 22, scale = 0)
	public BigDecimal getPofNum() {
		return this.pofNum;
	}

	public void setPofNum(BigDecimal pofNum) {
		this.pofNum = pofNum;
	}

	@Column(name = "CRA_CODE", length = 50)
	public String getCraCode() {
		return this.craCode;
	}

	public void setCraCode(String craCode) {
		this.craCode = craCode;
	}

	@Column(name = "DOF_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	@Column(name = "DCAD_NUM", precision = 22, scale = 0)
	public BigDecimal getDcadNum() {
		return this.dcadNum;
	}

	public void setDcadNum(BigDecimal dcadNum) {
		this.dcadNum = dcadNum;
	}

	@Column(name = "ANALYSE_STATUT", length = 1)
	public String getAnalyseStatut() {
		return this.analyseStatut;
	}

	public void setAnalyseStatut(String analyseStatut) {
		this.analyseStatut = analyseStatut;
	}

	@Column(name = "DCAD_LAA_ID", precision = 22, scale = 0)
	public BigDecimal getDcadLaaId() {
		return this.dcadLaaId;
	}

	public void setDcadLaaId(BigDecimal dcadLaaId) {
		this.dcadLaaId = dcadLaaId;
	}

	@Column(name = "POF_LIBELLE", length = 4000)
	public String getPofLibelle() {
		return this.pofLibelle;
	}

	public void setPofLibelle(String pofLibelle) {
		this.pofLibelle = pofLibelle;
	}

	@Column(name = "POF_CONFORME", length = 100)
	public String getPofConforme() {
		return this.pofConforme;
	}

	public void setPofConforme(String pofConforme) {
		this.pofConforme = pofConforme;
	}

	@Column(name = "POF_SCORE", precision = 10, scale = 0)
	public Long getPofScore() {
		return this.pofScore;
	}

	public void setPofScore(Long pofScore) {
		this.pofScore = pofScore;
	}

	@Column(name = "POF_OBS", length = 1000)
	public String getPofObs() {
		return this.pofObs;
	}

	public void setPofObs(String pofObs) {
		this.pofObs = pofObs;
	}

	@Column(name = "ANF_PRESENCE", length = 1)
	public String getAnfPresence() {
		return this.anfPresence;
	}

	public void setAnfPresence(String anfPresence) {
		this.anfPresence = anfPresence;
	}

	@Column(name = "ANF_NUM", precision = 22, scale = 0)
	public BigDecimal getAnfNum() {
		return this.anfNum;
	}

	public void setAnfNum(BigDecimal anfNum) {
		this.anfNum = anfNum;
	}

	@Column(name = "DCAD_DAC_CODE", length = 50)
	public String getDcadDacCode() {
		return this.dcadDacCode;
	}

	public void setDcadDacCode(String dcadDacCode) {
		this.dcadDacCode = dcadDacCode;
	}

	@Column(name = "BTN_ANF_VALEUR_CONF", precision = 22, scale = 0)
	public String getBtnAnfValeurConf() {
		return this.btnAnfValeurConf;
	}

	public void setBtnAnfValeurConf(String btnAnfValeurConf) {
		this.btnAnfValeurConf = btnAnfValeurConf;
	}

	@Column(name = "BTN_ANF_PRESENCE", precision = 22, scale = 0)
	public String getBtnAnfPresence() {
		return this.btnAnfPresence;
	}

	public void setBtnAnfPresence(String btnAnfPresence) {
		this.btnAnfPresence = btnAnfPresence;
	}

}
