package com.sndi.model;
// Generated 26 avr. 2021 17:28:05 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VPpmStatutId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PPM_STATUT")
public class VPpmStatut implements java.io.Serializable {

	private long hppId;
	private long hppDppId;
	private String hppStaCode;
	private String staLibelleCourt;
	private String staLibelleLong;
	private Date hppDate;
	private String hppMotif;
	private String fonCod;
	private String fonCodePf;
	private String fonLibelle;

	public VPpmStatut() {
	}

	public VPpmStatut(long hppId, long hppDppId, String hppStaCode) {
		this.hppId = hppId;
		this.hppDppId = hppDppId;
		this.hppStaCode = hppStaCode;
	}

	public VPpmStatut(long hppId, long hppDppId, String hppStaCode, String staLibelleCourt, String staLibelleLong,
			Date hppDate, String hppMotif, String fonCod, String fonCodePf, String fonLibelle) {
		this.hppId = hppId;
		this.hppDppId = hppDppId;
		this.hppStaCode = hppStaCode;
		this.staLibelleCourt = staLibelleCourt;
		this.staLibelleLong = staLibelleLong;
		this.hppDate = hppDate;
		this.hppMotif = hppMotif;
		this.fonCod = fonCod;
		this.fonCodePf = fonCodePf;
		this.fonLibelle = fonLibelle;
	}

	@Id
	@Column(name = "HPP_ID", nullable = false, precision = 10, scale = 0)
	public long getHppId() {
		return this.hppId;
	}

	public void setHppId(long hppId) {
		this.hppId = hppId;
	}

	@Column(name = "HPP_DPP_ID", nullable = false, precision = 10, scale = 0)
	public long getHppDppId() {
		return this.hppDppId;
	}

	public void setHppDppId(long hppDppId) {
		this.hppDppId = hppDppId;
	}

	@Column(name = "HPP_STA_CODE", nullable = false, length = 3)
	public String getHppStaCode() {
		return this.hppStaCode;
	}

	public void setHppStaCode(String hppStaCode) {
		this.hppStaCode = hppStaCode;
	}

	@Column(name = "STA_LIBELLE_COURT", length = 500)
	public String getStaLibelleCourt() {
		return this.staLibelleCourt;
	}

	public void setStaLibelleCourt(String staLibelleCourt) {
		this.staLibelleCourt = staLibelleCourt;
	}

	@Column(name = "STA_LIBELLE_LONG", length = 1000)
	public String getStaLibelleLong() {
		return this.staLibelleLong;
	}

	public void setStaLibelleLong(String staLibelleLong) {
		this.staLibelleLong = staLibelleLong;
	}

	@Column(name = "HPP_DATE", length = 7)
	public Date getHppDate() {
		return this.hppDate;
	}

	public void setHppDate(Date hppDate) {
		this.hppDate = hppDate;
	}

	@Column(name = "HPP_MOTIF", length = 1000)
	public String getHppMotif() {
		return this.hppMotif;
	}

	public void setHppMotif(String hppMotif) {
		this.hppMotif = hppMotif;
	}

	@Column(name = "FON_COD", length = 20)
	public String getFonCod() {
		return this.fonCod;
	}

	public void setFonCod(String fonCod) {
		this.fonCod = fonCod;
	}

	@Column(name = "FON_CODE_PF", length = 20)
	public String getFonCodePf() {
		return this.fonCodePf;
	}

	public void setFonCodePf(String fonCodePf) {
		this.fonCodePf = fonCodePf;
	}

	@Column(name = "FON_LIBELLE", length = 500)
	public String getFonLibelle() {
		return this.fonLibelle;
	}

	public void setFonLibelle(String fonLibelle) {
		this.fonLibelle = fonLibelle;
	}

}
