package com.sndi.model;
// Generated 14 déc. 2020 19:05:35 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VPrgAoId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PRG_AO")
public class VPrgAo implements java.io.Serializable {

	private long dppId;
	private String dppObjet;

	public VPrgAo() {
	}

	public VPrgAo(long dppId) {
		this.dppId = dppId;
	}

	public VPrgAo(long dppId, String dppObjet) {
		this.dppId = dppId;
		this.dppObjet = dppObjet;
	}

	@Id
	@Column(name = "DPP_ID", nullable = false, precision = 10, scale = 0)
	public long getDppId() {
		return this.dppId;
	}

	public void setDppId(long dppId) {
		this.dppId = dppId;
	}

	@Column(name = "DPP_OBJET", length = 1000)
	public String getDppObjet() {
		return this.dppObjet;
	}

	public void setDppObjet(String dppObjet) {
		this.dppObjet = dppObjet;
	}
}
