package com.sndi.model;
// Generated 15 déc. 2019 01:13:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VProjetAgpm generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_PROJET_AGPM")
public class VProjetAgpm implements java.io.Serializable {

	private long proId;
	private String proTitre;
	private String proTypeProjet;
	private String agpTypeDao;
	private String agpStaCode;
	private String agpActif;
	private BigDecimal proMontantTotCfa;
	private String proDescription;
	private long agpId;
	private Long agpDecId;
	private String agpModePassation;
	private long agpGesCode;
	private String agpCommentaire;
	private String agpStrCode;
	private String agpActeurSaisie;
	private Long regId;
	private String regLibelleLong;
	private String regLibelleCourt;
	private String minLibelle;
	private String minLibelleCourt;
	private String baiLibelle;
	private String devLibelle;
	private String souLibelle;
	private String finNumeroAccord;
	private BigDecimal finMontantCfa;
	private BigDecimal finMontantDevise;
	private String fonLibelle;

	public VProjetAgpm() {
		super();
	}
	
	
	public VProjetAgpm(long proId, String proTitre, String agpStaCode, long agpId, long agpGesCode,
			String agpStrCode, String baiLibelle) {
		this.proId = proId;
		this.proTitre = proTitre;
		this.agpStaCode = agpStaCode;
		this.agpId = agpId;
		this.agpGesCode = agpGesCode;
		this.agpStrCode = agpStrCode;
		this.baiLibelle = baiLibelle;
	}

	public VProjetAgpm(long proId, String proTitre, String proTypeProjet, String agpTypeDao, String agpStaCode,
			String agpActif, BigDecimal proMontantTotCfa, String proDescription, long agpId, Long agpDecId,
			String agpModePassation, long agpGesCode, String agpCommentaire, String agpStrCode, String agpActeurSaisie,
			Long regId, String regLibelleLong, String regLibelleCourt, String minLibelle, String minLibelleCourt,
			String baiLibelle, String devLibelle, String souLibelle, String finNumeroAccord, BigDecimal finMontantCfa,
			BigDecimal finMontantDevise, String fonLibelle) {
		this.proId = proId;
		this.proTitre = proTitre;
		this.proTypeProjet = proTypeProjet;
		this.agpTypeDao = agpTypeDao;
		this.agpStaCode = agpStaCode;
		this.agpActif = agpActif;
		this.proMontantTotCfa = proMontantTotCfa;
		this.proDescription = proDescription;
		this.agpId = agpId;
		this.agpDecId = agpDecId;
		this.agpModePassation = agpModePassation;
		this.agpGesCode = agpGesCode;
		this.agpCommentaire = agpCommentaire;
		this.agpStrCode = agpStrCode;
		this.agpActeurSaisie = agpActeurSaisie;
		this.regId = regId;
		this.regLibelleLong = regLibelleLong;
		this.regLibelleCourt = regLibelleCourt;
		this.minLibelle = minLibelle;
		this.minLibelleCourt = minLibelleCourt;
		this.baiLibelle = baiLibelle;
		this.devLibelle = devLibelle;
		this.souLibelle = souLibelle;
		this.finNumeroAccord = finNumeroAccord;
		this.finMontantCfa = finMontantCfa;
		this.finMontantDevise = finMontantDevise;
		this.fonLibelle = fonLibelle;
	}

	
	@Id
	@Column(name = "PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getProId() {
		return this.proId;
	}

	public void setProId(long proId) {
		this.proId = proId;
	}

	@Column(name = "PRO_TITRE", nullable = false, length = 500)
	public String getProTitre() {
		return this.proTitre;
	}

	public void setProTitre(String proTitre) {
		this.proTitre = proTitre;
	}

	@Column(name = "PRO_TYPE_PROJET", length = 10)
	public String getProTypeProjet() {
		return this.proTypeProjet;
	}

	public void setProTypeProjet(String proTypeProjet) {
		this.proTypeProjet = proTypeProjet;
	}

	@Column(name = "AGP_TYPE_DAO", length = 1000)
	public String getAgpTypeDao() {
		return this.agpTypeDao;
	}

	public void setAgpTypeDao(String agpTypeDao) {
		this.agpTypeDao = agpTypeDao;
	}

	@Column(name = "AGP_STA_CODE", nullable = false, length = 3)
	public String getAgpStaCode() {
		return this.agpStaCode;
	}

	public void setAgpStaCode(String agpStaCode) {
		this.agpStaCode = agpStaCode;
	}

	@Column(name = "AGP_ACTIF", length = 1)
	public String getAgpActif() {
		return this.agpActif;
	}

	public void setAgpActif(String agpActif) {
		this.agpActif = agpActif;
	}

	@Column(name = "PRO_MONTANT_TOT_CFA", precision = 15)
	public BigDecimal getProMontantTotCfa() {
		return this.proMontantTotCfa;
	}

	public void setProMontantTotCfa(BigDecimal proMontantTotCfa) {
		this.proMontantTotCfa = proMontantTotCfa;
	}

	@Column(name = "PRO_DESCRIPTION", length = 1000)
	public String getProDescription() {
		return this.proDescription;
	}

	public void setProDescription(String proDescription) {
		this.proDescription = proDescription;
	}

	@Column(name = "AGP_ID", nullable = false, precision = 10, scale = 0)
	public long getAgpId() {
		return this.agpId;
	}

	public void setAgpId(long agpId) {
		this.agpId = agpId;
	}

	@Column(name = "AGP_DEC_ID", precision = 10, scale = 0)
	public Long getAgpDecId() {
		return this.agpDecId;
	}

	public void setAgpDecId(Long agpDecId) {
		this.agpDecId = agpDecId;
	}

	@Column(name = "AGP_MODE_PASSATION", length = 1000)
	public String getAgpModePassation() {
		return this.agpModePassation;
	}

	public void setAgpModePassation(String agpModePassation) {
		this.agpModePassation = agpModePassation;
	}

	@Column(name = "AGP_GES_CODE", nullable = false, precision = 4, scale = 0)
	public long getAgpGesCode() {
		return this.agpGesCode;
	}

	public void setAgpGesCode(long agpGesCode) {
		this.agpGesCode = agpGesCode;
	}

	@Column(name = "AGP_COMMENTAIRE", length = 1000)
	public String getAgpCommentaire() {
		return this.agpCommentaire;
	}

	public void setAgpCommentaire(String agpCommentaire) {
		this.agpCommentaire = agpCommentaire;
	}

	@Column(name = "AGP_STR_CODE", nullable = false, length = 3)
	public String getAgpStrCode() {
		return this.agpStrCode;
	}

	public void setAgpStrCode(String agpStrCode) {
		this.agpStrCode = agpStrCode;
	}

	@Column(name = "AGP_ACTEUR_SAISIE", length = 12)
	public String getAgpActeurSaisie() {
		return this.agpActeurSaisie;
	}

	public void setAgpActeurSaisie(String agpActeurSaisie) {
		this.agpActeurSaisie = agpActeurSaisie;
	}

	@Column(name = "REG_ID", precision = 10, scale = 0)
	public Long getRegId() {
		return this.regId;
	}

	public void setRegId(Long regId) {
		this.regId = regId;
	}

	@Column(name = "REG_LIBELLE_LONG", length = 1000)
	public String getRegLibelleLong() {
		return this.regLibelleLong;
	}

	public void setRegLibelleLong(String regLibelleLong) {
		this.regLibelleLong = regLibelleLong;
	}

	@Column(name = "REG_LIBELLE_COURT", length = 500)
	public String getRegLibelleCourt() {
		return this.regLibelleCourt;
	}

	public void setRegLibelleCourt(String regLibelleCourt) {
		this.regLibelleCourt = regLibelleCourt;
	}

	@Column(name = "MIN_LIBELLE", length = 1000)
	public String getMinLibelle() {
		return this.minLibelle;
	}

	public void setMinLibelle(String minLibelle) {
		this.minLibelle = minLibelle;
	}

	@Column(name = "MIN_LIBELLE_COURT", length = 500)
	public String getMinLibelleCourt() {
		return this.minLibelleCourt;
	}

	public void setMinLibelleCourt(String minLibelleCourt) {
		this.minLibelleCourt = minLibelleCourt;
	}

	@Column(name = "BAI_LIBELLE", nullable = false, length = 1000)
	public String getBaiLibelle() {
		return this.baiLibelle;
	}

	public void setBaiLibelle(String baiLibelle) {
		this.baiLibelle = baiLibelle;
	}

	@Column(name = "DEV_LIBELLE", length = 500)
	public String getDevLibelle() {
		return this.devLibelle;
	}

	public void setDevLibelle(String devLibelle) {
		this.devLibelle = devLibelle;
	}

	@Column(name = "SOU_LIBELLE", length = 500)
	public String getSouLibelle() {
		return this.souLibelle;
	}

	public void setSouLibelle(String souLibelle) {
		this.souLibelle = souLibelle;
	}

	@Column(name = "FIN_NUMERO_ACCORD", length = 500)
	public String getFinNumeroAccord() {
		return this.finNumeroAccord;
	}

	public void setFinNumeroAccord(String finNumeroAccord) {
		this.finNumeroAccord = finNumeroAccord;
	}

	@Column(name = "FIN_MONTANT_CFA", precision = 15)
	public BigDecimal getFinMontantCfa() {
		return this.finMontantCfa;
	}

	public void setFinMontantCfa(BigDecimal finMontantCfa) {
		this.finMontantCfa = finMontantCfa;
	}

	@Column(name = "FIN_MONTANT_DEVISE", precision = 15)
	public BigDecimal getFinMontantDevise() {
		return this.finMontantDevise;
	}

	public void setFinMontantDevise(BigDecimal finMontantDevise) {
		this.finMontantDevise = finMontantDevise;
	}

	@Column(name = "FON_LIBELLE", length = 240)
	public String getFonLibelle() {
		return this.fonLibelle;
	}

	public void setFonLibelle(String fonLibelle) {
		this.fonLibelle = fonLibelle;
	}

}
