package com.sndi.model;
// Generated 2 juil. 2020 21:16:58 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VRecapSeuilAnormal generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_RECAP_SEUIL_ANORMAL")
public class VRecapSeuilAnormal implements java.io.Serializable {

	private BigDecimal dofLaaId;
	private BigDecimal laaMtEst;
	private BigDecimal moyOffFinQualtech;
	private BigDecimal moyPonderee;
	private BigDecimal sf1;
	private BigDecimal sf2;
	private BigDecimal mtMoinsDisant;

	public VRecapSeuilAnormal() {
	}

	public VRecapSeuilAnormal(BigDecimal dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	public VRecapSeuilAnormal(BigDecimal dofLaaId, BigDecimal laaMtEst, BigDecimal moyOffFinQualtech,
			BigDecimal moyPonderee, BigDecimal sf1, BigDecimal sf2, BigDecimal mtMoinsDisant) {
		this.dofLaaId = dofLaaId;
		this.laaMtEst = laaMtEst;
		this.moyOffFinQualtech = moyOffFinQualtech;
		this.moyPonderee = moyPonderee;
		this.sf1 = sf1;
		this.sf2 = sf2;
		this.mtMoinsDisant = mtMoinsDisant;
	}

	@Id
	@Column(name = "DOF_LAA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDofLaaId() {
		return this.dofLaaId;
	}

	public void setDofLaaId(BigDecimal dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	@Column(name = "LAA_MT_EST", precision = 22, scale = 0)
	public BigDecimal getLaaMtEst() {
		return this.laaMtEst;
	}

	public void setLaaMtEst(BigDecimal laaMtEst) {
		this.laaMtEst = laaMtEst;
	}

	@Column(name = "MOY_OFF_FIN_QUALTECH", precision = 22, scale = 0)
	public BigDecimal getMoyOffFinQualtech() {
		return this.moyOffFinQualtech;
	}

	public void setMoyOffFinQualtech(BigDecimal moyOffFinQualtech) {
		this.moyOffFinQualtech = moyOffFinQualtech;
	}

	@Column(name = "MOY_PONDEREE", precision = 22, scale = 0)
	public BigDecimal getMoyPonderee() {
		return this.moyPonderee;
	}

	public void setMoyPonderee(BigDecimal moyPonderee) {
		this.moyPonderee = moyPonderee;
	}

	@Column(name = "SF1", precision = 22, scale = 0)
	public BigDecimal getSf1() {
		return this.sf1;
	}

	public void setSf1(BigDecimal sf1) {
		this.sf1 = sf1;
	}

	@Column(name = "SF2", precision = 22, scale = 0)
	public BigDecimal getSf2() {
		return this.sf2;
	}

	public void setSf2(BigDecimal sf2) {
		this.sf2 = sf2;
	}

	@Column(name = "MT_MOINS_DISANT", precision = 22, scale = 0)
	public BigDecimal getMtMoinsDisant() {
		return this.mtMoinsDisant;
	}

	public void setMtMoinsDisant(BigDecimal mtMoinsDisant) {
		this.mtMoinsDisant = mtMoinsDisant;
	}

}
