package com.sndi.model;
// Generated 4 sept. 2020 14:32:11 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VReeditCojoId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_REEDIT_COJO")
public class VReeditCojo implements java.io.Serializable {

	private String aaoDacCode;
	private String aaoCode;

	public VReeditCojo() {
	}

	public VReeditCojo(String aaoCode) {
		this.aaoCode = aaoCode;
	}

	public VReeditCojo(String aaoDacCode, String aaoCode) {
		this.aaoDacCode = aaoDacCode;
		this.aaoCode = aaoCode;
	}
	@Id
	@Column(name = "AAO_DAC_CODE", length = 20)
	public String getAaoDacCode() {
		return this.aaoDacCode;
	}

	
	public void setAaoDacCode(String aaoDacCode) {
		this.aaoDacCode = aaoDacCode;
	}

	@Column(name = "AAO_CODE", nullable = false, length = 20)
	public String getAaoCode() {
		return this.aaoCode;
	}

	public void setAaoCode(String aaoCode) {
		this.aaoCode = aaoCode;
	}
}
