package com.sndi.model;
// Generated 13 juil. 2020 11:39:13 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VRepSoumissionnaire generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_REP_SOUMISSIONNAIRE")
public class VRepSoumissionnaire implements java.io.Serializable {

	private BigDecimal dcsid;
	private String dcsDacCode;
	private String dcsNom;
	private String dcsPrenoms;
	private String tel;
	private String dcsMail;
	private String dcsSouNcc;
	private String souSigleSte;

	public VRepSoumissionnaire() {
	}

	public VRepSoumissionnaire(BigDecimal dcsid, String dcsDacCode, String dcsNom, String dcsPrenoms, String tel,
			String dcsMail, String dcsSouNcc, String souSigleSte) {
		this.dcsid = dcsid;
		this.dcsDacCode = dcsDacCode;
		this.dcsNom = dcsNom;
		this.dcsPrenoms = dcsPrenoms;
		this.tel = tel;
		this.dcsMail = dcsMail;
		this.dcsSouNcc = dcsSouNcc;
		this.souSigleSte = souSigleSte;
	}

	
	@Id
	@Column(name = "DCSID", precision = 22, scale = 0)
	public BigDecimal getDcsid() {
		return this.dcsid;
	}

	public void setDcsid(BigDecimal dcsid) {
		this.dcsid = dcsid;
	}

	@Column(name = "DCS_DAC_CODE", length = 20)
	public String getDcsDacCode() {
		return this.dcsDacCode;
	}

	public void setDcsDacCode(String dcsDacCode) {
		this.dcsDacCode = dcsDacCode;
	}

	@Column(name = "DCS_NOM", length = 100)
	public String getDcsNom() {
		return this.dcsNom;
	}

	public void setDcsNom(String dcsNom) {
		this.dcsNom = dcsNom;
	}

	@Column(name = "DCS_PRENOMS", length = 200)
	public String getDcsPrenoms() {
		return this.dcsPrenoms;
	}

	public void setDcsPrenoms(String dcsPrenoms) {
		this.dcsPrenoms = dcsPrenoms;
	}

	@Column(name = "TEL", length = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "DCS_MAIL", length = 200)
	public String getDcsMail() {
		return this.dcsMail;
	}

	public void setDcsMail(String dcsMail) {
		this.dcsMail = dcsMail;
	}

	@Column(name = "DCS_SOU_NCC", length = 200)
	public String getDcsSouNcc() {
		return this.dcsSouNcc;
	}

	public void setDcsSouNcc(String dcsSouNcc) {
		this.dcsSouNcc = dcsSouNcc;
	}
	
	@Column(name = "SOU_SIGLE_STE", length = 500)
	public String getSouSigleSte() {
		return this.souSigleSte;
	}

	public void setSouSigleSte(String souSigleSte) {
		this.souSigleSte = souSigleSte;
	}

}
