package com.sndi.model;
// Generated 2 juil. 2020 19:52:59 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VResultPropAttribLot generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_RESULT_PROP_ATTRIB_LOT")
public class VResultPropAttribLot implements java.io.Serializable {

	private BigDecimal RId;
	private BigDecimal ordre;
	private BigDecimal dofNum;
	private String rang;
	private String laaDacCode;
	private BigDecimal lot;
	private BigDecimal dofLaaId;
	private String entreprise;
	private BigDecimal montant;
	private BigDecimal dofMtAtt;
	private BigDecimal noteCombinee;
	private BigDecimal delai;
	private BigDecimal delai2;
	private String offSouNcc;
	private String dofStatut;
	private String offSouSigleSte;
	private Date dofAttribDte;

	public VResultPropAttribLot() {
	}


	public VResultPropAttribLot(BigDecimal RId, BigDecimal ordre, BigDecimal dofNum,String rang, String laaDacCode,
			BigDecimal lot,BigDecimal dofLaaId ,String entreprise, BigDecimal montant,BigDecimal dofMtAtt, BigDecimal noteCombinee, BigDecimal delai, BigDecimal delai2,
			String offSouNcc, String offSouSigleSte,Date dofAttribDte,String dofStatut) {
       this.RId = RId;
       this.ordre = ordre;
       this.rang = rang;
       this.laaDacCode = laaDacCode;
       this.lot = lot;
       this.setDofLaaId(dofLaaId);
       this.entreprise = entreprise;
       this.montant = montant;
       this.noteCombinee = noteCombinee;
       this.delai = delai;
       this.delai2 = delai2;
       this.offSouNcc = offSouNcc;
       this.offSouSigleSte = offSouSigleSte;
       this.dofNum = dofNum;
       this.dofMtAtt = dofMtAtt;
       this.dofAttribDte = dofAttribDte;
       this.dofStatut = dofStatut;
    }

	
	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "ORDRE", precision = 22, scale = 0)
	public BigDecimal getOrdre() {
		return this.ordre;
	}

	public void setOrdre(BigDecimal ordre) {
		this.ordre = ordre;
	}
	
	@Column(name = "DOF_NUM")
	public BigDecimal getDofNum() {
		return this.dofNum;
	}

	public void setDofNum(BigDecimal dofNum) {
		this.dofNum = dofNum;
	}

	@Column(name = "RANG", length = 42)
	public String getRang() {
		return this.rang;
	}

	public void setRang(String rang) {
		this.rang = rang;
	}

	@Column(name = "LAA_DAC_CODE", length = 20)
	public String getLaaDacCode() {
		return this.laaDacCode;
	}

	public void setLaaDacCode(String laaDacCode) {
		this.laaDacCode = laaDacCode;
	}

	@Column(name = "LOT", precision = 22, scale = 0)
	public BigDecimal getLot() {
		return this.lot;
	}

	public void setLot(BigDecimal lot) {
		this.lot = lot;
	}
	
	@Column(name = "DOF_LAA_ID")
	public BigDecimal getDofLaaId() {
		return dofLaaId;
	}

	public void setDofLaaId(BigDecimal dofLaaId) {
		this.dofLaaId = dofLaaId;
	}

	@Column(name = "ENTREPRISE", length = 523)
	public String getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(String entreprise) {
		this.entreprise = entreprise;
	}

	@Column(name = "MONTANT", precision = 20, scale = 0)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}
	
	@Column(name = "DOF_MT_ATT")
	public BigDecimal getDofMtAtt() {
		return this.dofMtAtt;
	}

	public void setDofMtAtt(BigDecimal dofMtAtt) {
		this.dofMtAtt = dofMtAtt;
	}

	@Column(name = "NOTE_COMBINEE", precision = 22, scale = 0)
	public BigDecimal getNoteCombinee() {
		return this.noteCombinee;
	}

	public void setNoteCombinee(BigDecimal noteCombinee) {
		this.noteCombinee = noteCombinee;
	}

	@Column(name = "DELAI", nullable = false, precision = 20, scale = 0)
	public BigDecimal getDelai() {
		return this.delai;
	}

	public void setDelai(BigDecimal delai) {
		this.delai = delai;
	}
	
	@Column(name = "DELAI2", precision = 20, scale = 0)
	public BigDecimal getDelai2() {
		return this.delai2;
	}

	public void setDelai2(BigDecimal delai2) {
		this.delai2 = delai2;
	}

	@Column(name = "OFF_SOU_NCC", length = 20)
	public String getOffSouNcc() {
		return this.offSouNcc;
	}

	public void setOffSouNcc(String offSouNcc) {
		this.offSouNcc = offSouNcc;
	}

	@Column(name = "OFF_SOU_SIGLE_STE", length = 500)
	public String getOffSouSigleSte() {
		return this.offSouSigleSte;
	}

	public void setOffSouSigleSte(String offSouSigleSte) {
		this.offSouSigleSte = offSouSigleSte;
	}


	@Column(name = "DOF_ATTRIB_DTE")
	public Date getDofAttribDte() {
		return dofAttribDte;
	}


	public void setDofAttribDte(Date dofAttribDte) {
		this.dofAttribDte = dofAttribDte;
	}

	@Column(name = "DOF_STATUT")
	public String getDofStatut() {
		return dofStatut;
	}


	public void setDofStatut(String dofStatut) {
		this.dofStatut = dofStatut;
	}
	

}
