package com.sndi.model;
// Generated 2 juil. 2020 19:52:59 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VResultEvalClassLot generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_RESULT_EVAL_CLASS_LOT")
public class VResultEvalClassLot implements java.io.Serializable {

	private BigDecimal RId;
	private String rang;
	private String laaDacCode;
	private BigDecimal laaNum;
	private BigDecimal ordre;
	private String offSouNcc;
	private String offSouSigleSte;
	private BigDecimal dofMtCor;
	private String aaoRegQual;
	private BigDecimal mtMoinsDisant;
	private BigDecimal noteFinanciere;
	private BigDecimal valeurScore;
	private BigDecimal noteCombinee;
	private BigDecimal delai;
	private String commentaireOffin;
	private String commentaireAnormal;
	private String commentaireOffret;

	public VResultEvalClassLot() {
	}

	public VResultEvalClassLot(BigDecimal delai) {
		this.delai = delai;
	}

	public VResultEvalClassLot(BigDecimal RId, String rang, String laaDacCode, BigDecimal laaNum, BigDecimal ordre,
			String offSouNcc, String offSouSigleSte, BigDecimal dofMtCor, String aaoRegQual, BigDecimal mtMoinsDisant,
			BigDecimal noteFinanciere, BigDecimal valeurScore, BigDecimal noteCombinee, BigDecimal delai,
			String commentaireOffin, String commentaireAnormal, String commentaireOffret) {
		this.RId = RId;
		this.rang = rang;
		this.laaDacCode = laaDacCode;
		this.laaNum = laaNum;
		this.ordre = ordre;
		this.offSouNcc = offSouNcc;
		this.offSouSigleSte = offSouSigleSte;
		this.dofMtCor = dofMtCor;
		this.aaoRegQual = aaoRegQual;
		this.mtMoinsDisant = mtMoinsDisant;
		this.noteFinanciere = noteFinanciere;
		this.valeurScore = valeurScore;
		this.noteCombinee = noteCombinee;
		this.delai = delai;
		this.commentaireOffin = commentaireOffin;
		this.commentaireAnormal = commentaireAnormal;
		this.commentaireOffret = commentaireOffret;
	}

	@Id
	@Column(name = "R_ID", precision = 22, scale = 0)
	public BigDecimal getRId() {
		return this.RId;
	}

	public void setRId(BigDecimal RId) {
		this.RId = RId;
	}

	@Column(name = "RANG", length = 42)
	public String getRang() {
		return this.rang;
	}

	public void setRang(String rang) {
		this.rang = rang;
	}

	@Column(name = "LAA_DAC_CODE", length = 20)
	public String getLaaDacCode() {
		return this.laaDacCode;
	}

	public void setLaaDacCode(String laaDacCode) {
		this.laaDacCode = laaDacCode;
	}

	@Column(name = "LAA_NUM", precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "ORDRE", precision = 22, scale = 0)
	public BigDecimal getOrdre() {
		return this.ordre;
	}

	public void setOrdre(BigDecimal ordre) {
		this.ordre = ordre;
	}

	@Column(name = "OFF_SOU_NCC", length = 20)
	public String getOffSouNcc() {
		return this.offSouNcc;
	}

	public void setOffSouNcc(String offSouNcc) {
		this.offSouNcc = offSouNcc;
	}

	@Column(name = "OFF_SOU_SIGLE_STE", length = 500)
	public String getOffSouSigleSte() {
		return this.offSouSigleSte;
	}

	public void setOffSouSigleSte(String offSouSigleSte) {
		this.offSouSigleSte = offSouSigleSte;
	}

	@Column(name = "DOF_MT_COR", precision = 20, scale = 0)
	public BigDecimal getDofMtCor() {
		return this.dofMtCor;
	}

	public void setDofMtCor(BigDecimal dofMtCor) {
		this.dofMtCor = dofMtCor;
	}

	@Column(name = "AAO_REG_QUAL", length = 100)
	public String getAaoRegQual() {
		return this.aaoRegQual;
	}

	public void setAaoRegQual(String aaoRegQual) {
		this.aaoRegQual = aaoRegQual;
	}

	@Column(name = "MT_MOINS_DISANT", precision = 22, scale = 0)
	public BigDecimal getMtMoinsDisant() {
		return this.mtMoinsDisant;
	}

	public void setMtMoinsDisant(BigDecimal mtMoinsDisant) {
		this.mtMoinsDisant = mtMoinsDisant;
	}

	@Column(name = "NOTE_FINANCIERE", precision = 22, scale = 0)
	public BigDecimal getNoteFinanciere() {
		return this.noteFinanciere;
	}

	public void setNoteFinanciere(BigDecimal noteFinanciere) {
		this.noteFinanciere = noteFinanciere;
	}

	@Column(name = "VALEUR_SCORE", precision = 22, scale = 0)
	public BigDecimal getValeurScore() {
		return this.valeurScore;
	}

	public void setValeurScore(BigDecimal valeurScore) {
		this.valeurScore = valeurScore;
	}

	@Column(name = "NOTE_COMBINEE", precision = 22, scale = 0)
	public BigDecimal getNoteCombinee() {
		return this.noteCombinee;
	}

	public void setNoteCombinee(BigDecimal noteCombinee) {
		this.noteCombinee = noteCombinee;
	}

	@Column(name = "DELAI", nullable = false, precision = 20, scale = 0)
	public BigDecimal getDelai() {
		return this.delai;
	}

	public void setDelai(BigDecimal delai) {
		this.delai = delai;
	}

	@Column(name = "COMMENTAIRE_OFFIN", length = 500)
	public String getCommentaireOffin() {
		return this.commentaireOffin;
	}

	public void setCommentaireOffin(String commentaireOffin) {
		this.commentaireOffin = commentaireOffin;
	}

	@Column(name = "COMMENTAIRE_ANORMAL", length = 500)
	public String getCommentaireAnormal() {
		return this.commentaireAnormal;
	}

	public void setCommentaireAnormal(String commentaireAnormal) {
		this.commentaireAnormal = commentaireAnormal;
	}

	@Column(name = "COMMENTAIRE_OFFRET", length = 500)
	public String getCommentaireOffret() {
		return this.commentaireOffret;
	}

	public void setCommentaireOffret(String commentaireOffret) {
		this.commentaireOffret = commentaireOffret;
	}

}
