package com.sndi.model;
// Generated 6 sept. 2020 17:11:33 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VTabBordPf generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_TAB_BORD_PF")
public class VTabBordPf implements java.io.Serializable {

	private BigDecimal codeId;
	private String typ;
	private String typDac;
	private String typProc;
	private BigDecimal saisi;
	private BigDecimal transAc;
	private BigDecimal valPf;
	private BigDecimal difPf;
	private BigDecimal valDmp;
	private BigDecimal difDmp;
	private BigDecimal pub;
	private String codePf;

	public VTabBordPf() {
	}

	public VTabBordPf(BigDecimal codeId, String typ, String typDac, String typProc, BigDecimal saisi,
			BigDecimal transAc, BigDecimal valPf, BigDecimal difPf, BigDecimal valDmp, BigDecimal difDmp,
			BigDecimal pub, String codePf) {
		this.codeId = codeId;
		this.typ = typ;
		this.typDac = typDac;
		this.typProc = typProc;
		this.saisi = saisi;
		this.transAc = transAc;
		this.valPf = valPf;
		this.difPf = difPf;
		this.valDmp = valDmp;
		this.difDmp = difDmp;
		this.pub = pub;
		this.codePf = codePf;
	}

	@Id
	@Column(name = "CODE_ID", precision = 22, scale = 0)
	public BigDecimal getCodeId() {
		return this.codeId;
	}

	public void setCodeId(BigDecimal codeId) {
		this.codeId = codeId;
	}

	@Column(name = "TYP", length = 4)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Column(name = "TYP_DAC", length = 12)
	public String getTypDac() {
		return this.typDac;
	}

	public void setTypDac(String typDac) {
		this.typDac = typDac;
	}

	@Column(name = "TYP_PROC", length = 4)
	public String getTypProc() {
		return this.typProc;
	}

	public void setTypProc(String typProc) {
		this.typProc = typProc;
	}

	@Column(name = "SAISI", precision = 22, scale = 0)
	public BigDecimal getSaisi() {
		return this.saisi;
	}

	public void setSaisi(BigDecimal saisi) {
		this.saisi = saisi;
	}

	@Column(name = "TRANS_AC", precision = 22, scale = 0)
	public BigDecimal getTransAc() {
		return this.transAc;
	}

	public void setTransAc(BigDecimal transAc) {
		this.transAc = transAc;
	}

	@Column(name = "VAL_PF", precision = 22, scale = 0)
	public BigDecimal getValPf() {
		return this.valPf;
	}

	public void setValPf(BigDecimal valPf) {
		this.valPf = valPf;
	}

	@Column(name = "DIF_PF", precision = 22, scale = 0)
	public BigDecimal getDifPf() {
		return this.difPf;
	}

	public void setDifPf(BigDecimal difPf) {
		this.difPf = difPf;
	}

	@Column(name = "VAL_DMP", precision = 22, scale = 0)
	public BigDecimal getValDmp() {
		return this.valDmp;
	}

	public void setValDmp(BigDecimal valDmp) {
		this.valDmp = valDmp;
	}

	@Column(name = "DIF_DMP", precision = 22, scale = 0)
	public BigDecimal getDifDmp() {
		return this.difDmp;
	}

	public void setDifDmp(BigDecimal difDmp) {
		this.difDmp = difDmp;
	}

	@Column(name = "PUB", precision = 22, scale = 0)
	public BigDecimal getPub() {
		return this.pub;
	}

	public void setPub(BigDecimal pub) {
		this.pub = pub;
	}

	@Column(name = "CODE_PF", length = 30)
	public String getCodePf() {
		return this.codePf;
	}

	public void setCodePf(String codePf) {
		this.codePf = codePf;
	}

}
