package com.sndi.model;
// Generated 29 juil. 2021 08:30:21 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VTypeFontionOperateurId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_TYPE_FONTION_OPERATEUR")
public class VTypeFonctionOperateur implements java.io.Serializable 
{
	@Id
	@Column(name = "R_ID")
	private Long id;
	
	@Column(name = "FON_TYF_COD")
	private String fonTyfCod;
	
	@Column(name = "TYF_LIBELLE", length = 250)
	private String tyfLibelle;
	
	@Column(name = "OPE_MATRICULE", length = 250)
	private String opeMatricule;
	
	@Column(name = "STR_CODE", length = 50)
	private String strCode;
	
	@Column(name = "STR_LIBELLE_LONG", length = 250)
	private String strLibellLong;
	
	public TTypeFonction getTypeFonction()
	{
		TTypeFonction typeFonction = new TTypeFonction();
		typeFonction.setTyfCod(fonTyfCod);
		typeFonction.setTyfLibelle(tyfLibelle);
		return typeFonction;
	}
	/*
	 * public void setTypeFonction(TTypeFonction typeFonction) { this.fonTyfCod =
	 * typeFonction.getTyfCod(); this.tyfLibelle = typeFonction.getTyfLibelle(); }
	 */
}
