package com.sndi.model;
// Generated 7 juil. 2020 14:07:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VTypePieceOffreSg generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_TYPE_PIECE_OFFRE_SG")
public class VTypePieceOffreSg implements java.io.Serializable {

	private String tpoCode;
	private String tpoLibelle;
	private Date tpoDteSaisi;
	private String tpoOpeMatricule;
	private String tpoEtapPiece;
	private String tpoBaiEtat;

	public VTypePieceOffreSg() {
	}

	public VTypePieceOffreSg(String tpoCode) {
		this.tpoCode = tpoCode;
	}

	public VTypePieceOffreSg(String tpoCode, String tpoLibelle, Date tpoDteSaisi, String tpoOpeMatricule,
			String tpoEtapPiece, String tpoBaiEtat) {
		this.tpoCode = tpoCode;
		this.tpoLibelle = tpoLibelle;
		this.tpoDteSaisi = tpoDteSaisi;
		this.tpoOpeMatricule = tpoOpeMatricule;
		this.tpoEtapPiece = tpoEtapPiece;
		this.tpoBaiEtat = tpoBaiEtat;
	}

	@Id
	@Column(name = "TPO_CODE", nullable = false, length = 10)
	public String getTpoCode() {
		return this.tpoCode;
	}

	public void setTpoCode(String tpoCode) {
		this.tpoCode = tpoCode;
	}

	@Column(name = "TPO_LIBELLE", length = 200)
	public String getTpoLibelle() {
		return this.tpoLibelle;
	}

	public void setTpoLibelle(String tpoLibelle) {
		this.tpoLibelle = tpoLibelle;
	}

	@Column(name = "TPO_DTE_SAISI", length = 7)
	public Date getTpoDteSaisi() {
		return this.tpoDteSaisi;
	}

	public void setTpoDteSaisi(Date tpoDteSaisi) {
		this.tpoDteSaisi = tpoDteSaisi;
	}

	@Column(name = "TPO_OPE_MATRICULE", length = 25)
	public String getTpoOpeMatricule() {
		return this.tpoOpeMatricule;
	}

	public void setTpoOpeMatricule(String tpoOpeMatricule) {
		this.tpoOpeMatricule = tpoOpeMatricule;
	}

	@Column(name = "TPO_ETAP_PIECE", length = 10)
	public String getTpoEtapPiece() {
		return this.tpoEtapPiece;
	}

	public void setTpoEtapPiece(String tpoEtapPiece) {
		this.tpoEtapPiece = tpoEtapPiece;
	}

	@Column(name = "TPO_BAI_ETAT", length = 20)
	public String getTpoBaiEtat() {
		return this.tpoBaiEtat;
	}

	public void setTpoBaiEtat(String tpoBaiEtat) {
		this.tpoBaiEtat = tpoBaiEtat;
	}

}
