package com.sndi.model;
// Generated 27 oct. 2020 23:58:44 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VTypeDemande generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_TYPE_DEMANDE")
public class VTypeDemande implements java.io.Serializable {

	private String tdmCode;
	private String tdmLibelle;
	private Date tdmDteSaisi;
	private String tdmOpeMatricule;
	private Character tdmProDer;

	public VTypeDemande() {
	}

	public VTypeDemande(String tdmCode) {
		this.tdmCode = tdmCode;
	}

	public VTypeDemande(String tdmCode, String tdmLibelle, Date tdmDteSaisi, String tdmOpeMatricule,
			Character tdmProDer) {
		this.tdmCode = tdmCode;
		this.tdmLibelle = tdmLibelle;
		this.tdmDteSaisi = tdmDteSaisi;
		this.tdmOpeMatricule = tdmOpeMatricule;
		this.tdmProDer = tdmProDer;
	}

	
	@Id
	@Column(name = "TDM_CODE", nullable = false, length = 10)
	public String getTdmCode() {
		return this.tdmCode;
	}

	public void setTdmCode(String tdmCode) {
		this.tdmCode = tdmCode;
	}

	@Column(name = "TDM_LIBELLE", length = 500)
	public String getTdmLibelle() {
		return this.tdmLibelle;
	}

	public void setTdmLibelle(String tdmLibelle) {
		this.tdmLibelle = tdmLibelle;
	}

	@Column(name = "TDM_DTE_SAISI", length = 7)
	public Date getTdmDteSaisi() {
		return this.tdmDteSaisi;
	}

	public void setTdmDteSaisi(Date tdmDteSaisi) {
		this.tdmDteSaisi = tdmDteSaisi;
	}

	@Column(name = "TDM_OPE_MATRICULE", length = 25)
	public String getTdmOpeMatricule() {
		return this.tdmOpeMatricule;
	}

	public void setTdmOpeMatricule(String tdmOpeMatricule) {
		this.tdmOpeMatricule = tdmOpeMatricule;
	}

	@Column(name = "TDM_PRO_DER", length = 1)
	public Character getTdmProDer() {
		return this.tdmProDer;
	}

	public void setTdmProDer(Character tdmProDer) {
		this.tdmProDer = tdmProDer;
	}

}
