package com.sndi.model;
// Generated 30 mars 2020 01:35:59 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VUpdateAgpm generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_UPDATE_AGPM")
public class VUpdateAgpm implements java.io.Serializable {

	private long affId;
	private long affProId;
	private long affFinId;
	private short affGesCode;
	private Long affDecId;
	private String affAgpStaCode;
	private long affAgpId;
	private String affBaiCode;
	private String affSouCode;
	private String affDevCode;
	private String affStrCode;
	private String affFonCod;
	private String affAgpActeurSaisie;
	private String affAgpStatutRetour;
	private String affAgpActif;
	private String affAgpTypeDao;
	private String affAgpCommentaire;
	private String affAgpRecherche;
	private Date affAgpDateValAc;
	private Date affAgpDateValCpmp;
	private Date affAgpDateValDmp;
	private long proId;
	private Long proRegId;
	private String proCode;
	private String proTitre;
	private String proLibelle;
	private String proDescription;
	private BigDecimal proMontantTotCfa;
	private String proTypeProjet;
	private long finId;
	private String finDevCode;
	private String finBaiCode;
	private String finSouCode;
	private long finProId;
	private long finMontantCfa;
	private BigDecimal finMontantDevise;
	private String finNumeroAccord;
	private String finStatut;
	private Long finAgpId;
	private String finTypeFinance;
	private Long finPartTresor;
	private short gesCode;
	private Date gesDateDebut;
	private Date gesDateFin;
	private Long decId;
	private String decOrganExecLibelle;
	private String decOrganExecAdresse;
	private String decPersNomPrenom;
	private String decPersFonction;
	private String decLocalisation;
	private String decNumeroPorte;
	private String decBp;
	private String decTelephone;
	private String decEmail;
	private String decCel;
	private String staCode;
	private String staLibelleCourt;
	private String staLibelleLong;
	private long agpId;
	private String agpStrCode;
	private String agpFonCod;
	private short agpGesCode;
	private String agpStaCode;
	private long agpProId;
	private Long agpDecId;
	private String agpCommentaire;
	private String agpTypeDao;
	private String agpModePassation;
	private String agpActif;
	private String agpStatutRetour;
	private String agpActeurSaisie;
	private Date agpDateValAc;
	private Date agpDateValCpmp;
	private Date agpDateValDmp;
	private String baiCode;
	private String baiLibelle;
	private String baiAdresse;
	private String baiTelephone;

	public VUpdateAgpm() {
	}

	public VUpdateAgpm(long affId, long affProId, long affFinId, short affGesCode, String affAgpStaCode,
			long affAgpId, String affSouCode, String affDevCode, String affStrCode, String affFonCod, long proId,
			String proTitre, long finId, String finDevCode, String finSouCode, long finProId, short gesCode,
			String staCode, long agpId, String agpStrCode, String agpFonCod, short agpGesCode, String agpStaCode,
			long agpProId, String baiCode, String baiLibelle) {
		this.affId = affId;
		this.affProId = affProId;
		this.affFinId = affFinId;
		this.affGesCode = affGesCode;
		this.affAgpStaCode = affAgpStaCode;
		this.affAgpId = affAgpId;
		this.affSouCode = affSouCode;
		this.affDevCode = affDevCode;
		this.affStrCode = affStrCode;
		this.affFonCod = affFonCod;
		this.proId = proId;
		this.proTitre = proTitre;
		this.finId = finId;
		this.finDevCode = finDevCode;
		this.finSouCode = finSouCode;
		this.finProId = finProId;
		this.gesCode = gesCode;
		this.staCode = staCode;
		this.agpId = agpId;
		this.agpStrCode = agpStrCode;
		this.agpFonCod = agpFonCod;
		this.agpGesCode = agpGesCode;
		this.agpStaCode = agpStaCode;
		this.agpProId = agpProId;
		this.baiCode = baiCode;
		this.baiLibelle = baiLibelle;
	}

	public VUpdateAgpm(long affId, long affProId, long affFinId, short affGesCode, Long affDecId,
			String affAgpStaCode, long affAgpId, String affBaiCode, String affSouCode, String affDevCode,
			String affStrCode, String affFonCod, String affAgpActeurSaisie, String affAgpStatutRetour,
			String affAgpActif, String affAgpTypeDao, String affAgpCommentaire, String affAgpRecherche,
			Date affAgpDateValAc, Date affAgpDateValCpmp, Date affAgpDateValDmp, long proId, Long proRegId,
			String proCode, String proTitre, String proLibelle, String proDescription, BigDecimal proMontantTotCfa,
			String proTypeProjet, long finId, String finDevCode, String finBaiCode, String finSouCode, long finProId,
			long finMontantCfa, BigDecimal finMontantDevise, String finNumeroAccord, String finStatut,
			Long finAgpId, String finTypeFinance, Long finPartTresor, short gesCode, Date gesDateDebut, Date gesDateFin,
			Long decId, String decOrganExecLibelle, String decOrganExecAdresse, String decPersNomPrenom,
			String decPersFonction, String decLocalisation, String decNumeroPorte, String decBp, String decTelephone,
			String decEmail, String decCel, String staCode, String staLibelleCourt, String staLibelleLong, long agpId,
			String agpStrCode, String agpFonCod, short agpGesCode, String agpStaCode, long agpProId, Long agpDecId,
			String agpCommentaire, String agpTypeDao, String agpModePassation, String agpActif, String agpStatutRetour,
			String agpActeurSaisie, Date agpDateValAc, Date agpDateValCpmp, Date agpDateValDmp, String baiCode,
			String baiLibelle, String baiAdresse, String baiTelephone) {
		this.affId = affId;
		this.affProId = affProId;
		this.affFinId = affFinId;
		this.affGesCode = affGesCode;
		this.affDecId = affDecId;
		this.affAgpStaCode = affAgpStaCode;
		this.affAgpId = affAgpId;
		this.affBaiCode = affBaiCode;
		this.affSouCode = affSouCode;
		this.affDevCode = affDevCode;
		this.affStrCode = affStrCode;
		this.affFonCod = affFonCod;
		this.affAgpActeurSaisie = affAgpActeurSaisie;
		this.affAgpStatutRetour = affAgpStatutRetour;
		this.affAgpActif = affAgpActif;
		this.affAgpTypeDao = affAgpTypeDao;
		this.affAgpCommentaire = affAgpCommentaire;
		this.affAgpRecherche = affAgpRecherche;
		this.affAgpDateValAc = affAgpDateValAc;
		this.affAgpDateValCpmp = affAgpDateValCpmp;
		this.affAgpDateValDmp = affAgpDateValDmp;
		this.proId = proId;
		this.proRegId = proRegId;
		this.proCode = proCode;
		this.proTitre = proTitre;
		this.proLibelle = proLibelle;
		this.proDescription = proDescription;
		this.proMontantTotCfa = proMontantTotCfa;
		this.proTypeProjet = proTypeProjet;
		this.finId = finId;
		this.finDevCode = finDevCode;
		this.finBaiCode = finBaiCode;
		this.finSouCode = finSouCode;
		this.finProId = finProId;
		this.finMontantCfa = finMontantCfa;
		this.finMontantDevise = finMontantDevise;
		this.finNumeroAccord = finNumeroAccord;
		this.finStatut = finStatut;
		this.finAgpId = finAgpId;
		this.finTypeFinance = finTypeFinance;
		this.finPartTresor = finPartTresor;
		this.gesCode = gesCode;
		this.gesDateDebut = gesDateDebut;
		this.gesDateFin = gesDateFin;
		this.decId = decId;
		this.decOrganExecLibelle = decOrganExecLibelle;
		this.decOrganExecAdresse = decOrganExecAdresse;
		this.decPersNomPrenom = decPersNomPrenom;
		this.decPersFonction = decPersFonction;
		this.decLocalisation = decLocalisation;
		this.decNumeroPorte = decNumeroPorte;
		this.decBp = decBp;
		this.decTelephone = decTelephone;
		this.decEmail = decEmail;
		this.decCel = decCel;
		this.staCode = staCode;
		this.staLibelleCourt = staLibelleCourt;
		this.staLibelleLong = staLibelleLong;
		this.agpId = agpId;
		this.agpStrCode = agpStrCode;
		this.agpFonCod = agpFonCod;
		this.agpGesCode = agpGesCode;
		this.agpStaCode = agpStaCode;
		this.agpProId = agpProId;
		this.agpDecId = agpDecId;
		this.agpCommentaire = agpCommentaire;
		this.agpTypeDao = agpTypeDao;
		this.agpModePassation = agpModePassation;
		this.agpActif = agpActif;
		this.agpStatutRetour = agpStatutRetour;
		this.agpActeurSaisie = agpActeurSaisie;
		this.agpDateValAc = agpDateValAc;
		this.agpDateValCpmp = agpDateValCpmp;
		this.agpDateValDmp = agpDateValDmp;
		this.baiCode = baiCode;
		this.baiLibelle = baiLibelle;
		this.baiAdresse = baiAdresse;
		this.baiTelephone = baiTelephone;
	}

	@Id
	@Column(name = "AFF_ID", nullable = false, precision = 10, scale = 0)
	public long getAffId() {
		return this.affId;
	}

	public void setAffId(long affId) {
		this.affId = affId;
	}

	@Column(name = "AFF_PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getAffProId() {
		return this.affProId;
	}

	public void setAffProId(long affProId) {
		this.affProId = affProId;
	}

	@Column(name = "AFF_FIN_ID", nullable = false, precision = 10, scale = 0)
	public long getAffFinId() {
		return this.affFinId;
	}

	public void setAffFinId(long affFinId) {
		this.affFinId = affFinId;
	}

	@Column(name = "AFF_GES_CODE", nullable = false, precision = 4, scale = 0)
	public short getAffGesCode() {
		return this.affGesCode;
	}

	public void setAffGesCode(short affGesCode) {
		this.affGesCode = affGesCode;
	}

	@Column(name = "AFF_DEC_ID", precision = 10, scale = 0)
	public Long getAffDecId() {
		return this.affDecId;
	}

	public void setAffDecId(Long affDecId) {
		this.affDecId = affDecId;
	}

	@Column(name = "AFF_AGP_STA_CODE", nullable = false, length = 3)
	public String getAffAgpStaCode() {
		return this.affAgpStaCode;
	}

	public void setAffAgpStaCode(String affAgpStaCode) {
		this.affAgpStaCode = affAgpStaCode;
	}

	@Column(name = "AFF_AGP_ID", nullable = false, precision = 10, scale = 0)
	public long getAffAgpId() {
		return this.affAgpId;
	}

	public void setAffAgpId(long affAgpId) {
		this.affAgpId = affAgpId;
	}

	@Column(name = "AFF_BAI_CODE", length = 5)
	public String getAffBaiCode() {
		return this.affBaiCode;
	}

	public void setAffBaiCode(String affBaiCode) {
		this.affBaiCode = affBaiCode;
	}

	@Column(name = "AFF_SOU_CODE", nullable = false, length = 5)
	public String getAffSouCode() {
		return this.affSouCode;
	}

	public void setAffSouCode(String affSouCode) {
		this.affSouCode = affSouCode;
	}

	@Column(name = "AFF_DEV_CODE", nullable = false, length = 8)
	public String getAffDevCode() {
		return this.affDevCode;
	}

	public void setAffDevCode(String affDevCode) {
		this.affDevCode = affDevCode;
	}

	@Column(name = "AFF_STR_CODE", nullable = false, length = 3)
	public String getAffStrCode() {
		return this.affStrCode;
	}

	public void setAffStrCode(String affStrCode) {
		this.affStrCode = affStrCode;
	}

	@Column(name = "AFF_FON_COD", nullable = false, length = 12)
	public String getAffFonCod() {
		return this.affFonCod;
	}

	public void setAffFonCod(String affFonCod) {
		this.affFonCod = affFonCod;
	}

	@Column(name = "AFF_AGP_ACTEUR_SAISIE", length = 12)
	public String getAffAgpActeurSaisie() {
		return this.affAgpActeurSaisie;
	}

	public void setAffAgpActeurSaisie(String affAgpActeurSaisie) {
		this.affAgpActeurSaisie = affAgpActeurSaisie;
	}

	@Column(name = "AFF_AGP_STATUT_RETOUR", length = 2)
	public String getAffAgpStatutRetour() {
		return this.affAgpStatutRetour;
	}

	public void setAffAgpStatutRetour(String affAgpStatutRetour) {
		this.affAgpStatutRetour = affAgpStatutRetour;
	}

	@Column(name = "AFF_AGP_ACTIF", length = 1)
	public String getAffAgpActif() {
		return this.affAgpActif;
	}

	public void setAffAgpActif(String affAgpActif) {
		this.affAgpActif = affAgpActif;
	}

	@Column(name = "AFF_AGP_TYPE_DAO", length = 1000)
	public String getAffAgpTypeDao() {
		return this.affAgpTypeDao;
	}

	public void setAffAgpTypeDao(String affAgpTypeDao) {
		this.affAgpTypeDao = affAgpTypeDao;
	}

	@Column(name = "AFF_AGP_COMMENTAIRE", length = 1000)
	public String getAffAgpCommentaire() {
		return this.affAgpCommentaire;
	}

	public void setAffAgpCommentaire(String affAgpCommentaire) {
		this.affAgpCommentaire = affAgpCommentaire;
	}

	@Column(name = "AFF_AGP_RECHERCHE", length = 4000)
	public String getAffAgpRecherche() {
		return this.affAgpRecherche;
	}

	public void setAffAgpRecherche(String affAgpRecherche) {
		this.affAgpRecherche = affAgpRecherche;
	}

	@Column(name = "AFF_AGP_DATE_VAL_AC", length = 7)
	public Date getAffAgpDateValAc() {
		return this.affAgpDateValAc;
	}

	public void setAffAgpDateValAc(Date affAgpDateValAc) {
		this.affAgpDateValAc = affAgpDateValAc;
	}

	@Column(name = "AFF_AGP_DATE_VAL_CPMP", length = 7)
	public Date getAffAgpDateValCpmp() {
		return this.affAgpDateValCpmp;
	}

	public void setAffAgpDateValCpmp(Date affAgpDateValCpmp) {
		this.affAgpDateValCpmp = affAgpDateValCpmp;
	}

	@Column(name = "AFF_AGP_DATE_VAL_DMP", length = 7)
	public Date getAffAgpDateValDmp() {
		return this.affAgpDateValDmp;
	}

	public void setAffAgpDateValDmp(Date affAgpDateValDmp) {
		this.affAgpDateValDmp = affAgpDateValDmp;
	}

	@Column(name = "PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getProId() {
		return this.proId;
	}

	public void setProId(long proId) {
		this.proId = proId;
	}

	@Column(name = "PRO_REG_ID", precision = 10, scale = 0)
	public Long getProRegId() {
		return this.proRegId;
	}

	public void setProRegId(Long proRegId) {
		this.proRegId = proRegId;
	}

	@Column(name = "PRO_CODE", length = 50)
	public String getProCode() {
		return this.proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	@Column(name = "PRO_TITRE", nullable = false, length = 500)
	public String getProTitre() {
		return this.proTitre;
	}

	public void setProTitre(String proTitre) {
		this.proTitre = proTitre;
	}

	@Column(name = "PRO_LIBELLE", length = 500)
	public String getProLibelle() {
		return this.proLibelle;
	}

	public void setProLibelle(String proLibelle) {
		this.proLibelle = proLibelle;
	}

	@Column(name = "PRO_DESCRIPTION", length = 1000)
	public String getProDescription() {
		return this.proDescription;
	}

	public void setProDescription(String proDescription) {
		this.proDescription = proDescription;
	}

	@Column(name = "PRO_MONTANT_TOT_CFA", precision = 15)
	public BigDecimal getProMontantTotCfa() {
		return this.proMontantTotCfa;
	}

	public void setProMontantTotCfa(BigDecimal proMontantTotCfa) {
		this.proMontantTotCfa = proMontantTotCfa;
	}

	@Column(name = "PRO_TYPE_PROJET", length = 10)
	public String getProTypeProjet() {
		return this.proTypeProjet;
	}

	public void setProTypeProjet(String proTypeProjet) {
		this.proTypeProjet = proTypeProjet;
	}

	@Column(name = "FIN_ID", nullable = false, precision = 10, scale = 0)
	public long getFinId() {
		return this.finId;
	}

	public void setFinId(long finId) {
		this.finId = finId;
	}

	@Column(name = "FIN_DEV_CODE", nullable = false, length = 8)
	public String getFinDevCode() {
		return this.finDevCode;
	}

	public void setFinDevCode(String finDevCode) {
		this.finDevCode = finDevCode;
	}

	@Column(name = "FIN_BAI_CODE", length = 5)
	public String getFinBaiCode() {
		return this.finBaiCode;
	}

	public void setFinBaiCode(String finBaiCode) {
		this.finBaiCode = finBaiCode;
	}

	@Column(name = "FIN_SOU_CODE", nullable = false, length = 5)
	public String getFinSouCode() {
		return this.finSouCode;
	}

	public void setFinSouCode(String finSouCode) {
		this.finSouCode = finSouCode;
	}

	@Column(name = "FIN_PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getFinProId() {
		return this.finProId;
	}

	public void setFinProId(long finProId) {
		this.finProId = finProId;
	}

	@Column(name = "FIN_MONTANT_CFA", precision = 15)
	public long getFinMontantCfa() {
		return this.finMontantCfa;
	}

	public void setFinMontantCfa(long finMontantCfa) {
		this.finMontantCfa = finMontantCfa;
	}

	@Column(name = "FIN_MONTANT_DEVISE", precision = 15)
	public BigDecimal getFinMontantDevise() {
		return this.finMontantDevise;
	}

	public void setFinMontantDevise(BigDecimal finMontantDevise) {
		this.finMontantDevise = finMontantDevise;
	}

	@Column(name = "FIN_NUMERO_ACCORD", length = 500)
	public String getFinNumeroAccord() {
		return this.finNumeroAccord;
	}

	public void setFinNumeroAccord(String finNumeroAccord) {
		this.finNumeroAccord = finNumeroAccord;
	}

	@Column(name = "FIN_STATUT", length = 10)
	public String getFinStatut() {
		return this.finStatut;
	}

	public void setFinStatut(String finStatut) {
		this.finStatut = finStatut;
	}

	@Column(name = "FIN_AGP_ID", precision = 10, scale = 0)
	public Long getFinAgpId() {
		return this.finAgpId;
	}

	public void setFinAgpId(Long finAgpId) {
		this.finAgpId = finAgpId;
	}

	@Column(name = "FIN_TYPE_FINANCE", length = 20)
	public String getFinTypeFinance() {
		return this.finTypeFinance;
	}

	public void setFinTypeFinance(String finTypeFinance) {
		this.finTypeFinance = finTypeFinance;
	}

	@Column(name = "FIN_PART_TRESOR", precision = 15, scale = 0)
	public Long getFinPartTresor() {
		return this.finPartTresor;
	}

	public void setFinPartTresor(Long finPartTresor) {
		this.finPartTresor = finPartTresor;
	}

	@Column(name = "GES_CODE", nullable = false, precision = 4, scale = 0)
	public short getGesCode() {
		return this.gesCode;
	}

	public void setGesCode(short gesCode) {
		this.gesCode = gesCode;
	}

	@Column(name = "GES_DATE_DEBUT", length = 7)
	public Date getGesDateDebut() {
		return this.gesDateDebut;
	}

	public void setGesDateDebut(Date gesDateDebut) {
		this.gesDateDebut = gesDateDebut;
	}

	@Column(name = "GES_DATE_FIN", length = 7)
	public Date getGesDateFin() {
		return this.gesDateFin;
	}

	public void setGesDateFin(Date gesDateFin) {
		this.gesDateFin = gesDateFin;
	}

	@Column(name = "DEC_ID", precision = 10, scale = 0)
	public Long getDecId() {
		return this.decId;
	}

	public void setDecId(Long decId) {
		this.decId = decId;
	}

	@Column(name = "DEC_ORGAN_EXEC_LIBELLE", length = 500)
	public String getDecOrganExecLibelle() {
		return this.decOrganExecLibelle;
	}

	public void setDecOrganExecLibelle(String decOrganExecLibelle) {
		this.decOrganExecLibelle = decOrganExecLibelle;
	}

	@Column(name = "DEC_ORGAN_EXEC_ADRESSE", length = 500)
	public String getDecOrganExecAdresse() {
		return this.decOrganExecAdresse;
	}

	public void setDecOrganExecAdresse(String decOrganExecAdresse) {
		this.decOrganExecAdresse = decOrganExecAdresse;
	}

	@Column(name = "DEC_PERS_NOM_PRENOM", length = 500)
	public String getDecPersNomPrenom() {
		return this.decPersNomPrenom;
	}

	public void setDecPersNomPrenom(String decPersNomPrenom) {
		this.decPersNomPrenom = decPersNomPrenom;
	}

	@Column(name = "DEC_PERS_FONCTION", length = 500)
	public String getDecPersFonction() {
		return this.decPersFonction;
	}

	public void setDecPersFonction(String decPersFonction) {
		this.decPersFonction = decPersFonction;
	}

	@Column(name = "DEC_LOCALISATION", length = 500)
	public String getDecLocalisation() {
		return this.decLocalisation;
	}

	public void setDecLocalisation(String decLocalisation) {
		this.decLocalisation = decLocalisation;
	}

	@Column(name = "DEC_NUMERO_PORTE", length = 500)
	public String getDecNumeroPorte() {
		return this.decNumeroPorte;
	}

	public void setDecNumeroPorte(String decNumeroPorte) {
		this.decNumeroPorte = decNumeroPorte;
	}

	@Column(name = "DEC_BP", length = 500)
	public String getDecBp() {
		return this.decBp;
	}

	public void setDecBp(String decBp) {
		this.decBp = decBp;
	}

	@Column(name = "DEC_TELEPHONE", length = 500)
	public String getDecTelephone() {
		return this.decTelephone;
	}

	public void setDecTelephone(String decTelephone) {
		this.decTelephone = decTelephone;
	}

	@Column(name = "DEC_EMAIL", length = 500)
	public String getDecEmail() {
		return this.decEmail;
	}

	public void setDecEmail(String decEmail) {
		this.decEmail = decEmail;
	}

	@Column(name = "DEC_CEL", length = 500)
	public String getDecCel() {
		return this.decCel;
	}

	public void setDecCel(String decCel) {
		this.decCel = decCel;
	}

	@Column(name = "STA_CODE", nullable = false, length = 3)
	public String getStaCode() {
		return this.staCode;
	}

	public void setStaCode(String staCode) {
		this.staCode = staCode;
	}

	@Column(name = "STA_LIBELLE_COURT", length = 500)
	public String getStaLibelleCourt() {
		return this.staLibelleCourt;
	}

	public void setStaLibelleCourt(String staLibelleCourt) {
		this.staLibelleCourt = staLibelleCourt;
	}

	@Column(name = "STA_LIBELLE_LONG", length = 1000)
	public String getStaLibelleLong() {
		return this.staLibelleLong;
	}

	public void setStaLibelleLong(String staLibelleLong) {
		this.staLibelleLong = staLibelleLong;
	}

	@Column(name = "AGP_ID", nullable = false, precision = 10, scale = 0)
	public long getAgpId() {
		return this.agpId;
	}

	public void setAgpId(long agpId) {
		this.agpId = agpId;
	}

	@Column(name = "AGP_STR_CODE", nullable = false, length = 3)
	public String getAgpStrCode() {
		return this.agpStrCode;
	}

	public void setAgpStrCode(String agpStrCode) {
		this.agpStrCode = agpStrCode;
	}

	@Column(name = "AGP_FON_COD", nullable = false, length = 12)
	public String getAgpFonCod() {
		return this.agpFonCod;
	}

	public void setAgpFonCod(String agpFonCod) {
		this.agpFonCod = agpFonCod;
	}

	@Column(name = "AGP_GES_CODE", nullable = false, precision = 4, scale = 0)
	public short getAgpGesCode() {
		return this.agpGesCode;
	}

	public void setAgpGesCode(short agpGesCode) {
		this.agpGesCode = agpGesCode;
	}

	@Column(name = "AGP_STA_CODE", nullable = false, length = 3)
	public String getAgpStaCode() {
		return this.agpStaCode;
	}

	public void setAgpStaCode(String agpStaCode) {
		this.agpStaCode = agpStaCode;
	}

	@Column(name = "AGP_PRO_ID", nullable = false, precision = 10, scale = 0)
	public long getAgpProId() {
		return this.agpProId;
	}

	public void setAgpProId(long agpProId) {
		this.agpProId = agpProId;
	}

	@Column(name = "AGP_DEC_ID", precision = 10, scale = 0)
	public Long getAgpDecId() {
		return this.agpDecId;
	}

	public void setAgpDecId(Long agpDecId) {
		this.agpDecId = agpDecId;
	}

	@Column(name = "AGP_COMMENTAIRE", length = 1000)
	public String getAgpCommentaire() {
		return this.agpCommentaire;
	}

	public void setAgpCommentaire(String agpCommentaire) {
		this.agpCommentaire = agpCommentaire;
	}

	@Column(name = "AGP_TYPE_DAO", length = 1000)
	public String getAgpTypeDao() {
		return this.agpTypeDao;
	}

	public void setAgpTypeDao(String agpTypeDao) {
		this.agpTypeDao = agpTypeDao;
	}

	@Column(name = "AGP_MODE_PASSATION", length = 1000)
	public String getAgpModePassation() {
		return this.agpModePassation;
	}

	public void setAgpModePassation(String agpModePassation) {
		this.agpModePassation = agpModePassation;
	}

	@Column(name = "AGP_ACTIF", length = 1)
	public String getAgpActif() {
		return this.agpActif;
	}

	public void setAgpActif(String agpActif) {
		this.agpActif = agpActif;
	}

	@Column(name = "AGP_STATUT_RETOUR", length = 2)
	public String getAgpStatutRetour() {
		return this.agpStatutRetour;
	}

	public void setAgpStatutRetour(String agpStatutRetour) {
		this.agpStatutRetour = agpStatutRetour;
	}

	@Column(name = "AGP_ACTEUR_SAISIE", length = 12)
	public String getAgpActeurSaisie() {
		return this.agpActeurSaisie;
	}

	public void setAgpActeurSaisie(String agpActeurSaisie) {
		this.agpActeurSaisie = agpActeurSaisie;
	}

	@Column(name = "AGP_DATE_VAL_AC", length = 7)
	public Date getAgpDateValAc() {
		return this.agpDateValAc;
	}

	public void setAgpDateValAc(Date agpDateValAc) {
		this.agpDateValAc = agpDateValAc;
	}

	@Column(name = "AGP_DATE_VAL_CPMP", length = 7)
	public Date getAgpDateValCpmp() {
		return this.agpDateValCpmp;
	}

	public void setAgpDateValCpmp(Date agpDateValCpmp) {
		this.agpDateValCpmp = agpDateValCpmp;
	}

	@Column(name = "AGP_DATE_VAL_DMP", length = 7)
	public Date getAgpDateValDmp() {
		return this.agpDateValDmp;
	}

	public void setAgpDateValDmp(Date agpDateValDmp) {
		this.agpDateValDmp = agpDateValDmp;
	}

	@Column(name = "BAI_CODE", nullable = false, length = 5)
	public String getBaiCode() {
		return this.baiCode;
	}

	public void setBaiCode(String baiCode) {
		this.baiCode = baiCode;
	}

	@Column(name = "BAI_LIBELLE", nullable = false, length = 1000)
	public String getBaiLibelle() {
		return this.baiLibelle;
	}

	public void setBaiLibelle(String baiLibelle) {
		this.baiLibelle = baiLibelle;
	}

	@Column(name = "BAI_ADRESSE", length = 500)
	public String getBaiAdresse() {
		return this.baiAdresse;
	}

	public void setBaiAdresse(String baiAdresse) {
		this.baiAdresse = baiAdresse;
	}

	@Column(name = "BAI_TELEPHONE", length = 500)
	public String getBaiTelephone() {
		return this.baiTelephone;
	}

	public void setBaiTelephone(String baiTelephone) {
		this.baiTelephone = baiTelephone;
	}

}
