package com.sndi.model;
// Generated 2 mai 2020 10:48:14 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VUpdateFinancementPpmId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_UPDATE_FINANCEMENT_PPM")
public class VUpdateFinancementPpm implements java.io.Serializable {

	private long fppId;
	private String fppDevCode;
	private String fppBaiCode;
	private String fppSouCode;
	private long fppDppId;
	private Long fppMontantCfa;
	private BigDecimal fppMontantDevise;
	private String fppCommentaire;
	private String fppTypeFinance;
	private Long fppPartTresor;
	private String baiCode;
	private String baiLibelle;
	private String baiAdresse;
	private String baiTelephone;
	private String devCode;
	private String devLibelle;
	private String devSymbole;
	private String souCode;
	private String souLibelle;

	public VUpdateFinancementPpm() {
	}

	public VUpdateFinancementPpm(long fppId, String fppDevCode, String fppBaiCode, long fppDppId) {
		this.fppId = fppId;
		this.fppDevCode = fppDevCode;
		this.fppBaiCode = fppBaiCode;
		this.fppDppId = fppDppId;
	}

	public VUpdateFinancementPpm(long fppId, String fppDevCode, String fppBaiCode, String fppSouCode, long fppDppId,
			Long fppMontantCfa, BigDecimal fppMontantDevise, String fppCommentaire, String fppTypeFinance,
			Long fppPartTresor, String baiCode, String baiLibelle, String baiAdresse, String baiTelephone,
			String devCode, String devLibelle, String devSymbole, String souCode, String souLibelle) {
		this.fppId = fppId;
		this.fppDevCode = fppDevCode;
		this.fppBaiCode = fppBaiCode;
		this.fppSouCode = fppSouCode;
		this.fppDppId = fppDppId;
		this.fppMontantCfa = fppMontantCfa;
		this.fppMontantDevise = fppMontantDevise;
		this.fppCommentaire = fppCommentaire;
		this.fppTypeFinance = fppTypeFinance;
		this.fppPartTresor = fppPartTresor;
		this.baiCode = baiCode;
		this.baiLibelle = baiLibelle;
		this.baiAdresse = baiAdresse;
		this.baiTelephone = baiTelephone;
		this.devCode = devCode;
		this.devLibelle = devLibelle;
		this.devSymbole = devSymbole;
		this.souCode = souCode;
		this.souLibelle = souLibelle;
	}

	@Id
	@Column(name = "FPP_ID", nullable = false, precision = 10, scale = 0)
	public long getFppId() {
		return this.fppId;
	}

	public void setFppId(long fppId) {
		this.fppId = fppId;
	}

	@Column(name = "FPP_DEV_CODE", nullable = false, length = 8)
	public String getFppDevCode() {
		return this.fppDevCode;
	}

	public void setFppDevCode(String fppDevCode) {
		this.fppDevCode = fppDevCode;
	}

	@Column(name = "FPP_BAI_CODE", nullable = false, length = 5)
	public String getFppBaiCode() {
		return this.fppBaiCode;
	}

	public void setFppBaiCode(String fppBaiCode) {
		this.fppBaiCode = fppBaiCode;
	}

	@Column(name = "FPP_SOU_CODE", length = 5)
	public String getFppSouCode() {
		return this.fppSouCode;
	}

	public void setFppSouCode(String fppSouCode) {
		this.fppSouCode = fppSouCode;
	}

	@Column(name = "FPP_DPP_ID", nullable = false, precision = 10, scale = 0)
	public long getFppDppId() {
		return this.fppDppId;
	}

	public void setFppDppId(long fppDppId) {
		this.fppDppId = fppDppId;
	}

	@Column(name = "FPP_MONTANT_CFA", precision = 15)
	public Long getFppMontantCfa() {
		return this.fppMontantCfa;
	}

	public void setFppMontantCfa(Long fppMontantCfa) {
		this.fppMontantCfa = fppMontantCfa;
	}

	@Column(name = "FPP_MONTANT_DEVISE", precision = 15)
	public BigDecimal getFppMontantDevise() {
		return this.fppMontantDevise;
	}

	public void setFppMontantDevise(BigDecimal fppMontantDevise) {
		this.fppMontantDevise = fppMontantDevise;
	}

	@Column(name = "FPP_COMMENTAIRE", length = 500)
	public String getFppCommentaire() {
		return this.fppCommentaire;
	}

	public void setFppCommentaire(String fppCommentaire) {
		this.fppCommentaire = fppCommentaire;
	}

	@Column(name = "FPP_TYPE_FINANCE", length = 20)
	public String getFppTypeFinance() {
		return this.fppTypeFinance;
	}

	public void setFppTypeFinance(String fppTypeFinance) {
		this.fppTypeFinance = fppTypeFinance;
	}

	@Column(name = "FPP_PART_TRESOR", precision = 15, scale = 0)
	public Long getFppPartTresor() {
		return this.fppPartTresor;
	}

	public void setFppPartTresor(Long fppPartTresor) {
		this.fppPartTresor = fppPartTresor;
	}

	@Column(name = "BAI_CODE", length = 5)
	public String getBaiCode() {
		return this.baiCode;
	}

	public void setBaiCode(String baiCode) {
		this.baiCode = baiCode;
	}

	@Column(name = "BAI_LIBELLE", length = 1000)
	public String getBaiLibelle() {
		return this.baiLibelle;
	}

	public void setBaiLibelle(String baiLibelle) {
		this.baiLibelle = baiLibelle;
	}

	@Column(name = "BAI_ADRESSE", length = 500)
	public String getBaiAdresse() {
		return this.baiAdresse;
	}

	public void setBaiAdresse(String baiAdresse) {
		this.baiAdresse = baiAdresse;
	}

	@Column(name = "BAI_TELEPHONE", length = 500)
	public String getBaiTelephone() {
		return this.baiTelephone;
	}

	public void setBaiTelephone(String baiTelephone) {
		this.baiTelephone = baiTelephone;
	}

	@Column(name = "DEV_CODE", length = 8)
	public String getDevCode() {
		return this.devCode;
	}

	public void setDevCode(String devCode) {
		this.devCode = devCode;
	}

	@Column(name = "DEV_LIBELLE", length = 500)
	public String getDevLibelle() {
		return this.devLibelle;
	}

	public void setDevLibelle(String devLibelle) {
		this.devLibelle = devLibelle;
	}

	@Column(name = "DEV_SYMBOLE", length = 500)
	public String getDevSymbole() {
		return this.devSymbole;
	}

	public void setDevSymbole(String devSymbole) {
		this.devSymbole = devSymbole;
	}

	@Column(name = "SOU_CODE", length = 5)
	public String getSouCode() {
		return this.souCode;
	}

	public void setSouCode(String souCode) {
		this.souCode = souCode;
	}

	@Column(name = "SOU_LIBELLE", length = 500)
	public String getSouLibelle() {
		return this.souLibelle;
	}

	public void setSouLibelle(String souLibelle) {
		this.souLibelle = souLibelle;
	}

}
