package com.sndi.model;
// Generated 12 avr. 2020 14:58:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VUpdateDacId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "V_UPDATE_DAC")
public class VUpdateDac implements java.io.Serializable {

	private String dacCode;
	private String dacObjet;
	private Date dacDteSaisi;
	private String dacStaCode;
	private String dacTymCode;
	private String dacMopCode;
	private BigDecimal dacNbrOuv;
	private BigDecimal dacGesCode;
	private String dacFonCodAc;
	private String dacStrCode;
	private String dacFonCodeCpmp;
	private Date dacDteValCpmp;
	private Date dacDteValDmp;
	private String dacTdCode;
	private Date dacDateReception;
	private String dacStatutRetour;
	private String dacMention;
	private Date dacDateValAc;
	private String dacAvisBailleur;
	private Date dacDateAvisBailleur;
	private String dacBailleur;
	private Long dacCout;
	private String dacTypePlan;
	private String dacRecherche;
	private BigDecimal pidCode;
	private String pidLibelle;
	private String pidTpiCode;
	private String pidStaCode;
	private Date pidDteSaisi;
	private String pidDacCode;
	private String pidObservation;
	private String pidPresente;
	private String pidConforme;
	private long affDaoId;
	private BigDecimal affDcsNum;
	private String affDacCode;
	private String affOpeMatricule;
	private String affStaCode;
	private String affStatutRetour;
	private Date affDacDteSaisi;
	private String affDacObjet;
	private String affDacTymCode;
	private String affDacMopCode;
	private BigDecimal affNbrOuv;
	private String affDacStrCode;
	private BigDecimal affDacGesCode;
	private String affDacFonCodeCpmp;
	private String affDacFonCodAc;
	private Date affDacDacDteValCpmp;
	private Date affDacDacDteValDmp;
	private String affDacTdCode;
	private BigDecimal affDacDppId;
	private Date affDacDateReception;
	private String affDacStatutRetour;
	private String affDacMention;
	private String affDacRecherche;
	private Date affDacValAc;
	private String affDacAvisBailleur;
	private Date affDacDateBailleur;
	private String affDacBailleur;
	private Long affDacCout;
	private String affDacTypePlan;
	private String tymCode;
	private String tymLibelleCourt;
	private String tymLibelleLong;
	private String tymTymCode;
	private String tymGroupe;
	private String mopCode;
	private String mopLibelleCourt;
	private String mopLibelleLong;
	private BigDecimal dtaNum;
	private BigDecimal dtaAdaNum;
	private String dtaTitre;
	private String dtaLibelle;
	private Date dtaDteSaisi;
	private Short dtaLiaNum;
	private BigDecimal pofNum;
	private String pofDacCode;
	private BigDecimal pofLaaId;
	private BigDecimal pofOpdNum;
	private String pofOpdTpoCode;
	private BigDecimal pofDofNum;
	private String pofPresent;
	private String pofConforme;
	private String pofTypeAct;
	private Date pofDteSaisi;
	private String pofOpeMatricule;
	private String pofObs;
	private BigDecimal adaNum;
	private String adaLibelle;
	private String adaFonCod;
	private String aaoCode;
	private String aaoLibelle;
	private String aaoDacCode;
	private Date aaoDteSaisi;
	private String aaoStaCode;
	private Date aaoDtePub;
	private Date aaoDteOuvTec;
	private String aaoDteHeurOuv;
	private Date aaoDteOuvFin;
	private BigDecimal aaoNbrLot;
	private BigDecimal aaoNbrOuv;
	private BigDecimal aaoDelaiVal;
	private String aaoFonCodAc;
	private String aaoFonCodeCpmp;
	private String aaoNatInt;
	private String aaoTaux;
	private String aaoLieuExe;
	private String aaoNomResp;
	private String aaoInterPub;
	private String aaoCautDefExig;
	private String aaoBompPub;
	private String aaoVenteParLot;
	private String aaoAvisBail;
	private BigDecimal aaoMtCaut;
	private String aaoModePaiement;
	private BigDecimal aaoCoutDac;
	private String aaoLieuRecep;
	private Date aaoDateRecep;
	private String aaoHeureRecep;
	private BigDecimal aaoAdaNum;
	private String aaoNatPrix;
	private String aaoRegQual;
	private String aaoAvisBai;
	private String aaoRespBai;
	private String aaoPrecisModEval;
	private Date aaoDteValAc;
	private Date aaoDteValCpmp;
	private Date aaoDteValDmp;
	private Short aaoNbrOff;
	private Short aaoNbrOffAccpet;
	private Short aaoNbrOffRej;
	private Short aaoNbrOffHorDelai;
	private BigDecimal laaId;
	private String laaAaoCode;
	private String laaObjet;
	private String laaObservation;
	private BigDecimal laaMtCaut;
	private BigDecimal laaMtEst;
	private Date laaDteSaisi;
	private String laaStaCode;
	private String laaFonCodSaisi;
	private String laaFonCodCpmp;
	private String laaOpeMatricule;
	private String laaLieuExe;
	private String laaLbgImputation;
	private BigDecimal laaNum;
	private BigDecimal laaCoutLot;
	private String laaDacCode;
	private String laaAjoutPanier;

	public VUpdateDac() {
	}

	public VUpdateDac(String dacCode, BigDecimal pidCode, long affDaoId, String affDacCode, String tymCode,
			String tymLibelleCourt, String mopCode, String mopLibelleCourt, BigDecimal dtaNum, String aaoCode) {
		this.dacCode = dacCode;
		this.pidCode = pidCode;
		this.affDaoId = affDaoId;
		this.affDacCode = affDacCode;
		this.tymCode = tymCode;
		this.tymLibelleCourt = tymLibelleCourt;
		this.mopCode = mopCode;
		this.mopLibelleCourt = mopLibelleCourt;
		this.dtaNum = dtaNum;
		this.aaoCode = aaoCode;
	}

	public VUpdateDac(String dacCode, String dacObjet, Date dacDteSaisi, String dacStaCode, String dacTymCode,
			String dacMopCode, BigDecimal dacNbrOuv, BigDecimal dacGesCode, String dacFonCodAc, String dacStrCode,
			String dacFonCodeCpmp, Date dacDteValCpmp, Date dacDteValDmp, String dacTdCode, Date dacDateReception,
			String dacStatutRetour, String dacMention, Date dacDateValAc, String dacAvisBailleur,
			Date dacDateAvisBailleur, String dacBailleur, Long dacCout, String dacTypePlan, String dacRecherche,
			BigDecimal pidCode, String pidLibelle, String pidTpiCode, String pidStaCode, Date pidDteSaisi,
			String pidDacCode, String pidObservation, String pidPresente, String pidConforme, long affDaoId,
			BigDecimal affDcsNum, String affDacCode, String affOpeMatricule, String affStaCode, String affStatutRetour,
			Date affDacDteSaisi, String affDacObjet, String affDacTymCode, String affDacMopCode, BigDecimal affNbrOuv,
			String affDacStrCode, BigDecimal affDacGesCode, String affDacFonCodeCpmp, String affDacFonCodAc,
			Date affDacDacDteValCpmp, Date affDacDacDteValDmp, String affDacTdCode, BigDecimal affDacDppId,
			Date affDacDateReception, String affDacStatutRetour, String affDacMention, String affDacRecherche,
			Date affDacValAc, String affDacAvisBailleur, Date affDacDateBailleur, String affDacBailleur,
			Long affDacCout, String affDacTypePlan, String tymCode, String tymLibelleCourt, String tymLibelleLong,
			String tymTymCode, String tymGroupe, String mopCode, String mopLibelleCourt, String mopLibelleLong,
			BigDecimal dtaNum, BigDecimal dtaAdaNum, String dtaTitre, String dtaLibelle, Date dtaDteSaisi,
			Short dtaLiaNum, BigDecimal pofNum, String pofDacCode, BigDecimal pofLaaId, BigDecimal pofOpdNum,
			String pofOpdTpoCode, BigDecimal pofDofNum, String pofPresent, String pofConforme, String pofTypeAct,
			Date pofDteSaisi, String pofOpeMatricule, String pofObs, BigDecimal adaNum, String adaLibelle,
			String adaFonCod, String aaoCode, String aaoLibelle, String aaoDacCode, Date aaoDteSaisi, String aaoStaCode,
			Date aaoDtePub, Date aaoDteOuvTec, String aaoDteHeurOuv, Date aaoDteOuvFin, BigDecimal aaoNbrLot,
			BigDecimal aaoNbrOuv, BigDecimal aaoDelaiVal, String aaoFonCodAc, String aaoFonCodeCpmp, String aaoNatInt,
			String aaoTaux, String aaoLieuExe, String aaoNomResp, String aaoInterPub, String aaoCautDefExig,
			String aaoBompPub, String aaoVenteParLot, String aaoAvisBail, BigDecimal aaoMtCaut, String aaoModePaiement,
			BigDecimal aaoCoutDac, String aaoLieuRecep, Date aaoDateRecep, String aaoHeureRecep, BigDecimal aaoAdaNum,
			String aaoNatPrix, String aaoRegQual, String aaoAvisBai, String aaoRespBai, String aaoPrecisModEval,
			Date aaoDteValAc, Date aaoDteValCpmp, Date aaoDteValDmp, Short aaoNbrOff, Short aaoNbrOffAccpet,
			Short aaoNbrOffRej, Short aaoNbrOffHorDelai, BigDecimal laaId, String laaAaoCode, String laaObjet,
			String laaObservation, BigDecimal laaMtCaut, BigDecimal laaMtEst, Date laaDteSaisi, String laaStaCode,
			String laaFonCodSaisi, String laaFonCodCpmp, String laaOpeMatricule, String laaLieuExe,
			String laaLbgImputation, BigDecimal laaNum, BigDecimal laaCoutLot, String laaDacCode,
			String laaAjoutPanier) {
		this.dacCode = dacCode;
		this.dacObjet = dacObjet;
		this.dacDteSaisi = dacDteSaisi;
		this.dacStaCode = dacStaCode;
		this.dacTymCode = dacTymCode;
		this.dacMopCode = dacMopCode;
		this.dacNbrOuv = dacNbrOuv;
		this.dacGesCode = dacGesCode;
		this.dacFonCodAc = dacFonCodAc;
		this.dacStrCode = dacStrCode;
		this.dacFonCodeCpmp = dacFonCodeCpmp;
		this.dacDteValCpmp = dacDteValCpmp;
		this.dacDteValDmp = dacDteValDmp;
		this.dacTdCode = dacTdCode;
		this.dacDateReception = dacDateReception;
		this.dacStatutRetour = dacStatutRetour;
		this.dacMention = dacMention;
		this.dacDateValAc = dacDateValAc;
		this.dacAvisBailleur = dacAvisBailleur;
		this.dacDateAvisBailleur = dacDateAvisBailleur;
		this.dacBailleur = dacBailleur;
		this.dacCout = dacCout;
		this.dacTypePlan = dacTypePlan;
		this.dacRecherche = dacRecherche;
		this.pidCode = pidCode;
		this.pidLibelle = pidLibelle;
		this.pidTpiCode = pidTpiCode;
		this.pidStaCode = pidStaCode;
		this.pidDteSaisi = pidDteSaisi;
		this.pidDacCode = pidDacCode;
		this.pidObservation = pidObservation;
		this.pidPresente = pidPresente;
		this.pidConforme = pidConforme;
		this.affDaoId = affDaoId;
		this.affDcsNum = affDcsNum;
		this.affDacCode = affDacCode;
		this.affOpeMatricule = affOpeMatricule;
		this.affStaCode = affStaCode;
		this.affStatutRetour = affStatutRetour;
		this.affDacDteSaisi = affDacDteSaisi;
		this.affDacObjet = affDacObjet;
		this.affDacTymCode = affDacTymCode;
		this.affDacMopCode = affDacMopCode;
		this.affNbrOuv = affNbrOuv;
		this.affDacStrCode = affDacStrCode;
		this.affDacGesCode = affDacGesCode;
		this.affDacFonCodeCpmp = affDacFonCodeCpmp;
		this.affDacFonCodAc = affDacFonCodAc;
		this.affDacDacDteValCpmp = affDacDacDteValCpmp;
		this.affDacDacDteValDmp = affDacDacDteValDmp;
		this.affDacTdCode = affDacTdCode;
		this.affDacDppId = affDacDppId;
		this.affDacDateReception = affDacDateReception;
		this.affDacStatutRetour = affDacStatutRetour;
		this.affDacMention = affDacMention;
		this.affDacRecherche = affDacRecherche;
		this.affDacValAc = affDacValAc;
		this.affDacAvisBailleur = affDacAvisBailleur;
		this.affDacDateBailleur = affDacDateBailleur;
		this.affDacBailleur = affDacBailleur;
		this.affDacCout = affDacCout;
		this.affDacTypePlan = affDacTypePlan;
		this.tymCode = tymCode;
		this.tymLibelleCourt = tymLibelleCourt;
		this.tymLibelleLong = tymLibelleLong;
		this.tymTymCode = tymTymCode;
		this.tymGroupe = tymGroupe;
		this.mopCode = mopCode;
		this.mopLibelleCourt = mopLibelleCourt;
		this.mopLibelleLong = mopLibelleLong;
		this.dtaNum = dtaNum;
		this.dtaAdaNum = dtaAdaNum;
		this.dtaTitre = dtaTitre;
		this.dtaLibelle = dtaLibelle;
		this.dtaDteSaisi = dtaDteSaisi;
		this.dtaLiaNum = dtaLiaNum;
		this.pofNum = pofNum;
		this.pofDacCode = pofDacCode;
		this.pofLaaId = pofLaaId;
		this.pofOpdNum = pofOpdNum;
		this.pofOpdTpoCode = pofOpdTpoCode;
		this.pofDofNum = pofDofNum;
		this.pofPresent = pofPresent;
		this.pofConforme = pofConforme;
		this.pofTypeAct = pofTypeAct;
		this.pofDteSaisi = pofDteSaisi;
		this.pofOpeMatricule = pofOpeMatricule;
		this.pofObs = pofObs;
		this.adaNum = adaNum;
		this.adaLibelle = adaLibelle;
		this.adaFonCod = adaFonCod;
		this.aaoCode = aaoCode;
		this.aaoLibelle = aaoLibelle;
		this.aaoDacCode = aaoDacCode;
		this.aaoDteSaisi = aaoDteSaisi;
		this.aaoStaCode = aaoStaCode;
		this.aaoDtePub = aaoDtePub;
		this.aaoDteOuvTec = aaoDteOuvTec;
		this.aaoDteHeurOuv = aaoDteHeurOuv;
		this.aaoDteOuvFin = aaoDteOuvFin;
		this.aaoNbrLot = aaoNbrLot;
		this.aaoNbrOuv = aaoNbrOuv;
		this.aaoDelaiVal = aaoDelaiVal;
		this.aaoFonCodAc = aaoFonCodAc;
		this.aaoFonCodeCpmp = aaoFonCodeCpmp;
		this.aaoNatInt = aaoNatInt;
		this.aaoTaux = aaoTaux;
		this.aaoLieuExe = aaoLieuExe;
		this.aaoNomResp = aaoNomResp;
		this.aaoInterPub = aaoInterPub;
		this.aaoCautDefExig = aaoCautDefExig;
		this.aaoBompPub = aaoBompPub;
		this.aaoVenteParLot = aaoVenteParLot;
		this.aaoAvisBail = aaoAvisBail;
		this.aaoMtCaut = aaoMtCaut;
		this.aaoModePaiement = aaoModePaiement;
		this.aaoCoutDac = aaoCoutDac;
		this.aaoLieuRecep = aaoLieuRecep;
		this.aaoDateRecep = aaoDateRecep;
		this.aaoHeureRecep = aaoHeureRecep;
		this.aaoAdaNum = aaoAdaNum;
		this.aaoNatPrix = aaoNatPrix;
		this.aaoRegQual = aaoRegQual;
		this.aaoAvisBai = aaoAvisBai;
		this.aaoRespBai = aaoRespBai;
		this.aaoPrecisModEval = aaoPrecisModEval;
		this.aaoDteValAc = aaoDteValAc;
		this.aaoDteValCpmp = aaoDteValCpmp;
		this.aaoDteValDmp = aaoDteValDmp;
		this.aaoNbrOff = aaoNbrOff;
		this.aaoNbrOffAccpet = aaoNbrOffAccpet;
		this.aaoNbrOffRej = aaoNbrOffRej;
		this.aaoNbrOffHorDelai = aaoNbrOffHorDelai;
		this.laaId = laaId;
		this.laaAaoCode = laaAaoCode;
		this.laaObjet = laaObjet;
		this.laaObservation = laaObservation;
		this.laaMtCaut = laaMtCaut;
		this.laaMtEst = laaMtEst;
		this.laaDteSaisi = laaDteSaisi;
		this.laaStaCode = laaStaCode;
		this.laaFonCodSaisi = laaFonCodSaisi;
		this.laaFonCodCpmp = laaFonCodCpmp;
		this.laaOpeMatricule = laaOpeMatricule;
		this.laaLieuExe = laaLieuExe;
		this.laaLbgImputation = laaLbgImputation;
		this.laaNum = laaNum;
		this.laaCoutLot = laaCoutLot;
		this.laaDacCode = laaDacCode;
		this.laaAjoutPanier = laaAjoutPanier;
	}

	@Id
	@Column(name = "DAC_CODE", nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "DAC_OBJET", length = 1000)
	public String getDacObjet() {
		return this.dacObjet;
	}

	public void setDacObjet(String dacObjet) {
		this.dacObjet = dacObjet;
	}

	@Column(name = "DAC_DTE_SAISI", length = 7)
	public Date getDacDteSaisi() {
		return this.dacDteSaisi;
	}

	public void setDacDteSaisi(Date dacDteSaisi) {
		this.dacDteSaisi = dacDteSaisi;
	}

	@Column(name = "DAC_STA_CODE", length = 3)
	public String getDacStaCode() {
		return this.dacStaCode;
	}

	public void setDacStaCode(String dacStaCode) {
		this.dacStaCode = dacStaCode;
	}

	@Column(name = "DAC_TYM_CODE", length = 5)
	public String getDacTymCode() {
		return this.dacTymCode;
	}

	public void setDacTymCode(String dacTymCode) {
		this.dacTymCode = dacTymCode;
	}

	@Column(name = "DAC_MOP_CODE", length = 3)
	public String getDacMopCode() {
		return this.dacMopCode;
	}

	public void setDacMopCode(String dacMopCode) {
		this.dacMopCode = dacMopCode;
	}

	@Column(name = "DAC_NBR_OUV", precision = 22, scale = 0)
	public BigDecimal getDacNbrOuv() {
		return this.dacNbrOuv;
	}

	public void setDacNbrOuv(BigDecimal dacNbrOuv) {
		this.dacNbrOuv = dacNbrOuv;
	}

	@Column(name = "DAC_GES_CODE", precision = 22, scale = 0)
	public BigDecimal getDacGesCode() {
		return this.dacGesCode;
	}

	public void setDacGesCode(BigDecimal dacGesCode) {
		this.dacGesCode = dacGesCode;
	}

	@Column(name = "DAC_FON_COD_AC", length = 12)
	public String getDacFonCodAc() {
		return this.dacFonCodAc;
	}

	public void setDacFonCodAc(String dacFonCodAc) {
		this.dacFonCodAc = dacFonCodAc;
	}

	@Column(name = "DAC_STR_CODE", length = 3)
	public String getDacStrCode() {
		return this.dacStrCode;
	}

	public void setDacStrCode(String dacStrCode) {
		this.dacStrCode = dacStrCode;
	}

	@Column(name = "DAC_FON_CODE_CPMP", length = 12)
	public String getDacFonCodeCpmp() {
		return this.dacFonCodeCpmp;
	}

	public void setDacFonCodeCpmp(String dacFonCodeCpmp) {
		this.dacFonCodeCpmp = dacFonCodeCpmp;
	}

	@Column(name = "DAC_DTE_VAL_CPMP", length = 7)
	public Date getDacDteValCpmp() {
		return this.dacDteValCpmp;
	}

	public void setDacDteValCpmp(Date dacDteValCpmp) {
		this.dacDteValCpmp = dacDteValCpmp;
	}

	@Column(name = "DAC_DTE_VAL_DMP", length = 7)
	public Date getDacDteValDmp() {
		return this.dacDteValDmp;
	}

	public void setDacDteValDmp(Date dacDteValDmp) {
		this.dacDteValDmp = dacDteValDmp;
	}

	@Column(name = "DAC_TD_CODE", length = 3)
	public String getDacTdCode() {
		return this.dacTdCode;
	}

	public void setDacTdCode(String dacTdCode) {
		this.dacTdCode = dacTdCode;
	}

	@Column(name = "DAC_DATE_RECEPTION", length = 7)
	public Date getDacDateReception() {
		return this.dacDateReception;
	}

	public void setDacDateReception(Date dacDateReception) {
		this.dacDateReception = dacDateReception;
	}

	@Column(name = "DAC_STATUT_RETOUR", length = 2)
	public String getDacStatutRetour() {
		return this.dacStatutRetour;
	}

	public void setDacStatutRetour(String dacStatutRetour) {
		this.dacStatutRetour = dacStatutRetour;
	}

	@Column(name = "DAC_MENTION", length = 100)
	public String getDacMention() {
		return this.dacMention;
	}

	public void setDacMention(String dacMention) {
		this.dacMention = dacMention;
	}

	@Column(name = "DAC_DATE_VAL_AC", length = 7)
	public Date getDacDateValAc() {
		return this.dacDateValAc;
	}

	public void setDacDateValAc(Date dacDateValAc) {
		this.dacDateValAc = dacDateValAc;
	}

	@Column(name = "DAC_AVIS_BAILLEUR", length = 4000)
	public String getDacAvisBailleur() {
		return this.dacAvisBailleur;
	}

	public void setDacAvisBailleur(String dacAvisBailleur) {
		this.dacAvisBailleur = dacAvisBailleur;
	}

	@Column(name = "DAC_DATE_AVIS_BAILLEUR", length = 7)
	public Date getDacDateAvisBailleur() {
		return this.dacDateAvisBailleur;
	}

	public void setDacDateAvisBailleur(Date dacDateAvisBailleur) {
		this.dacDateAvisBailleur = dacDateAvisBailleur;
	}

	@Column(name = "DAC_BAILLEUR", length = 1)
	public String getDacBailleur() {
		return this.dacBailleur;
	}

	public void setDacBailleur(String dacBailleur) {
		this.dacBailleur = dacBailleur;
	}

	@Column(name = "DAC_COUT", precision = 11, scale = 0)
	public Long getDacCout() {
		return this.dacCout;
	}

	public void setDacCout(Long dacCout) {
		this.dacCout = dacCout;
	}

	@Column(name = "DAC_TYPE_PLAN", length = 4)
	public String getDacTypePlan() {
		return this.dacTypePlan;
	}

	public void setDacTypePlan(String dacTypePlan) {
		this.dacTypePlan = dacTypePlan;
	}

	@Column(name = "DAC_RECHERCHE", length = 4000)
	public String getDacRecherche() {
		return this.dacRecherche;
	}

	public void setDacRecherche(String dacRecherche) {
		this.dacRecherche = dacRecherche;
	}

	@Column(name = "PID_CODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPidCode() {
		return this.pidCode;
	}

	public void setPidCode(BigDecimal pidCode) {
		this.pidCode = pidCode;
	}

	@Column(name = "PID_LIBELLE", length = 1000)
	public String getPidLibelle() {
		return this.pidLibelle;
	}

	public void setPidLibelle(String pidLibelle) {
		this.pidLibelle = pidLibelle;
	}

	@Column(name = "PID_TPI_CODE", length = 10)
	public String getPidTpiCode() {
		return this.pidTpiCode;
	}

	public void setPidTpiCode(String pidTpiCode) {
		this.pidTpiCode = pidTpiCode;
	}

	@Column(name = "PID_STA_CODE", length = 3)
	public String getPidStaCode() {
		return this.pidStaCode;
	}

	public void setPidStaCode(String pidStaCode) {
		this.pidStaCode = pidStaCode;
	}

	@Column(name = "PID_DTE_SAISI", length = 7)
	public Date getPidDteSaisi() {
		return this.pidDteSaisi;
	}

	public void setPidDteSaisi(Date pidDteSaisi) {
		this.pidDteSaisi = pidDteSaisi;
	}

	@Column(name = "PID_DAC_CODE", length = 20)
	public String getPidDacCode() {
		return this.pidDacCode;
	}

	public void setPidDacCode(String pidDacCode) {
		this.pidDacCode = pidDacCode;
	}

	@Column(name = "PID_OBSERVATION", length = 2000)
	public String getPidObservation() {
		return this.pidObservation;
	}

	public void setPidObservation(String pidObservation) {
		this.pidObservation = pidObservation;
	}

	@Column(name = "PID_PRESENTE", length = 3)
	public String getPidPresente() {
		return this.pidPresente;
	}

	public void setPidPresente(String pidPresente) {
		this.pidPresente = pidPresente;
	}

	@Column(name = "PID_CONFORME", length = 3)
	public String getPidConforme() {
		return this.pidConforme;
	}

	public void setPidConforme(String pidConforme) {
		this.pidConforme = pidConforme;
	}

	@Column(name = "AFF_DAO_ID", nullable = false, precision = 10, scale = 0)
	public long getAffDaoId() {
		return this.affDaoId;
	}

	public void setAffDaoId(long affDaoId) {
		this.affDaoId = affDaoId;
	}

	@Column(name = "AFF_DCS_NUM", precision = 22, scale = 0)
	public BigDecimal getAffDcsNum() {
		return this.affDcsNum;
	}

	public void setAffDcsNum(BigDecimal affDcsNum) {
		this.affDcsNum = affDcsNum;
	}

	@Column(name = "AFF_DAC_CODE", nullable = false, length = 20)
	public String getAffDacCode() {
		return this.affDacCode;
	}

	public void setAffDacCode(String affDacCode) {
		this.affDacCode = affDacCode;
	}

	@Column(name = "AFF_OPE_MATRICULE", length = 25)
	public String getAffOpeMatricule() {
		return this.affOpeMatricule;
	}

	public void setAffOpeMatricule(String affOpeMatricule) {
		this.affOpeMatricule = affOpeMatricule;
	}

	@Column(name = "AFF_STA_CODE", length = 3)
	public String getAffStaCode() {
		return this.affStaCode;
	}

	public void setAffStaCode(String affStaCode) {
		this.affStaCode = affStaCode;
	}

	@Column(name = "AFF_STATUT_RETOUR", length = 4)
	public String getAffStatutRetour() {
		return this.affStatutRetour;
	}

	public void setAffStatutRetour(String affStatutRetour) {
		this.affStatutRetour = affStatutRetour;
	}

	@Column(name = "AFF_DAC_DTE_SAISI", length = 7)
	public Date getAffDacDteSaisi() {
		return this.affDacDteSaisi;
	}

	public void setAffDacDteSaisi(Date affDacDteSaisi) {
		this.affDacDteSaisi = affDacDteSaisi;
	}

	@Column(name = "AFF_DAC_OBJET", length = 1000)
	public String getAffDacObjet() {
		return this.affDacObjet;
	}

	public void setAffDacObjet(String affDacObjet) {
		this.affDacObjet = affDacObjet;
	}

	@Column(name = "AFF_DAC_TYM_CODE", length = 5)
	public String getAffDacTymCode() {
		return this.affDacTymCode;
	}

	public void setAffDacTymCode(String affDacTymCode) {
		this.affDacTymCode = affDacTymCode;
	}

	@Column(name = "AFF_DAC_MOP_CODE", length = 3)
	public String getAffDacMopCode() {
		return this.affDacMopCode;
	}

	public void setAffDacMopCode(String affDacMopCode) {
		this.affDacMopCode = affDacMopCode;
	}

	@Column(name = "AFF_NBR_OUV", precision = 22, scale = 0)
	public BigDecimal getAffNbrOuv() {
		return this.affNbrOuv;
	}

	public void setAffNbrOuv(BigDecimal affNbrOuv) {
		this.affNbrOuv = affNbrOuv;
	}

	@Column(name = "AFF_DAC_STR_CODE", length = 3)
	public String getAffDacStrCode() {
		return this.affDacStrCode;
	}

	public void setAffDacStrCode(String affDacStrCode) {
		this.affDacStrCode = affDacStrCode;
	}

	@Column(name = "AFF_DAC_GES_CODE", precision = 22, scale = 0)
	public BigDecimal getAffDacGesCode() {
		return this.affDacGesCode;
	}

	public void setAffDacGesCode(BigDecimal affDacGesCode) {
		this.affDacGesCode = affDacGesCode;
	}

	@Column(name = "AFF_DAC_FON_CODE_CPMP", length = 12)
	public String getAffDacFonCodeCpmp() {
		return this.affDacFonCodeCpmp;
	}

	public void setAffDacFonCodeCpmp(String affDacFonCodeCpmp) {
		this.affDacFonCodeCpmp = affDacFonCodeCpmp;
	}

	@Column(name = "AFF_DAC_FON_COD_AC", length = 12)
	public String getAffDacFonCodAc() {
		return this.affDacFonCodAc;
	}

	public void setAffDacFonCodAc(String affDacFonCodAc) {
		this.affDacFonCodAc = affDacFonCodAc;
	}

	@Column(name = "AFF_DAC_DAC_DTE_VAL_CPMP", length = 7)
	public Date getAffDacDacDteValCpmp() {
		return this.affDacDacDteValCpmp;
	}

	public void setAffDacDacDteValCpmp(Date affDacDacDteValCpmp) {
		this.affDacDacDteValCpmp = affDacDacDteValCpmp;
	}

	@Column(name = "AFF_DAC_DAC_DTE_VAL_DMP", length = 7)
	public Date getAffDacDacDteValDmp() {
		return this.affDacDacDteValDmp;
	}

	public void setAffDacDacDteValDmp(Date affDacDacDteValDmp) {
		this.affDacDacDteValDmp = affDacDacDteValDmp;
	}

	@Column(name = "AFF_DAC_TD_CODE", length = 3)
	public String getAffDacTdCode() {
		return this.affDacTdCode;
	}

	public void setAffDacTdCode(String affDacTdCode) {
		this.affDacTdCode = affDacTdCode;
	}

	@Column(name = "AFF_DAC_DPP_ID", precision = 20, scale = 0)
	public BigDecimal getAffDacDppId() {
		return this.affDacDppId;
	}

	public void setAffDacDppId(BigDecimal affDacDppId) {
		this.affDacDppId = affDacDppId;
	}

	@Column(name = "AFF_DAC_DATE_RECEPTION", length = 7)
	public Date getAffDacDateReception() {
		return this.affDacDateReception;
	}

	public void setAffDacDateReception(Date affDacDateReception) {
		this.affDacDateReception = affDacDateReception;
	}

	@Column(name = "AFF_DAC_STATUT_RETOUR", length = 2)
	public String getAffDacStatutRetour() {
		return this.affDacStatutRetour;
	}

	public void setAffDacStatutRetour(String affDacStatutRetour) {
		this.affDacStatutRetour = affDacStatutRetour;
	}

	@Column(name = "AFF_DAC_MENTION", length = 100)
	public String getAffDacMention() {
		return this.affDacMention;
	}

	public void setAffDacMention(String affDacMention) {
		this.affDacMention = affDacMention;
	}

	@Column(name = "AFF_DAC_RECHERCHE", length = 4000)
	public String getAffDacRecherche() {
		return this.affDacRecherche;
	}

	public void setAffDacRecherche(String affDacRecherche) {
		this.affDacRecherche = affDacRecherche;
	}

	@Column(name = "AFF_DAC_VAL_AC", length = 7)
	public Date getAffDacValAc() {
		return this.affDacValAc;
	}

	public void setAffDacValAc(Date affDacValAc) {
		this.affDacValAc = affDacValAc;
	}

	@Column(name = "AFF_DAC_AVIS_BAILLEUR", length = 4000)
	public String getAffDacAvisBailleur() {
		return this.affDacAvisBailleur;
	}

	public void setAffDacAvisBailleur(String affDacAvisBailleur) {
		this.affDacAvisBailleur = affDacAvisBailleur;
	}

	@Column(name = "AFF_DAC_DATE_BAILLEUR", length = 7)
	public Date getAffDacDateBailleur() {
		return this.affDacDateBailleur;
	}

	public void setAffDacDateBailleur(Date affDacDateBailleur) {
		this.affDacDateBailleur = affDacDateBailleur;
	}

	@Column(name = "AFF_DAC_BAILLEUR", length = 1)
	public String getAffDacBailleur() {
		return this.affDacBailleur;
	}

	public void setAffDacBailleur(String affDacBailleur) {
		this.affDacBailleur = affDacBailleur;
	}

	@Column(name = "AFF_DAC_COUT", precision = 11, scale = 0)
	public Long getAffDacCout() {
		return this.affDacCout;
	}

	public void setAffDacCout(Long affDacCout) {
		this.affDacCout = affDacCout;
	}

	@Column(name = "AFF_DAC_TYPE_PLAN", length = 4)
	public String getAffDacTypePlan() {
		return this.affDacTypePlan;
	}

	public void setAffDacTypePlan(String affDacTypePlan) {
		this.affDacTypePlan = affDacTypePlan;
	}

	@Column(name = "TYM_CODE", nullable = false, length = 3)
	public String getTymCode() {
		return this.tymCode;
	}

	public void setTymCode(String tymCode) {
		this.tymCode = tymCode;
	}

	@Column(name = "TYM_LIBELLE_COURT", nullable = false, length = 500)
	public String getTymLibelleCourt() {
		return this.tymLibelleCourt;
	}

	public void setTymLibelleCourt(String tymLibelleCourt) {
		this.tymLibelleCourt = tymLibelleCourt;
	}

	@Column(name = "TYM_LIBELLE_LONG", length = 1000)
	public String getTymLibelleLong() {
		return this.tymLibelleLong;
	}

	public void setTymLibelleLong(String tymLibelleLong) {
		this.tymLibelleLong = tymLibelleLong;
	}

	@Column(name = "TYM_TYM_CODE", length = 3)
	public String getTymTymCode() {
		return this.tymTymCode;
	}

	public void setTymTymCode(String tymTymCode) {
		this.tymTymCode = tymTymCode;
	}

	@Column(name = "TYM_GROUPE", length = 2)
	public String getTymGroupe() {
		return this.tymGroupe;
	}

	public void setTymGroupe(String tymGroupe) {
		this.tymGroupe = tymGroupe;
	}

	@Column(name = "MOP_CODE", nullable = false, length = 3)
	public String getMopCode() {
		return this.mopCode;
	}

	public void setMopCode(String mopCode) {
		this.mopCode = mopCode;
	}

	@Column(name = "MOP_LIBELLE_COURT", nullable = false, length = 500)
	public String getMopLibelleCourt() {
		return this.mopLibelleCourt;
	}

	public void setMopLibelleCourt(String mopLibelleCourt) {
		this.mopLibelleCourt = mopLibelleCourt;
	}

	@Column(name = "MOP_LIBELLE_LONG", length = 1000)
	public String getMopLibelleLong() {
		return this.mopLibelleLong;
	}

	public void setMopLibelleLong(String mopLibelleLong) {
		this.mopLibelleLong = mopLibelleLong;
	}

	@Column(name = "DTA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDtaNum() {
		return this.dtaNum;
	}

	public void setDtaNum(BigDecimal dtaNum) {
		this.dtaNum = dtaNum;
	}

	@Column(name = "DTA_ADA_NUM", precision = 22, scale = 0)
	public BigDecimal getDtaAdaNum() {
		return this.dtaAdaNum;
	}

	public void setDtaAdaNum(BigDecimal dtaAdaNum) {
		this.dtaAdaNum = dtaAdaNum;
	}

	@Column(name = "DTA_TITRE", length = 200)
	public String getDtaTitre() {
		return this.dtaTitre;
	}

	public void setDtaTitre(String dtaTitre) {
		this.dtaTitre = dtaTitre;
	}

	@Column(name = "DTA_LIBELLE", length = 500)
	public String getDtaLibelle() {
		return this.dtaLibelle;
	}

	public void setDtaLibelle(String dtaLibelle) {
		this.dtaLibelle = dtaLibelle;
	}

	@Column(name = "DTA_DTE_SAISI", length = 7)
	public Date getDtaDteSaisi() {
		return this.dtaDteSaisi;
	}

	public void setDtaDteSaisi(Date dtaDteSaisi) {
		this.dtaDteSaisi = dtaDteSaisi;
	}

	@Column(name = "DTA_LIA_NUM", precision = 3, scale = 0)
	public Short getDtaLiaNum() {
		return this.dtaLiaNum;
	}

	public void setDtaLiaNum(Short dtaLiaNum) {
		this.dtaLiaNum = dtaLiaNum;
	}

	@Column(name = "POF_NUM", precision = 22, scale = 0)
	public BigDecimal getPofNum() {
		return this.pofNum;
	}

	public void setPofNum(BigDecimal pofNum) {
		this.pofNum = pofNum;
	}

	@Column(name = "POF_DAC_CODE", length = 25)
	public String getPofDacCode() {
		return this.pofDacCode;
	}

	public void setPofDacCode(String pofDacCode) {
		this.pofDacCode = pofDacCode;
	}

	@Column(name = "POF_LAA_ID", precision = 22, scale = 0)
	public BigDecimal getPofLaaId() {
		return this.pofLaaId;
	}

	public void setPofLaaId(BigDecimal pofLaaId) {
		this.pofLaaId = pofLaaId;
	}

	@Column(name = "POF_OPD_NUM", precision = 22, scale = 0)
	public BigDecimal getPofOpdNum() {
		return this.pofOpdNum;
	}

	public void setPofOpdNum(BigDecimal pofOpdNum) {
		this.pofOpdNum = pofOpdNum;
	}

	@Column(name = "POF_OPD_TPO_CODE", length = 10)
	public String getPofOpdTpoCode() {
		return this.pofOpdTpoCode;
	}

	public void setPofOpdTpoCode(String pofOpdTpoCode) {
		this.pofOpdTpoCode = pofOpdTpoCode;
	}

	@Column(name = "POF_DOF_NUM", precision = 22, scale = 0)
	public BigDecimal getPofDofNum() {
		return this.pofDofNum;
	}

	public void setPofDofNum(BigDecimal pofDofNum) {
		this.pofDofNum = pofDofNum;
	}

	@Column(name = "POF_PRESENT", length = 1)
	public String getPofPresent() {
		return this.pofPresent;
	}

	public void setPofPresent(String pofPresent) {
		this.pofPresent = pofPresent;
	}

	@Column(name = "POF_CONFORME", length = 1)
	public String getPofConforme() {
		return this.pofConforme;
	}

	public void setPofConforme(String pofConforme) {
		this.pofConforme = pofConforme;
	}

	@Column(name = "POF_TYPE_ACT", length = 10)
	public String getPofTypeAct() {
		return this.pofTypeAct;
	}

	public void setPofTypeAct(String pofTypeAct) {
		this.pofTypeAct = pofTypeAct;
	}

	@Column(name = "POF_DTE_SAISI", length = 7)
	public Date getPofDteSaisi() {
		return this.pofDteSaisi;
	}

	public void setPofDteSaisi(Date pofDteSaisi) {
		this.pofDteSaisi = pofDteSaisi;
	}

	@Column(name = "POF_OPE_MATRICULE", length = 25)
	public String getPofOpeMatricule() {
		return this.pofOpeMatricule;
	}

	public void setPofOpeMatricule(String pofOpeMatricule) {
		this.pofOpeMatricule = pofOpeMatricule;
	}

	@Column(name = "POF_OBS", length = 500)
	public String getPofObs() {
		return this.pofObs;
	}

	public void setPofObs(String pofObs) {
		this.pofObs = pofObs;
	}

	@Column(name = "ADA_NUM", precision = 22, scale = 0)
	public BigDecimal getAdaNum() {
		return this.adaNum;
	}

	public void setAdaNum(BigDecimal adaNum) {
		this.adaNum = adaNum;
	}

	@Column(name = "ADA_LIBELLE", length = 500)
	public String getAdaLibelle() {
		return this.adaLibelle;
	}

	public void setAdaLibelle(String adaLibelle) {
		this.adaLibelle = adaLibelle;
	}

	@Column(name = "ADA_FON_COD", length = 12)
	public String getAdaFonCod() {
		return this.adaFonCod;
	}

	public void setAdaFonCod(String adaFonCod) {
		this.adaFonCod = adaFonCod;
	}

	@Column(name = "AAO_CODE", nullable = false, length = 20)
	public String getAaoCode() {
		return this.aaoCode;
	}

	public void setAaoCode(String aaoCode) {
		this.aaoCode = aaoCode;
	}

	@Column(name = "AAO_LIBELLE", length = 1000)
	public String getAaoLibelle() {
		return this.aaoLibelle;
	}

	public void setAaoLibelle(String aaoLibelle) {
		this.aaoLibelle = aaoLibelle;
	}

	@Column(name = "AAO_DAC_CODE", length = 20)
	public String getAaoDacCode() {
		return this.aaoDacCode;
	}

	public void setAaoDacCode(String aaoDacCode) {
		this.aaoDacCode = aaoDacCode;
	}

	@Column(name = "AAO_DTE_SAISI", length = 7)
	public Date getAaoDteSaisi() {
		return this.aaoDteSaisi;
	}

	public void setAaoDteSaisi(Date aaoDteSaisi) {
		this.aaoDteSaisi = aaoDteSaisi;
	}

	@Column(name = "AAO_STA_CODE", length = 3)
	public String getAaoStaCode() {
		return this.aaoStaCode;
	}

	public void setAaoStaCode(String aaoStaCode) {
		this.aaoStaCode = aaoStaCode;
	}

	@Column(name = "AAO_DTE_PUB", length = 7)
	public Date getAaoDtePub() {
		return this.aaoDtePub;
	}

	public void setAaoDtePub(Date aaoDtePub) {
		this.aaoDtePub = aaoDtePub;
	}

	@Column(name = "AAO_DTE_OUV_TEC", length = 7)
	public Date getAaoDteOuvTec() {
		return this.aaoDteOuvTec;
	}

	public void setAaoDteOuvTec(Date aaoDteOuvTec) {
		this.aaoDteOuvTec = aaoDteOuvTec;
	}

	@Column(name = "AAO_DTE_HEUR_OUV", length = 20)
	public String getAaoDteHeurOuv() {
		return this.aaoDteHeurOuv;
	}

	public void setAaoDteHeurOuv(String aaoDteHeurOuv) {
		this.aaoDteHeurOuv = aaoDteHeurOuv;
	}

	@Column(name = "AAO_DTE_OUV_FIN", length = 7)
	public Date getAaoDteOuvFin() {
		return this.aaoDteOuvFin;
	}

	public void setAaoDteOuvFin(Date aaoDteOuvFin) {
		this.aaoDteOuvFin = aaoDteOuvFin;
	}

	@Column(name = "AAO_NBR_LOT", precision = 22, scale = 0)
	public BigDecimal getAaoNbrLot() {
		return this.aaoNbrLot;
	}

	public void setAaoNbrLot(BigDecimal aaoNbrLot) {
		this.aaoNbrLot = aaoNbrLot;
	}

	@Column(name = "AAO_NBR_OUV", precision = 22, scale = 0)
	public BigDecimal getAaoNbrOuv() {
		return this.aaoNbrOuv;
	}

	public void setAaoNbrOuv(BigDecimal aaoNbrOuv) {
		this.aaoNbrOuv = aaoNbrOuv;
	}

	@Column(name = "AAO_DELAI_VAL", precision = 22, scale = 0)
	public BigDecimal getAaoDelaiVal() {
		return this.aaoDelaiVal;
	}

	public void setAaoDelaiVal(BigDecimal aaoDelaiVal) {
		this.aaoDelaiVal = aaoDelaiVal;
	}

	@Column(name = "AAO_FON_COD_AC", length = 12)
	public String getAaoFonCodAc() {
		return this.aaoFonCodAc;
	}

	public void setAaoFonCodAc(String aaoFonCodAc) {
		this.aaoFonCodAc = aaoFonCodAc;
	}

	@Column(name = "AAO_FON_CODE_CPMP", length = 12)
	public String getAaoFonCodeCpmp() {
		return this.aaoFonCodeCpmp;
	}

	public void setAaoFonCodeCpmp(String aaoFonCodeCpmp) {
		this.aaoFonCodeCpmp = aaoFonCodeCpmp;
	}

	@Column(name = "AAO_NAT_INT", length = 1)
	public String getAaoNatInt() {
		return this.aaoNatInt;
	}

	public void setAaoNatInt(String aaoNatInt) {
		this.aaoNatInt = aaoNatInt;
	}

	@Column(name = "AAO_TAUX", length = 3)
	public String getAaoTaux() {
		return this.aaoTaux;
	}

	public void setAaoTaux(String aaoTaux) {
		this.aaoTaux = aaoTaux;
	}

	@Column(name = "AAO_LIEU_EXE", length = 200)
	public String getAaoLieuExe() {
		return this.aaoLieuExe;
	}

	public void setAaoLieuExe(String aaoLieuExe) {
		this.aaoLieuExe = aaoLieuExe;
	}

	@Column(name = "AAO_NOM_RESP", length = 200)
	public String getAaoNomResp() {
		return this.aaoNomResp;
	}

	public void setAaoNomResp(String aaoNomResp) {
		this.aaoNomResp = aaoNomResp;
	}

	@Column(name = "AAO_INTER_PUB", length = 1)
	public String getAaoInterPub() {
		return this.aaoInterPub;
	}

	public void setAaoInterPub(String aaoInterPub) {
		this.aaoInterPub = aaoInterPub;
	}

	@Column(name = "AAO_CAUT_DEF_EXIG", length = 1)
	public String getAaoCautDefExig() {
		return this.aaoCautDefExig;
	}

	public void setAaoCautDefExig(String aaoCautDefExig) {
		this.aaoCautDefExig = aaoCautDefExig;
	}

	@Column(name = "AAO_BOMP_PUB", length = 1)
	public String getAaoBompPub() {
		return this.aaoBompPub;
	}

	public void setAaoBompPub(String aaoBompPub) {
		this.aaoBompPub = aaoBompPub;
	}

	@Column(name = "AAO_VENTE_PAR_LOT", length = 1)
	public String getAaoVenteParLot() {
		return this.aaoVenteParLot;
	}

	public void setAaoVenteParLot(String aaoVenteParLot) {
		this.aaoVenteParLot = aaoVenteParLot;
	}

	@Column(name = "AAO_AVIS_BAIL", length = 1)
	public String getAaoAvisBail() {
		return this.aaoAvisBail;
	}

	public void setAaoAvisBail(String aaoAvisBail) {
		this.aaoAvisBail = aaoAvisBail;
	}

	@Column(name = "AAO_MT_CAUT", precision = 22, scale = 0)
	public BigDecimal getAaoMtCaut() {
		return this.aaoMtCaut;
	}

	public void setAaoMtCaut(BigDecimal aaoMtCaut) {
		this.aaoMtCaut = aaoMtCaut;
	}

	@Column(name = "AAO_MODE_PAIEMENT", length = 20)
	public String getAaoModePaiement() {
		return this.aaoModePaiement;
	}

	public void setAaoModePaiement(String aaoModePaiement) {
		this.aaoModePaiement = aaoModePaiement;
	}

	@Column(name = "AAO_COUT_DAC", precision = 22, scale = 0)
	public BigDecimal getAaoCoutDac() {
		return this.aaoCoutDac;
	}

	public void setAaoCoutDac(BigDecimal aaoCoutDac) {
		this.aaoCoutDac = aaoCoutDac;
	}

	@Column(name = "AAO_LIEU_RECEP", length = 1000)
	public String getAaoLieuRecep() {
		return this.aaoLieuRecep;
	}

	public void setAaoLieuRecep(String aaoLieuRecep) {
		this.aaoLieuRecep = aaoLieuRecep;
	}

	@Column(name = "AAO_DATE_RECEP", length = 7)
	public Date getAaoDateRecep() {
		return this.aaoDateRecep;
	}

	public void setAaoDateRecep(Date aaoDateRecep) {
		this.aaoDateRecep = aaoDateRecep;
	}

	@Column(name = "AAO_HEURE_RECEP", length = 20)
	public String getAaoHeureRecep() {
		return this.aaoHeureRecep;
	}

	public void setAaoHeureRecep(String aaoHeureRecep) {
		this.aaoHeureRecep = aaoHeureRecep;
	}

	@Column(name = "AAO_ADA_NUM", precision = 22, scale = 0)
	public BigDecimal getAaoAdaNum() {
		return this.aaoAdaNum;
	}

	public void setAaoAdaNum(BigDecimal aaoAdaNum) {
		this.aaoAdaNum = aaoAdaNum;
	}

	@Column(name = "AAO_NAT_PRIX", length = 20)
	public String getAaoNatPrix() {
		return this.aaoNatPrix;
	}

	public void setAaoNatPrix(String aaoNatPrix) {
		this.aaoNatPrix = aaoNatPrix;
	}

	@Column(name = "AAO_REG_QUAL", length = 100)
	public String getAaoRegQual() {
		return this.aaoRegQual;
	}

	public void setAaoRegQual(String aaoRegQual) {
		this.aaoRegQual = aaoRegQual;
	}

	@Column(name = "AAO_AVIS_BAI", length = 1)
	public String getAaoAvisBai() {
		return this.aaoAvisBai;
	}

	public void setAaoAvisBai(String aaoAvisBai) {
		this.aaoAvisBai = aaoAvisBai;
	}

	@Column(name = "AAO_RESP_BAI", length = 200)
	public String getAaoRespBai() {
		return this.aaoRespBai;
	}

	public void setAaoRespBai(String aaoRespBai) {
		this.aaoRespBai = aaoRespBai;
	}

	@Column(name = "AAO_PRECIS_MOD_EVAL", length = 200)
	public String getAaoPrecisModEval() {
		return this.aaoPrecisModEval;
	}

	public void setAaoPrecisModEval(String aaoPrecisModEval) {
		this.aaoPrecisModEval = aaoPrecisModEval;
	}

	@Column(name = "AAO_DTE_VAL_AC", length = 7)
	public Date getAaoDteValAc() {
		return this.aaoDteValAc;
	}

	public void setAaoDteValAc(Date aaoDteValAc) {
		this.aaoDteValAc = aaoDteValAc;
	}

	@Column(name = "AAO_DTE_VAL_CPMP", length = 7)
	public Date getAaoDteValCpmp() {
		return this.aaoDteValCpmp;
	}

	public void setAaoDteValCpmp(Date aaoDteValCpmp) {
		this.aaoDteValCpmp = aaoDteValCpmp;
	}

	@Column(name = "AAO_DTE_VAL_DMP", length = 7)
	public Date getAaoDteValDmp() {
		return this.aaoDteValDmp;
	}

	public void setAaoDteValDmp(Date aaoDteValDmp) {
		this.aaoDteValDmp = aaoDteValDmp;
	}

	@Column(name = "AAO_NBR_OFF", precision = 4, scale = 0)
	public Short getAaoNbrOff() {
		return this.aaoNbrOff;
	}

	public void setAaoNbrOff(Short aaoNbrOff) {
		this.aaoNbrOff = aaoNbrOff;
	}

	@Column(name = "AAO_NBR_OFF_ACCPET", precision = 4, scale = 0)
	public Short getAaoNbrOffAccpet() {
		return this.aaoNbrOffAccpet;
	}

	public void setAaoNbrOffAccpet(Short aaoNbrOffAccpet) {
		this.aaoNbrOffAccpet = aaoNbrOffAccpet;
	}

	@Column(name = "AAO_NBR_OFF_REJ", precision = 4, scale = 0)
	public Short getAaoNbrOffRej() {
		return this.aaoNbrOffRej;
	}

	public void setAaoNbrOffRej(Short aaoNbrOffRej) {
		this.aaoNbrOffRej = aaoNbrOffRej;
	}

	@Column(name = "AAO_NBR_OFF_HOR_DELAI", precision = 4, scale = 0)
	public Short getAaoNbrOffHorDelai() {
		return this.aaoNbrOffHorDelai;
	}

	public void setAaoNbrOffHorDelai(Short aaoNbrOffHorDelai) {
		this.aaoNbrOffHorDelai = aaoNbrOffHorDelai;
	}

	@Column(name = "LAA_ID", precision = 22, scale = 0)
	public BigDecimal getLaaId() {
		return this.laaId;
	}

	public void setLaaId(BigDecimal laaId) {
		this.laaId = laaId;
	}

	@Column(name = "LAA_AAO_CODE", length = 20)
	public String getLaaAaoCode() {
		return this.laaAaoCode;
	}

	public void setLaaAaoCode(String laaAaoCode) {
		this.laaAaoCode = laaAaoCode;
	}

	@Column(name = "LAA_OBJET", length = 1000)
	public String getLaaObjet() {
		return this.laaObjet;
	}

	public void setLaaObjet(String laaObjet) {
		this.laaObjet = laaObjet;
	}

	@Column(name = "LAA_OBSERVATION", length = 200)
	public String getLaaObservation() {
		return this.laaObservation;
	}

	public void setLaaObservation(String laaObservation) {
		this.laaObservation = laaObservation;
	}

	@Column(name = "LAA_MT_CAUT", precision = 22, scale = 0)
	public BigDecimal getLaaMtCaut() {
		return this.laaMtCaut;
	}

	public void setLaaMtCaut(BigDecimal laaMtCaut) {
		this.laaMtCaut = laaMtCaut;
	}

	@Column(name = "LAA_MT_EST", precision = 22, scale = 0)
	public BigDecimal getLaaMtEst() {
		return this.laaMtEst;
	}

	public void setLaaMtEst(BigDecimal laaMtEst) {
		this.laaMtEst = laaMtEst;
	}

	@Column(name = "LAA_DTE_SAISI", length = 7)
	public Date getLaaDteSaisi() {
		return this.laaDteSaisi;
	}

	public void setLaaDteSaisi(Date laaDteSaisi) {
		this.laaDteSaisi = laaDteSaisi;
	}

	@Column(name = "LAA_STA_CODE", length = 3)
	public String getLaaStaCode() {
		return this.laaStaCode;
	}

	public void setLaaStaCode(String laaStaCode) {
		this.laaStaCode = laaStaCode;
	}

	@Column(name = "LAA_FON_COD_SAISI", length = 20)
	public String getLaaFonCodSaisi() {
		return this.laaFonCodSaisi;
	}

	public void setLaaFonCodSaisi(String laaFonCodSaisi) {
		this.laaFonCodSaisi = laaFonCodSaisi;
	}

	@Column(name = "LAA_FON_COD_CPMP", length = 20)
	public String getLaaFonCodCpmp() {
		return this.laaFonCodCpmp;
	}

	public void setLaaFonCodCpmp(String laaFonCodCpmp) {
		this.laaFonCodCpmp = laaFonCodCpmp;
	}

	@Column(name = "LAA_OPE_MATRICULE", length = 20)
	public String getLaaOpeMatricule() {
		return this.laaOpeMatricule;
	}

	public void setLaaOpeMatricule(String laaOpeMatricule) {
		this.laaOpeMatricule = laaOpeMatricule;
	}

	@Column(name = "LAA_LIEU_EXE", length = 1000)
	public String getLaaLieuExe() {
		return this.laaLieuExe;
	}

	public void setLaaLieuExe(String laaLieuExe) {
		this.laaLieuExe = laaLieuExe;
	}

	@Column(name = "LAA_LBG_IMPUTATION", length = 50)
	public String getLaaLbgImputation() {
		return this.laaLbgImputation;
	}

	public void setLaaLbgImputation(String laaLbgImputation) {
		this.laaLbgImputation = laaLbgImputation;
	}

	@Column(name = "LAA_NUM", precision = 22, scale = 0)
	public BigDecimal getLaaNum() {
		return this.laaNum;
	}

	public void setLaaNum(BigDecimal laaNum) {
		this.laaNum = laaNum;
	}

	@Column(name = "LAA_COUT_LOT", precision = 22, scale = 0)
	public BigDecimal getLaaCoutLot() {
		return this.laaCoutLot;
	}

	public void setLaaCoutLot(BigDecimal laaCoutLot) {
		this.laaCoutLot = laaCoutLot;
	}

	@Column(name = "LAA_DAC_CODE", length = 20)
	public String getLaaDacCode() {
		return this.laaDacCode;
	}

	public void setLaaDacCode(String laaDacCode) {
		this.laaDacCode = laaDacCode;
	}

	@Column(name = "LAA_AJOUT_PANIER", length = 1)
	public String getLaaAjoutPanier() {
		return this.laaAjoutPanier;
	}

	public void setLaaAjoutPanier(String laaAjoutPanier) {
		this.laaAjoutPanier = laaAjoutPanier;
	}

}
