package com.sndi.model;
// Generated 9 sept. 2020 15:08:06 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VxAdresseAvisId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VX_ADRESSE")
public class VxAdresseAvis implements java.io.Serializable {

	private String libdetail;
	private BigDecimal adaNum;
	private String adaLibelle;
	private String adaFonCod;
	private BigDecimal dtaNum;
	private BigDecimal dtaAdaNum;
	private String dtaTitre;
	private String dtaLibelle;
	private Date dtaDteSaisi;
	private Short dtaLiaNum;
	private String aaoCode;
	private String aaoDacCode;
	private String liaLibelle;

	public VxAdresseAvis() {
	}

	public VxAdresseAvis(BigDecimal adaNum, BigDecimal dtaNum, String aaoCode) {
		this.adaNum = adaNum;
		this.dtaNum = dtaNum;
		this.aaoCode = aaoCode;
	}

	public VxAdresseAvis(String libdetail, BigDecimal adaNum, String adaLibelle, String adaFonCod, BigDecimal dtaNum,
			BigDecimal dtaAdaNum, String dtaTitre, String dtaLibelle, Date dtaDteSaisi, Short dtaLiaNum, String aaoCode,
			String aaoDacCode, String liaLibelle) {
		this.libdetail = libdetail;
		this.adaNum = adaNum;
		this.adaLibelle = adaLibelle;
		this.adaFonCod = adaFonCod;
		this.dtaNum = dtaNum;
		this.dtaAdaNum = dtaAdaNum;
		this.dtaTitre = dtaTitre;
		this.dtaLibelle = dtaLibelle;
		this.dtaDteSaisi = dtaDteSaisi;
		this.dtaLiaNum = dtaLiaNum;
		this.aaoCode = aaoCode;
		this.aaoDacCode = aaoDacCode;
		this.liaLibelle = liaLibelle;
	}

	@Column(name = "LIBDETAIL", length = 703)
	public String getLibdetail() {
		return this.libdetail;
	}

	public void setLibdetail(String libdetail) {
		this.libdetail = libdetail;
	}

	@Column(name = "ADA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdaNum() {
		return this.adaNum;
	}

	public void setAdaNum(BigDecimal adaNum) {
		this.adaNum = adaNum;
	}

	@Column(name = "ADA_LIBELLE", length = 500)
	public String getAdaLibelle() {
		return this.adaLibelle;
	}

	public void setAdaLibelle(String adaLibelle) {
		this.adaLibelle = adaLibelle;
	}

	@Column(name = "ADA_FON_COD", length = 12)
	public String getAdaFonCod() {
		return this.adaFonCod;
	}

	public void setAdaFonCod(String adaFonCod) {
		this.adaFonCod = adaFonCod;
	}

	 @Id
	@Column(name = "DTA_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDtaNum() {
		return this.dtaNum;
	}

	public void setDtaNum(BigDecimal dtaNum) {
		this.dtaNum = dtaNum;
	}

	@Column(name = "DTA_ADA_NUM", precision = 22, scale = 0)
	public BigDecimal getDtaAdaNum() {
		return this.dtaAdaNum;
	}

	public void setDtaAdaNum(BigDecimal dtaAdaNum) {
		this.dtaAdaNum = dtaAdaNum;
	}

	@Column(name = "DTA_TITRE", length = 200)
	public String getDtaTitre() {
		return this.dtaTitre;
	}

	public void setDtaTitre(String dtaTitre) {
		this.dtaTitre = dtaTitre;
	}

	@Column(name = "DTA_LIBELLE", length = 500)
	public String getDtaLibelle() {
		return this.dtaLibelle;
	}

	public void setDtaLibelle(String dtaLibelle) {
		this.dtaLibelle = dtaLibelle;
	}

	@Column(name = "DTA_DTE_SAISI", length = 7)
	public Date getDtaDteSaisi() {
		return this.dtaDteSaisi;
	}

	public void setDtaDteSaisi(Date dtaDteSaisi) {
		this.dtaDteSaisi = dtaDteSaisi;
	}

	@Column(name = "DTA_LIA_NUM", precision = 3, scale = 0)
	public Short getDtaLiaNum() {
		return this.dtaLiaNum;
	}

	public void setDtaLiaNum(Short dtaLiaNum) {
		this.dtaLiaNum = dtaLiaNum;
	}

	@Column(name = "AAO_CODE", nullable = false, length = 20)
	public String getAaoCode() {
		return this.aaoCode;
	}

	public void setAaoCode(String aaoCode) {
		this.aaoCode = aaoCode;
	}

	@Column(name = "AAO_DAC_CODE", length = 20)
	public String getAaoDacCode() {
		return this.aaoDacCode;
	}

	public void setAaoDacCode(String aaoDacCode) {
		this.aaoDacCode = aaoDacCode;
	}

	@Column(name = "LIA_LIBELLE", length = 500)
	public String getLiaLibelle() {
		return this.liaLibelle;
	}

	public void setLiaLibelle(String liaLibelle) {
		this.liaLibelle = liaLibelle;
	}

}
