package com.sndi.model;
// Generated 9 sept. 2020 15:55:09 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * VxAdresseId generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "VX_ADRESSE")
public class VxAdresse implements java.io.Serializable {

	private String dacCode;
	private String libdetail;

	public VxAdresse() {
	}

	
	public VxAdresse(String dacCode) {
		this.dacCode = dacCode;
	}

	public VxAdresse(String dacCode, String libdetail) {
		this.dacCode = dacCode;
		this.libdetail = libdetail;
	}

	@Id
	@Column(name = "DAC_CODE", nullable = false, length = 20)
	public String getDacCode() {
		return this.dacCode;
	}

	public void setDacCode(String dacCode) {
		this.dacCode = dacCode;
	}

	@Column(name = "LIBDETAIL", length = 4000)
	public String getLibdetail() {
		return this.libdetail;
	}

	public void setLibdetail(String libdetail) {
		this.libdetail = libdetail;
	}

}
